### ISSUE TITLE
Nav: Few pages does not fit Mac's 13" with the new nav

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1000]
Reproduced on pages:
- Alert list
- Specific schedule edit

https://user-images.githubusercontent.com/3284841/207865654-78155277-8cd1-48be-9c8d-8f1c4dcf732f.mov

P.S. I was not able to reproduce it in the developer mode in chrome 0_o

**Comment by raphael-batte** [comment]
We can shorten the names and give them as tooltips if the table needs to be decrease to fit small screens
![image](https://user-images.githubusercontent.com/102970268/208070317-b806016a-201e-4cd6-9550-315823a471f4.png)

**Comment by raphael-batte** [comment]
Added tooltip hover 
![image](https://user-images.githubusercontent.com/102970268/208428873-fe67dee4-fe5a-4a6a-ba3e-c6595b9b57ea.png)

Figma https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=5310%3A108929&t=h3qXWrpGqXkNfNC9-1

**Comment by teodosii** [comment]
I believe this no longer reproduces. Could you please double check? Either @Matvey-Kuk or @raphael-batte 

Screenshot for macbook 13'
![image](https://user-images.githubusercontent.com/40542072/212282561-67d75635-6b8d-4381-be9e-8786219f30e2.png)
![image](https://user-images.githubusercontent.com/40542072/212282601-586a1b13-99f3-4476-8529-d0a7352a2f9b.png)

These are screenshots from Ildar on current ops version.
