### ISSUE TITLE
Nav: No "Alert Groups" page in the menu

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1001]
Now "OnCall" menu leads to "Alert Groups" list which makes it hard to find AGs if you look for them. Btw would be nice to keep OnCall leading to the list of AGs as well.<img width="743" alt="Screenshot 2022-12-15 at 15 03 25" src="https://user-images.githubusercontent.com/3284841/207865985-ca5621d2-f17c-456b-b766-53fd8aba679e.png">

**Comment by raphael-batte** [comment]
As quick fix we can add Alert groups page as menu item
![image](https://user-images.githubusercontent.com/102970268/208427499-f718ef34-d0cf-4363-a80a-e2d3923eac35.png)

Possible behaviour is to redirect users from OnCall main page to new page
