### ISSUE TITLE
Schedules: Long popup does not fit screen & buttons unreachable & objects outside of the popup

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1002]
<img width="729" alt="Screenshot 2022-12-15 at 15 09 29" src="https://user-images.githubusercontent.com/3284841/207867248-5ea1347d-7c83-495b-bb20-51845a83d59c.png">

**Comment by raphael-batte** [comment]
UI proposal:
1. Limit max-height for popup to 95% from user viewport height
2. Add right scrollbar if we have a size bigger than the viewport

**Comment by raphael-batte** [comment]
UI update

![Image](https://user-images.githubusercontent.com/102970268/209155737-37ec5ae2-f57b-4815-9df6-ad48500bac5e.png)

**Comment by joeyorlando** [comment]
fwiw, this still exists as of v1.3.3. I opened #2365 for this yesterday (just closed as a duplicate)
