### ISSUE TITLE
Nav: no text for OnCall in the "/alerts-and-incidents" page

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1003]
I propose such a text:
Collect and store alerts, group them, route, escalate based on schedules, and deliver to Slack, Telegram, Phone Calls, SMS, E-Mails, and other destinations 🚀

<img width="1426" alt="Screenshot 2022-12-15 at 15 11 17" src="https://user-images.githubusercontent.com/3284841/207867701-5b73f4a2-f7b4-494c-b768-77e79d53cbbe.png">

**Comment by raphael-batte** [comment]
Unformatted long text can be a little bit hard to read:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/102970268/208056687-dbefb567-89a8-4df0-8f23-8cf77888164f.png">
Do we allow to make some kind of list here?

**Comment by raphael-batte** [comment]
Possible direction https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=5310%3A108207&t=h3qXWrpGqXkNfNC9-1

**Comment by teodosii** [comment]
@Matvey-Kuk The one you posted is too long and it gets trimmed - I suggest we put this copy in place as this one is also aligned with the project's description on GitHub

**Collect and analyze alerts, escalate based on schedules and deliver them to Slack, Phone Calls, SMS and others.**

**Comment by teodosii** [comment]
PR [here](https://github.com/grafana/oncall/pull/1259)

@Matvey-Kuk @raphael-batte let me know if you have better ideas on the copy - that's about the max characters we can fit into description

**Comment by maskin25** [comment]
done on the Grafana side
