### ISSUE TITLE
Date picker breaks search layout in the Alert Group list

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1004]
OnCall version: r51-v1.1.8
https://user-images.githubusercontent.com/3284841/207868883-f127f29a-7212-43ce-a004-42cacb740265.mov

**Comment by Ukochka** [comment]
It is a bug in grafana. Was fixed in this [PR](https://github.com/grafana/grafana/pull/63472) 
I will test and close this bug after fix will be released

**Comment by Ukochka** [comment]
Tested at ops with Grafana version 9.5.0 it is not reproducible anymore.
