### ISSUE TITLE
Calendar UI add logic description to delete rotation action

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1008]
Users do not understand the logic that when we delete a rotation, we leave part of it. 
Will be good to add confirmation popup with description to 'delete' icon.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/102970268/208058509-de8f3059-287a-4c21-aa85-d7ebb2d568a4.png">

**Comment by raphael-batte** [comment]
Modal with draft text 

![image](https://user-images.githubusercontent.com/102970268/209325572-6b1e979e-565f-45a5-851a-2e43a3a40adf.png)

**Comment by Ukochka** [comment]
design https://www.figma.com/file/e8B4keoGxQRlenH8rYTCpN/Grafana-OnCall-schedules-UI?node-id=2922%3A58330&t=vgqqQNa9xNnoXbCz-1
