### ISSUE TITLE
Docs feedback: /_index.md Api teams is empty

### ISSUE THREAD

**Issue by romanskugarevLMRU** [grafana/oncall#1018]
Hello, i see API endpoints in https://github.com/grafana/oncall/tree/dev/engine/apps/api Team, but in https://grafana.com/docs/oncall/latest/oncall-api-reference/  no information about api/v1/teams.
If use it by API it's work, but i don't understand how use parameters in request.
Please add page.

**Comment by McMerph** [comment]
I believe @romanskugarevLMRU is trying to say that the Grafana OnCall API actually has a `GET /api/teams/` endpoint, but it's not documented.

Is it a stable feature?
Can we use this endpoint in production?

**Comment by joeyorlando** [comment]
closing as a duplicate of https://github.com/grafana/oncall/issues/2448
