### ISSUE TITLE
Support for ARM on mariadb, rabbitmq and redis helm charts

### ISSUE THREAD

**Issue by pikilisaikiran** [grafana/oncall#1023]
The "'Cluster requirements ensure you can run x86-64/amd64 workloads,"' according to the Grafana Oncall Helm Chart. The arm64 architecture is not supported right now.

Grafana oncall was deployed using the official helm chart and was successful in running on amd64 machines but failed to support arm64.

This is what I observe because of a few dependencies, including mariadb, rabbitmq, and redis, which use helm charts with bitnami images that lack support for arm64. We ask that you update the helm charts of the dependencies and add supported images for arm.

Please provide support for the arm as soon as you can.
Thank you.

**Comment by Matvey-Kuk** [comment]
Related: https://github.com/grafana/oncall/issues/86

**Comment by pikilisaikiran** [comment]
ARM support for mariadb, rabbitmq and redis not for Grafana Oncall (arm is supported). Can we get helm chart for ARM supported images for mariadb, rabbitmq and redis?
And one more question what other messaging brokers can we use instead of rabbitmq, can  we you kafka?

**Comment by joeyorlando** [comment]
#2144 updated the `helm` chart versions used for `rabbitmq` and `mariadb`.

In the latest version of OnCall as of this writing (v1.3.1), the default image tags used by the `rabbitmq`, `redis`, and `mariadb` charts all provide arm64 arch support:
- https://hub.docker.com/_/mariadb/tags?page=1&name=10.11.4
- https://hub.docker.com/_/redis/tags?page=1&name=6.2.7
- https://hub.docker.com/_/rabbitmq/tags?page=1&name=3.12.0

Additionally, you are free to update the image tags used by these charts. For example, see the available parameters in the `mariadb` bitnami chart docs [here](https://artifacthub.io/packages/helm/bitnami/mariadb#mariadb-common-parameters).

Feel free to re-open a new issue if this does not solve your issue @pikilisaikiran
