### ISSUE TITLE
Improve startup time 

### ISSUE THREAD

**Issue by torkelo** [grafana/oncall#1024]
It feels like there is could be some easy quick wins to improve the loading time, especially when visiting OnCall again after the first time it takes almost the same amount of time (multiple seconds, more than Grafana itself). 

Seems to be multiple network requests (7x to /sync)  (and svg logo) that take up the booting time. 
![image](https://user-images.githubusercontent.com/10999/208599462-4d0f9776-4dbb-4065-ae86-648fcb11e5c0.png)
 
Also try to Use the PluginPage component when showing the loading state, so the user does not loose the left side section nav. 

![Screenshot from 2022-12-20 07-36-03](https://user-images.githubusercontent.com/10999/208600109-618c2fdf-419f-4dba-aa22-24e0ee42a39d.png)

**Comment by Matvey-Kuk** [comment]
Duplicate #816
