### ISSUE TITLE
Nav: left margin on smaller screens

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1026]
Looks like our plugin has some margin incompatible with the new nav. 

<img width="864" alt="Screenshot 2022-12-20 at 10 44 59" src="https://user-images.githubusercontent.com/3284841/208623174-fd7de001-7960-4c40-8b0f-0aac2ad506a4.png">

CC @torkelo

**Comment by maskin25** [comment]
@Matvey-Kuk can you check once again? I see narrow padding, it's done by Grafana itself intentionally 
<img width="680" alt="Screenshot 2023-01-19 at 12 52 22" src="https://user-images.githubusercontent.com/3278022/213448037-68fb7117-2226-4d36-b715-740c963f5d88.png">

**Comment by teodosii** [comment]
We can close this issue as this seems to be done on purpose within topnavbar now that there's the right arrow next to it - it's also aligned with next to the hamburger menu

![image](https://user-images.githubusercontent.com/40542072/215778656-e298838d-e489-4729-8106-08e8b0112a82.png)
