### ISSUE TITLE
Allow Alert API endpoint to be sorted by newest issue first

### ISSUE THREAD

**Issue by tleecsm** [grafana/oncall#1031]
The current functionality of the [Alerts API endpoint](https://grafana.com/docs/oncall/latest/oncall-api-reference/alerts/) is to return alerts by `created_at` in ascending order.  This means our oldest alerts will always be at the top of the response.  For our use cases, this is pretty inconvenient.  It would be nice if this endpoint returned the newest alerts first with the older alerts following thereafter.  This doesn't necessarily need to be default behavior, and could be locked behind a query parameter.

**Comment by Matvey-Kuk** [comment]
Sounds like a bug for me, worth fixing.

**Comment by Matvey-Kuk** [comment]
Taking this one to the core team's backlog.

**Comment by Matvey-Kuk** [comment]
@jtheory I think it's purely backend
