### ISSUE TITLE
Fix width in user settings popup

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1032]
There is a nav issue in some subsections in user profile:
![image](https://user-images.githubusercontent.com/102970268/208867500-16938ec7-c451-4a70-91da-41a1a6f66d01.png)

Proposal is to fix width to 1100 px inside all the tabs
![image](https://user-images.githubusercontent.com/102970268/208868100-cc54d01b-85b9-4343-8448-98cc1ca94032.png)

**Comment by raphael-batte** [comment]
Relevant additional proposal:
Will be great to rename **Mobile app verification** to **Mobile app connection**. **Connection** looks more relevant here

**Comment by teodosii** [comment]
Closing this issue as it was merged to `dev`.
