### ISSUE TITLE
Add white bg under QR code block

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1033]
![image](https://user-images.githubusercontent.com/102970268/208875274-e4a276a5-ad3c-4990-b432-2f8cb4e56d66.png)

**Comment by teodosii** [comment]
I'm not sure what version are you using but this is on dev

![image](https://user-images.githubusercontent.com/40542072/209016609-ab0396da-a71a-453f-b652-b7f496279b63.png)
