### ISSUE TITLE
Schedule export button disappeared

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1036]
<img width="1452" alt="Screenshot 2022-12-22 at 10 09 24" src="https://user-images.githubusercontent.com/3284841/209087947-c1bcf8cb-1e5f-444b-87f3-38c77cff7d9c.png">
It used to be somewhere on this screen, right? Is it a bug?

**Comment by PhantomPhreak** [comment]
Also missing it, it was a handy feature to export schedules to the calendar

**Comment by Matvey-Kuk** [comment]
@matiasb @maskin25 could you please check?
