### ISSUE TITLE
Schedule details page. We don't fit to screen on small and medium monitors.

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1039]
I noticed that with the new nav we have a problem with the horizontal scrollbar on screen resolutions of less than 1900 px. Will be good to fix this and fit the detail schedule page to 1300 px (with opened side nav).
![image](https://user-images.githubusercontent.com/102970268/209159628-6f083849-752d-4840-85d2-fc5c0c036cdc.png)

**Comment by Matvey-Kuk** [comment]
Looks like a duplicate for https://github.com/grafana/oncall/issues/1000
