### ISSUE TITLE
AlertManager Heartbeat to OnCall missing configuration

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/oncall#1047]
In OnCall OSS, I have added a new integration for AlertManager (using Mimir AlertManager).  In the integration configuration screen, on the Heartbeat tab, it appears that it's missing configuration - see "To send periodic heartbeat alerts from AlertManager to OnCall, do the following".

I can add the alert and the receiver config file, but what do we need to do to generate heartbeats from Mimir AlertManager to  OnCall?

There are also references to amixr still.  

![image](https://user-images.githubusercontent.com/25855524/209695610-dabc8012-7ba3-4204-9e89-a2130030b7c2.png)

**Comment by roock** [comment]
The given alert expression (`vector(1)`)  will always be true, so it will be a constant alert and alertmanager will send a "heartbeat" (an alert event) every 50s (configured in the route). It's possible that Mimir Alertmanager behaves differently from Prometheus Alertmanager. In my setup it works with Prometheus Alertmanager. I'll probably play around with Mimir next week, I'll can check if it works there too.

And i totally agree, somebody should remove the references to amixr :)

**Comment by MaxDiOrio** [comment]
Ugh - this was totally my error.  I had a label match in the Alerting Notification policy for the heartbeat alertname=heartbeat - but the alert was set for capital H - case sensitivity killed me.  I fixed that and the heart went green - all good.
