### ISSUE TITLE
Feature for making Escalation chains/Integration/Schedules editable/read-only

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/oncall#1054]
Oncall inherit access permissions from Grafana, and we can override the global user's role and permission in the Org by teams, per-dashboard permissions and so on, it's flexible.
Also, dashboards has very handy feature to set them in Read-only:
![image](https://user-images.githubusercontent.com/8307692/210050640-101ed80c-11b7-42b3-a994-2ae825b68cf2.png)
This works as a safety latch, preventing dashboard from the unintentional changes.

We do plenty of users in the Org with Oncall installed with `Admin` Role. Their permissions can't be adjusted/overriden by the Team's permissions.
Recently we had a situation, when somebody changed the escalation chain, and this slipped unnoticed.
It would be nice to have a feature of setting read-only mode for the escalaton chains, schedules and so on, just to have a safety latch, same as Grafana dashboards has.

Thanks!

**Comment by greatvovan** [comment]
I support the idea, but I think there is more to do here. OnCall should have roles that allow to configure escalation chains and integrations, independently from working with alert groups. Currently the only way to allow the user to use OnCall is to give them Grafana Editor role, which allows too much.

RBAC for OnCall was allegedly in progress (as of the end of last year), but public has no visibility on the progress and the planned capabilities.

**Comment by joeyorlando** [comment]
hi there 👋 I'm going to close this as RBAC for OnCall is now supported (**note**: you must be running Grafana >= 9.4 ([release notes](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-4/#rbac-support-for-grafana-oncall-plugin)))
