### ISSUE TITLE
Support custom personal notification types

### ISSUE THREAD

**Issue by zackman0010** [grafana/oncall#1057]
I'd like to have the ability to set up a custom personal notification type/CahtOps system rather than only using the ones built in. 

Two use cases I see:
1) Companies might use a chat client that isn't Slack or Telegram, so the ability to roll their own ChatOps integration would be necessary to connect to internal chats
2) I work at a telecom company, so we have our own processes to make phone calls and send texts. We'd like to use those rather than having to pay an external company to do so. 

The simplest solution I can think of would be a new webhook configuration. The current one only works with escalation chains. A new webhook could be set up to call to an external service and can include information from the user's profile, such as email or username.

**Comment by PhantomPhreak** [comment]
Possibly related to https://github.com/grafana/oncall/issues/213

**Comment by Matvey-Kuk** [comment]
Custom messenger integrations are possible and descuribed here: https://youtu.be/o9HkQLrBbtE?t=183
