### ISSUE TITLE
Slack permissions

### ISSUE THREAD

**Issue by NimoTh** [grafana/oncall#1082]
Why are the following permissions needed for Slack integration?
- Send messages to channels Grafana Oncall isn't a member of `chat:write.public`
- Create and manage user groups `usergroups:write`
- Upload, edit, and delete files as Grafana Oncall `files:write`
- Send messages on a user’s behalf `chat:write`

Thanks and regards!

**Comment by Matvey-Kuk** [comment]
Would be nice to cover it in public docs based on our internal Q&A doc. CC @alyssawada

**Comment by alyssawada** [comment]
Matvey added this information to the docs [here](https://grafana.com/docs/grafana-cloud/alerting-and-irm/oncall/manage/notify/slack/#why-does-oncall-slack-app-require-so-many-permissions). 

But we will refresh the content will be updated during the Q1 refactor.

**Comment by NimoTh** [comment]
Thanks for taking the time to document the needed permissions. One permission is still not clear to me.

> Send messages on your behalf — this permission may sound suspicious, but it’s actually a general ability to send messages as the bot: https://api.slack.com/scopes/chat:write Grafana OnCall will not impersonate or post using your handle to slack. It will always post as the bot.

That sounds wrong. You already have permission "Send messages as @grafana_oncall". Sending as another user is what it says and should not be necessary.
