### ISSUE TITLE
Notifications for non-work phone and no cell tower signal

### ISSUE THREAD

**Issue by zalegrala** [grafana/oncall#109]
I have recently moved to a basement office, which has zero cell signal, so when I am on call I need to work from upstairs.  No big deal.  The obvious solution here is to connect Slack on my phone to the account for work, and don't complain about all of the notifications I need to look at.

However, I'm wondering if there could be a future feature that could enable a user such as myself, to receive notifications from an internet location, that is not a work-related account.  Work-life balance and such.  What do you think of this idea?

**Comment by raphael-batte** [comment]
Thanks for the feedback! The idea looks interesting, we will discuss it in the UX team.

**Comment by joeyorlando** [comment]
@zalegrala does the mobile app suit your needs listed here? 🙂 (going to close this as I _think_ it should but feel free to reopen)

**Comment by zalegrala** [comment]
Oh thanks, I'd forgotten about this one, but yes the app has been working great.
