### ISSUE TITLE
Feature Request: Make integration and notifications via Microsoft Teams

### ISSUE THREAD

**Issue by roock** [grafana/oncall#110]
Docs:
- https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions
- https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook

**Comment by Matvey-Kuk** [comment]
We are working on the MS teams integration as a part of our cloud offering.

**Comment by roock** [comment]
@Matvey-Kuk Does that mean it will only be available in the OnCall Cloud version or does it mean the ms-teams will behave similar to the current SMS/telephone-Cloud-Integration and only the notification part will need to run on Grafana Cloud?

**Comment by Matvey-Kuk** [comment]
@roock the whole MS Teams integration will be available only in Grafana Cloud OnCall. MS Teams for OSS is not in our plans, sorry.

**Comment by roock** [comment]
@Matvey-Kuk nothing to apologize for. I'm very happy Grafana is providing such amazing OSS software. I was just asking what to expect 👍
