### ISSUE TITLE
Filter alerts assigned by user

### ISSUE THREAD

**Issue by marctc** [grafana/oncall#1119]
I was oncall last weekend and I got multiple pages that I had to acknowledge.
The problem is that I had to scroll up on a slack channel to find all the alerts (more than 20)
and acknowledge one by one.

I tried to do that in the UI but I couldn't find any option to filter firing alerts assigned to
me. The only option that I found is filter by integration, but that's not very useful if someone
belongs to multiple rotations (i.e integrations). 

Would it make sense to add a filter for alerts by user (assigned)?

**Comment by stevesg** [comment]
+1 for an "Ack All" feature for coping with pager storms.

**Comment by iskhakov** [comment]
closed by https://github.com/grafana/oncall/pull/1240
