### ISSUE TITLE
Unable to change users order within one group in schedule rotation

### ISSUE THREAD

**Issue by dmitry-tiger** [grafana/oncall#1130]
How to reproduce
1. Add two users into one group in rotation and save
2. edit rotation and drag users to change order within one group and save (see in screenshot that editor10 placed before admin)
3. see that nothing changed in rotations and final schedule 
![image](https://user-images.githubusercontent.com/4358421/212045717-23478214-45fc-425c-b17f-794073114c4f.png)
![image](https://user-images.githubusercontent.com/4358421/212045945-4ea7a8c8-90af-4e3b-8a70-f035833ecc15.png)
![image](https://user-images.githubusercontent.com/4358421/212046069-f78c570b-9387-4abb-be34-06a7584d5273.png)

**Comment by Matvey-Kuk** [comment]
User order within a group actually doesn't change anything. Ordering is only important for groups. Curious what's the idea behind changing the order of userw within the group :)
