### ISSUE TITLE
Plugin stuck on "Validatiing your plugin connection"

### ISSUE THREAD

**Issue by Konstantinov-Innokentii** [grafana/oncall#1146]
After changing IP of the OnCall's host OSS user stuck on that page in plugin without opportunity to Remove Current Configuration. 

![image](https://user-images.githubusercontent.com/20221722/213134521-410af345-c325-4caa-a0ad-6bfe4ee25516.png)

Engine version 1.1.16, plugin version 1.1.16, docker-compose.

**Comment by Konstantinov-Innokentii** [comment]
I think we should provide "Remove current configuration" while syncing too.

**Comment by joeyorlando** [comment]
@Konstantinov-Innokentii can we have the initial user that reported this supply their engine & celery logs, as well as a screenshot of any non HTTP 200 network calls from their browser (if there are any)?
