### ISSUE TITLE
Allow outgoing webhooks to set custom headers

### ISSUE THREAD

**Issue by sd2k** [grafana/oncall#1178]
It would be great if outgoing webhooks could set additional headers as well as just `Authorization`. I'm imagining a similar UI/UX to adding custom headers when configuring HTTP-based Grafana datasources:

![image](https://user-images.githubusercontent.com/5464991/213693971-68d9291b-26e7-4810-9173-01ad48d81070.png)

**Comment by mderynck** [comment]
Headers can now be set to anything including templates, might need to revisit the UI though
