### ISSUE TITLE
Allow configuring users through Terraform

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1193]
Use-case: large org onboards to OnCall. They would like to pre-fill notification policies & phone numbers.

We don't allow editing **Users** though API or TF, only to list: https://grafana.com/docs/oncall/latest/oncall-api-reference/users/

We allow editing **Personal Notifications** through API but we don't allow editing through Terraform: https://grafana.com/docs/oncall/latest/oncall-api-reference/personal_notification_rules/

**Comment by greatvovan** [comment]
OnCall user list seems to replicate Grafana users from /admin/users. It seems that we can add basic auth users (https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/user), but it will not work with OAuth SSO users, whose access list is controlled elsewhere. But I agree that it would be great to have pre-configured dummy user records that later (when users actually log in) would be joined with Grafana users. Now we need to wait until users log in at least once before we can terraform them into escalation chains.

Allowing setting a phone number through TF will open a loophole to sign up a phone number without owner's confirmation. Maybe add them in not confirmed state (unsupported currently)?

**Comment by joeyorlando** [comment]
This will be closed soon by https://github.com/grafana/terraform-provider-grafana/pull/1653
