### ISSUE TITLE
Setting Escalation Chain Step Importance Before Target Does Not Set Importance

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1196]
Steps to Reproduce:
1. Create a new escalation chain from the Web UI
2. Create a step of type "Notify users from on-call schedule"
3. Set the notification level to Important
4. Set the schedule target
5. Navigate to a different escalation chain / navigate away from the page
6. Return to the escalation chain, and notice that it has actually been set to the Default notification level

Notes:

Doing steps 3 and 4 reversed results in the expected behavior, where the notification step is properly set to Important.

Also, it displays that it is set to Important until you navigate away from the escalation chain - however, it does not appear to actually set it as important if you do the steps in the above order.

**Comment by brojd** [comment]
Seems that every time frontend sends HTTP PUT `escalation_policies/someIdHere` with payload:
```
{
  "step": 6,
  "notify_schedule": "someOtherIdHere"
}
```
then `important` flag is being reset on the backend even though it has been successfully set to `true` before. Easy to reproduce:


https://github.com/grafana/oncall/assets/12073649/0281dc5b-262d-4ca3-8d2d-e92c22e5881f

**Comment by vadimkerr** [comment]
support escalation: https://github.com/grafana/support-escalations/issues/7920

**Comment by vadimkerr** [comment]
This should be fixed in [v1.3.55](https://github.com/grafana/oncall/releases/tag/v1.3.55)
