### ISSUE TITLE
OnCall calling numbers not mobile

### ISSUE THREAD

**Issue by dfranco87** [grafana/oncall#1203]
Hi people...
I'm new here and now me and my company are testing grafana onCall and others features from grafana.
My dout is, i tried to make a phone call with a normal telephone number not a cellphone number, but in the onCall configs there is a field where i need to put a confirmation code,  when I configure a cellphone, OK no problem it's easy and simple... but how can I configure onCall for a number not mobile, not is a cellphone?

Thanks guys.

**Comment by Matvey-Kuk** [comment]
Hi! OnCall is designed only to call mobile phone numbers.

**Comment by husimo-tilleuls** [comment]
Hello! Well, that's unfortunate! 

We have virtual (SIP) numbers provided by a telecom operator that do not receive SMS.

Would be great to think about implement that fonctionality, I think Grafana OnCall is able to call people ;-p
