### ISSUE TITLE
iCal caching bug - optimize unnecessary queries to custom oncall shifts

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#1216]
```python3
cached_ical_file_primary = models.TextField(null=True, default=None)
cached_ical_file_overrides = models.TextField(null=True, default=None)
```

These fields are `None` by default and the invalidation criteria ([here](https://github.com/grafana/oncall/blob/dev/engine/apps/schedules/models/on_call_schedule.py#L637) and [here](https://github.com/grafana/oncall/blob/dev/engine/apps/schedules/models/on_call_schedule.py#L537)) is “being equal to None”, so there will always be extra SQL queries for schedules that are either empty or have no overrides. If this is fixed, these extra SQL queries to custom oncall shifts would disappear, making loading schedules more efficient.

**Comment by matiasb** [comment]
This should have been fixed by #1312.
