### ISSUE TITLE
Clicking on override in the past on Web schedule disables editing buttons until refresh, maybe crashes backend

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1221]
Steps to reproduce:

1. Make a schedule
2. Make a recurring shift
3. Make an override shift that begins and ends in the past.
4. Refresh the page
5. Attempt to click on the override shift to edit it.
6. Notice that the Add Rotation and Add Override buttons have been disabled as if to bring up the modal, but because no modal ever surfaces, they cannot be reenabled without refreshing the page.

Additional notes:

By doing this repeatedly, it seems that I can crash the engine backend, though it doesn't log why this occurs. It does not necessarily appear that the entire process crashes, but it stops successfully responding to liveness checks in Kubernetes and the Grafana plugin stops working, so it gets restarted.

Notably, the request to `POST https://<domain>/api/plugin-proxy/grafana-oncall-app/api/internal/v1/oncall_shifts/preview/?date=2023-01-23` that occurs after clicking on the override shift never gets a response, indicating that the thread responsible for responding to this either crashes or hangs. It's possible that if enough of these stack up, the process will stop responding to requests?

**Comment by Ukochka** [comment]
To be able to fix this properly and easier we need backend changes @vadimkerr  could you please help?

**Comment by vadimkerr** [comment]
I was able to reproduce this, defineltely a backend bug.

**Comment by vadimkerr** [comment]
https://github.com/grafana/oncall/pull/1474 will prohibit creating & updating past overrides. 
However, it won't fix the issue with buttons being disabled after the API returns 400 errors, I think this should be handled on the frontend side. @Ukochka could you please take a look at this?

**Comment by matiasb** [comment]
There were UI updates related to validation/when update/create buttons are enabled that prevent this now, closing.
