### ISSUE TITLE
Team' oncall member is not shown in the Final schedule

### ISSUE THREAD

**Issue by yasharne** [grafana/oncall#1247]
We have different teams like DevOps, SRE, etc., each with a separate Ical calendar and members inside their grafana teams.
When I define an on-call for DevOps, it shows the on-call person on the Final schedule:
![image](https://user-images.githubusercontent.com/7656049/215418557-a6f58868-13b7-4c62-8fca-c68ef01b63a3.png)
But when I define an on-call person on the SRE calendar, it is not showing the on-call person in the Final schedule and, therefore not announce it to the group as well:
![image](https://user-images.githubusercontent.com/7656049/215420062-f40c79ab-7590-45cc-a93e-abe76bc2324d.png)

**Comment by yasharne** [comment]
Thanks @Matvey-Kuk, I changed the user's permission to edit, and now everything is ok, and I get the notification for current oncall, but why can't someone with the view role become oncall?

**Comment by Matvey-Kuk** [comment]
@yasharne it's by design, viewers should not be oncall. It will be adjustable with RBAC in grafana 9.4.
