### ISSUE TITLE
Import avatars from Slack 

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1260]
Grafana has its own user avatars but it isn't easy to manage them. 

Will be great to add a checkbox to the personal Slack connection page **"Use Slack avatar in OnCall"** and use this avatar across OnCall.

**Comment by Matvey-Kuk** [comment]
I don't think it's up to OnCall to manage avatars or bypass Grafana's avatars system with our own avatars. Mind opening issue in grafana/grafana?
