### ISSUE TITLE
"X alerts in Y alert groups" button on integrations page does not properly redirect to incidents page

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1271]
1. Go to the integrations page
2. Click the "X alerts in Y alert groups" link under the name of the integration.
3. At this point it should have gone to the incidents page, but it does not

Firefox 109.0 (64-bit)

**Comment by Matvey-Kuk** [comment]
@thomasmitchell what's your OnCall plugin and backend version?

**Comment by raphael-batte** [comment]
Hi @thomasmitchell ! Do you mean the link **58 alerts in 58 alert groups** on this example screen? 
![image](https://user-images.githubusercontent.com/102970268/216277490-0b6451e1-aae1-47b5-8377-13ba22c7b4ad.png)

**Comment by thomasmitchell** [comment]
Yes; that one. I’m currently on 1.1.18 for both backend and engine.

**Comment by thomasmitchell** [comment]
Just tried this in Edge on a different computer just to test - still broken. Seeing this in the console
```
3 Icon.tsx:57 
        
       Icon component passed an invalid icon name wrench
(anonymous) @ Icon.tsx:57
ra @ react-dom.production.min.js:157
Ia @ react-dom.production.min.js:176
Ws @ react-dom.production.min.js:271
Ou @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:250
Eu @ react-dom.production.min.js:250
vu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
Zo @ react-dom.production.min.js:123
Vo @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
invokeTask @ zone.js:406
runTask @ zone.js:178
invokeTask @ zone.js:487
O @ zone.js:1661
f @ zone.js:1704
m @ zone.js:1725
```

**Comment by thomasmitchell** [comment]
I've upgraded to v1.1.22 and it works now. 🎊
