### ISSUE TITLE
Viewer have no Telegram verification code

### ISSUE THREAD

**Issue by PCbIX** [grafana/oncall#1273]
OnCall 1.1.20
Grafana 9.3.6
When new user with Viewer rights trying to verify their Telegram over OnCall. Field with verification code is empty.
![image](https://user-images.githubusercontent.com/32132480/216291201-a4d3364d-8965-4043-a6c9-05bd6e6d4bb5.png)

**Comment by vadimkerr** [comment]
Hi @PCbIX, thank you for opening the issue!
Viewers are not allowed to change their user configuration (including Telegram configuration), so this is expected that Telegram verification code is not shown for viewers. However, this should be indeed improved to show a user-friendly message about insufficient permissions (now it looks like a UI bug).

**Comment by PCbIX** [comment]
> Hi @PCbIX, thank you for opening the issue! Viewers are not allowed to change their user configuration (including Telegram configuration), so this is expected that Telegram verification code is not shown for viewers. However, this should be improved to show a user-friendly message about insufficient permissions (because now it looks like a UI bug).

Very strange logic. Not all engineers need editor or admin Grafana rights to work with their metrics. They needs only right notification over OnCall system in Telegram. How get it?

**Comment by Matvey-Kuk** [comment]
@PCbIX it's valid according to OnCall's permission model. Viewers are not supposed to be on-call and receive notifications. Minimal role for that is Editor. Even though I agree it's a UX bug, we shouldn't confuse viewers with TG validation.

**Comment by PCbIX** [comment]
@Matvey-Kuk I have no idea how to explain to you that your approach is fundamentally wrong. What kind of model in Grafana prohibits editing your personal data, or linking your accounts, I'm hearing about this for the first time, as are the people who put a like on my message above.  As an example, many help desk and service desk systems allow ordinary users to close their tickets. You come up with something of your own that clearly goes against standard methods. I hope you will try to understand

**Comment by Matvey-Kuk** [comment]
Grafana has only 3 roles: viewer, editor and admin. Grafana OnCall has to provide 3 roles: observer who could see everything but cannot change anything, person who is able to work with alerts, person who is able to perform configuration. That's the reason behind:
- viewer = observer who could see everything but cannot change anything
- editor = person who is able to work with alerts
- admin = person who is able to perform configuration

Please take into consideration that current stable versions of Grafana has no ability to set custom roles. 

@PCbIX if you would like to propose better way of roles distribution, please feel free to open the new issue. This exact issue should be fixed according to the current principle the whole system is following.

**Comment by dmitry-tiger** [comment]
> @PCbIX it's valid according to OnCall's permission model. Viewers are not supposed to be on-call and receive notifications. Minimal role for that is Editor. Even though I agree it's a UX bug, we shouldn't confuse viewers with TG validation.

@Matvey-Kuk  you mentioned that Minimal role for that is Editor but in fact connecting telegram in user profile requires OtherSettingsWrite permissions (after [d182e71](https://github.com/grafana/oncall/commit/d182e71f62c77be489aa50865f4320fccac4b771)) which is only Admin access

**Comment by teodosii** [comment]
@dmitry-tiger It's the same as for the other tabs in User Profile, I don't think it should be Editor because the other tabs in User Profile also required admin access.
