### ISSUE TITLE
PagerDuty migrator: migrate on-call shifts

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1283]
Current implementation of PagerDuty migrator doesn't migrate on-call shifts, but only "imports" the ICal file from PagerDuty. This makes migrated schedules read-only. This is listed as one of the limitations of the tool: https://github.com/grafana/oncall/tree/dev/tools/pagerduty-migrator#limitations

Migrating on-call shifts instead of the ICal file will allow editing migrated schedules from the web UI directly and improve the migration process.

**Comment by carlmagnusholmstrom-tomtom** [comment]
Actually, it does migrate the schedules, but they are read-only in the UI.

**Comment by Matvey-Kuk** [comment]
Fixed & rolled to production.
