### ISSUE TITLE
Team change in the Integration page always causes 403

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1292]
Also fallback link to the integrations does not work.

https://user-images.githubusercontent.com/3284841/216629696-d6c0e4f0-6801-46e1-b9ce-5e8245bc0358.mov

**Comment by maskin25** [comment]
there are two options:
1. Just redirect to list of integrations after team change (/a/grafana-oncall-app/integrations)
2. Show current 403 screen, fix link to integrations

@Matvey-Kuk which one would you prefer?

**Comment by Matvey-Kuk** [comment]
I don’t think that user should face 403 during normal navigation in the product.

What happens:
- We open the page, we set URL to specific integration (/integrations/C8XIJ7ACH35MV)
- When we change team, user don’t have this integration in the team so we give him 403.

Our limitations:
- We want to have unique url’s for Integrations
- We want to change teams without 403’s

Is it possible to drop object ID from the url when we change the team?
