### ISSUE TITLE
Filters are getting lost when navigating from AG List to Alert Group and back

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1294]
https://user-images.githubusercontent.com/3284841/216631639-4e6bed88-b452-422f-8237-d8bdb387142a.mov

**Comment by vadimkerr** [comment]
Seems like a duplicate of https://github.com/grafana/oncall/issues/482?

**Comment by Matvey-Kuk** [comment]
@vadimkerr true!
