### ISSUE TITLE
Schedule list -> current on-caller ignores overrides 

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1296]
Version: r75-v1.1.22

<img width="1128" alt="Screenshot 2023-02-06 at 10 31 54" src="https://user-images.githubusercontent.com/3284841/216924039-df55e00f-ddd4-40d4-a836-a3608d25968d.png">

**Comment by armandgrillet** [comment]
Also affects the person related to Slack user group.
