### ISSUE TITLE
show link_to_upstream_url on alert group page

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1305]
For Formatted Webhooks that specify the `link_to_upstream_url` property, it would be helpful if it displayed on the alert group's web page as a clickable link. This is typically the first place that we find that people go after getting an alert so that they can find out specific details about what is going on.

In the meantime, the "alert payload" modal contains the url, so people can find it with some digging.

**Comment by Matvey-Kuk** [comment]
Sounds like a pretty basic UX bug for me, so tagging as "Bug".

**Comment by thomasmitchell** [comment]
There is now a Source button that takes the user to the upstream alert page, so seems fulfilled to me!
