### ISSUE TITLE
Telegram connection doesn't work

### ISSUE THREAD

**Issue by tommy04062019** [grafana/oncall#1307]
In my Oncall, I configured to enable Telegram as bellow:
<img width="1438" alt="Screen Shot 2023-02-08 at 09 32 00" src="https://user-images.githubusercontent.com/8014325/217413782-0baa6f1c-0802-491b-b1f3-9ca466820c78.png">

From the user's profile, I got the info to verify with my personal bot.

<img width="1100" alt="Screen Shot 2023-02-08 at 09 34 15" src="https://user-images.githubusercontent.com/8014325/217414070-1acd05dc-9bc3-4590-9dce-74a8483e320d.png">

When I chat with my bot and send this verification code , nothing to shown, something wrong with this?How can I connect Telegram to my Oncall account?

**Comment by Matvey-Kuk** [comment]
Hey, here is a video how to configure Telegram: https://www.youtube.com/watch?v=YMDFZP7Dxns&t=12s Did you repeat all steps mentioned in the instruction?

**Comment by tommy04062019** [comment]
> Hey, here is a video how to configure Telegram: https://www.youtube.com/watch?v=YMDFZP7Dxns&t=12s Did you repeat all steps mentioned in the instruction?

Not yet, I will try this, thank you

**Comment by Matvey-Kuk** [comment]
Please re-opent the issue once you have more details.
