### ISSUE TITLE
Support new nav's breadcrumbs

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1310]
We added to OnCall new URL logic but still have one difference from Grafana core and other apps:
We don't place current page to the breadcrumbs 
![image](https://user-images.githubusercontent.com/102970268/217551265-df3ce7f8-c335-415a-8a7c-be32c37b0984.png)

Grafana has such thing:
![image](https://user-images.githubusercontent.com/102970268/217551461-3ab88a68-e1d7-48b6-b436-869b2247ce0c.png)

Will be great to unify breadcrumbs behavior with Grafana.

**Comment by jtheory** [comment]
Checking on sedemo -- it looks like both of these issues have been fixed already. @raphael-batte should we close this issue?

**Comment by maskin25** [comment]
duplicate of https://github.com/grafana/oncall/issues/1906, so I'm closing
