### ISSUE TITLE
Allow "web" type schedules from external API

### ISSUE THREAD

**Issue by nijave** [grafana/oncall#1321]
We'd like to be able to have teams manage their own schedules via the web UI while also being able to use infrastructure as code (Terraform) to provision routes and escalation policies. As such, it would be useful if we can create empty "web" type schedules from the external API so teams can go fill things in themselves. 

Related (not sure why it was disabled) https://github.com/grafana/oncall/pull/196/commits/d18d78a48f224c53827b55772edf308f077ee17e

**Comment by Matvey-Kuk** [comment]
The idea behind https://github.com/grafana/oncall/commit/d18d78a48f224c53827b55772edf308f077ee17e was to make sure that Terraform doesn't override changes made in web. Not sure how to fix that problem.

**Comment by nijave** [comment]
> The idea behind [d18d78a](https://github.com/grafana/oncall/commit/d18d78a48f224c53827b55772edf308f077ee17e) was to make sure that Terraform doesn't override changes made in web. Not sure how to fix that problem.

For my use case, I'd usually just utilize Terraform's built-in functionality for that https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

I'm mostly interested in being able to do this
```
{"team":null,"type":"web","name":"nickv-test","slack_channel_id":"H...","user_group":"G...","time_zone": "America/New_York"}
```

so I can get an On-Call Schedule ID back. We have Terraform setup to loop over a list of teams and create routes but without the ability to create a schedule we have to rely on teams naming things correctly so they can be data sourced by Terraform.

What we currently have:
- Team adds schedule or SRE goes through in the UI and adds a bunch of schedules
- Update Terraform loop with team name (submit a PR)
- Terraform automatically runs and sets up routing

What we want:
- Add all teams to Terraform (one PR)
- Teams can update schedules if they need to

In our case, some teams will immediately setup paging and on-call rotations. Other teams may look at this in coming months and leave their rotations empty or only setup Slack. We'd like the latter process where Terraform pre-provisions everything except the on-call schedule/rotation members so there's no "team on-boarding" required

At past places, I've tried to manage PagerDuty config fully with Terraform but it becomes quite tedious--especially for other teams without good Terraform knowledge

**Comment by project0** [comment]
I have a pretty similar use case: 
Adding overrides via web is not possible when the schedule is provisioned via terraform. This is very annoying as this is actually only a temporary override and requires changes in IaC. 
Only workaround is to provide additional iCal what is not very intuitive.

**Comment by matiasb** [comment]
> I have a pretty similar use case: Adding overrides via web is not possible when the schedule is provisioned via terraform. This is very annoying as this is actually only a temporary override and requires changes in IaC. Only workaround is to provide additional iCal what is not very intuitive.

Note it is now possible to setup overrides in the web UI (https://github.com/grafana/oncall/issues/828)

**Comment by matiasb** [comment]
> We'd like to be able to have teams manage their own schedules via the web UI while also being able to use infrastructure as code (Terraform) to provision routes and escalation policies. As such, it would be useful if we can create empty "web" type schedules from the external API so teams can go fill things in themselves.
> 
> Related (not sure why it was disabled) [d18d78a](https://github.com/grafana/oncall/commit/d18d78a48f224c53827b55772edf308f077ee17e)

Web schedules are enabled in the public API since https://github.com/grafana/oncall/pull/1317 (the existing PagerDuty migrator uses this).
Just in case, note that it is not possible to combine a terraform-managed schedule with web shifts.

**Comment by Matvey-Kuk** [comment]
I think we could close this one, thank you @matiasb !
