### ISSUE TITLE
Update Rotations popup doesn't seem to reflect actual rotation values

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#1322]
Steps to reproduce
- Create a new schedule
- Add a new rotation with duration of 1 month for user 1 with recurring days of Monday, Wednesday and Friday
- Add a new rotation with duration of 1 month for user 2 with recurring days of Tuesday, Thursday and Saturday

All good until now, it should look like this 
![image](https://user-images.githubusercontent.com/40542072/218777223-f98583f7-75fb-476a-ab01-c291de6465c6.png)

Try opening the rotation for user 1 and you will notice it says the repeated days are Tuesday, Thursday and Sunday (!)

![image](https://user-images.githubusercontent.com/40542072/218777414-16e55799-abb6-48a8-98ff-2d24fcd63182.png)

Do the same for user 2 and you will notice it says Monday, Wednesday and Friday

![image](https://user-images.githubusercontent.com/40542072/218777540-e08e88f5-d978-422e-b845-3688e7c4bf9f.png)

Whenever I try opening a rotation it seems the wrong days are displayed.

**Comment by Matvey-Kuk** [comment]
Good catch @teodosii ! Like your attention to details.

**Comment by teodosii** [comment]
Just checked on this one to see if it's on the frontend side, but seems to be an issue in the api response

Here's what I see when I should be seeing Monday, Wednesday, Friday

![image](https://user-images.githubusercontent.com/40542072/220614582-16e558e2-1cc9-488c-817a-aab575cfe426.png)

Normal schedule view illustrates the correct days

![image](https://user-images.githubusercontent.com/40542072/220614729-3c5f17b2-5363-46c3-b90e-520422aa941a.png)
