### ISSUE TITLE
Notify when members in rota do not have notification modes set

### ISSUE THREAD

**Issue by dannykopping** [grafana/oncall#1326]
We recently encountered a situation where a notification got escalated from L1 (engineers) to L2 (managers) due to the alert not being acknowledged. The L2 contact did not have any notification mode set for their _Important_ messages due to an oversight, and the escalation did not reach them. The alert then escalated to L3 (directors), which was unfortunate.

I propose that oncall should send a notification when any members in the rota do not have notification modes set, in a similar fashion to how the notifications for no-one being actively on-call at the moment works. This would have helped us preemptively address this misconfiguration, and avoid an unnecessary escalation to very senior staff.

**Comment by Matvey-Kuk** [comment]
I agree, also faced this problem.

**Comment by joeyorlando** [comment]
closing as duplicate of https://github.com/grafana/oncall/issues/1511
