### ISSUE TITLE
"Wait" step shows no options

### ISSUE THREAD

**Issue by navinpai** [grafana/oncall#1331]
https://user-images.githubusercontent.com/408863/219140652-2944cad9-df0f-4f51-97bc-b2dcee3ba36a.mov

Selecting a "Wait" step in Escalation Policy doesn't give any options for duration (Video attached). Unsure whether I'm missing something here

Grafana Version: `v9.3.6 OSS`
OnCall Version: `v1.1.23` _(both engine and Grafana plugin)_
```[tasklist]

```

**Comment by Matvey-Kuk** [comment]
Can't reproduce on 1.1.24
