### ISSUE TITLE
Mobile app connection doesn't work with OSS Oncall

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/oncall#1334]
I've tried to link a mobile app with my OSS Oncall instance ([v1.1.23](https://github.com/grafana/oncall/releases/tag/v1.1.23)), but it doesn't work.

`BASE_URL` is set to `https://hostname/something`, `API URL` on the Settings page looks like `https://hostname/something`

When scanning a QR code with a mobile app (Android, v0.1.5 - build 213), it makes queries to `/api/internal/v1/mobile_app/auth_token`, not respecting the path in `BASE URL`

```
[16/Feb/2023:09:21:11 +0000] <hostname> <ip> "POST /api/internal/v1/mobile_app/auth_token HTTP/1.1" 404 - "-" "Dart/2.19 (dart:io)" "-" "-" "-" "127.0.0.1:8181" 404 0.000 223 343 0.000
```

**Comment by vadimkerr** [comment]
Hi @PhantomPhreak, thank you for opening the issue!
Could you please also provide some engine logs when trying to connect?

@imtoori could you please take a look at this as well?

**Comment by vadimkerr** [comment]
One more thing, @PhantomPhreak could you please specify where this 👇  log is coming from?
```
[16/Feb/2023:09:21:11 +0000] <hostname> <ip> "POST /api/internal/v1/mobile_app/auth_token HTTP/1.1" 404 - "-" "Dart/2.19 (dart:io)" "-" "-" "-" "127.0.0.1:8181" 404 0.000 223 343 0.000
```

Is it the mobile app log or something different?

**Comment by PhantomPhreak** [comment]
@vadimkerr we have several instances of Oncall backend (Org-specific, dev/test instances) and single domain with a "white" ip, used for integration with external services (slack/telegram/twilio/etc.), thus, we're routing requests by a specific path (`/something` in the example above).
We're using NGINX Ingress on top of the Oncall backend instances, running in k8s, so that :point_up: log is ingress log, and since there are no `/api` location configured, it returns http/404. There are no engine logs, since there are no request issued to the Oncall backend.
`/api/internal/v1/mobile_app/auth_token` is requested by the mobile app, when we're expecting it to be `/something/api/internal/v1/mobile_app/auth_token`, since BASE and API URLs set as `https://hostname/something`, and text under generated QR says following:

**Comment by imtoori** [comment]
Hey @PhantomPhreak that's an interesting use case and I think I understood the issue and how to solve it
I'll release a patch next week 👍

**Comment by imtoori** [comment]
@PhantomPhreak we're releasing a new version that includes the fix

**Comment by PhantomPhreak** [comment]
@vadimkerr @imtoori thanks a lot for the quick response and fix, i've just checked recent IOS/Android apps with v1.1.26 backend - it works like a charm!
