### ISSUE TITLE
telegram: can't connect user account

### ISSUE THREAD

**Issue by kandeshvari** [grafana/oncall#1341]
* Open Source OnCall v1.1.24 helm installation

I set only telegram token. I have no public access to the oncall, so I didn't set webhook URL. As I understand from documentation I can connect user account without "full" integration, but I got this message all the time

![image](https://user-images.githubusercontent.com/2115549/219965864-051bf280-d716-462f-86d9-57d6937f831b.png)

What I'm doing wrong?

**Comment by Matvey-Kuk** [comment]
Tg personal account needs full TG installation including public access

**Comment by kandeshvari** [comment]
@Matvey-Kuk Thannks for your reply! 

Is there a "notify-only" mode in the Oncall for the Telegram that would work without public access? I don't need alert management via TG but notifications only.
