### ISSUE TITLE
Display a sample command when creating API token

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#135]
On the Grafana OnCall->Settings page when you create a new API token it would be nice if it also displayed an example curl command to make use of the token for testing instead of needing to lookup in the docs.  This would match the behavior that Grafana has when you create an API key in its settings page.

**Comment by Konstantinov-Innokentii** [comment]
Good idea, we have /info endpoint in public api. But I am wondering which url wi should use, BASE_URL from settings I guess?

**Comment by Matvey-Kuk** [comment]
We added this task to the core team's backlog.

**Comment by raphael-batte** [comment]
Some concept 

![Image](https://user-images.githubusercontent.com/102970268/177986735-13079746-4b4c-42b9-a64d-7311929b8a60.png)
