### ISSUE TITLE
Alert tag dropdown using wrong red color

### ISSUE THREAD

**Issue by torkelo** [grafana/oncall#1355]
Hi, 

Trying to align the theme / colors of apps to use the design system theme colors. 

This red here is not using the theme.colors.error.main  (and the acknowledge should be using theme.colors.warning.text if you want a good contrast text orange/warning color ) 
<img width="215" alt="Screenshot 2023-02-21 at 07 49 46" src="https://user-images.githubusercontent.com/10999/220269141-e274716a-ad05-4e23-a794-10efd5c5efbc.png">

**Comment by teodosii** [comment]
@raphael-batte ideas here? should we change the color scheme?

**Comment by raphael-batte** [comment]
This red tone was here from very beginning. 
Just checked Alerting and yes, probably we can use theme.colors.error.main for firing state and theme.colors.warning.text for acknowledge

**Comment by raphael-batte** [comment]
@torkelo I Played with this UI and think that the question about alert states has more complexity.

If we use theme.colors.error.main for Firing, probably we need to use theme.colors.warning.main for Acknowledge. But such an object looks low contrast even with max-contrast-white text inside. If we make text black, it will be different from other alert states. 

In addition to these, we have Silence state which is gray and green for Resolve. Probably this was the main reason why OnCall uses for states Tag color palette.

Below visualized the comparison using two palettes.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/102970268/220622394-e08c18a7-0ebc-4eb6-884c-134f70b50015.png">

**Comment by joeyorlando** [comment]
@raphael-batte is this issue still relevant?

**Comment by teodosii** [comment]
@joeyorlando should be addressed once we fully migrate to emotionjs. so far 1/3 of it it's been done in this PR
https://github.com/grafana/oncall/pull/4123

For reference only https://github.com/grafana/oncall/issues/2666

**Comment by joeyorlando** [comment]
going to close as I assume this was done in #2666. @grafana/grafana-oncall-frontend can you confirm?

**Comment by teodosii** [comment]
Yes, can be closed. OnCall uses same coloring as Alerting, not the ones defined by grafana styles, but the ones used to display rules/alerts in Alerting
