### ISSUE TITLE
FEATURE: Use Twilio API keys instead of Auth Tokens

### ISSUE THREAD

**Issue by Monkman08** [grafana/oncall#136]
Can we use Twilio API Credentials instead of Auth Tokens? This is an issue for us as there is only one set of Auth Tokens per Twilio account.

**Comment by Matvey-Kuk** [comment]
I see https://github.com/grafana/oncall/pull/664/files is merged, just checking if it requires documentation & ENV page update?

**Comment by mderynck** [comment]
This feature is still being tested, currently auth token is still required for call status verification.

**Comment by joeyorlando** [comment]
Closing as this was introduced in #664
