### ISSUE TITLE
Button Create iCal link in user profile requires admin permissions

### ISSUE THREAD

**Issue by dmitry-tiger** [grafana/oncall#1378]
In user profile button Create iCal link requires admin permission (OtherSettingsWrite)
Could it be reduced to editor or to viewer for owned profile?

**Comment by matiasb** [comment]
I was just double-checking this, as far as I can tell you should be able (and it seems to work) to create the export as an editor user (and the required perm to do it is `USER_SETTINGS_WRITE`). Please let us know if that's not the case or where you were checking the permission. Thanks!
