### ISSUE TITLE
LiveSettings.EMAIL_HOST is not populating from environment variable EMAIL_HOST

### ISSUE THREAD

**Issue by dmitry-tiger** [grafana/oncall#1379]
After adding EMAIL notification related settings to container environment email notification fails with error
`task_name=apps.email.tasks.notify_user_async name=apps.email.tasks level=ERROR Error while sending email: empty EMAIL_HOST env variable`
"Env Variables" page in oncall plugin shows Empty in column Status and dashes in "Value" column but values in "ENV or default" column are correct.
How values from ENV are supposed to update values in live settings? 
Celery task notify_user_async uses  live_settings.EMAIL_HOST but doesn't check env variable EMAIL_HOST
We are using OSS version 1.1.18

**Comment by Matvey-Kuk** [comment]
@dmitry-tiger settings made in the ui override ENV variables. Looks like it made an override with empty value. Resetting in the Live Settings page may help.

**Comment by dmitry-tiger** [comment]
We configure our environment using helm chart and don't do any manual steps, in our case in a result we set FEATURE_LIVE_SETTINGS_ENABLED to false to get all configuration from env values, but it is not clear from documentation that live settings are not automatically populating from environment by default. 
Probably it is good to mention that in documentation or add FEATURE_LIVE_SETTINGS_ENABLED to helm chart as variable option

**Comment by mhgao2021** [comment]
@dmitry-tiger, you did help me, thanks a lot
