### ISSUE TITLE
oncall keeps sending message about unassigned times

### ISSUE THREAD

**Issue by yasharne** [grafana/oncall#1385]
Hi
We've using grafana oncall for a while, but from few days ago, it started to send message about `There are time periods that are unassigned` almost every 20 minutes, we haven't update the oncall's version so it is odd why it start to show such behaviour.
![image](https://user-images.githubusercontent.com/7656049/220548211-f6dce5c2-0696-4a8b-ba28-d2ac21113ec8.png)
We are using opensource oncall with plugin version: v1.1.0 and engine version: v1.0.51

**Comment by Konstantinov-Innokentii** [comment]
Hello, are you using iCal schedules? If so, please, consider updating to the latest OnCall version, we fixed this bug.

**Comment by yasharne** [comment]
Upgrading fixed the issue
