### ISSUE TITLE
Source link is not the same thing as integration, can be confusing for users

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1387]
We introduced source link at the Alert Group page, but the link to source we use can be any link, because we can change it in the template. So probably better, if we will use just general button "Go to source" and do not use Integration itself

For example this alert was generated with DataDog integration, but I changed the template source link and now if user clicks DataDog it will open "google.com" it is a bit confusing
![Screenshot 2023-02-22 at 15 32 40](https://user-images.githubusercontent.com/20494436/220654397-65d8dc24-078b-4b53-9f98-9267e91e19a8.png)

**Comment by Ukochka** [comment]
Hi @raphael-batte ! We should rework a bit this button "Go to source"

**Comment by raphael-batte** [comment]
Sure! Lets discuss this usecase tomorrow morning.
