### ISSUE TITLE
Reference resources from other teams

### ISSUE THREAD

**Issue by vadimkerr** [grafana/oncall#1392]
When setting up escalation chains, it's not possible to reference resources (e.g. schedules, outgoing webhooks, etc.) from other teams. There are cases when this might be useful, for example:
-  Having a single instance of outgoing webhook and being able to use it in escalation chains for any team
- Using schedules from a different team in escalation chains

**Comment by vadimkerr** [comment]
Similar issue on sharing integrations between teams: https://github.com/grafana/oncall/issues/981

**Comment by dmitry-tiger** [comment]
+1 for this feature
we are hacked a bit source code to make webhooks from General team available to all others and it works like a charm

**Comment by vadimkerr** [comment]
Should be resolved by https://github.com/grafana/oncall/pull/1528
