### ISSUE TITLE
Shift timestamps rendered incorrectly in Slack on mobile

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#140]
![Screenshot_20220623-084450_Slack](https://user-images.githubusercontent.com/28077050/175336328-7c4bd41a-266b-4246-8625-2c4df17a16fb.jpg)

Times for shift notification are being rendered as ms instead of normal format. 
Screenshot is from Slack app, Android 10 on Samsung Galaxy S10e

**Comment by vadimkerr** [comment]
Renders correctly on iOS 15, so seems like the issue is Android specific.

**Comment by mderynck** [comment]
Docs:
https://api.slack.com/reference/surfaces/formatting#date-formatting
To recreate:
https://app.slack.com/block-kit-builder/T01TZ502XCH#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%3C!date%5E1392734382%5E%7Bdate_short%7D%20%7Btime%7D%7CFail%20to%20parse%3E%22%7D%7D%5D%7D
