### ISSUE TITLE
Frontend static config

### ISSUE THREAD

**Issue by maskin25** [grafana/oncall#1405]
So as agreed at the meeting, our plan is:
1. Store frontend static config vars in the vault
2. Values should depend on environment (dev, staging, prod)
3. Need to update deployment tools to pass those values
4. Frontend should receive values from instance plugin.jsonData (?, clarification required)
_Feel free to enrich description_

**Comment by maskin25** [comment]
the first step is to save **reCAPTCHA_site_key** [(recaptcha v3)](https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge) in the vault for dev environment, and then we will try to catch this value on frontend side, @joeyorlando can you provide the exact value of **reCAPTCHA_site_key** for dev env?

**Comment by mderynck** [comment]
In this first pass the site key is just in the environment not in vault since it isn't really a secret.
https://github.com/grafana/oncall/pull/1400
https://github.com/grafana/deployment_tools/pull/58259
