### ISSUE TITLE
Mobile app: need multiple accounts / integrations for DEV and PROD grafana oncall installations.

### ISSUE THREAD

**Issue by ksa-real** [grafana/oncall#1415]
It seems that the mobile apps (Android / iOS) cannot be integrated with multiple Grafana Oncall accounts. We have two OSS deployments: DEV and PROD. This is to roll out a new version to a non-prod environment first. The ask is to be able to add Grafana Oncall mobile app to both deployments and be able to switch between these inside the app.

**Comment by PhantomPhreak** [comment]
Having the same case with DEV/PROD OSS installations, it would be nice to have them both in the app

**Comment by Dieterbe** [comment]
what do you think of having 2 apps installed? one linked to your dev, one to your ops.
these apps could even be different versions (e.g. the beta/preview linked to dev).

does this make sense or do you still prefer to use the same app for both dev and prod?

**Comment by ksa-real** [comment]
I think both make sense:
- Two apps make sense if not trusting a new version enough. Then we can use a newer version in dev first.  I (as a user) wouldn't bother testing as there are alternative/backup escalation channels (Slack/Telegram/Cloud).
- Just for the purpose of being able to use multiple Grafana OnCall instances I would certainly prefer single app with multiple accounts. This is also consistent with other apps: Telegram - two bots, same app; Slack - two Slack apps (https://api.slack.com/apps), two channels, single Slack client application.

**Comment by Dieterbe** [comment]
this is all very useful information, thanks.
we have started designing a multi-account feature.
it will probably look something like this:
* "my oncall status / upcoming shifts" will be show an aggregated view across all your accounts
* viewing schedules, alert groups would be bound to a single account, allowing you to switch between accounts
* for settings, we're not quite sure yet. would you prefer your notification/sound settings apply across all your accounts? or do you need to differentiate them between accounts?

**Comment by cvvs** [comment]
Unique alerts per account isn't high on my list of requirements. That might be valuable for teams supporting different environments, but not for my use case.

**Comment by ksa-real** [comment]
> 

+1. Once I woke up, it is fine to use UI to check where the alert is coming from. So, for me particularly personalized settings are good to have but not critical.

**Comment by inkel** [comment]
> * for settings, we're not quite sure yet. would you prefer your notification/sound settings apply across all your accounts? or do you need to differentiate them between accounts?

I think one global setting is the best course of action right now. If I hypothesize I can imagine a scenario where I would like to have different sounds for each account, however, it could definitely be a YAGNI thing.

**Comment by wz2b** [comment]
I would like to upvote this.  My issue is similar to this, two accounts, but instead of dev/prod I actually have a work account and a home one.  I use the home one for learning, experimenting, and home automation stuff, it's kind of my R&D playground.  The work one is for some IIoT / Industry 4.0 stuff we're trying to demo for potential customers.

I prefer the same app with multiple accounts, I wouldn't mind if I had to 'switch' between them if it was easy, the main thing is to be able to receive push notifications from the other one if it's in the background / not the one I'm switched to.

Will follow this ticket for news.

**Comment by imtoori** [comment]
This has been implemented and it will be out to beta testers by the end of the week!

Here is a quick demo
https://www.loom.com/share/13791f6f27c84146b0bc9718a752124d?sid=32d313aa-3969-4a74-bb97-0d8e577160b2

Thanks everyone for requesting this feature and I'm looking forward to get some feedback :)

**Comment by ksa-real** [comment]
One complain I have about design is that it makes too much effort to switch profiles. It takes 4 taps to switch:
- Settings tab
- Tap on user name (first entry in Account section)
- Select account from the list
- Confirm account selection

I think it is better to implement this in two taps:
- Tap on profile picture (similar to Google account selection)
- Select account (no extra confirmation)
