### ISSUE TITLE
No documentation about how to edit outgoing webhooks via API

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1416]
Our docs: https://grafana.com/docs/oncall/latest/oncall-api-reference/outgoing_webhooks/
But we have TF resource so looks like its possible via API: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_outgoing_webhook

**Comment by matiasb** [comment]
Documentation has been updated to include update endpoint details (added during the new webhooks implementation release).
