### ISSUE TITLE
Docs: Add screenshots to mobile app

### ISSUE THREAD

**Issue by Dieterbe** [grafana/oncall#1446]
Hey,
I think https://grafana.com/docs/grafana-cloud/oncall/mobile-app/ would be a lot more convincing if we had some beautiful screenshots of the app on it.

perhaps a quick win is to use the same ones from https://apps.apple.com/gb/app/grafana-oncall-preview/id1669759048 even if they're a bit dated.

In the future, i'ld like to show the alert group list too, and maybe don't include the opening screen.

**Comment by imtoori** [comment]
Screenshots have been added and docs have been updated
