### ISSUE TITLE
Can't create schedules with name used by the other team

### ISSUE THREAD

**Issue by orz80i1345** [grafana/oncall#1452]
I have some problems
show ststus=400  when I am create schedules 
How can I do?

log:
msg="Request Completed" method=POST path=/api/plugin-proxy/grafana-oncall-app/api/internal/v1/schedules/ status=400

![image](https://user-images.githubusercontent.com/126868261/222691553-e43d8c39-51b2-4d15-bf16-390967efbc5d.png)

**Comment by orz80i1345** [comment]
![image](https://user-images.githubusercontent.com/126868261/222691414-fd6416cb-f9cb-4106-a212-03f36b1e65ab.png)

**Comment by Konstantinov-Innokentii** [comment]
@orz80i1345 Oh, it seems that schedule with same name exists in your organization, but  in another team. It looks like a validation bug on oncall side. You can try different name for your schedule.

Thanks for reporting!
