### ISSUE TITLE
Adapt schedules UI for users with limited permissions

### ISSUE THREAD

**Issue by maskin25** [grafana/oncall#1453]
Simplify the UI and display appropriate notifications for users with limited permissions. Context here https://raintank-corp.slack.com/archives/C0229FD3CE9/p1677835468222789

**Comment by Matvey-Kuk** [comment]
@maskin25 could you please share context here since it's a private link?

**Comment by matiasb** [comment]
Displaying user names when checking a schedule as a Viewer has been fixed (per https://github.com/grafana/oncall/issues/999), but we are still noticing this other issue https://github.com/grafana/oncall/issues/1820 (note there is now an endpoint to get user information for users in a given schedule).
Closing this one, feel free to reopen if there is anything else in mind here.
