### ISSUE TITLE
Trigger an escalation chain by calling a number

### ISSUE THREAD

**Issue by Marialehman** [grafana/oncall#1459]
Currently alerts are being sent to Grafana OnCall by webhooks and integrating alert sources. These trigger escalation chains upon firing. Some of my prospects want to trigger an escalation chain by calling a number.
Someone notices something is not working; worst case a customer files a complaint. then someone wants to notify the corresponding oncall team by calling a number. Calling the number will start the escalation

**Comment by greatvovan** [comment]
How are you going to provide details about what is not working through a phone call? Your escalation chain will receive an empty incident with no details.

**Comment by Matvey-Kuk** [comment]
Also customers mentioning a use-cases of routing incoming phone calls to on-call engineer.

**Comment by patrickamullin** [comment]
> How are you going to provide details about what is not working through a phone call? Your escalation chain will receive an empty incident with no details.

How about a voice message - I.e. recorded message invites the user to leave a voice message. This then gets escalated up the chain.

**Comment by onikolaev-impossiblecloud** [comment]
Important to mention that PagerDuty does have the feature "[Live Call Routing](https://support.pagerduty.com/docs/live-call-routing)". Would be great to have something similar. A dedicated number or a possibility to use external VoiceIP provider via API (PagerDuty may utilize MessageBird API).

**Comment by anthosz** [comment]
+1, can be really useful especially when we need a relay (central point) for direct call in addition of automatic alerts.

**Comment by MrLesk** [comment]
We also have the need of this feature.
The reason is that our on-call team has a phone number that is accessible within our organization to contact us in case of problems. It would be great if grafana oncall would keep in sync the call forwarding with the current oncall schedule

**Comment by fabiogermann** [comment]
Same use case here.

**Comment by joeyorlando** [comment]
This should be possible.

Check-out [our docs on Advanced SMS & call routing configuration](https://grafana.com/docs/oncall/latest/configure/live-call-routing/#advanced-sms--call-routing-configuration) + a [recent blog post](https://grafana.com/blog/2024/06/10/a-guide-to-grafana-oncall-sms-and-call-routing/) by @mderynck on this.

Going to close this issue out for now, but please feel free to comment back if you've tried out the call routing setup and let us know how things went for you!
