### ISSUE TITLE
Fix "Grafana Cloud OnCall" wording

### ISSUE THREAD

**Issue by Konstantinov-Innokentii** [grafana/oncall#1468]
We have different naming for "connect to cloud" feature in Phone Verification (With cloud notifications enabled) and in mobile app connection. For cloud phone notifications we suggest user to connect/use/etc. to Grafana Cloud, but for the mobile app we are naming that Cloud OnCall. In env variables tab we have setting name "GRAFANA_CLOUD_NOTIFICATIONS_ENABLED" and description "Enable SMS/call notifications via Grafana Cloud OnCall".
  So, we have three different names for one thing ( Grafana Cloud, Cloud OnCall, Grafana Cloud OnCall).
  Upd: In docs I found that for mobile app we are asking users to connect to Grafana Cloud ([link](https://grafana.com/docs/oncall/latest/mobile-app/#connect-to-your-open-source-grafana-oncall-account)) And in docs [about cloud phone calls](https://grafana.com/docs/oncall/latest/mobile-app/#connect-to-your-open-source-grafana-oncall-account) we use both Cloud OnCall and Grafana Cloud.
  
  **So, the task is to name it "Grafana Cloud OnCall" everywhere**

**Comment by alyssawada** [comment]
Closing as complete
