### ISSUE TITLE
Paggination endpoint Alerts

### ISSUE THREAD

**Issue by romanskugarevLMRU** [grafana/oncall#1476]
Hello, we have problem with work the paggintaion endpoint GET Alerts, in particalar, it shows data from first alert in system and last alert will be on last page and we must make a lot of request for import all data, or re-import all alerts.
Also if i check endpoint Alerts_group, that have another sorting, but that endpoint haven't all data what we need.
Can you change sorting or make param for reversing paggination?

**Comment by vadimkerr** [comment]
Duplicate https://github.com/grafana/oncall/issues/1031
