### ISSUE TITLE
The message when hovering the grey “Add override” button of a schedule

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1483]
Internal customer:

The message when hovering the grey “Add override” button of a schedule is not very actionable, could we somehow check if a schedule has an override calendar and mention “You can set an override using the override calendar.” or have a link to docs explaining how to do somehow?
![image](https://user-images.githubusercontent.com/3284841/223670569-784233ec-19da-41a0-9841-10c2b92f0f44.png)

**Comment by matiasb** [comment]
Tooltip messages were improved in the referenced PR.
