### ISSUE TITLE
Modal of Editing rotation is sticking to the top of the screen 

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1489]
1. Scroll to the bottom
2. Click Add rotation -> Layer 1
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/20494436/223697391-d45212ff-f4a5-4587-91d8-83c757c61766.png">

**Comment by matiasb** [comment]
This should have been fixed by https://github.com/grafana/oncall/pull/1678 (checked).
