### ISSUE TITLE
Remove incident word from frontend

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1490]
1. from URL: instead of `incidents/<id>` should be `alertgroups/<id>` or `alert-groups/<id>`
2. could you remind me another place @raphael-batte  ?

**Comment by Matvey-Kuk** [comment]
It was in routes, but removed with latest Ildar's update.

**Comment by jtheory** [comment]
The routes like https://ops.grafana-ops.net/a/grafana-oncall-app/incidents are still there in Ops
 (but I'm guessing Ildar's changes aren't deployed here yet?)

I also see "incident" mentioned in the "Mode" dropdown when creating a new Maintenance.
