### ISSUE TITLE
iCal export final schedule

### ISSUE THREAD

**Issue by matiasb** [grafana/oncall#1501]
When a schedule is exported, the final resolved shifts should be exported.
Also fix issues with sync.

**Comment by Konstantinov-Innokentii** [comment]
The code which is used in sending notifications about new shifts (recalculate_shifts_with_respect_to_priority) basically resolves a shifts between several overrides, it can be reused or at least place to start

**Comment by Matvey-Kuk** [comment]
Somehow related: https://github.com/grafana/oncall/issues/829

**Comment by devinrcheevers** [comment]
Here is some feedback I've heard from a customer in this are:

- it’s slow to update (if it updates, I’m still not sure)
- the calendars show shifts that have been overridden, and in my personal calendar
- I can’t see what schedule each shift is associated with, so I have no idea if I am primary or secondary on call

**Comment by devinrcheevers** [comment]
https://github.com/grafana/oncall/issues/1689

**Comment by devinrcheevers** [comment]
Hiya is running into sync issues, I expect this issue to solve Hiya's bug, which was filed here:https://github.com/grafana/oncall/issues/1689

**Comment by Matvey-Kuk** [comment]
Related: https://github.com/grafana/oncall-private/issues/996

**Comment by matiasb** [comment]
We are now exporting final schedule shifts (for schedules,  and also for personal exported calendars, where we include schedule name information too).

About syncing delays and issues, I have been monitoring google calendar refresh frequency and it seems to be between 12-24hs (most of the times it is around 12hs, but there are a few cases where it can take up to 24hs). Issues with sync should hopefully be solved (meaning that when a calendar is synced, removed shifts should be removed, which wasn't always the case).
