### ISSUE TITLE
(Potential issue / not sure how to reproduce) Failure to notify primary oncall when other notification failed

### ISSUE THREAD

**Issue by leveyjam** [grafana/oncall#1503]
We have configured an on-call Shadow rotation. As Shadow, I had not successfully connected my example OnCall Ap -> example Internal Slack integration, so I was not notified on Slack (and the critical warning Slack notification included an error while attempting to notify me). 

However, it also appears the Primary was not notified (although the subsequent escalation step was successful, so we're not certain if the issue can be reproduced / is related)

Our configuration for OnCall is here: <github>/deployment_tools/blob/15d884bb0aaa769f2f7a156cd41e71b540ba685f/terraform/ancillary/<example>-oncall/app_o11y/amixr.tf#L334

Alert in question: https://raintank-corp.slack.com/archives/C04R2V99A4D/p1678250987033159?thread_ts=1678250986.820499&cid=C04R2V99A4D

Log sent to Slack - failure relates to my failure to setup Slack integration, but there is a suspicion that the primary was not notified
```
0s: alert group registered
0s: alert group assigned to route ""severity": "critical"" with escalation chain "example app_o11y Critical"
3s: triggered step "Notify on-call from Schedule 'example app_o11y Primary' (Important)"
8s: triggered step "Notify on-call from Schedule 'example app_o11y Shadow'"
8s: invited [<me>@example.com](mailto:<me>@example.com) in Slack
8s: failed to notify [<me>@example.com](mailto:<me>@example.com) in Slack, because [<me>@example.com](mailto:<me>@example.com) is not in Slack
10m5s: alert group resolved
```

Please let me know if you need any other information.

**Comment by matiasb** [comment]
We debugged this and the issue was related to the primary user missing notification policies configured in their profile. However it would be good to warn about this at the schedule level as well as in the alert group log (see https://github.com/grafana/oncall/issues/1511).

**Comment by leveyjam** [comment]
Thanks @matiasb - we were just discussing the need for us to double check our notification settings - a warning would definitely help reduce the chance of a notification going astray based on who's on the schedule. 👍 
Cheers!
