### ISSUE TITLE
Quick actions when editing a schedule

### ISSUE THREAD

**Issue by matiasb** [grafana/oncall#1507]
E.g.
 - instant override (setup an override directly from an existing shift)
 - create rotation from template (predefined list of often used rotations)

**Comment by devinrcheevers** [comment]
Do when instant overrides will be released?

> instant override (setup an override directly from an existing shift)

**Comment by matiasb** [comment]
> Do when instant overrides will be released?

Updated schedule UI should get released hopefully next week.

**Comment by matiasb** [comment]
Action to allow quick overrides added to shift hover details in the mentioned release. Other actions/shortcuts will be added as separate issues.
