### ISSUE TITLE
Simple install without Docker or Helm/k8s ?

### ISSUE THREAD

**Issue by arjunnath** [grafana/oncall#152]
Hi Folks,

It would be nice to have a simple/plain install option or instructions for Oncall.
The current options all heavily imply existence of Docker/Helm/Kubernetes and this is clearly not the case in all environments.

Thanks

**Comment by Matvey-Kuk** [comment]
Hi! docker-compose.yml environment described in readme.ms usually takes a few minutes to launch, which environment you think will be easier to start with?

**Comment by arjunnath** [comment]
> Hi! docker-compose.yml environment described in readme.md usually takes a few minutes to launch, which environment you think will be easier to start with?

Similar to how we can download and launch grafana using an rpm, deb package or simple tar.gz file, like here : https://grafana.com/grafana/download

What does one do if their environment doesn't have docker ?

**Comment by xom4ek** [comment]
So you can copy script from Dockerfile and install this applications by hands and pip.

But regards diffirents between grafana and oncall.
Grafana can start without any dependency.
Oncall cant work without rabbitmq/mysql - you can find issue for `lightweight` installation here #85.

So if problem install docker to your env i suppose its not a problem just read Dockerfile/docker-compose and install all this applications by hands

**Comment by andrelop** [comment]
I think a more detailed set of instructions for those of use who want to install a production environment (not hobby) and wnat to use external tools (external Redis, MySQL and RabbitMQ, not the ones provided as part of the docker-compose stack) would be very welcome.

I for one, am struggling getting it to work correclty. There are lots of env vars which do not need to be set when using `settings.hobby`, but which need to be set when using these external tools.

I tried using `settings.heml` even though I'm not really using Heklm/Kubernetes, and had to set things like `MIRAGE_SECRET_KEY` and `MIRAGE_CIPHER_IV`, which one only learn about if reading yhe various `setting.*` files or reading the source code of Grafana OnCall.

I'm also still receiving error 403 when rtrying to active Grafana OnCall (403 on the `/api/plugin-proxy/grafana-oncall-app/api/internal/v1/plugin/self-hosted/install` endpoint then later also on `/api/plugin-proxy/grafana-oncall-app/api/internal/v1/plugin/sync` endpoint) and I'm not really sure how to solve this issue as everything I got in the logs (both on Grafana and in the engine logs) are these 403 errors.

**Comment by mmarin11** [comment]
Hi Andrelop/arjunnath I was wondering if you were able to install a production environment without the K8s/Helm. I'm trying to install Grafana oncall but facing issues due to the lack of experience with K8s :( . I simple/plain installation option would be great.

**Comment by joeyorlando** [comment]
hi there @dmgeurts 👋 there's no long term plans for the core team to maintain documentation on running OnCall outside of Docker/k8s. _However_, there exist docs in [`dev/README.md`](https://github.com/grafana/oncall/tree/dev/dev#running-backend-services-outside-docker) around "Running backend services outside Docker". This would be a good starting point!
