### ISSUE TITLE
Grafana OnCall (Preview) referred to as "Grafana IRM app"

### ISSUE THREAD

**Issue by leveyjam** [grafana/oncall#1523]
This text on the Mobile App Connection tab of /grafana-oncall-app/users/<uid> didn't help me find the App in the App Store:
```
The Grafana IRM app is available on both the App Store and Google Play Store.
```
Viewing the page on a laptop and searching the App Store on mobile for "Grafana IRM" returned no results, but "Grafana OnCall" did - could the text be updated to refer to "The Grafana OnCall app" for anyone who is trying to find it by searching?

<img width="1026" alt="Screenshot 2023-03-10 at 11 14 48" src="https://user-images.githubusercontent.com/121335650/224289735-fff0a9cf-d19f-4536-a68b-8ffe9113f36b.png">

**Comment by maskin25** [comment]
@imtoori and @Dieterbe should we either rename it on the page above or make it findable by  "Grafana IRM" or both...

**Comment by imtoori** [comment]
I think we should fix the text in the web ui
I'll make sure we do this asap

**Comment by maskin25** [comment]
nice, you can update the text here https://github.com/grafana/oncall/blob/03663ea3196f53629f8e0bb860584481759d8392/grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/index.tsx#L20
