### ISSUE TITLE
not connecting via https

### ISSUE THREAD

**Issue by v7enov91** [grafana/oncall#153]
oncall hobby not connecting via https to existing grafana, 
![oncall-error](https://user-images.githubusercontent.com/108201474/175794509-066b1af8-696b-49ea-9189-7bed5e11dec1.png)
grafana v9.0.1

**Comment by Matvey-Kuk** [comment]
@v7enov91 could you please try entering the OnCall engine docker container (using "exec") and try "curl -V" grafana url? What will you see?

**Comment by v7enov91** [comment]
root@oncall:/home/oncall-admin# docker exec -it 39fb0d79e549 bash
bash-5.1# curl -V htts://<grafanaurl>:3000
bash: curl: command not found

**Comment by Matvey-Kuk** [comment]
@v7enov91 I guess you need to do smth like "apk add curl"

**Comment by v7enov91** [comment]
container logs:

**Comment by v7enov91** [comment]
2022-06-26 10:21:25 source=engine:app google_trace_id=none logger=apps.grafana_plugin.helpers.client Error connecting to api instance HTTPSConnectionPool(host='grafanaurl', port=3000): Max retries exceeded with url: /api/org/users (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by v7enov91** [comment]
bash-5.1# curl -V "htts://grafanaurl:3000"
curl 7.83.1 (x86_64-alpine-linux-musl) libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by v7enov91** [comment]
bash-5.1# curl "htts://grafanaurl:3000"    
curl: (1) Protocol "htts" not supported or disabled in libcurl

**Comment by v7enov91** [comment]
i'm sorry
curl "https://grafanaurl:3000"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by v7enov91** [comment]
curl -vs https://grafanaurl:3000
*   Trying grafanaip:3000...
* Connected to grafanaurl (grafanaip) port 3000 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

**Comment by v7enov91** [comment]
after :
bash-5.1# cp DigiCertGlobalRootCA.crt.pem /usr/local/share/ca-certificates
bash-5.1# update-ca-certificates                                          
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Global_Root_CA.pem

**Comment by mttradebyte** [comment]
Did you ever figure this one out? I also have the same issue currently. Curl works just fine, but it doesn't connect 🤷

**Comment by v7enov91** [comment]
Hello, after replacing Rapid SSL certificate to free LetsEncrypt on grafana, oncall plugin connected normally.

**Comment by Matvey-Kuk** [comment]
@v7enov91 thank you!

**Comment by mingaliev-e** [comment]
how to connect self-signed certificate ?
