### ISSUE TITLE
Integration searching has weird behaviour

### ISSUE THREAD

**Issue by Konstantinov-Innokentii** [grafana/oncall#1536]
1. Open "Create Integration" modal
2. Type anything there ( Some random text always cause that bug, when no integration found)
3. Zabbix intergation logo will stuck, multiply, etc.
![image](https://user-images.githubusercontent.com/20221722/224897951-79d6c08b-0cda-4718-959a-db1580b83cf0.png)

**Comment by joeyorlando** [comment]
The duplicate Zabbix integration is being handled in https://github.com/grafana/oncall-private/pull/1692 and https://github.com/grafana/oncall/pull/1579.

However, there is still a separate issue with using the search input to filter inputs (this appears to be done solely on the frontend). I've renamed this GitHub issue to track this bug.

**Comment by joeyorlando** [comment]
actually this can be closed, https://github.com/grafana/oncall-private/pull/1692 fixed this. I re-tested locally and can no longer reproduce this.
