### ISSUE TITLE
Slack Integration i.e  connect to slack workspace option not showing in Chatops tab

### ISSUE THREAD

**Issue by amitshr6779** [grafana/oncall#1573]
Slack Integration i.e  connect to slack workspace option not showing in Chatops tab

Unable to connect to slack as no option of connect is showing.

 **FYI** : I am using Oncall PlayGround Environment

![Screenshot from 2023-03-20 13-25-21](https://user-images.githubusercontent.com/84858868/226280003-46f7a3b5-b49b-49bf-82be-d4be07e99689.png)

**Comment by Konstantinov-Innokentii** [comment]
@amitshr6779 Hey, did you followed the https://grafana.com/docs/oncall/latest/open-source/#slack-setup doc?
