### ISSUE TITLE
Filter alert groups by title.

### ISSUE THREAD

**Issue by jeschkies** [grafana/oncall#158]
Is it possible to filter alert groups by title? I could not find that option
![image](https://user-images.githubusercontent.com/2418440/175982902-17835d34-daa0-4a9e-a9ce-23737bb0c0cc.png)

**Comment by mderynck** [comment]
You should be able to type into that box and it will search alert group text including the titles. 
We should probably improve how that is presented and communicated to the user.

**Comment by raphael-batte** [comment]
@mderynck filtering option will be useful in the list. But usually this functional is on the table title as additional icon
![image](https://user-images.githubusercontent.com/102970268/176210382-2eef8e1f-669d-407e-9b6a-4320889ca0b1.png)

**Comment by raphael-batte** [comment]
Just quick idea 
![image](https://user-images.githubusercontent.com/102970268/176211371-8648fa20-a86a-4283-a0c9-c3a1ff576b4d.png)

**Comment by raphael-batte** [comment]
@jeschkies Yes, agree. 1000+ items list is really hard to navigate directly without additional filtering. The most common pattern here is to filter items by one or more criteria (for example by incident status Firing) and sort remaining positions by column Title or other. 

Can you please describe your current use-case?

**Comment by Matvey-Kuk** [comment]
Closing this since filtering by title is there :) 

https://user-images.githubusercontent.com/3284841/176725097-97741a41-4438-4db5-9ff8-f3ec2d851813.mp4
