### ISSUE TITLE
MS Teams integration doc 

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#159]
Add new doc to support the newly released MS Teams chatops integration with Grafana OnCall

**Comment by jeremyruffell** [comment]
Would love to see this!

**Comment by alyssawada** [comment]
This issue was left open by mistake and should have been close on June 29. This work was completed in [PR 168](https://github.com/grafana/oncall/pull/168). The Microsoft Teams integration doc can be found at https://grafana.com/docs/grafana-cloud/oncall/chat-options/configure-teams/
