### ISSUE TITLE
Refresh incident page with filters

### ISSUE THREAD

**Issue by jeschkies** [grafana/oncall#161]
How would I update a page showing all incidents for an integration with a status filter? If I reload the filters are gone.

**Comment by Matvey-Kuk** [comment]
@maskin25 @Ukochka what do you think? 😊

**Comment by maskin25** [comment]
@jeschkies sorry for late response, actually it was a bug, it's fixed now, you can reload page and filters will not be cleared

**Comment by jeschkies** [comment]
It's working :tada:
