### ISSUE TITLE
[Grouping&Templating] Move the creation of integration from popup to Drawer

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1621]
https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=4167-89171&t=7OoE9YlUNl1xUF2i-0
 
Now we have a modal for creating an integration, we need to transition it to the drawer

**Comment by greatvovan** [comment]
The link is inaccessible for me.
