### ISSUE TITLE
[Grouping&Templating] Create an integration landing page 

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1622]
https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=4167-89171&t=7OoE9YlUNl1xUF2i-0

1. Create a page
2. Integration Link
3. Buttons for Editing Groups/Templates/Alert Behaviour
4. NO ROUTE work yet

**Comment by greatvovan** [comment]
The link is inaccessible for me.

**Comment by joeyorlando** [comment]
Closing as not enough details
