### ISSUE TITLE
[Grouping&Templating] Add Route configuration to the integration landing page

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1623]
https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=4167-89171&t=7OoE9YlUNl1xUF2i-0

Add all the functionality we have now
Create a tree view for the page with collapsable elements
Check backend if it has new data for routing

**Comment by greatvovan** [comment]
The link is inaccessible.

**Comment by maskin25** [comment]
@Ukochka do we have any updates here?
