### ISSUE TITLE
[Grouping&Templating] Create a component for list of alerts and payloads

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#1624]
https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=6501-126023&t=7OoE9YlUNl1xUF2i-0

[Left side of the modal]
This component will be used at all 3 modals with Grouping/Templating/Alert behaviour
When you click on the alert you should see the payload

**Comment by greatvovan** [comment]
The link is inaccessible.
