### ISSUE TITLE
Performance Issue in GSelect component when searching

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#1628]
See [here](https://www.loom.com/share/45a4244d99d24e06b435ca39b97de094) for detailed explanation/reproduction steps.

In addition, we should remove [these lines](https://github.com/grafana/oncall/blob/dev/grafana-plugin/integration-tests/utils/forms.ts#L92-L97) in the `selectDropdownValue` e2e tests helper function (was a temporary workaround for this issue and will no longer be needed once this is patched).

**Comment by maskin25** [comment]
@joeyorlando seems [this link ](https://www.loom.com/share/45a4244d99d24e06b435ca39b97de094)is broken

**Comment by joeyorlando** [comment]
@maskin25 ah yes. Loom only let me keep a certain number of videos. I probably deleted that one. whoops.

I think overall it was just showing the network pane and each HTTP request on key-down.

**Comment by joeyorlando** [comment]
@maskin I believe this was deployed in #2466, closing this
