### ISSUE TITLE
Schedules has missing users

### ISSUE THREAD

**Issue by simonswine** [grafana/oncall#1634]
When I am looking at schedules (that I am no longer or not necessarily part of) in the Grafana Labs internal ops environment: 

I am unable to retrieve the user information, so some blocks in the calendar view stay empty.

* Version r105-v1.2.2
* I tested 3 different schedules all have the same problem
* I have the same issue in Chromium 111.0 and Firefox 111.0.1
* Grafana shows "You do not have permissions to perform this action"
* The console shows that 403 are generated for some user calls

#### Screenshots

I have tried to remove a few things that are identifying people. The purple block shows the correct users, while the others stay empty.

![image](https://user-images.githubusercontent.com/223048/227999693-1b0916a1-b697-4493-a816-816b97e6bfd6.png)

![image](https://user-images.githubusercontent.com/223048/227999873-403d8521-251d-4fc5-8d85-422c979b41e6.png)

![image](https://user-images.githubusercontent.com/223048/227998758-368fd6e1-5402-4811-a3fa-4df0be5eba6f.png)

**Comment by thomasmitchell** [comment]
might be related to #999

**Comment by matiasb** [comment]
As mentioned, this looks like #999 which was fixed and released in [1.2.4](https://github.com/grafana/oncall/releases/tag/v1.2.4). Closing this one, but feel free to re-open if you still experience the issue.
