### ISSUE TITLE
Status Column of Users Page Showing Warning Symbol with No Warnings

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1636]
The status column of the users page in the plugin still shows the warning symbol for users with no warnings. I imagine this is because the display of the Telegram warning has been removed (thank you!), but it still counts as the user having a warning despite that.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/12000017/228049697-dab4ef9a-f60b-4c57-8bf1-8ba74f208967.png">

Open Source OnCall
Plugin version: v1.2.2
Engine version v1.2.2

**Comment by matiasb** [comment]
This seems to have been fixed, closing.
