### ISSUE TITLE
When adding a schedule rotation, via the UI, the rotation layer sometimes disappears randomly

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#1655]
[ae5206ab2b2be6045c3574f5909833983a0f9162.webm](https://user-images.githubusercontent.com/9406895/228458205-75c18c3a-7d06-40f3-82e0-7ffac7c2855b.webm)

1. Download the Playwright test report for [this failing build](https://github.com/grafana/oncall/actions/runs/4545145398/jobs/8012313310#step:17:23) by clicking [here](https://github.com/grafana/oncall/suites/11865803208/artifacts/620465507)
2. Run the following command against the `.zip` you just downloaded
    ```bash
    unzip playwright-report-grafana-main.zip -d playwright-report && cd playwright-report && python -m http.server
    ```
3. In your browser, visit [here](http://localhost:8000/#?testId=7a91e0f0d0609bcf5c48-cc5b6c5d31c275a6de7b). The test trace is very useful here and can be visited [here](http://localhost:8000/trace/index.html?trace=http://localhost:8000/data/4ee7ba8613609fcf7274de367f373ea88842b02f.zip). Particularly take a look at the last two steps in the trace, the rotation layer never appears in the UI. The network pane can also be useful for debugging:
<img width="589" alt="Screenshot 2023-03-29 at 09 24 32" src="https://user-images.githubusercontent.com/9406895/228457805-3816d1b5-1b3d-43ab-91c9-e0bf54ecef14.png">

**Comment by matiasb** [comment]
[This change](https://github.com/grafana/oncall/pull/2279) may help with this issue too (since the refresh in the backend was async, a web update could miss a change in rare circumstances).

**Comment by Matvey-Kuk** [comment]
Should be fixed with the latest release.
