### ISSUE TITLE
Multiple Routes within Integration Need to be Capable of Posting the Same Alert to Different Teams Channels

### ISSUE THREAD

**Issue by sdg4754** [grafana/oncall#1660]
Currently, if you devise a route, it is evaluated such that an action is taken on that route and anything not caught by that route gets a different escalation/treatment.

We need to have two equivalent routes, and take different action on the alerts caught by these routes - that is to say, post them to different MS Teams Channels.

If / else logic doesn't work here.  We need if / also if / else logic for evaluation of routes within the integration.

Another solution would be to include the ability to post to different Teams channels as escalation line items.  Then one single route could escalate by postings to two different channels simultaneously.

**Comment by Matvey-Kuk** [comment]
@azkore this issue violated issue formatting requirements: https://github.com/grafana/oncall/blob/dev/.github/ISSUE_TEMPLATE/issue-template.md
