### ISSUE TITLE
Sending a demo alert shows two notifications

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#1662]
**Steps to reproduce**
1. Create an integration
2. Click "Send demo alert"
3. You should see the following. If you go to the alert group's page you'll notice only one alert group was indeed created, but there were two notifications
<img width="608" alt="Screenshot 2023-03-29 at 20 40 04" src="https://user-images.githubusercontent.com/9406895/228736355-ab640fab-e76d-400b-9857-905812c50981.png">

**Comment by greatvovan** [comment]
Your first item

> Create an integration

– of which type???
I tried a few, including Grafana and web hooks, but could not reproduce the issue.

**Comment by joeyorlando** [comment]
@greatvovan this was likely on an older version of grafana. I'm also not able to reproduce on the `grafana:main` published image (as of this writing). Going to close this issue w/ that said.
