### ISSUE TITLE
Cannot see name and delete icon for schedule rotation

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#1683]
When a schedule rotation has several groups, you cannot see the rotation title, or delete icon:
<img width="780" alt="Screenshot 2023-03-31 at 11 30 51" src="https://user-images.githubusercontent.com/9406895/229083343-da7d7020-47d4-41b7-8000-db851ef1373e.png">

**To reproduce**
1. An example schedule is [this one](https://ops.grafana-ops.net/a/grafana-oncall-app/schedules/SV7S7TE9IAJPT)
2. Go to the week of "03 Apr - 09 Apr" in the schedule
3. Try clicking on my name in "Layer 1" of the rotations

**Comment by matiasb** [comment]
This seems to have been fixed along this one https://github.com/grafana/oncall/issues/1489.
