### ISSUE TITLE
Provide vCard for OnCall, including automatic management via Grafana OnCall App

### ISSUE THREAD

**Issue by devinrcheevers** [grafana/oncall#1688]
Provide the ability to automatically update Grafana OnCall phone and SMS numbers via a vCard.
Provide a weblink to download vCard.
Provide automatic updates of vCard via OnCall mobile app.

**Comment by greatvovan** [comment]
Can you elaborate, are you suggesting to allow users to configure their their numbers from a vCard? Or to be able to download the number you are receiving calls from the system? If latter, I noticed that the calls are incoming from different numbers and different locations all around the world, so it's impossible to have a single vCard for OnCall at this moment.

**Comment by devinrcheevers** [comment]
@greatvovan thanks for comment, this request was from a customer of Grafana OnCall, I was logging it here to track the world, I'm the product manager for OnCall!

I assume it would be something similar in implementation this https://support.pagerduty.com/docs/notification-phone-numbers

**Comment by devinrcheevers** [comment]
re: Country specific vCards, I'm not 100% sure on implementation, but I would expect it to support at least the country I'm based in as a user.
