### ISSUE TITLE
Query Primary ical exports not updating when terraform changes

### ISSUE THREAD

**Issue by ywwg** [grafana/oncall#1695]
This is the internal version of Oncall (cloud?). 

We use terraform to create our rotation, and when we make changes to the terraform those changes are not reflected in the ical exports we use. We have to revoke the export and recreate it. This is clunky because every member of the team has to know to do this or they will be looking at an incorrect version in their google calendar. Overrides are correctly reflected in the exported calendars, however.

discussed in #gops-oncall here: https://raintank-corp.slack.com/archives/C0229FD3CE9/p1680531423829939

linked to: https://github.com/grafana/oncall/issues/1501

**Comment by matiasb** [comment]
This should be improved per https://github.com/grafana/oncall/issues/1501#issuecomment-1527872565. As mentioned there, there is a 12-24hs delay between refreshes from google that are out of our control; nonetheless, there were sync issues that should hopefully be fixed now. Feel free to re-open if you notice any problems.
