### ISSUE TITLE
request /api/plugins/grafana-incident-app/settings return 404

### ISSUE THREAD

**Issue by guetbh** [grafana/oncall#1711]
hello
When I open the On-call alerting page for incident management, it shows a 404 error.
<img width="1755" alt="image" src="https://user-images.githubusercontent.com/26177357/230431792-606d29ed-3323-4ec4-9e59-7c3f4b3211bf.png">
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/26177357/230431948-eee26f2e-01f0-4d81-ab29-862e35a6ed90.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/26177357/230431997-584da54f-f018-424c-bb15-9b1086c3da45.png">

please help me check that error.

I tried multiple versions:
grafana-oncall-plug version :1.4.1
grafana-oncall backend version : 1.4.1
grafana version : 8.5.15
grafana-oncall-plug version :1.2.7
grafana-oncall backend version : 1.2.7
grafana version : 8.5.15

**Comment by Konstantinov-Innokentii** [comment]
This error should not impact oncall. The reason is that oss version tries to make request for integration with incident plugin, which is available only for OSS.

**Comment by guetbh** [comment]
thank you
