### ISSUE TITLE
Scheduled maintenance support

### ISSUE THREAD

**Issue by freeseacher** [grafana/oncall#173]
As for now we only have an ability to create maintenance that starts right now. 
As owner of service i would like to create scheduled maintenance that will start at some time in future. 
It would be really great if every scheduled maintenance would have some kind of workflow attached to it for example simple approval would be greatly appreciated.

**Comment by Matvey-Kuk** [comment]
Maintenance could be started over API as a temporary solution

**Comment by joeyorlando** [comment]
Going to close as a duplicate of https://github.com/grafana/oncall/issues/1919 (please feel free to continue discussing over there)
