### ISSUE TITLE
ChatOps tab not loading [v1.2.7]

### ISSUE THREAD

**Issue by AlbertasG** [grafana/oncall#1735]
ChatOps page does not load or perform any network requests when selecting ChatOps tab. Tested on both Firefox and Chrome.

Edit: Other functionality works: Schedules, Escalation chains, Integrations, etc.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/27416848/231472069-371b3a3e-232e-4e60-acf6-0559c8b7a904.png">

- [OpenSource ]
- [v1.2.7] 
- [`part:chartops`]
- [bug]

**Comment by AlbertasG** [comment]
Tried with `v1.2.9` also same behaviour.

**Comment by xom4ek** [comment]
Same problem with 1.1.41 
![telegram-cloud-photo-size-2-5251325628442069318-y](https://user-images.githubusercontent.com/29627495/233379013-e74fd777-9c50-4cc0-92ea-10e0ce8c8e61.jpg)

Downgrade to 1.1.40 fix problem
![telegram-cloud-photo-size-2-5251325628442068764-y](https://user-images.githubusercontent.com/29627495/233379071-92c82574-a6fc-4020-a4cb-1b62ed3f5ddd.jpg)

**Comment by baracoder** [comment]
Still occurs on 1.2.41

**Comment by teodosii** [comment]
@baracoder Hi there! Can you post your response for this request? `[your-instance]/api/plugin-proxy/grafana-oncall-app/api/internal/v1/features/`? I just checked what the ChatOps tab renders and if you don't have any chatops feature enabled (such as Slack/Telegram), then that will not show up there, most likely resulting in an empty display

**Comment by baracoder** [comment]
@teodosii I totally missed the feature toggle :see_no_evil:   - the slack feature was not enabled. 
```
["grafana_cloud_connection","grafana_cloud_notifications"]
```
With the feature enabled, it works

**Comment by Ukochka** [comment]
Seems this bug is not relevant anymore.

**Comment by teodosii** [comment]
We will now be showing this banner with links to slack/telegram docs if the env vars are set to false 
![image](https://github.com/grafana/oncall/assets/40542072/1d4a186b-7ec5-456f-b068-aae4bcc80b68)
