### ISSUE TITLE
create silece for alert till next working hours

### ISSUE THREAD

**Issue by freeseacher** [grafana/oncall#174]
Lots of small p5 alerts can wait till next working hours. 
As schedule owner i would like to setup some kind of working hours or time to debug and close low priority alerts.  something like 
notify mon: 9-18, tue: 9-18... fri: 9-18, sat, sun do not notify
and two option notify if still firing, notify anyway.

of cause low priority alerts lead to alert fatigue and must me eliminated but still popular case

**Comment by raphael-batte** [comment]
@freeseacher We plan to add 'working hours' time for users in our upcoming scheduling tools. @Matvey-Kuk Probably, we should to add additional notification options in user settings as well.

**Comment by raphael-batte** [comment]
Something like this in user settings
![image](https://user-images.githubusercontent.com/102970268/176444267-ee0895f0-ec02-4e50-a560-9f21f81e81b6.png)

**Comment by freeseacher** [comment]
:thinking:. that settings sounds very opinionated for me.
what is low-priority? how do they defined ? 
for me that is not personal setting but option in silence 
![image](https://user-images.githubusercontent.com/289277/176445909-6ca82615-0c85-46bd-9c38-1b73a99bd46e.png)

or part of alert proccessing before escalation 


as for me i see them throw prism of another product like this 


![image](https://user-images.githubusercontent.com/289277/176445669-5178bcb2-b780-4025-b0b8-d5a926556390.png)

**Comment by raphael-batte** [comment]
@freeseacherhow do these settings work if there are people in different timezones with different working hours in the schedule?

**Comment by freeseacher** [comment]
great question! 
i believe that notification should be delivered as fast as possible. so it should be delivered to someone who is on call first

**Comment by Matvey-Kuk** [comment]
@raphael-batte we have this concept on the Escalation Chain level (with time), why do you think it should go to the Notification Level?

**Comment by raphael-batte** [comment]
@Matvey-Kuk I am not suggesting removing the silence from the OnCall escalation chain level. 
But if users need local time silence, it should be on profile level.

Example: 
1. We have an escalation chain with silence step, the server time is Tel Aviv TZ
2. At 9:00 a.m. monday we restart the chain, but at this time we have an engineer from New York oncall, who is now outside of his working hours.

If he does not have personal silence option in user-settings, he will receive an alerts.

**Comment by Matvey-Kuk** [comment]
Time-based silence in the user space will mean "we escalate to a user" -> "user reacts in a few hours". 

It's a pattern we generally want to avoid project-wise. We don't want alerts to "stick" to users for multiple hours. The goal of OnCall is to be an effective alert distributor between team members. What if the user will go to a vacation after the timeout? How to indicate the reason of long response delay to other users?

I believe in this particular case the alert should stuck on the escalation chain, or be routed to the other person if there is a time-zone distributed team immediately. 

So I think we either should think of improving our Calendar either about adding more adjustable escaltion step.

**Comment by raphael-batte** [comment]
Yes, this is the other side of this situation. Agree with the need to rethink/improve the transition mechanic here.

**Comment by joeyorlando** [comment]
@freeseacher I _think_ this should now be achievable with the custom silence durations:
![Screenshot 2024-06-14 at 13 14 41](https://github.com/grafana/oncall/assets/9406895/f63fd0fb-360c-463b-87fa-cf67613e16bd)
![Screenshot 2024-06-14 at 13 14 44](https://github.com/grafana/oncall/assets/9406895/3c85ce1a-d688-433a-9ab6-de1838a62e5a)

I'll go ahead and close this out but feel free to open a new feature request if this does not suit what you need!
