### ISSUE TITLE
iCal export is getting non-synced with Google Calendar

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1758]
Multiple customers reporting our iCall export not getting pulled by Google Calendar. The problem is not on OnCall side, but bothering OnCall users a lot. The only one possible solution I see is to rewrite using google's API. It's a huge rewrite and will make the solution incompatible with other calendar systems like MS Outlook & others.

Opening the issue to crawl ideas about what to do.

This issue is related to https://github.com/grafana/oncall/issues/1501, but 1501 is mostly about exporting the correct schedule. This issue is about sync problems.

**Comment by pr00se** [comment]
possibly related: https://github.com/grafana/oncall/issues/1695

**Comment by matiasb** [comment]
This should be improved per https://github.com/grafana/oncall/issues/1501#issuecomment-1527872565. As mentioned, there is a 12-24hs delay between refreshes from google that are out of our control; nonetheless, there were sync issues that should hopefully be fixed now.
