### ISSUE TITLE
Back button in alertgroup doesn't persist filter

### ISSUE THREAD

**Issue by renrutmas** [grafana/oncall#1769]
- Open source
- Version 1.2.11
- bug

To reproduce: set your filter e.g. status = Firing; go into an alert group; click the back button; filter will have reset back to default i.e. all alert groups.

**Comment by tommysitehost** [comment]
A regression from this issue: https://github.com/grafana/oncall/issues/482. I tried to apply the same fix from this PR: https://github.com/grafana/oncall/pull/1311 but it doesn't work.

**Comment by greatvovan** [comment]
That's an annoying issue that appeared recently.
I would add that the filters should be persisted not only when navigating through the list back and forth, but also between user sessions (through cookies or somehow).

**Comment by iskhakov** [comment]
fixed  by https://github.com/grafana/oncall/issues/1433
