### ISSUE TITLE
Update onboarding path in UI to make it more accurate.

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1771]
Today we have such view as onboarding visual on the pages. 
![image](https://user-images.githubusercontent.com/102970268/232708461-b03d6215-9e34-4381-97af-37bd898cd6c3.png)

Will be nice to change order to make it more relevant to reference path:
- Connect to your chat workspace
- Add your team calendar to define an on-call rotation.
- Setup escalation chain to handle notifications
- Add integration with a monitoring system
- OnCall manages your alerts

**Comment by greatvovan** [comment]
Those are prerequisites and can be done in any order IMO.
My personal order was like on the screenshot, and I cannot say it was bad.

**Comment by raphael-batte** [comment]
@greatvovan there are a real use-cases where user start to use OnCall from scratch, creates integration and has a dead end, because it's not possible to escalate it without chain.

**Comment by greatvovan** [comment]
You can define a chain right from the UI of an integration, not sure how this particular connection could be missed.

I mean one can get stuck to a dead end with any sequence, you never know. I just personally find the existing sequence "from the source to the destination" more logical, like making your way to where you need to, while your way is reversed. And it's a minor thing anyway. In case of problems one will reach out to community or support.
