### ISSUE TITLE
Timeouts on "Mine" endpoint in the mobile app

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#1780]
Filing issue based on customer report, I guess r119-v1.2.11 is affected:
<img width="317" alt="Screenshot 2023-04-18 at 14 48 22" src="https://user-images.githubusercontent.com/3284841/232767848-054f527a-e79d-422a-bf53-05677cb797c0.png">

Kindly asking to investigate performance of this endpoint & set tight SLO for mobile API endpoints + set alerting.

**Comment by Matvey-Kuk** [comment]
Comment from @imtoori : it's not mobile specific, possible degradation on the whole alert groups endpoint.

**Comment by iskhakov** [comment]
This issue was fixed
