### ISSUE TITLE
Transition OnCall plugin to use Grafana service account

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#1806]
This issue is for tracking transitioning the OnCall plugin to use a service account instead of API key for communication with the OnCall backend. We should still keep the API key code and use it for older versions that do not support service accounts.

More info about API key deprecation: https://github.com/grafana/grafana/issues/53567

**Comment by robinsmedberg** [comment]
How is it going with this one? We are having problems with "Invalid API key".
Is there currently any work around? Or Grafana + OnCall versions that work together?

**Comment by mderynck** [comment]
Hi @robinsmedberg! Can you enter a separate issue describing the problem you are experiencing with Invalid API key?  Changing to service accounts in the OnCall plugin code has not been prioritized as API keys have remained compatible.

**Comment by robinsmedberg** [comment]
@mderynck Our problem is very similar to https://github.com/grafana/oncall/issues/1876

We made a clean install of Grafana (v9.2.19) + Oncall (v1.2.41) (external postgres, included redis).

After we restarted the Oncall engine the "Invalid API key" error returned.
