### ISSUE TITLE
Purpose of Level in Schedule

### ISSUE THREAD

**Issue by vakhariad** [grafana/oncall#1819]
-  Open Source OnCall.
-  Info.
-  Version:1.2.6

While creating an OnCall Schedule, if I add a user to say L0 and add another one to L1, user on L1 will be notified. In such a scenario, I am unable to understand the purpose of Levels in schedule, if it'll only notify those at higher Levels. I've gone through the docs but couldn't find anything related to that.

**Comment by alyssawada** [comment]
Closing as stale
