### ISSUE TITLE
Maintenance page does not respect teams 

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#183]
## Description
1. Maintenance page shows all the maintenances from all teams
2. If integration does not belong to the team it's name not displayed in the table
3. If integration does not belong to the team it's not possible to stop it
## Steps to reproduce
1. In Grafana OnCall choose Team 1 in the top right corner
2. Create any integration on the Integrations page
3. Create a maintenance on Maintenance page
4. Switch to Team2
5. Try to stop maintenance 
## Screenshot
<img width="1275" alt="Screenshot 2022-06-30 at 17 22 27" src="https://user-images.githubusercontent.com/2262529/176701821-23297d09-e76c-452c-aedb-c3cd84e33eb5.png">

**Comment by ryanisnan** [comment]
Thank you for this!
