### ISSUE TITLE
The escalation chain should not need to be assigned to the same team as the integration.

### ISSUE THREAD

**Issue by Espigah** [grafana/oncall#1851]
Open Source OnCall
Backend/Frontend v1.2.16
Feature Request
part:Integrations
involved:Backend

Does it make sense to have a lock that only works for API (+ Terraform) and doesn't work for the user interface?

![image](https://user-images.githubusercontent.com/489612/235173803-3e92b6f7-9856-4e62-8111-931297cea3b4.png)
![image](https://user-images.githubusercontent.com/489612/235175890-c81919b1-03f7-4e22-a89d-b701e2dcb0df.png)

This scenario makes it quite difficult to use Terraform where I have an integration with Alertmanager for multiple teams and their escalations.

**Comment by wstiehler** [comment]
I have the same problem over here!

**Comment by Espigah** [comment]
I created this repository to reproduce the behavior
https://github.com/Espigah/grafana-oncall-1851

**Comment by iskhakov** [comment]
fixed by https://github.com/grafana/oncall/pull/2606
