### ISSUE TITLE
Unable to connect Slack account to User in Grafana Oncall UI (no 'connect' button)

### ISSUE THREAD

**Issue by Milamary** [grafana/oncall#1855]
Hi!
Having issue with connecting Slack account to User in Grafana Oncall UI (no 'connect' button).
We're using Open Source Grafana Oncall helm installation:  grafana/oncall:v1.2.15
 
<img width="1079" alt="Screenshot 2023-05-01 at 3 19 38 PM" src="https://user-images.githubusercontent.com/118387423/235524596-5d627ef2-cdae-47b0-bc8a-818a7779520a.png">

When trying to Create manual alert group to trigger Slack notification, this user cannot be invited to Slack channel:

<img width="406" alt="Screenshot 2023-05-01 at 4 06 09 PM" src="https://user-images.githubusercontent.com/118387423/235531889-f58d7677-af67-4148-b0c7-f319711dab99.png">

**Comment by iskhakov** [comment]
Fixed
