### ISSUE TITLE
Annoying Slack Ping on Resolving Alerts

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#187]
When you close an alert it tags the person who resolved it in the thread. When closing even a single alert, I get a ping from slack about it. However I obviously know that I resolved the ticket, so why do I need to get tagged about it. This makes slack unusable when we have to close multiple alerts, and slack blows up and pushing our real conversations below a wall of pings about resolved alerts.
Please make an option to not tag the person who resolved an alert.
![image](https://user-images.githubusercontent.com/77802/176759236-e1eb12f2-1edf-46b3-a57b-2738f375999e.png)

**Comment by qubitspace** [comment]
We had another developer encounter this and post some feedback, adding it to try to get some traction here. It is a bigger issue that it might appear on the surface as slack is such as important tool for for developers, and losing your thread history because of a bunch of alerts is very frustering.
![image](https://user-images.githubusercontent.com/77802/188777477-31462912-db9e-4c1c-979c-ef461b3edcb2.png)

**Comment by Matvey-Kuk** [comment]
Also worth thinking about removing tags in mentions after alert is resolved. It's polluting slack's "Threads" stack a lot.
<img width="555" alt="Screenshot 2022-10-11 at 15 56 39" src="https://user-images.githubusercontent.com/3284841/195096877-38aa2b80-1445-4a6e-81a0-d7e2a92b8263.png">
