### ISSUE TITLE
/escalate slack command should show teams that you are not a member of, but that have "All Users" access

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1886]
Open Source OnCall
Backend/Frontend version: v1.2.16

The Slack command /escalate filters escalation chains, responders, and schedules by the team dropdown. If one of these objects that you'd like to escalate to is assigned to a team, but you are not assigned to that team, you cannot escalate to that object, because you cannot select that team from the dropdown. This is true even if that team's access settings in Grafana OnCall for `Who can see the team name and access the team resources` is set to `All Users`. Ideally, you should be able to select from any of the public teams, so that members of one team can page another team when necessary.

**Comment by iskhakov** [comment]
/escalate doesn't use escalation chains, responders, and schedules anymore.
