### ISSUE TITLE
Bug: User Info shows Slack Name, but Slack Integration is disabled (part:chatops)

### ISSUE THREAD

**Issue by roock** [grafana/oncall#1888]
Using Oncall OnPremise Frontend: 1.2.18 Backend 1.2.17

User Settings:
![Screenshot 2023-05-08 at 12 36 14](https://user-images.githubusercontent.com/533172/236804309-b7243634-bb10-40b6-b095-5977bf45d798.png)

Chat Ops Settings are empty:
![image](https://user-images.githubusercontent.com/533172/236802801-3d6b5e43-bc0a-47c7-97b1-0e297b510fa9.png)

Slack Configuration has been disabled in the Docker Compose setup:
```
FEATURE_SLACK_INTEGRATION_ENABLED: "False"
```

part:chatops

**Comment by greatvovan** [comment]
This issue is mentioned here #852 ("Slack-bound" section).
Please upvote.
