### ISSUE TITLE
Add info about Slack slash commands so users could find them

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#190]
Slack command "/oncall" could invoke such a window for manual alert raising which is a very handful feature. We don't tell about it anywhere in the UI or docs. Does OnCall have other slash commands?

<img width="528" alt="Screenshot 2022-07-02 at 18 51 40" src="https://user-images.githubusercontent.com/3284841/177007529-2445fa97-30ed-471f-9cc9-cbf65aa4fe42.png">

**Comment by alyssawada** [comment]
Addressed by PR #994
