### ISSUE TITLE
Unify logo placement with other IRM apps

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1905]
We are currently using a version of the logo that was implemented 1 in 1 from the old navigation as a solution fro transition period.
The logo is present on all pages and makes it difficult to focus on the content.

Proposal to unify the logo, its size and behavior with other IRM applications: small on the first page with alert groups and completely absent on the internal ones.

**Comment by Matvey-Kuk** [comment]
@raphael-batte please add version & other labels.

**Comment by joeyorlando** [comment]
Closing as this appears to have been done in #3552/#3531
