### ISSUE TITLE
Confusing "Connectivity Warning" panel

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#191]
I see such a panel in one of my stacks. It doesn't say what exactly is not good which is pretty confusing. It used to say the reason before so seems like it degraded a bit.

<img width="1359" alt="Screenshot 2022-07-02 at 18 54 41" src="https://user-images.githubusercontent.com/3284841/177007637-2e042ec9-b272-42dd-b793-cd00c4d23561.png">

@Ukochka could you please take a look? Thank you!

**Comment by Matvey-Kuk** [comment]
Just installed fresh GO, looks like it has explanations for Slack and Phone validation, but it's missing explanation for smth else.

<img width="1310" alt="Screenshot 2022-07-03 at 14 09 31" src="https://user-images.githubusercontent.com/3284841/177036845-48b812cd-9027-4cb2-a045-8bba532994aa.png">

**Comment by raphael-batte** [comment]
@Matvey-Kuk Maybe make this warning more universal as warning for entire ChatOps?

**Idea** Provide context about ChatOps connectivity, because someone uses MS Teams or telegram as main channel for example.

**Proposal**
ChatOps are not connected. Configure(link) at least one ChatOps channel to receive notifications.

**How it works**
If user connects at least one ChatOps channel, warning banner disappears.

**Comment by Matvey-Kuk** [comment]
@raphael-batte I like the idea! Actually once user is connecting any ChatOps **or** mobile phone -> no need to show such a banner.

**Comment by raphael-batte** [comment]
**Proposal**
Communication channels are not connected. Configure at least one ChatOps(link) channel or mobile phone(link) to receive notifications.

**Comment by jpike88** [comment]
I've already connected slack, but the banner still shows. I don't use telegram or teams, nor do I want to.
<img width="558" alt="Screen Shot 2022-08-23 at 11 22 13" src="https://user-images.githubusercontent.com/9585787/186069160-bc725710-4e05-4b6f-84c2-200392618bbc.png">

**Comment by UbiquitousBear** [comment]
@Ukochka  - the change in #512 shows a warning is chatops is [not enabled](https://github.com/grafana/oncall/pull/512/files#diff-5b1c7219e6b618a4d3f49a9d24df7d1c3d7ce0e92289cf9d33da054c3073f364R143); is it possible to permanently dismiss if we don't use chatops options?
