### ISSUE TITLE
Wrong titles for the incidents

### ISSUE THREAD

**Issue by Issif** [grafana/oncall#1910]
Hi,

I’m trying to integrate a new source of events for OnCall, I’m using for that the Formatted Webhook integration.

Everything works as expected, but the Titles are always “Incident”, whatever the value of the field title in my payload. I tested with my program, and with the example provided by the integration at bootstrap.

![image](https://github.com/grafana/oncall/assets/4520100/c17e497a-8fa1-4a95-90b0-b8d0f63c53f4)
![image](https://github.com/grafana/oncall/assets/4520100/2fc4e052-afd5-4ded-83de-8d104705ca81)

I’m using the r129-v1.2.20 of OnCall in Grafana Cloud.

Is that a normal behavior? The screenshots I saw had different Titles for the incidents.

Regards

**Comment by mderynck** [comment]
Under settings for that Formatted Webhook integration, on the `Alert Templates` tab, `Edit template for: Web` can you share what the template for `Title` is set to?
