### ISSUE TITLE
Integration grafana oncall with zvonok.com

### ISSUE THREAD

**Issue by bndrv** [grafana/oncall#195]
Hi! Please make integration Grafana Oncall with zvonok.com 

API - https://api-docs.zvonok.com/
Github - https://github.com/ZvonokComGroup?q=zvonok-example

Link issue - https://github.com/ZvonokComGroup/zvonok-example-python/issues/1

**Comment by Matvey-Kuk** [comment]
Hi! That's something I'm not sure the core team will take. We'll be happy to assist external contributors to build a proper PR and get it merged.

**Comment by Matvey-Kuk** [comment]
If somebody wants to take this task and discuss design with a team, 27 July we'll have a call: https://github.com/grafana/oncall/discussions/151

**Comment by eugenefeel** [comment]
@Matvey-Kuk I think you can close this issue because it was done #2339
