### ISSUE TITLE
Add Advanced Outgoing Webhooks

### ISSUE THREAD

**Issue by eskemojoe007** [grafana/oncall#1977]
Within OnCall cloud - In the outgoing webhooks, the options are extremely limited.  

I have a scenario where I need to change the URL programmatically, which I don't believe is possible.  

For example I need to do a put at /api/[ID]/ with a json payload and I don't see a way to do that.

**Comment by Matvey-Kuk** [comment]
It will be included as a part of upcoming webhooks update
