### ISSUE TITLE
Send "you're going oncall" mobile push notification according to user's "configured notification timing preference"

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#1999]
Since mobile app doesn't support changing `going_oncall_notification_timing` setting, it was temporary commented out from the code to prevent sending push notification 12 hours before the shift.

- [x] Return `going_oncall_notification_timing`
- [x] Change default value from 12 hours

**Comment by Matvey-Kuk** [comment]
I'm pretty sure it should be disabled by default.

**Comment by joeyorlando** [comment]
@Matvey-Kuk correct, the notifications are disabled by default, but @grafana/grafana-oncall-mobile recently released a version which introduces a toggler to enable these notifications.

The notifications were setup to send @ 12h before the shift start & 15mins before the shift start. @grafana/grafana-oncall-mobile would only like them to be sent out @ 15mins before (for now).
