### ISSUE TITLE
Alert group screen has cluttered design

### ISSUE THREAD

**Issue by greatvovan** [grafana/oncall#2008]
The alert group screen has
- title repeated 3 times,
- message repeated 2 times,
- timestamp repeated 3 times,

which deteriorates readability and increases amount of time to understand the problem.

Example:

<img width="739" alt="Screenshot 2023-05-23 at 4 55 59 PM" src="https://github.com/grafana/oncall/assets/4903007/d74b6bcd-edf7-459f-b916-cc1695e15b32">

#### Suggestions:
1. Remove the second title along with the update timestamp.
Rationale: the title is just a duplicate and update timestamp is shown below in the grouped alerts header (it's the same).

2. Always open alert group card with grouped alerts panel collapsed.
Rationale: the current state is the most relevant, while historical information is needed from occasion to occasion.

3. Reduce font (and maybe change color or other style) in the grouped alerts panel.
Rationale: once expanded, the panel should not detract attention from the main content. Additionally, the top element of the list is always a duplicate of the current content, so it should not collide with the main content and cause confusion.

Approximate new view (besides a smaller font):

<img width="733" alt="image" src="https://github.com/grafana/oncall/assets/4903007/f969b427-a314-483d-b3ba-49113d89e3f6">

**Comment by iskhakov** [comment]
This makes sense, thank you for suggestions
