### ISSUE TITLE
Integration Settings Save Changes not working

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#2010]
On the settings page of an integration the Save changes button does not work after you change Autoresolve or Team assignment.  When pressed I am not seeing any requests being made.

OnCall Version: r145-v1.2.31
Grafana Version: 10.0.0-cloud.2.aef9c3bd

**Comment by Ukochka** [comment]
Seems it is related with Drawer changes. Should be fixed when https://github.com/grafana/grafana/pull/69083 will be released

**Comment by dmitry-tiger** [comment]
I found out that save button only doesn't work when "default" team is chosen as selected team.
When switch default team in settings -> teams and access settings to another, save button starts working

**Comment by Matvey-Kuk** [comment]
@mderynck please specify the frontend version.
