### ISSUE TITLE
Bad variables {{ alert_title }}, {{alert_message }}, {{alert_url }} in the outgoing webhook.

### ISSUE THREAD

**Issue by BortovEvgeniy** [grafana/oncall#202]
- Outgoing Webhook:
  ![image](https://user-images.githubusercontent.com/66424944/177355202-d234b420-a2bd-4fbc-b16c-5c6f57e9132c.png)

- Alert Templates:
  ![image](https://user-images.githubusercontent.com/66424944/177355809-aa1bdc78-9883-46a2-b80b-b597cc56d6bb.png)

- The received JSON:  
  ![image](https://user-images.githubusercontent.com/66424944/177349507-93e99a6e-f0cf-4cc4-a18a-7b3f51a617e2.png)

**Comment by Konstantinov-Innokentii** [comment]
Thanks, I'll check it

**Comment by Konstantinov-Innokentii** [comment]
@Matvey-Kuk let's close it once we will deploy fix

**Comment by Konstantinov-Innokentii** [comment]
Merged
