### ISSUE TITLE
Trigger Outgoing Webhook on Alert Acknowledgement/Resolution

### ISSUE THREAD

**Issue by navinpai** [grafana/oncall#2029]
- Open Source OnCall 1.2.26 plugin/server +  Grafana 9.4.3

---
I have a outgoing webhook which I use to trigger messages to an external service when an alert happens. I can trigger this webhook using the webhook configuration in OnCall and add it to the OnCall Escalation Chain to ensure it gets triggered as needed.

However, if the alert is ACK-ed/Resolved, I would like to have some way to trigger the same webhook with a Resolved/Acked message so that the team knows someone is looking at the issue without having to log into Grafana. Does OnCall offer some way to do this today? If not, this is a feature I'd like to request

**Comment by Matvey-Kuk** [comment]
This will be addressed in the new version of webhooks which is at alpha already

**Comment by mderynck** [comment]
This feature is available
