### ISSUE TITLE
simple architecture

### ISSUE THREAD

**Issue by kfox1111** [grafana/oncall#203]
One of the things I really like about alert manager is its very simple design. you launch one and your good to go. You want ha, you launch more then one. If the clustering fails, you still get delivery.

The instructions for oncall mention:
```
RABBITMQ_PASSWORD=rabbitmq_secret_pw
MYSQL_PASSWORD=mysql_secret_pw
```

deploying a ha oncall is very nontrivial, for something that needs to be highly reliable. It would be good to consider an architecture more like alertmanager.

**Comment by Matvey-Kuk** [comment]
@kfox1111 thank you for the feedback! We're discussing smaller deployment footprint here: https://github.com/grafana/oncall/issues/85
