### ISSUE TITLE
Use "Important" notification type consistently.

### ISSUE THREAD

**Issue by colega** [grafana/oncall#2043]
See:

![image](https://github.com/grafana/oncall/assets/1511481/cdfa0ef5-c613-42e7-94d8-02801804b6ae)

vs

![image](https://github.com/grafana/oncall/assets/1511481/2eef6eb9-2e2c-4f86-af82-0e2c589954ed)

We should refer to the notification type as "Important" consistently, instead of using alternative words as "Critical" which can make the user journey more confusing.

(I assume "Important" is the word we want everywhere, or we could switch to "Critical", but it should be the same adjective)

**Comment by Matvey-Kuk** [comment]
Closing because missing app version.

**Comment by colega** [comment]
Sorry @Matvey-Kuk, it's whatever is deployed right now on ops, I guess this is the version:
> r145-v1.2.31

**Comment by qashlan** [comment]
I can work on this

**Comment by iskhakov** [comment]
fixed in https://github.com/grafana/oncall/pull/2063
