### ISSUE TITLE
Mobile push message is not taken from the template

### ISSUE THREAD

**Issue by greatvovan** [grafana/oncall#2050]
While the title and the message in the mobile app or controlled be templates of "Web" type, the push message itself is using different template, which is not under user's control.

Currently a push message looks as follows:

**Grafana Alerting integration type:**
```text
New Alert
#<ID> <alertname> via <integration_name>
Status: Firing, alerts: <count>
```

**Webhook integration type:**
```text
New Alert
#<ID> Incident via <integration_name>
Status: Firing, alerts: <count>
```

**Reproducing**
1. Create an escalation chain sending yourself a default notification.
2. Create an integration of type _Grafana Alerting_ and give it a recognizable name, e.g. "My GA integration".
3. Set up the web templates as follows: _Title:_ `Title`, _Message:_ `Message`.
4. Create an integration of type _Webhook_ and give it a recognizable name, e.g. "My WH integration".
5. Set up the web templates as follows: _Title:_ `Title`, _Message:_ `Message`.
6. Assign your created escalation chain from item 1.
7. Copy and store URLs of the created integrations.

<details>
  <summary>Payload</summary>

```json
{
    "receiver": "",
    "status": "firing",
    "alerts": [
      {
        "status": "firing",
        "labels": {
          "alertname": "My alert name"
        },
        "annotations": {},
        "startsAt": "2023-04-22T21:19:00Z",
        "endsAt": "0001-01-01T00:00:00Z",
        "generatorURL": "https://xxx.grafana.net/alerting/grafana/a9fa1566-5622-47f9-87b9-f5bbed1aa604/view",
        "fingerprint": "1738c614a1f918d1",
        "silenceURL": "https://xxx.grafana.net/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DMy+alert+name",
        "dashboardURL": "",
        "panelURL": "",
        "values": {},
        "valueString": ""
      }
    ],
    "groupLabels": {},
    "commonLabels": {
      "alertname": "My alert name"
    },
    "commonAnnotations": {},
    "externalURL": "",
    "version": "1",
    "groupKey": "",
    "truncatedAlerts": 0,
    "orgId": 1,
    "title": "",
    "state": "",
    "message": ""
  }
```

</details>

8. Send the payload to each of integration URLs to create alert groups. Example command:
`curl $url -H 'Content-Type: application/json' -d @$HOME/Downloads/oncall.json`

**Expected behaviour:**
Push message uses the configured text templates (in our case "Tittle" and "Message").

**Actual behaviour:**
![IMG_0768](https://github.com/grafana/oncall/assets/4903007/fdfdedfa-d8d1-4cce-ae52-721c7cc2ec50)

![IMG_0769](https://github.com/grafana/oncall/assets/4903007/639d3d0b-3c3d-4ae7-bd19-25ac7de6bc7c)

**Suggested solution**
Push text must include the configured title.
Rationale: only the user knows how to compose a useful message from the payload. Integration name and alert name might be not specific. "Incident via Integration name" may provide zero information. Looking at how other applications do the same, they try to fit as much information as possible into the push message.

Example:
```text
#<ID> <templated_title>
<Templated message, if any>
```

- I suggest to remove "New alert" row. What value does it give? Can there be messages of other types from OnCall? If yes, then keep it.
- The `Status: Firing, alerts: <count>` row is also questionable. Are we sending pushes about "Acknowledged" or other status? If yes, then keep it.

**System information**
- Cloud Grafana OnCall
- version r145-v1.2.31

**Comment by imtoori** [comment]
@greatvovan thanks a lot for the suggestions! 

I totally agree with your feedback and we're already working on templates for mobile push notifications.

I agree with your suggested solutions as well and we'll take them into consideration for the default template!

**Comment by Dieterbe** [comment]
@iskhakov what's the status of this? just curious. i assume priority for this is rather low. thanks :)

**Comment by krptg0** [comment]
Curious about that also :)

**Comment by Matvey-Kuk** [comment]
The team will work on this later, it got pulled out of the short-term backlog :(
