### ISSUE TITLE
unable to add phone number when using twilio

### ISSUE THREAD

**Issue by CA1087** [grafana/oncall#2076]
I deployed the open source oncall plugin with grafana version v9.5.2 and oncall plugin version v1.2.34 using the helm chart. I am trying to integrate it with twilio. I disabled grafana OSS env variables and added the configs for twilio. When i am trying to add my phone number I am getting an error on the browser, seems like js error and no errors in the oncall pods or grafana pods. 

`90.cf2da2a42f577bdb1843.js:sourcemap:153 TypeError: Cannot read properties of undefined (reading 'verification_sms')
    at BD (PhoneVerification.tsx:367:38)
    at oc (7490.cf2da2a42f577bdb1843.js:sourcemap:151:55165)
    at Mh (7490.cf2da2a42f577bdb1843.js:sourcemap:155:9221)
    at Vd (7490.cf2da2a42f577bdb1843.js:sourcemap:155:996)
    at Ah (7490.cf2da2a42f577bdb1843.js:sourcemap:155:924)
    at wd (7490.cf2da2a42f577bdb1843.js:sourcemap:155:774)
    at Gl (7490.cf2da2a42f577bdb1843.js:sourcemap:153:11343)
    at 7490.cf2da2a42f577bdb1843.js:sourcemap:151:39855
    at g.unstable_runWithPriority (7490.cf2da2a42f577bdb1843.js:sourcemap:434:3866)
    at nu (7490.cf2da2a42f577bdb1843.js:sourcemap:151:39629)
P`

<img width="1109" alt="Screenshot 2023-06-01 at 4 52 51 PM" src="https://github.com/grafana/oncall/assets/128349798/d4209043-4a62-4e10-a7ba-bfe83f8bdb19">
<img width="1512" alt="Screenshot 2023-06-01 at 4 52 02 PM" src="https://github.com/grafana/oncall/assets/128349798/317c15db-a01a-4658-abfa-4e0402cfa813">

Not sure if i am missing something here. Any help here would be appreciated.

**Comment by Konstantinov-Innokentii** [comment]
Could you please share response from /current_team endpoint in browser developer tools?

**Comment by CA1087** [comment]
@Konstantinov-Innokentii - this is the response from the /current_team endpoint
`{"pk":"OC9NPPXJIVBZL","name":"Self-Hosted Organization","slack_team_identity":null,"maintenance_mode":null,"maintenance_till":null,"slack_channel":null,"limits":{"period_title":"Daily limit","limits_to_show":[{"limit_title":"Phone Calls & SMS","total":200,"left":200}],"show_limits_warning":false,"warning_text":"You almost have exceeded the limit of phone calls and sms: 200 of 200 left."},"archive_alerts_from":"1970-01-01","is_resolution_note_required":false,"env_status":{"telegram_configured":false,"twilio_configured":true},"banner":{"title":null,"body":null}}`

**Comment by CA1087** [comment]
@Konstantinov-Innokentii - I am getting blocked on this issue.  Any leads here will be useful.

**Comment by joeyorlando** [comment]
@CA1087 can you elaborate on what you mean by:

> I disabled grafana OSS env variables

which env variables did you disable?

**Comment by Konstantinov-Innokentii** [comment]
@CA1087 it is needed to update oncall backend version. If you don't want to upgrade backend, frontend fix will be available next week.

**Comment by CA1087** [comment]
@Konstantinov-Innokentii  What will be the working version for grafana oncall backend version?

**Comment by Konstantinov-Innokentii** [comment]
@CA1087 minimum [v1.2.30](https://github.com/grafana/oncall/releases/tag/v1.2.30). But feel free to use just latest version, they have lots of cool stuff usually :)

**Comment by CA1087** [comment]
@Konstantinov-Innokentii  - I am already using the latest image using the  helm chart. I am not sure if you are talking any other version.

**Comment by CA1087** [comment]
I am able to add the phone number after updating the backend version. Thanks for your help on this.

**Comment by Konstantinov-Innokentii** [comment]
@CA1087 thanks for the reporting!
