### ISSUE TITLE
Mobile app does not update the alerts list

### ISSUE THREAD

**Issue by greatvovan** [grafana/oncall#2086]
Since the very first release in the App Store and till the current day the application has never updated the list of alerts on my phone, when opened. It only updates it if I pull the list down to force a refresh. I was hoping it could be an early stage defect, but now I think we need to document it as a bug.

### Setup
1. Create an escalation chain sending a default notification to yourself.
2. Create an integration of type Webhook.
3. Assign your created escalation chain from step 1.
4. Copy and store the URL of the created integration.
5. Configure your user profile to receive mobile pushes as part of default flow.
6. Open Grafana OnCall app and remember the current state of the alert list (both _Mine_ and _All_ here and below).

#### Reproducing
1. Send an alert to OnCall (example and payload can be found in #2050).
2. Ensure it appeared in web version.
3. Ensure you got a push on the mobile device.
4. Open the application using **its icon**.

#### Expected result
The lists in the web version and mobile versions are in sync (discounting for applied filters).

#### Actual result
The list is not changed after getting the push notification.

#### Reproducing
1. Send an alert to OnCall (example and payload can be found in #2050).
2. Ensure it appeared in the web version.
3. Ensure you got a push on the mobile device.
4. Open the application using **the push message**.
5. Tap <-- ("back") button.

#### Expected result
The lists in the web version and mobile versions are in sync (discounting for applied filters).

#### Actual result
The list is not changed after getting the push notification.
While the item opened directly from the push message looks correct, upon returning to the main list the user sees outdated content.

### Suggested solution
- When a list is activated in _Feeds_ section, refresh the selected list if last time it was refreshed was more than `X` = 15 s ago (configuration parameter?). Track last refresh time individually for each list.
- When a list is active, refresh it every `X` seconds.
- When opened from a push notification, reset the refresh timestamp of both lists to 0, so that after navigating back to the list it refreshes regardless `X` seconds passed or not.
- If a push is received when a list is active, reload the current list and reset the refresh timestamp of another one as above.

Rationale:
- the web version refreshes the list every 15 seconds and does not require the user to force refresh;
- after getting a push, the list undergoes changes so needs to be reloaded.

### System info
- Platform: iOS
- version: 1.0.3
- Cloud OnCall version: r155-v1.2.35

**Comment by imtoori** [comment]
@greatvovan thanks a lot for reporting the issue and sorry for the delay

I'll verify this behaviour and find a good solution. We were planning on adding a polling mechanism to the alert list, I think that could help, but we need to polish it a bit more.

I'll post an update later this week.

**Comment by Dieterbe** [comment]
@greatvovan the fix is coming in open beta, and in about a week to 10 days it should be in the stable app.
