### ISSUE TITLE
Local development - is there a better approach to handling grafana-plugin/node_modules?

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2097]
This issue stems from [this conversation](https://github.com/grafana/oncall/pull/2053#discussion_r1214121505).

From @alexintech:

> Exactly the same in this case. You run make init and it downloads node_modules and exposes them to host machine. So PyCharm can find imports and you can dive into sources of installed dependencies if you need. And I suppose other IDEs also may benefit.
>
> Actually, there is no need to mount ./grafana-plugin/node_modules:/etc/app/node_modules, as ./grafana-plugin:/etc/app already can expose node_modules.
>
> What code editor do you use? Does it find node_modules inside docker volume?

**Comment by joeyorlando** [comment]
> What code editor do you use? Does it find node_modules inside docker volume?

@alexintech personally I use VSCode. If `grafana-plugin/node_modules` is not present, the UI docker container runs fine, but as you mentioned, the IDE is obviously not able to resolve dependencies. 

This is probably the perfect use-case for a "dev container" ([docs](https://code.visualstudio.com/docs/devcontainers/containers)). This would obviously only work for VSCode though. Do you know if PyCharm has a comparable feature?

**Comment by joeyorlando** [comment]
@alexintech another reason I think it's useful not to volume mount the host `node_modules`:

> since your host & container might not be able to share the same modules. For example, if you use Mac/Windows and you have some compiled modules (i.e. node-sass or bcrypt), sharing those onto a Linux based container will likely not work

**Comment by alexintech** [comment]
@joeyorlando 
> if you use Mac/Windows and you have some compiled modules (i.e. node-sass or bcrypt), sharing those onto a Linux based container will likely not work

Agree, that will not work. But after `make init` you actually expose `node_modules` from Linux based container to your Mac/Windows. Actually, docker volume is another folder somewhere on the host machine 😄

**Comment by joeyorlando** [comment]
curious what @grafana/grafana-oncall-frontend thinks here
