### ISSUE TITLE
Pre-release schedule v2 bug collection

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#2118]
✅
1) Schedule list, "Oncall" -> "On-call now"
<img width="188" alt="Screenshot 2023-06-07 at 12 19 44" src="https://github.com/grafana/oncall/assets/3284841/5b093cf9-e08d-4184-91ee-502035f39983">

✅
2) New schedule, "Additional notification settings" -> "Notification settings"
<img width="311" alt="Screenshot 2023-06-07 at 12 20 48" src="https://github.com/grafana/oncall/assets/3284841/30dd9f12-f332-4aaa-84c5-b91be75eda06">

✅
3) Top nav stick to the top of the schedule screen:
<img width="1215" alt="Screenshot 2023-06-07 at 12 25 33" src="https://github.com/grafana/oncall/assets/3284841/24a2c1ff-e8a9-47d9-b1a1-41cb83b9f7c7">

✅
4) Didn't we update texts here? I think we agreed on "Delete past shifts".
<img width="516" alt="Screenshot 2023-06-07 at 12 26 53" src="https://github.com/grafana/oncall/assets/3284841/3e660d83-f9a4-403b-82ad-38e5d69d13ba">

✅
5)  "Add rotation to the schedule to see users" -> "Add rotation to see users"
<img width="396" alt="Screenshot 2023-06-07 at 12 59 17" src="https://github.com/grafana/oncall/assets/3284841/2f42451e-9e63-41e7-8069-7b504333b2c6">

**Comment by raphael-batte** [comment]
There are white visual artefacts in the modal
![image](https://github.com/grafana/oncall/assets/102970268/c6d68e62-0416-421b-bd69-c139adab4f4d)

**Comment by raphael-batte** [comment]
Show warning when user tries to save rotation without users. Modal shouldn't closes.

**Comment by raphael-batte** [comment]
Sometimes dropdown with recurrence option is empty 
![image](https://github.com/grafana/oncall/assets/102970268/51d90ad7-4884-45b4-ac62-3e4a809ea3b3)

**Comment by raphael-batte** [comment]
Week start settings and days arrangement in the modal should be the same
![image](https://github.com/grafana/oncall/assets/102970268/3fcb948c-95fb-4511-a4f1-27199683a6a1)

**Comment by Ferril** [comment]
Some weird prerendered shifts behavior when opening update shift window
<img width="1504" alt="Screenshot 2023-06-07 at 12 11 47" src="https://github.com/grafana/oncall/assets/22730923/30a7dbf2-1a15-43fc-9420-9c84f366a351">
(pressed on the first shift and rotation broke)
<img width="1775" alt="Screenshot 2023-06-07 at 12 12 24" src="https://github.com/grafana/oncall/assets/22730923/22c0b88b-d4a5-4e62-96b9-3ceddec94553">
After pressing "update" shift was moved forward to 06.06 but the start date is 05.06
 
<img width="1500" alt="Screenshot 2023-06-07 at 12 17 50" src="https://github.com/grafana/oncall/assets/22730923/b69c08dd-b145-4e3e-8615-de911a3554cd">

**Comment by Matvey-Kuk** [comment]
Use-cases for repeters:

**Grafana-style rotation 8-8-8:** 
Recurrence period: 1 week
Mask by weekdays: Mo, Tu, We, Th, Fr
Limit each shift length: 8h
People: 
Group 1: [Alex]
Group 2: [Bob]

Expected outcome:
Mo            |   Tu           |    We         |    Th           |    Fr           |    St   |   Su   |
[Alex, 8h] | [Alex, 8h] | [Alex, 8h] | [Alex, 8h] | [Alex, 8h]

**Customer's daily rotation 8h:** 
Recurrence period: 1 day
Mask by weekdays: Mo, Tu, We, Th, Fr
Limit each shift length: 8h
People: 
Group 1: [Alex]
Group 2: [Bob]

Expected outcome:
Mo            |   Tu           |    We         |    Th           |    Fr           |    St   |   Su   |
[Alex, 8h] | [Bob, 8h] | [Alex, 8h] | [Bob, 8h] | [Alex, 8h]

**Comment by Ferril** [comment]
Grafana-style rotation doesn't work correctly.
test timezone - timezone GTM+2
In this example rotation starts on Monday, user - Matias. On Tuesday user changes to Maxim. Next week starts with Maxim and changes to Matias.
<img width="1513" alt="Screenshot 2023-06-07 at 12 44 07" src="https://github.com/grafana/oncall/assets/22730923/207d6bb4-d528-46e2-bc71-3e76fefebd21">
<img width="1490" alt="Screenshot 2023-06-07 at 12 44 15" src="https://github.com/grafana/oncall/assets/22730923/ceaf06af-e925-4a7d-9d64-13f85517d998">

**Comment by Matvey-Kuk** [comment]
Also reproducing: https://github.com/grafana/oncall/issues/2048

**Comment by raphael-batte** [comment]
Hide working hours in user's blocks in case recurrence period more than 1 week 
![image](https://github.com/grafana/oncall/assets/102970268/2c6c02c9-f932-4db8-8377-9787b49c2f76)

**Comment by Matvey-Kuk** [comment]
Also not fixed: https://github.com/grafana/oncall/issues/1820

**Comment by Matvey-Kuk** [comment]
This release will close: https://github.com/grafana/oncall/issues/2118

**Comment by Matvey-Kuk** [comment]
This release will close: https://github.com/grafana/oncall/issues/1505

**Comment by Matvey-Kuk** [comment]
This release will close: https://github.com/grafana/oncall/issues/1460

**Comment by Matvey-Kuk** [comment]
Also not fixed: https://github.com/grafana/oncall/issues/1433

**Comment by Matvey-Kuk** [comment]
Boolean filters doesn't stay in the same state after getting back from the schedule:

https://github.com/grafana/oncall/assets/3284841/143e9c1d-ba7c-4ff2-9553-4d4a3cae9302

**Comment by raphael-batte** [comment]
Still have visual artefacts in modal (Chrome Version 114.0.5735.90 (Official Build) (arm64))
![image](https://github.com/grafana/oncall/assets/102970268/b98ae295-8699-4ad5-bd23-b8cf0d33c390)

Looks like they are connected to **overflow: scroll** parameter
![image](https://github.com/grafana/oncall/assets/102970268/afd7ef16-492a-46b4-a4ed-de30f3dd92e2)

**Comment by raphael-batte** [comment]
Rotation renaming isn't work.

**Comment by raphael-batte** [comment]
When we move courser over rotation title, modal header twitches.

https://github.com/grafana/oncall/assets/102970268/986abc4b-efb6-47dc-a7e6-ec733a4a3b36

**Comment by raphael-batte** [comment]
Labels are broken. 
1. Escalations and warning labels inside should have an icons
2. Escalations label should be green 
![image](https://github.com/grafana/oncall/assets/102970268/96455ec2-efad-48ec-a7e9-68c2b3765458) 
![image](https://github.com/grafana/oncall/assets/102970268/2ea78222-0b30-40ae-aaa0-e1bcec462736)

**Comment by matiasb** [comment]
:white_check_mark: 
This release will close https://github.com/grafana/oncall/issues/1322

**Comment by matiasb** [comment]
I guess we can close this one? Let's open new issues for new bugs.
