### ISSUE TITLE
Slack `/escalate` command doesn't show the correct Escalation Chains for a Team

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#2126]
The UI that pops up when you type '/escalate` doesn't correctly lists the Escalation Chains (as I understand how it should work.)
Right now, if you type `/escalate` it gives you the UI. But it only lists the Escalation chains that are not associated with a team.
Even if I set the team to something that has it's own escalation chains, I can only select the escalation chain that doesn't have any team.
However I think it "should" show the escalation chains associated with the specific team that I select, so We can properly escalate adhoc issues directly to a teams oncall schedule.

![image](https://github.com/grafana/oncall/assets/77802/eb42ea9d-c85a-41c2-a816-3dfc5b5a75a4)
![image](https://github.com/grafana/oncall/assets/77802/bdba6e0b-4732-4b49-a1ca-3c7ebe5d1de6)
![image](https://github.com/grafana/oncall/assets/77802/03467b39-ec2e-498d-bb67-3defc7bfef57)

Labels:
part:teams
part:escalation_chains
bug

**Comment by vadimkerr** [comment]
This shouldn't be an issue now after https://github.com/grafana/oncall/pull/2537 is merged & released
