### ISSUE TITLE
Use variables in the webhook url

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#213]
OnCall allows using variables in the webhook body. Customer just asked to allow using them in the webhook url. Please +1 if you need this feature!

<img width="569" alt="Screenshot 2022-07-08 at 13 48 26" src="https://user-images.githubusercontent.com/3284841/178000752-b35dcefc-9535-481d-8178-05ef5b1adf9a.png">

**Comment by CastawayEGR** [comment]
+1 for this functionality, this could be useful for rest apis that have different endpoints per "runbook". This way we could add that as a defined label on the alert as a variable in the webhook url.

**Comment by PhantomPhreak** [comment]
+1
It will allow us to make integrations more flexible. For example, we have our own SMS backend, so it would be nice to trigger a webhook with a variable, containing on-duty username, for sending him an SMS message

**Comment by amezioud** [comment]
+1

**Comment by altokarev** [comment]
+1
