### ISSUE TITLE
Link to docs from schedule quality returns 404

### ISSUE THREAD

**Issue by devinrcheevers** [grafana/oncall#2138]
<img width="746" alt="Screenshot 2023-06-08 at 8 03 32 AM" src="https://github.com/grafana/oncall/assets/85312870/f2168c52-3dce-495a-a070-9fb5f0e514e7">

The link shown above links to https://grafana.com/docs/oncall/latest/calendar-schedules/web-schedule/#schedule-quality-report which returns a 404

**Comment by Matvey-Kuk** [comment]
Closing, please specify OnCall version. Should be fixed in the latest versions.
