### ISSUE TITLE
Alert Group is not found in current team, what should we do?

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#215]
### Discussed in https://github.com/grafana/oncall/discussions/128

<div type='discussions-op-text'>

<sup>Originally posted by **Ukochka** June 22, 2022</sup>
It can be a situation that we got a link to alert group, but currently we are on the team which does not know about this alert (seems it can be a situation not only for alerts, but also for other objects in OnCall) 

What are our options?

- The simplest one is to show that Alert group is not found in this team. But for user it is not clear where to look for this incident. Should we offer a list with all available groups? (suggested design from @raphael-batte )
<img width="690" alt="image" src="https://user-images.githubusercontent.com/20494436/174990278-b153a7ea-9f93-47de-b6ac-934e06394ac6.png">

- Should we automatically switch the team? But seems it will be complicated

What do you think?
</div>

**Comment by Ukochka** [comment]
@Matvey-Kuk How urgent is this task? I can add just a message from frontend that Incident is not found in this team. but to show which team we should switch we need to do changes on backend.

**Comment by Matvey-Kuk** [comment]
@Ukochka it's not urgent, but definitely worth fixing.
