### ISSUE TITLE
Mobile app: Add correct handling of 403 when user tries to ack, resolve, silence alert group

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#2153]
This issue is blocking "making mobile app available for users with role Viewer": https://github.com/grafana/oncall/pull/1892

See this [comment](https://github.com/grafana/oncall/pull/1892#issuecomment-1542131633) by @joeyorlando for details:
> I believe the main thing the mobile app would need to change would be handling authorization. Viewers aren't allow to modify alert group state. If you try doing this atm it crashes the app because the HTTP request returns a 403. Aside from authorization, it appears to work as expected.

**Comment by Matvey-Kuk** [comment]
@iskhakov please don't forget to mention OnCall version.
