### ISSUE TITLE
update isort and black tools to use Python 3.11 as their "target version"

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2172]
Currently [they're configured](https://github.com/grafana/oncall/blob/dev/engine/pyproject.toml#L4-L11) to use Python 3.9 as the target version. We've since upgraded to Python 3.11, and should update this.

Additionally, we should consider centralizing the configuration for `isort`, `black`, and `flake8`. Currently we duplicate the configuration to handle `engine`, `dev/scripts`, and `tools/pagerduty-migrator`.

this exists as of v1.2.43

**Comment by Matvey-Kuk** [comment]
@joeyorlando please format according to requirements or close.

**Comment by vadimkerr** [comment]
Done in https://github.com/grafana/oncall/pull/2641 ([isort](https://github.com/grafana/oncall/pull/2641/files#diff-262ba8727e625e7c53accd7457e696deb98c4328d153085b25166f83900714eeR5), [black](https://github.com/grafana/oncall/pull/2641/files#diff-262ba8727e625e7c53accd7457e696deb98c4328d153085b25166f83900714eeR10))
