### ISSUE TITLE
Unable to connect Mobile App - NetworkUnavailable error

### ISSUE THREAD

**Issue by Curo18** [grafana/oncall#2231]
Hi,

I'm using Open Source OnCall v.1.2.43 on a docker container that include also Grafana OSS v.9.5.2.
I have an account on Grafana Cloud and I have connected the Open Source OnCall with Cloud OnCall using same user name and email, as shown below:

![image](https://github.com/grafana/oncall/assets/41854342/cadce370-de6d-4d01-b329-1e00caf1e919)

When I try to connect the Mobile App for the user Fabrizio18 from Open Source OnCall, on the mobile App I get "NetworkUnavailable" error. While I can connect successfully from Cloud OnCall.

![Screenshot_20230614_103015_Grafana OnCall](https://github.com/grafana/oncall/assets/41854342/3da18419-b994-4fd4-8530-d2a731a54bb0)

I'm sure the server URL embedded in the QR code is reachable and is working because I tested it with a REST API app for Android and I got correct response.

Any help would be appreciated.
Thanks

**Comment by imtoori** [comment]
I'm taking a look at this and the first thing that came in my mind was to check if the url is reachable. 
Maybe you were running the oncall instance locally and the mobile app can't access your localhost, but I think that's not the case since you specified 

> I'm sure the server URL embedded in the QR code is reachable and is working because I tested it with a REST API app for Android and I got correct response.

I'm still testing the setup of an oss instance though, I'll post an update

**Comment by Curo18** [comment]
I compared the two QR code generated during Mobile App Connection from Grafana Cloud and from Grafana OSS and while in cloud one the url starts with "https://..." the OSS one is missing it. It is just "oncall.mysiteurl".
I don't know if it can help.

**Comment by Curo18** [comment]
yep...that's was the issue! I update BASE_URL (inside the x-environment section) of my docker-compose.yaml adding "https://" before my base url and the problem has been solved.
Sorry for wasting your time, but I hope this can help someone else.

Thanks
