### ISSUE TITLE
Unable to create new Notification Policy on the mobile app

### ISSUE THREAD

**Issue by vakhariad** [grafana/oncall#2233]
Hi, we are currently using Grafana Oncall OSS v1.2.43 on production. The issue that we are facing is that when i try to create new notification policy on the mobile app, it just shows blank screen. We have faced this issue on Android as well as iOS. Apart from that if we try to edit existing policy created on the Oncall Web UI, we're able to edit it on the App.
Attaching a video for reference.

https://github.com/grafana/oncall/assets/126227177/5fd4365b-1e58-4d89-b210-3d9b8da07494

**Comment by imtoori** [comment]
hey 👋🏼 
Thanks a lot for reporting this issue! 
I'm quite sure I found out the problem, but please confirm my intuition 👇🏼 

Basically when you create a new step the backend creates it as a "Slack" step, but I think you disabled the slack integration and the app doesn't understand this error 😓 
I think we'll push a fix for the backend, but I'll work on a patch for the mobile app

**Comment by Dieterbe** [comment]
> Basically when you create a new step the backend creates it as a "Slack" step, but I think you disabled the slack integration and the app doesn't understand this error

do we know exactly what kind of step gets created (what the data looks like) or which error is generated?  @grafana/grafana-oncall

**Comment by imtoori** [comment]
We know.
The step gets created as a Slack step, but the app can't match the step id to the list of notify_by_options because slack is disabled and the backend doesn't return the slack notify option in the list

**Comment by imtoori** [comment]
We just merged a fix on the mobile app. It will be published asap as version 1.0.7!
