### ISSUE TITLE
MS Teams integration for OSS

### ISSUE THREAD

**Issue by martinscholz-mediatis** [grafana/oncall#2240]
Hi OnCall Team,
as after my discussion with @devinrcheevers on Slack in the #grafanacon channel, he asked to raise a feature request here.

For those who use OSS version of Grafana and Grafana OnCall it would be awesome to also have the ability to natively use a MS Teams integration. So far I saw it had been available for Grafana Cloud with OnCall but not for an On-Prem version with OSS. 

As I do not think the webhook solution we build as a workaround would be the most effective way to go.

Greetings Martin

**Comment by ToonTijtgat2** [comment]
+1

**Comment by iskhakov** [comment]
MS Teams is cloud only feature and there is no close plans to add it to OSS

**Comment by dmgeurts** [comment]
> As I do not think the webhook solution we build as a workaround would be the most effective way to go.

@martinscholz-mediatis Could you elaborate on your workaround?

**Comment by itspngu** [comment]
> > As I do not think the webhook solution we build as a workaround would be the most effective way to go.
> 
> @martinscholz-mediatis Could you elaborate on your workaround?

I'd imagine they used the "Generic Webhook" feature in both Grafana OnCall as well as MS Teams to post messages with a link to the OnCall instance and some basic info in a Teams channel. It's not as neat as having a fully-fledged "Application" that gives you widgets that can be interacted with, but it's the best you can get without an enterprise subscription I'm afraid.

**Comment by martinscholz-mediatis** [comment]
@dmgeurts, what we use right now is something @itspngu mentioned.
We have a webhook enabled for it in Grafana OnCall, that pushes the message to a third party service called make (https://www.make.com/en), this service is doing some cleanup of the passed metadata for the issue and pushes the issue then to our Microsoft Teams. It is not a nice part of it and nothing really fancy, but it does what we want so far, but if there would be a better solution that would be interactable we would be even more happy. But here comes the Grafana Dev in Case, who just told that this will not happen and there are no plans for it.

**Comment by dmgeurts** [comment]
Thank you, it's always so helpful to see how people deal with issues. Having spent some days on this, I can now confirm that sending from Grafana OSS to Grafana Cloud and onwards to MS Teams is possible without an intermediary. The way I managed it is as follows:

Grafana Cloud >> OnCall >> Integrations >> Alertmanager (copy the generated URL)
Grafana OSS >> Alerting >> Contact Points >> Added a webhook (use the copied URL)

Typical alert routing in Grafana OSS, either direct in the Alert or via a Notification policy.

The Alertmanager route can then point to an MS Teams channel. There's one limitation I ran into; you can't resolve the alert using the buttons in the Teams channel. But if you do so from the Mobile app, it does update the Teams channel message, so keeping team members updated at least works. I've not run into further issues yet, but I'm completely new to Oncall and IRM so I probably shouldn't cheer too soon. An obvious one is likely that forwarding alerts this way means that alerts resolved in Grafana Cloud aren't then marked as resolved in Grafana OSS. I'm not too worried about this as I can set Oncall OSS to automatically resolve issues if everything ends up in Grafana Cloud anyway.

One thing I'm missing is seeing the hostnames being alerted on when alerts are grouped, but this is probably easily to solve with a template update.
