### ISSUE TITLE
Allow specifying the alert group ID that will be used for template payload example

### ISSUE THREAD

**Issue by ramir-savvy** [grafana/oncall#2244]
Feature request for Grafana OnCall OSS (could be relevant also for the cloud).
It would be very nice to be able to use a specific alert group ID for generating the template preview - meaning, for selecting which ID will be used for the payload example.
Today, it uses the most recent alert as payload example.
I see that the API already supports it - I managed to do it from curl:
`curl 'https://<URL>/api/plugin-proxy/grafana-oncall-app/api/internal/v1/alert_receive_channel_templates/<integration_id>/?alert_group_id=<pk>'
`
But need to find some way to allow selecting it in the UI.
Maybe just do it when clicking the `Edit templates` button when viewing alert details.

**Comment by Matvey-Kuk** [comment]
FYI @iskhakov @raphael-batte

**Comment by iskhakov** [comment]
@ramir-savvy thank you for the request. For now you can copy-paste the payload from any alert group into Template Editor -> Use custom payload

<img width="1252" alt="Screenshot 2023-06-27 at 9 48 05 AM" src="https://github.com/grafana/oncall/assets/2262529/641ec6ed-7063-4f86-8cd8-271c37ec6d6d">

**Comment by ramir-savvy** [comment]
Oh, nice! that's a new editor I haven't seen yet.
That will do the trick.
I am closing the pull request.
