### ISSUE TITLE
Grafana Oncall templates new helper filter regex_replace()

### ISSUE THREAD

**Issue by njohnstone2** [grafana/oncall#226]
Grafana Oncall currently supports the default jinja2 filter functions with a handful of helper functions included in this repo. I would like to propose adding a new filter to support the use of regex to replace values within a template.

Grafana alerts provide a `valueString` field in the payload that is sent to grafana oncall. I would like to include this value in my alerting template however customizing this field is limited to the existing jinja2 filtering functions.

## Example
Given the following `valueString` it would be nice to have the option to strip out the `var` field to display a more concise summary of what values are triggering the alert.

### Payload
```
{
  "labels": {
    "env": "prod",
    "alertname": "Prod - My Alert"
  },
  "status": "firing",
  "valueString": "[ var='B0' metric='my_metric' labels={} value=175 ]"
}
```

### Message Template
```
{{- payload.message }}
{%- if "status" in payload %}
**Status**: {{ payload.status }}
{% endif -%}
{%- if "valueString" in payload -%}
**Value**: {{ payload.valueString | regex_replace("var=\'[a-zA-Z0-9]+\'", "") }}
{% endif -%}
```

### Desired Output
```
Prod - My Alert
Status: firing
Value: "[ metric='my_metric' labels={} value=175 ]"
```

**Comment by Matvey-Kuk** [comment]
@njohnstone2 thank you for implementing this feature!

**Comment by njohnstone2** [comment]
No worries and thanks for accepting the change!

**Comment by mimahesh** [comment]
Hi i am trying to get Metric and value output separately and did same for web template but for Microsoft team Template same rule are not able to apply . is there any specific reason for that
 
<img width="663" alt="jinjatemplate" src="https://user-images.githubusercontent.com/101265259/183857721-7b98fd37-3393-45e9-80d4-02d0e29df836.PNG">

Metric = {{payload.valueString|regex_replace("\[ var='.*' metric='", "")|regex_replace("'.*", "")}}
Value = {{payload.valueString|regex_replace("\[ var='.*' metric='.*' labels=\{.*\} value=", "")|regex_replace(" \]", "")}}

**Comment by Matvey-Kuk** [comment]
@matiasb could you please check this one ☝️ ? Thank you!

**Comment by PhantomPhreak** [comment]
Here are my 2cents how to filter the `valueString` with added `regex_replace()` (which is just a `re.sub()` under the hood).

 `valueString` may contain more than 1 metric, i want to get only metric name and it's value, represented as `K:V`, to make alert message shorter and easier to read.


Slack template:
```
{%- if "valueString" in payload -%}
*Metrics*:
{{ payload.valueString | regex_replace("\[( var='.+?')? metric='", "\t") | regex_replace("' labels={.+?} value=", ": ") | regex_replace("\]\,?", "\n") }}
{% endif -%}
```

Result:
![image](https://user-images.githubusercontent.com/8307692/209115471-a67d73a6-98cc-42ca-8a3d-6cf213c3cd9c.png)
