### ISSUE TITLE
Clicking on 'Overrides' brings up a modal for a past override

### ISSUE THREAD

**Issue by joe-stelmach** [grafana/oncall#2303]
### What went wrong?

**What happened**: Using the schedules view to add an override, I clicked on the override calendar. In the date range that was visible, there are no overrides yet a modal popped up to modify an override that occurred in the past.
  -

**What did you expect to happen**: I would expect a modal to pop up to _create_ an override on the day specified. I certainly did not expect to get an _edit_ modal for an override that was not visible. 

  -

### How do we reproduce it?

1. Open Grafana OnCall and navigate to an OnCall schedule that allows for overrides to be created in the web ui AND has an override that was entered in the past. Be sure there are no overrides scheduled in the future.
2. Now click on a day within the `Overrides` section
3. A modal should pop up with the last override that was entered

### Grafana OnCall Version

r172-v1.2.45

### Product Area

Schedules

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

Version 114.0.5735.133 (Official Build) (arm64)

**Comment by Matvey-Kuk** [comment]
Hi! This should be fixed with the latest release.
