### ISSUE TITLE
Rotation name rendering issue

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#2324]
### I am starting to collect new bugs in the thread

Issue # 1. Some schedules have an issue with rotation name rendering inside tooltip.

### How do we reproduce it?

1. Open a schedule
2. Hover mouse over rotation to see shift details.  
3. Some shifts don't render names on tooltip, just color dot.
![image](https://github.com/grafana/oncall/assets/102970268/55e570a2-945f-4dc1-93b7-2ca4cdc38a5b)
4. If we open rotation modal, name will be visible
![image](https://github.com/grafana/oncall/assets/102970268/8c300fda-5870-46b6-a4bd-349e2606e5ee)
5. After closing name becomes visible on tooltips
![image](https://github.com/grafana/oncall/assets/102970268/5170dbba-0511-47e2-8021-d17d1f02ed9e)

### Grafana OnCall Version

r173-v1.2.46

### Product Area

Schedules

**Comment by Matvey-Kuk** [comment]
I think after release it worth creating specific issues for each bug.

**Comment by raphael-batte** [comment]
The problem is no longer visible in the UI. I'am closing the issue.
