### ISSUE TITLE
[Getting Started] Hobby Env Prometheus Indentation Error

### ISSUE THREAD

**Issue by jackycsl** [grafana/oncall#2326]
### What went wrong?

**What happened**:
  - When enable the prometheus metrics exporter, Prometheus throws an error:
```
caller=main.go:479 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/
prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 9: cannot unmarshal !!seq into config.Authorization"
```

**What did you expect to happen**:
  - Prometheus able to start.

### How do we reproduce it?

1. Follow the instructions in getting started guide.
2. Set variables:
COMPOSE_PROFILES=with_grafana,with_prometheus
PROMETHEUS_EXPORTER_SECRET=my_random_prometheus_secret
FEATURE_PROMETHEUS_EXPORTER_ENABLED=True
3. Then create the prometheus error.

### Grafana OnCall Version

dev

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by matiasb** [comment]
Thanks @jackycsl for filing the issue and the fix.
