### ISSUE TITLE
Grafana OnCall OSS - Slack Integration | Slack Channels Not Found

### ISSUE THREAD

**Issue by UGS-DanielSoriano** [grafana/oncall#2332]
### What went wrong?

**What happened**:
  - I configured Grafana OnCall and Slack Integration by following the [link](https://grafana.com/docs/oncall/latest/open-source/). The slack integration was successful but when I tried to select a channel on the integrations it shows "Not Found"
  
![Screen Shot 2023-06-26 at 3 40 48 PM](https://github.com/grafana/oncall/assets/100192893/58528e9c-57e7-46e9-8b0e-7cfed1a6b60e)

**What did you expect to happen**:
  - It should show channels that exists in our workspace

### How do we reproduce it?

1. Open Grafana OnCall, Then Integrations, Then add Grafana Alerting.
2. Select Slack Channels.

### Grafana OnCall Version

v1.2.45

### Product Area

Chatops

### Grafana OnCall Platform?

Kubernetes

**Comment by Matvey-Kuk** [comment]
@UGS-DanielSoriano could you please provide logs from celery workers? I guess you should be able to fine a traceback of a celery task which is syncing Slack channels.

**Comment by UGS-DanielSoriano** [comment]
Hi @Matvey-Kuk sorry for the noob question, can you provide a command to view the logs from the celery worker?

**Comment by UGS-DanielSoriano** [comment]
Ohhh, I see just the kubectl logs. I thought there is a command that I need to execute inside the celery pod.

Here is the screenshot that you have requested:

![Screen Shot 2023-06-26 at 9 28 38 PM](https://github.com/grafana/oncall/assets/100192893/cdcb40e4-268f-4768-871a-16ae4ec23fad)

There is not much logs inside the pods so I'm not sure if this will help you.

**Comment by UGS-DanielSoriano** [comment]
Good catch! I overlooked that part thank you for that. Here is the new screenshot of the logs.

![Screen Shot 2023-06-26 at 11 58 02 PM](https://github.com/grafana/oncall/assets/100192893/4358c192-bb4c-4977-b83d-e472e570d1b0)

**Comment by UGS-DanielSoriano** [comment]
Hi @Matvey-Kuk, It works now but I can't find private channels. It only shows public channels. How can I also add the private channels?

**Comment by Matvey-Kuk** [comment]
@UGS-DanielSoriano happy it works now! Will close the issue than. You need to add oncall slack bot to private channels
