### ISSUE TITLE
Longer silence periods

### ISSUE THREAD

**Issue by msbannert** [grafana/oncall#2333]
### What would you like to see!

Alert Groups can be "silenced" for a limited period up to 24 hours.
It would be nice to have longer periods selectable in the dropdown (1 week, up to 1 month).
Use case: Suppress an alert group  while dev teams are working on a fix, which usually takes some days or weeks.

### Product Area

Alert Flow & Configuration

**Comment by chencs** [comment]
This is quite hacky, but I worked around this by editing and resending the `silence` API request via my browser's network panel with `{delay: $numSeconds}` in the body.
