### ISSUE TITLE
Make adding responders in Slack consistent with web UI

### ISSUE THREAD

**Issue by vadimkerr** [grafana/oncall#2336]
Alert group messages in Slack have this "Invite..." dropdown:

<img width="628" alt="Screenshot 2023-06-26 at 10 19 09" src="https://github.com/grafana/oncall/assets/20116910/fc61f6fc-bd50-4200-ab83-fb003bc971dd">

It's not consistent with the "Add Responders" button in web UI:
- Users invited via Slack don't show up in responder list
- It's not possible to page a schedule via Slack
- "Invite..." dropdown uses an outdated mechanism for paging users, which has been superseded by [Direct Paging](https://github.com/grafana/oncall/issues/823)
- The list of users in dropdown is static, which may lead to outdated user selection & unnecessary large payload size when sending messages to Slack API.

"Inviting" users in Slack should be similar to `/escalate` command, allowing to select schedules / users to page for an existing alert group:

<img width="520" alt="Screenshot 2023-06-26 at 10 37 28" src="https://github.com/grafana/oncall/assets/20116910/77c7016e-9719-49ec-88d9-3a87c00b860c">

**Comment by raphael-batte** [comment]
Any opinions about this order by default? 
![image](https://github.com/grafana/oncall/assets/102970268/f463eb03-8b9a-4772-9156-15884ca2285e)
