### ISSUE TITLE
Connection issue grafana oncall plugin and oncall engine

### ISSUE THREAD

**Issue by pcornelissen** [grafana/oncall#234]
We are having problems to connect the grafana we are running on a kubernetes cluster to the oncall engine running in the same cluster.
The link to the slack conversation is: https://grafana.slack.com/archives/C02LSUUSE2G/p1657620688864209?thread_ts=1657175948.937299&cid=C02LSUUSE2G

But I'll try to sum up what has happened and what we have learned so far:

We tried to connect grafana to oncall using the oncall plugin, by using the servicename in kubernetes, but we just see a 404 request in the logs of Grafana and no logs on oncall:

```
grafana-production-f47dd5bbd-mzhrx grafana logger=plugindashboards t=2022-07-12T12:03:35.761928787+02:00 level=info msg="Plugin state changed" pluginId=grafana-oncall-app enabled=true
grafana-production-f47dd5bbd-mzhrx grafana logger=plugindashboards t=2022-07-12T12:03:35.76197009+02:00 level=info msg="Syncing plugin dashboards to DB" pluginId=grafana-oncall-app
grafana-production-f47dd5bbd-mzhrx grafana logger=context traceID=00000000000000000000000000000000 userId=13 orgId=1 uname=rri*** t=2022-07-12T12:03:36.014878041+02:00 level=info msg="Request Completed" method=POST path=/api/plugin-proxy/grafana-oncall-app/api/internal/v1/plugin/self-hosted/install status=404 remote_addr=10.110.XX.XX time_ms=6 duration=6.282694ms size=24 referer=https://grafana.xxxxxx.de/plugins/grafana-oncall-app traceID=00000000000000000000000000000000
grafana-production-f47dd5bbd-mzhrx grafana logger=context traceID=00000000000000000000000000000000 userId=13 orgId=1 uname=rri*** t=2022-07-12T12:03:38.617641354+02:00 level=info msg="Request Completed" method=POST path=/api/plugin-proxy/grafana-oncall-app/api/internal/v1/plugin/sync status=404 remote_addr=10.110.XXX.XXX time_ms=6 duration=6.368829ms size=24 referer=https://grafana.xxxxxxxx.de/plugins/grafana-oncall-app traceID=00000000000000000000000000000000
```

As suggested by @iskhakov we have tried to wget from the grafana container to the oncall engine service with success:
```
wget -qO- oncall-engine:8080
Ok
```

We even tried to connect from oncall engine to grafana using the public URL, we used in the grafana plugin:
```
wget -qO- https://grafana.xxxx.de/
<!doctype html><html....
```

Ildar did a short call with us to verify the problem, but we are missing further ways to debug this, because we get no detailed information what has been tried and what the exact result was. So we need some way to increase the log-verbosity in the grafana plugin and maybe in oncall-engine as well.

By the way, thanks to @iskhakov for the excelent support we received until now!

**Comment by iskhakov** [comment]
This issue is probably connected to the following grafana bug: https://github.com/grafana/grafana/issues/47530
Please try to restart the grafana pod and run the connection process between Grafana OnCall Plugin and Backend

**Comment by iskhakov** [comment]
The problem was fixed by grafana pod restart

**Comment by pcornelissen** [comment]
Although a better error message would still be helpful for other users that fall into the same trap

**Comment by itay-grudev** [comment]
I had the same problem. Deleting the `OnCall` Grafana API Key from the admin panel resolved the issue for me.

**Comment by VenkatChowdaryK** [comment]
I am having the same problem. but i have restarted the celery & engine and also restarted grafana as well.
But still i am facing the issue and seeing celery pods are restarting. 

and also i have removed the value (worker_shutdown_interval: "65m" )from the values.yaml file, for 2 weeks it was fine and now again having issue.


```yaml
  ## If this setting is set numbers of pod restarts will increase
  ## Comment this line out if you want to remove restarts
  worker_shutdown_interval: "65m" ( i have removed this too)
```

and the error I can see only on the celery pod logs as below.

2023-04-17 20:30:00,280 source=engine:celery worker=ForkPoolWorker-2 task_id=77e7669a-71c2-41c6-ac69-b11cee82be8e task_name=apps.grafana_plugin.tasks.sync.sync_organization_async name=apps.grafana_plugin.helpers.client level=WARNING Error connecting to api instance 404 Client Error: Not Found for url: .......arch?actionPrefix=grafana-oncall-app

**Comment by Milamary** [comment]
> I am having the same problem. but i have restarted the celery & engine and also restarted grafana as well. But still i am facing the issue and seeing celery pods are restarting.
> 
> and also i have removed the value (worker_shutdown_interval: "65m" )from the values.yaml file, for 2 weeks it was fine and now again having issue.
> 
> ```yaml
>   ## If this setting is set numbers of pod restarts will increase
>   ## Comment this line out if you want to remove restarts
>   worker_shutdown_interval: "65m" ( i have removed this too)
> ```
> 
> and the error I can see only on the celery pod logs as below.
> 
> 2023-04-17 20:30:00,280 source=engine:celery worker=ForkPoolWorker-2 task_id=77e7669a-71c2-41c6-ac69-b11cee82be8e task_name=apps.grafana_plugin.tasks.sync.sync_organization_async name=apps.grafana_plugin.helpers.client level=WARNING Error connecting to api instance 404 Client Error: Not Found for url: .......arch?actionPrefix=grafana-oncall-app

hi! having the same issue. Did you resolve it?
