### ISSUE TITLE
Bring new Jinja editor to webhooks

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#2344]
In v1.3.0 we rolled out new Jinja editor. We want to use it for editing of Jinja in webhooks as well.

Also we need to build webhook cheatsheet and variable hints.

**Comment by teodosii** [comment]
Quick update on this ticket:
- @maskin25 added the changes need for the `GForm` to support editing monaco fields
- I replicated the template editor built from Integrations and added the required changes to open the editor & update the form accordingly. Once we have a working endpoint for fetching these new alert groups for webhooks, we'll need to add to fetch the given alert groups and pass the webhook id to the preview endpoint to visualize the template result.
