### ISSUE TITLE
Clearer UX when grouping is 'inherited' from Grafana Alerting

### ISSUE THREAD

**Issue by devinrcheevers** [grafana/oncall#2347]
### What would you like to see!

<img width="1151" alt="Screenshot 2023-06-26 at 10 23 12 AM" src="https://github.com/grafana/oncall/assets/85312870/8cef8c75-1e86-4fad-9845-1de280206523">

When editing the grouping for a Grafana Alerting integration, it is not clear that the autoresolve functionality 'inherits' the grouping rules from Grafana Alerting, see above. Could we make this clearer?

### Product Area

Alert Flow & Configuration

**Comment by raphael-batte** [comment]
I think it makes sense to add such description to behaviour templates group in case integration is between OnCall and Grafana Alerting.

**Comment by iskhakov** [comment]
Grafana OnCall now inherits grouping and auto-resolve signal from Alerting alert rules. It was introduced by https://github.com/grafana/oncall/pull/2643/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR13
