### ISSUE TITLE
No template for auto resolve

### ISSUE THREAD

**Issue by julien-maurel** [grafana/oncall#2355]
### What went wrong?

**What happened**:
On integration templates page, there is a toggle switch to enable or not auto resolution, but it's not possible to edit condition like in v1.2
But I can see previous template from integration page

![image](https://github.com/grafana/oncall/assets/2444807/aa967089-2a07-4ac1-92fe-3267c0abab54)

![image](https://github.com/grafana/oncall/assets/2444807/26d1ffcb-33ba-487f-be99-8fac99bb3f03)

### How do we reproduce it?

Go on integration template page

### Grafana OnCall Version

v1.3.1

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Docker

**Comment by iskhakov** [comment]
Unable to reproduce that, please check if the issue persists and reopen the issue

**Comment by salarali** [comment]
I have the same issue. There is no place in the template to edit these fields. Editing these fields manually in the UI also doesnt lead to any terraform drift.
