### ISSUE TITLE
Schedules. Incorrect link (+link color) for schedule quality metric documentation

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#2357]
### What went wrong?

If we open quality tooltip and expand methodology section, there is a link to documentation in the text. 
![image](https://github.com/grafana/oncall/assets/102970268/a7ba5eef-2439-4bb5-82fc-540ae59f93b8)

It opens such page which is 404 https://grafana.com/docs/oncall/latest/calendar-schedules/web-schedule/#schedule-quality-report. 

Also link has incorrect color - it should be blue without underline.

### How do we reproduce it?

Open a schedule and hover mouse over schedule quality label.

### Grafana OnCall Version

r175-v1.3.1

### Product Area

Schedules

### Grafana OnCall Platform?

None

**Comment by vadimkerr** [comment]
After merging https://github.com/grafana/oncall/pull/2358 I still see that the link is underlined, but can't figure out why (underline is [false by default](https://github.com/grafana/oncall/blob/3fafcb43b1f4a5824d947ecd7398e4605c406a3c/grafana-plugin/src/components/Text/Text.tsx#L16) for the `Text` component).

<img width="334" alt="Screenshot 2023-06-27 at 14 45 11" src="https://github.com/grafana/oncall/assets/20116910/9be18f6d-884f-44ed-87b3-05782189d24a">


@grafana/grafana-oncall-frontend could you please take a look at this?

**Comment by teodosii** [comment]
@vadimkerr added the change in #2372
