### ISSUE TITLE
User profiles should not have a warning for unconfigured chatops integrations

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#2367]
### What went wrong?

If an OnCall instance does not have a chatops integration setup it should not warn users that they have not verified with that service.

![Screenshot from 2023-06-27 10-36-07](https://github.com/grafana/oncall/assets/28077050/0c974b40-5def-4f14-8cc7-2efbc7440016)

### How do we reproduce it?

Default state for new users logging into OnCall

### Grafana OnCall Version

r175-v1.3.1

### Product Area

Chatops

### Grafana OnCall Platform?

None

**Comment by Ukochka** [comment]
Should be fixed by https://github.com/grafana/oncall-private/pull/1965

**Comment by iskhakov** [comment]
@joeyorlando here is the part related to the other chatops: https://github.com/grafana/oncall/pull/2425/

**Comment by joeyorlando** [comment]
thanks 🙂 I added this issue to be auto-closed when #2425 is merged
