### ISSUE TITLE
Auto-merge "Merge: Release oncall Helm chart vX.Y.Z" PRs after Drone OSS promote builds

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2380]
### What would you like to see!

Right now these PRs have to be manually merged. If we forget to do this before performing the next release it can lead to this scenario where we have two open PRs and the previous release's PR becomes irrelevant and should be closed:
<img width="518" alt="Screenshot 2023-06-28 at 13 21 29" src="https://github.com/grafana/oncall/assets/9406895/8feec98e-db10-4d2d-9ca1-9ff698e840f5">

Ideally, we'd be able to automate merging these PRs once the Drone `oss` promote build is finished.

### Product Area

Other

**Comment by joeyorlando** [comment]
[This](https://github.com/gboddin/drone-github-pr) Drone plugin looks like it could be useful. It would allow us to merge a GitHub PR from Drone. However, there is still the unknown of how we would get the relevant PR number (maybe use the GitHub API?)

**Comment by iskhakov** [comment]
done, see https://github.com/grafana/oncall/blob/dev/.drone.yml#L278
