### ISSUE TITLE
Provide a way to easily use k8s/helm for local development

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2381]
### What would you like to see!

At the moment we currently (mostly) use `make start` (ie. `docker-compose`) for spinning up a local environment to develop on. This approach works great currently.

**Proposal**
Refactor the `make` commands to use `helm` under the hood, instead of `docker-compose`.

We receive a good amount of community questions and GitHub issues surrounding various issues w/ running the project via the published `helm` chart. This proposal should _hopefully_ give us more exposure on some of these "sharp-edges", and motivate us to patch these.

This local setup approach should be as easy to use as the current setup. We should update the `./dev/README.md` to reflect these new changes.

### Product Area

Helm

**Comment by Konstantinov-Innokentii** [comment]
maybe we can use tilt for that
