### ISSUE TITLE
Add more filtering options to Integrations list

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#2389]
### What would you like to see!

Right now we have just team filter as option inside Integrations page. 
![image](https://github.com/grafana/oncall/assets/102970268/47f35e71-0768-4a9d-a53b-517a0b29c80e)

I think will be nice to add these filters:
- integration type (list)
- heartbeat (set/not set)
- maintenance (set/not set)
- has alert groups (yes/no)
- has errors (yes)

### Product Area

Alert Flow & Configuration

**Comment by iskhakov** [comment]
filtering based on labels is added
