### ISSUE TITLE
Change the location of the QR-code for authorization in the mobile app and place it to Grafana user profile

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#2393]
### What would you like to see!

**Problem** 
At the moment the QR-code for connection with the mobile app is located inside OnCall in the user section. This makes it difficult to auto-authorise in other IRM products and integrate their features into the app.

**Solution**
The proposal is to migrate the QR-code to the Grafana level user profile. That change will make possible to use the same auth for OnCall and other Grafana products and enable their features in the app.
![image](https://github.com/grafana/oncall/assets/102970268/4af13348-08e8-4c2c-b279-17ab3ecda38b)

In next iterations new section inside the Profile can be transformed to **Personal connections hub** and allocate all relevant to user integrations like:
- mobile app
- Slack
- MS Teams
- Phone
- Workday or Reclaim
etc

### Product Area

Auth, Mobile App

**Comment by joeyorlando** [comment]
closing as completed in https://github.com/grafana/oncall/pull/3296
