### ISSUE TITLE
Docker Image not available for v1.3.3 and v1.3.2

### ISSUE THREAD

**Issue by themitigater** [grafana/oncall#2394]
### What went wrong?

**What happened**:
  - Docker image for release v1.3.3 is not available on DockerHub

**What did you expect to happen**:
  - Image to be published to DockerHub with the latest tag

### How do we reproduce it?

NA

### Grafana OnCall Version

v1.3.3

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by Matvey-Kuk** [comment]
It's a temporary delay in CI/CD, will be there soon.
