### ISSUE TITLE
vv1.3.2 deployed with incorrect engine identifier (dev-oss)

### ISSUE THREAD

**Issue by portswigger-tim** [grafana/oncall#2409]
### What went wrong?

**What happened**:
  - Upgraded plugin and engine to oncall vv1.3.2
  - UI gives a warning:
    ![Screenshot 2023-06-29 at 16 27 30](https://github.com/grafana/oncall/assets/109664963/3e9f3217-27dd-4a19-b8a4-c4e771110e7e)

**What did you expect to happen**:
  - Versions to match

### How do we reproduce it?

1. Install oncall with helm chart version 1.3.2

### Grafana OnCall Version

vv1.3.2

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

**Comment by joeyorlando** [comment]
@portswigger-tim v1.3.2 and v1.3.3 images have since been republished w/ the proper version, do you mind repulling? I'll close this, but if you are still running into issues, feel free to comment here.
