### ISSUE TITLE
Enable logging on escalation outgoing webhooks

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/oncall#2432]
### What would you like to see!

Please add some logging on the outgoing webhooks so it's easier to troubleshoot.

### Product Area

Other

**Comment by mderynck** [comment]
Log of response is available as Last Event on the webhook.  More responses can be accessed by via [API](https://grafana.com/docs/oncall/latest/oncall-api-reference/outgoing_webhooks/#get-webhook-responses)
