### ISSUE TITLE
/escalate Slack command does not work

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2439]
### What went wrong?

**What happened**:
- A user used the `/escalate` Slack command to create an alert group. Slack mentioned to them that the "Alert <alert name> successfully submitted". However, in the OnCall UI, they do not see this Alert Group.

**What did you expect to happen**:
- The alert group should show up in the UI once created via the Slack `/escalate` command.

### How do we reproduce it?

1. Create alert group via Slack `/escalate` command
2. Visit web UI. Alert group is not present

### Grafana OnCall Version

r179-v1.3.5

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

I use Grafana Cloud

### Anything else to add?

This user does have RBAC enabled. They reported that they had a Grafana basic role of "Admin" when trying the above steps.

**Comment by vadimkerr** [comment]
I'm currently working on https://github.com/grafana/oncall/issues/2336 and planning to fix this issue as well.

**Comment by vadimkerr** [comment]
Should be fixed in https://github.com/grafana/oncall/pull/2537 and released in [v1.3.14](https://github.com/grafana/oncall/releases/tag/v1.3.14)
