### ISSUE TITLE
UI making too many requests

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#2462]
### What went wrong?

**What happened**:
  - Alert groups page keeps making new requests for stats and updates when previous ones are still pending
  - These requests are made every 15s, in the case any of these requests takes longer than 15s due to DB performance or network issues more requests can keep stacking up making the problem worse.

**What did you expect to happen**:
  - Alert groups page should not make new requests for updates while the same requests are already pending
  - Alert groups page should not make requests if it is not visible (not active tab or minimized)

### How do we reproduce it?

1. Open Grafana OnCall and navigate to Alert groups
2. Open dev tools, network page to watch requests
3. Simulate requests taking longer than 15s and observe

### Grafana OnCall Version

v1.3.7

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Hosted Grafana had an incident recently w/ # of egress connections in Azure, and [part of the problem](https://raintank-corp.slack.com/archives/C05H0LEGCE5/p1689585617895639) was that we make too many requests.

**Comment by joeyorlando** [comment]
Also, I think we should revisit the [`RootBaseStore.updateBasicData` function](https://github.com/grafana/oncall/blob/dev/grafana-plugin/src/state/rootBaseStore/index.ts#L108-L130). It makes 12 HTTP requests on initial plugin load. Most of them are for things that are not even relevant to the currently loaded page. Instead we should make these requests as needed.
