### ISSUE TITLE
Make it possible to freely choose the amount of minutes an escalation chain should wait.

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/oncall#2464]
### What would you like to see!

Right now, the only options for wait period before an escalation is 1,5,15,30,60. if you want for example 45 minutes to wait you'll have to create 2 wait steps. it would be nice if we could specify a number instead of using a dropdown.

Thanks in advance.

### Product Area

Alert Flow & Configuration

**Comment by KevinDW-Fluxys** [comment]
+1

**Comment by teodosii** [comment]
Implemented frontend in https://github.com/grafana/oncall/pull/4383, waiting for backend to add support for saving the value

**Comment by teodosii** [comment]
Has been implemented in https://github.com/grafana/oncall/pull/4422

**Comment by vadimkerr** [comment]
https://github.com/grafana/oncall/pull/4422 was reverted so reopening the issue

**Comment by vadimkerr** [comment]
This was released in https://github.com/grafana/oncall/releases/tag/v1.6.0

**Comment by dosmanak** [comment]
We have 1.8.5 but Wait in Escalation chain still offers only dropdown with 1, 5, 15, 30, 60 minutes options.
Is it regression or error in upgrade path?
