### ISSUE TITLE
Docs Feedback: Include ChatBot Command Lists

### ISSUE THREAD

**Issue by skeilson** [grafana/oncall#2469]
### What would you like to see!

In our documentation, it would be helpful for users to be able to view a list of the available commands for each ChatBot (Slack, MS Teams, etc) and what each command does. 

### Product Area

Chatops

**Comment by Matvey-Kuk** [comment]
Hi! Those commands are available for slack only and documented here: https://grafana.com/docs/oncall/latest/notify/slack/#slack-commands-and-message-shortcuts
