### ISSUE TITLE
Oncall configuration after update to v1.3.7: ErrTokenAlreadyExists

### ISSUE THREAD

**Issue by danielcb** [grafana/oncall#2481]
### What went wrong?

We're using Grafana Oncall for a while now. After updating to v1.3.7 we get the following error:

```
An unknown error occurred when trying to install the plugin. Verify OnCall API URL, https://<our-oncall-url>, is correct?
Refresh your page and try again, or try removing your plugin configuration and reconfiguring.
```

Oncall delivers an 'Ok' and seems to work fine. In the browser console we can see a request to `/api/serviceaccounts/` failing with status code 400:

```
XHRPOST
https://<our-grafana-url>/api/serviceaccounts/18/tokens
[HTTP/2 400 Bad Request 60ms]

	
message	"service account token with given name already exists in the organization"
messageId	"serviceaccounts.ErrTokenAlreadyExists"
statusCode	400
traceID	""
```

After removing all service accounts and oncall settings and reinstalling oncall the same thing happens.

**Versions:**

Grafana v10.0.1
Oncall-Plugin: v1.3.7
Oncall: v1.3.7

### How do we reproduce it?

1. Open Grafana Plugin settings for oncall after upgrading to v1.3.7

### Grafana OnCall Version

v1.3.7

### Product Area

Other

### Grafana OnCall Platform?

Docker

**Comment by traskat** [comment]
same problem here.

**Comment by danielcb** [comment]
Update to Grafana 10.0.2 + Oncall v1.3.9 does not change the behavior.

**Comment by UbiquitousBear** [comment]
Managed to upgrade in steps to the latest plugin, and this issue doesn't happen anymore.

**Comment by enterdv** [comment]
I went to Grafana API keys menu, migrate oncall API key to service account, reconnect oncall to grafana and the issue doesn't happen anymore.

**Comment by danielcb** [comment]
Thanks for that tip. Works now. :facepalm:
