### ISSUE TITLE
Slack doesn't show graphics in alerts

### ISSUE THREAD

**Issue by VVgin** [grafana/oncall#252]
Good day)

After we moved from amixr to Grafana OnCall we got a problem.
When alerts come to slack we don't get graphics from grafana, like it was in amixr (check my screenshot).
But if we check row, we see  "imageUrl": "https://sravni.blob.core.windows.net/sravni-grafana/N56bnrJF9pnNf21OcURFPKpjxXMxk5.png",
This link is opened and correctly, but slack doesn't show it at all.

Payload example for you:

{
    "tags": {},
    "orgId": 1,
    "state": "alerting",
    "title": "[Alerting] Время ответа на запросы (Росгосстрах НС)",
    "ruleId": 696,
    "panelId": 52,
    "ruleUrl": "https://grafana.sravni-team.ru/d/9vfh5CTGk/accidentinsurance-service-details?tab=alert&viewPanel=52&orgId=1",
    "imageUrl": "https://sravni.blob.core.windows.net/sravni-grafana/N56bnrJF9pnNf21OcURFPKpjxXMxk5.png",
    "ruleName": "Время ответа на запросы (Росгосстрах НС)",
    "dashboardId": 311,
    "evalMatches": [
        {
            "tags": {
                "method": "POST calculate",
                "insuranceCompanyName": "Росгосстрах"
            },
            "value": 14.75,
            "metric": "POST calculate"
        }
    ]
}

**Comment by VVgin** [comment]
<img width="593" alt="How it was from amixr" src="https://user-images.githubusercontent.com/108666699/179692803-dfcd0a95-379c-4760-ac49-76425557761b.png">
<img width="375" alt="How it looks now" src="https://user-images.githubusercontent.com/108666699/179693082-a1a00c6e-7a70-4afb-b961-2155cb6bfbd8.png">

**Comment by Matvey-Kuk** [comment]
Hi @VVgin, thank you for reporting! what's your image template in the integration settings? From what I see in the payload it should be smth like: `{{ payload. imageUrl }}`.

<img width="500" alt="Screenshot 2022-07-19 at 11 07 24" src="https://user-images.githubusercontent.com/3284841/179700233-2c3ffbd6-f531-474a-a7f4-8e4b62b69920.png">

**Comment by VVgin** [comment]
yes, it's the same - {{- payload.get(imageUrl) -}}

**Comment by VVgin** [comment]
@Matvey-Kuk good evening)
I corrected mistake, but nothing change.
Attached new image
<img width="574" alt="Снимок экрана 2022-07-21 в 17 47 27" src="https://user-images.githubusercontent.com/108666699/180243937-3012bb32-966b-401d-8f09-723b3190f1c7.png">

**Comment by atownsend247** [comment]
> @VVgin the image is not working. Also there seems like a mistake in your template: `{{- payload.get(imageUrl) -}}`, should be ` {{ payload.imageURL }}`

This resolved it for me also, thank you for finding this!

**Comment by Matvey-Kuk** [comment]
@VVgin sorry for not answering you earlier. Looks like this fix is working for @atownsend247 . If it's not working for you, I could suggest checking rendered URL if it's accessible from the internet.
