### ISSUE TITLE
Link template for autoresolve and "Autoresolve enabled" in the UI

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#254]
Those 2 settings are related. We should help users to understand that they are relevant. Users sometimes miss one of them:

<img width="514" alt="Screenshot 2022-07-19 at 12 34 30" src="https://user-images.githubusercontent.com/3284841/179718689-83ec6e87-3d3d-46a7-aace-2a5a0705dbb1.png">
<img width="561" alt="Screenshot 2022-07-19 at 12 33 56" src="https://user-images.githubusercontent.com/3284841/179718696-d1fa5393-5dab-4037-b4ec-b3a747f5631f.png">

**Comment by raphael-batte** [comment]
**Proposal**

Settings tab:

![Image](https://user-images.githubusercontent.com/102970268/180960794-dc018b15-0f1c-49ec-b0ad-9fea7b90cee9.png)

Templates tab. Also added as idea context button to reset field data:


![Image](https://user-images.githubusercontent.com/102970268/180961077-2990bcef-f66e-4ebd-bdbd-e45f69f6d0c5.png)

**Comment by Matvey-Kuk** [comment]
@Ukochka closed it with https://github.com/grafana/oncall/pull/309
