### ISSUE TITLE
Problem with the alertmanager integration

### ISSUE THREAD

**Issue by artemnikitin2023** [grafana/oncall#2556]
### What went wrong?

**What happened**:
  - I have an alertmanager with some test alerts in it, also i have external grafana and cert-manager (using selfsigned certs) + trust-manager. I've created the alertmanager type integration in oncall-frontend plugin and configred the alertmanager to send alerts via webhook (using oncall oss docs).
  - All looks fine, there is no any errors in the alermanager logs or oncall-engine backend logs but alerts not appears in the grafana. In the grafana logs i see messages like: 
`msg="Request Completed" method="POST" path=/integrations/v1/alertmanager/<XXXX>/ status=302 handler=notfound`

**What did you expect to happen**:
  Alerts fired by alertmanger appears in the grafana on call frontend plugin

### How do we reproduce it?

1. Deploy external grafana and external cert-manager, generate and use selfsigned certs (inner corporate domain), deploy oncall helm chart.
2. Deploy alertmanager, configure it and rise some alerts (route to the oncall receiver)

### Grafana OnCall Version

v1.3.9

### Product Area

Helm, Other

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Google Chrome 112.0.5615.49 x64

### Anything else to add?

User browser communicating with the Grafana via https
Oncall backend communicating with the Grafana via http

**Comment by alexintech** [comment]
Hi! I suppose you're sending alerts to the Grafana address. But you need to send them to oncall-engine address. There should not be any request logs in grafana container.

**Comment by artemnikitin2023** [comment]
Hi, thanks for the reply!
When i creating the integraion, it generates a webhook url for me automatically. This url contains grafana instance url. It needs to be changed  to the backend engine url right?

**Comment by alexintech** [comment]
> Hi, thanks for the reply!
> 
> When i creating the integraion, it generates a webhook url for me automatically. This url contains grafana instance url. It needs to be changed  to the backend engine url right?

Right

**Comment by artemnikitin2023** [comment]
It worked.
Thank you!

**Comment by artemnikitin2023** [comment]
It worked.
Thank you!
