### ISSUE TITLE
Better routing mechanism for JSON

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#258]
We need some better routing mechanism for complex JSON parsing. Doing it with regex only is tricky in cases:
1) You need to match `"key": "value"` and the same `"key": "value"` show up on different levels of JSON. It may be `a.b.c.key` or `a.key`.
2) It's hard to write regex for JSON because JSON is not strict about whitespaces and newlines.

I'm thinking about smth like:
```
if a.b.c == regex
```

**Comment by mderynck** [comment]
What do you think about an option to use `jq` instead of plain regex here?

**Comment by james-callahan** [comment]
Considering that order of json fields it's guaranteed, I don't know how to nicely use a regex for routing more than one field.
I consider this a must-have.

**Comment by iskhakov** [comment]
we don't use regex anymore, now this is possible with junja templates
