### ISSUE TITLE
OnCall <-> Alerting integration: Frontend

### ISSUE THREAD

**Issue by Konstantinov-Innokentii** [grafana/oncall#2585]
After sync with alerting team, it looks like, that the best approach is to call alering APIs from frontend to create/fetch/get_warning about contact points.
It is needed to implement UI from figma mockup and sync with @konrad147 about usage of alerting API

Useful links:
– [Figma](https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?type=design&node-id=7970-135661&mode=design&t=F9etJH0rI1W12GEb-0)
– [Kata](https://grafana.kata.dreamteamos.com/project/alerting-oncall-integration)

**Comment by Konstantinov-Innokentii** [comment]
After discussion we decided to call alerting APIs from backend side, will create new task for that

**Comment by joeyorlando** [comment]
Closing as this was moved from "In Progress" to "Done" on the project board
