### ISSUE TITLE
Add the ability to CRUD Shift Swap Requests

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2587]
### What would you like to see!

**Deliverables**
1. A data model that supports the feature set as outlined in the latest design doc/mockups.
2. I should be able to CRUD a `ShiftSwapRequest` object via the internal API. 

**Non-deliverables for this task**
The following will be done in subsequent tasks.

1. Accepting open shift swap requests
2. ChatOps notifications
3. "deadlines"
4. UI work
 
**Resources**

- [Design doc](https://docs.google.com/document/d/1BLIWkfd5fNKVzQ342wU7mQ9IwXiEvt-xCmJ-GFldlKw/edit?usp=sharing)
- [Mockups](https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?type=design&node-id=8116%3A136607&mode=design&t=5IA3tWes8OoxBM1w-1) 

### Product Area

Schedules

**Comment by Matvey-Kuk** [comment]
That's API/backend only task.
