### ISSUE TITLE
Oncall plugin goes blank on narrow windows.

### ISSUE THREAD

**Issue by tomwilkie** [grafana/oncall#260]
* Chrome Version 103.0.5060.114 (Official Build) (arm64)
* Grafana 39025bb4c
* OnCall v1.0.7

https://user-images.githubusercontent.com/444037/179988214-7ae07384-000c-43a2-8ec9-16e3fef1f3db.mov

**Comment by grafanalf** [comment]
For the record, I've seen this behaviour while on Safari too, Version 16.0 (18614.1.19.1.5)

**Comment by tomwilkie** [comment]
Thank you for the quick turn around :-)
