### ISSUE TITLE
Shift Swap Requests - when a new request is created, intelligently send out mobile app push notifications

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2630]
### What would you like to see!

**Deliverables**
When a new shift swap request (SSR) is created, we should **intelligently** send info-level push notifications to users on the same team as the shift swap's schedule. The push notification should contain basic details about the request. Clicking on the notification should "deep-link" you to the individual shift-swap request view on the mobile app.

A few things to note:
- if the SSR is created for shifts that are occurring far in the future (ex. 3 months from now), we should not send the push notifications right away. The logic in [`should_we_send_going_oncall_push_notification`](https://github.com/grafana/oncall/blob/dev/engine/apps/mobile_app/tasks.py#L361-L417) may come in handy (periodic Celery task which runs every 15mins and checks for the right time to send the notifications; if you go this route, consider refactoring this method to make it more generic for both use cases)
- Consider only sending the push notifications to users whose mobile device's `time_zone` is +/- 2 hours (?) from that of the user that created the SSR. There might be some cases here where it's tricky. For example if the only other people on the schedule's team are outside of this range.
- ~~Follow up strategy. We should come to a consensus a notification follow-up schedule. Ex. First notification <= 1 week before the first shift starts. Second X time before shift starts, etc.~~ this will be done in #2679

### Product Area

Mobile App, Schedules

**Comment by Dieterbe** [comment]
> users whose mobile device's time_zone is +/- 2 hours (?) from that of the user that created the SSR. 

Perhaps more relevant to the beneficiary's timezone, is the SSR start/end times and the working hours of the people to contact (though we may not know them, and can fall back to assuming 9-17 for their TZ)

**Comment by vadimkerr** [comment]
The backend changes were merged in https://github.com/grafana/oncall/pull/2717 and released in [v1.3.22](https://github.com/grafana/oncall/releases/tag/v1.3.22). 
There's also some WIP documentation about SSR push notifications [here](https://github.com/grafana/oncall/pull/2719/files#diff-834c536ec575a5d225fc40f88e275e09ceae9f95a11981f5f0669b3da770b0e1).
