### ISSUE TITLE
[AMV2]: Frontend

### ISSUE THREAD

**Issue by Konstantinov-Innokentii** [grafana/oncall#2631]
- [x]  Remove integration which types starts from "legacy_" from drawer
- [x]  Tooltip with some placeholder text when hover on legacy integration in table
- [x]  Banner with some placeholder text on legacy integration page
- [x]  "Migrate" button which opens a confirmation Modal with some placeholder text. Once confirmed – POST "api/internal/v1/alert_receive_channels/id/migrate/" endpoint
- [ ]  Add information that legacy integrations [will be migrated automatically](https://raintank-corp.slack.com/archives/C04JCU51NF8/p1690345605451209?thread_ts=1690286926.014779&cid=C04JCU51NF8) in X months

**Comment by iskhakov** [comment]
> Remove integration which types starts from "legacy_" from drawer

@Konstantinov-Innokentii can we do that on the backend? https://github.com/grafana/oncall/blob/dev/engine/config_integrations/alertmanager.py#L6

**Comment by Konstantinov-Innokentii** [comment]
@iskhakov Once I remove integration type from web integration choices it disappears from table and all filters. So I think filtering them on frontend-side is much simpler.
