### ISSUE TITLE
Sending resolve message via outgoing webhook

### ISSUE THREAD

**Issue by fierceou** [grafana/oncall#264]
Hi! There is no possibility to send resolve message via outgoing webhook now, but it seems to be useful.

**Comment by vadimkerr** [comment]
Similar issue: https://github.com/grafana/oncall/issues/906

**Comment by vadimkerr** [comment]
It should be possible starting from [v1.3.12](https://github.com/grafana/oncall/releases/tag/v1.3.12).
Navigate to the "Outgoing webhooks" page, click "+ Create" and select "Resolved" as the trigger type.

<img width="742" alt="Screenshot 2023-07-18 at 20 59 37" src="https://github.com/grafana/oncall/assets/20116910/f9fc0761-4114-47ae-a4cb-39d605cd32b5">

[Refer to the docs](https://grafana.com/docs/oncall/latest/outgoing-webhooks/) for more details on how to configure outgoing webhooks.
