### ISSUE TITLE
Alert loads slow in the web when the payload is too big (has too many nested objects)

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#267]
This bug occurred on our test cluster when uploaded a huge alert the alert with an extremely large payload (json with a huge number nested objects). Template renderer traverses over this data for too long. This is an artificial situation and should happen with normal alerts. Let's consider adding some limit for the alert payload size (i.e. 10000 fields)

**Comment by mderynck** [comment]
Payload size limits are now in place
