### ISSUE TITLE
Grafana On-Call Cannot update

### ISSUE THREAD

**Issue by brngates98** [grafana/oncall#2682]
### What went wrong?

Error received when trying to update Grafana On-Call

**What happened**:
  - 

ERROR: for engine  Container "1129db889dbd" exited with code 1.

ERROR: for celery  Container "1129db889dbd" exited with code 1.
ERROR: Encountered errors while bringing up the project.

**What did you expect to happen**:
  - Successful Upgrade

### How do we reproduce it?

1. Open ssh and run sudo docker-compose pull engine && sudo docker-compose up -d
2. Errors out with message above
3. Also tried a fresh install on a fresh ubuntu server and received the same error.

### Grafana OnCall Version

1.3.16 trying to install 1.3.18

### Product Area

Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Google Chrome

### Anything else to add?

So yea went to do normal upgrade process which has never given me issues, even built a script to automate it whenever a new version is available.

it runs sudo docker-compose pull engine && sudo docker-compose up -d and it kicks an error;

ERROR: for engine  Container "1129db889dbd" exited with code 1.

ERROR: for celery  Container "1129db889dbd" exited with code 1.
ERROR: Encountered errors while bringing up the project.

Then out of curiosity i stood up a new ubuntu server and attempted to follow the instructions to a T and received the same error at the end. 

Leading me to believe the latest docker image is fubar

**Comment by vadimkerr** [comment]
Hi @brngates98 👋 
There's an issue in the latest release `v1.3.18` impacting [hobby setup](https://github.com/grafana/oncall#getting-started) instances. The issue should be fixed in [this PR](https://github.com/grafana/oncall/pull/2680) and released in [`v1.3.19`](https://github.com/grafana/oncall/releases/tag/v1.3.19). Upgrading your instance to `v1.3.19` should resolve the issue.

**Comment by brngates98** [comment]
Will attempt upgrade now :)

**Comment by brngates98** [comment]
Upgrade Successful
bgates.adm@tmg-ubuntu01:~/on-call$ sudo docker-compose pull engine
[sudo] password for bgates.adm:
WARNING: The FEATURE_PROMETHEUS_EXPORTER_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The PROMETHEUS_EXPORTER_SECRET variable is not set. Defaulting to a blank string.
Pulling engine ... done
bgates.adm@tmg-ubuntu01:~/on-call$ sudo docker-compose up -d
WARNING: The FEATURE_PROMETHEUS_EXPORTER_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The PROMETHEUS_EXPORTER_SECRET variable is not set. Defaulting to a blank string.
on-call_redis_1 is up-to-date
Recreating on-call_oncall_db_migration_1 ... done
Recreating on-call_engine_1              ... done
Recreating on-call_celery_1              ... done
bgates.adm@tmg-ubuntu01:~/on-call$

**Comment by vadimkerr** [comment]
Glad it solved the issue, thank you for raising this!
