### ISSUE TITLE
On-Call OSS ChatOps: MS Teams

### ISSUE THREAD

**Issue by brngates98** [grafana/oncall#2683]
### What would you like to see!

I would love to see MS Teams integration into Grafana On-Call OSS like how it is on the Cloud Version, but with the same features available to Slack.

Ideally we would like to get all the same abilities(notify new on call person and all the features of slack integration but with MS Teams)

As we really dont want to have multiple chat platforms for our org.

Another related item to add on with could also be able to import a schedule from o365, as our tenant does not allow to export an ical link, that is just a wild idea but probably too far out.

### Product Area

Chatops

### Anything else to add?

MS Teams integration to the same level of slack+Bring the same functionality of MS Teams from Grafana cloud to OSS

Background:

We have local grafana oss and alert rules etc.

They all flow into a few escalation chains that then get piped to our grafana cloud instance with webhooks to handle posting messages into MS Teams, and sending SMS, and Phone Calls along with using the On-Call app and IRM Pro.

**Comment by ToonTijtgat2** [comment]
+1

**Comment by ohmennn** [comment]
I would like to see MS Teams integration into Grafana On-Call OSS also

**Comment by iskhakov** [comment]
Currently MS Teams is only available in cloud. There is no close plans to move add it to OSS

**Comment by dmgeurts** [comment]
Is it possible to route alerts to MS Teams from Grafana OSS to Grafana Cloud, as per the way SMS messages are sent?
