### ISSUE TITLE
Phone verification does not work because of invalid reCAPTCHA side key

### ISSUE THREAD

**Issue by lu1as** [grafana/oncall#2687]
### What went wrong?

**What happened**:
  - Phone verification via Twilio does nothing after clicking "Verify"
  - Browser console logs `Uncaught Error: Invalid site key or not loaded in api.js: <key>` althrough reCAPTCHA is not enabled

**What did you expect to happen**:
  - Verification code is sent and code input form is no longer greyed out

The issue was introduced with Grafana On-Call plugin v1.3.18 and it seems to be a frontend problem. Plugin version v1.3.17 with the same On-Call backend works fine.

### How do we reproduce it?

1. Open Grafana OnCall (with Twilio phone provider) and try to add a new phone number for a user
2. Fill in the number and click verify
3. Browser console logs `Uncaught Error: Invalid site key or not loaded in api.js: <key>` and no code is sent

### Grafana OnCall Version

v1.3.19

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Firefox Version 115.0.2

**Comment by lu1as** [comment]
It seems to be a bug in Grafana Cloud IRM, too. I'm not able to verify phone numbers anymore, the browser console logs the same message and the code input field stays greyed out.
I also tried it with Google Chrome.

**Comment by joeyorlando** [comment]
I'm able to reproduce as well on a Cloud stack
<img width="1467" alt="Screenshot 2023-07-31 at 13 49 14" src="https://github.com/grafana/oncall/assets/9406895/a60c052b-73bf-407f-bf2b-07ab0ed61e05">

**Comment by vadimkerr** [comment]
The fix is released in [v1.3.20](https://github.com/grafana/oncall/releases/tag/v1.3.20)
