### ISSUE TITLE
500 Internal Server Error from Endpoint

### ISSUE THREAD

**Issue by brngates98** [grafana/oncall#2733]
### What went wrong?

**What happened**:
  - i have local grafana on-call with webhook endpoint http://localhost:8080/integrations/v1/grafana_alerting/nN2ON6kvqUBtyrHVhRsu6RXBK/
  In my contact points in grafana, it is set to this webhook, in which this was working without issue up until this morning.
  now i receive 500 internal server error from grafana when i test contact point, and i receive 500 error when i go to the endpoint in my browser and simulate a notification

**What did you expect to happen**:
  -
it to function and stream alerts

### How do we reproduce it?

1. Contact Points Select Webhook contact point
2. Test Receive 500 error.

Alternative
1. go to http endpoint in browser.
2. Test, Receive error

### Grafana OnCall Version

1.3.21

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Docker

### User's Browser?

Google Chrome

**Comment by alexfun1** [comment]
Same problem. Getting an error in logs:

**Comment by brngates98** [comment]
Interesting wonder if the latest update fubar? Grafana cloud on call still
functions properly so I rerouted our default contact policy there for now

**Comment by brngates98** [comment]
Update:
Apparently Grafana On-call cloud version is having issues too.
Went to test default contact point there that goes to oncall-prod-us-central-0 and i received 403 error: Failed to send test alert.: webhook response status 403 Forbidden
![image](https://github.com/grafana/oncall/assets/59444489/2d1c8758-cf9e-4417-88ff-cf5583658b70)

but from local grafana pushing to cloud on call i get success
![image](https://github.com/grafana/oncall/assets/59444489/92e8aad8-e72f-4b22-86a6-2f3889be532a)

And from Local Grafana to Local On-Call

![image](https://github.com/grafana/oncall/assets/59444489/b9817caf-d9e2-49de-9470-ce2216da8ccd)

**Comment by joeyorlando** [comment]
Can you repull the image v1.3.21 image? I believe we briefly published this image yesterday, w/ this error, but then re-released the image w/ the fix shortly thereafter. It's possible you pulled it during that time frame.

Also, we have https://github.com/grafana/oncall/issues/2709 which should prevent this from popping up in the future.

Feel free to re-open should this still be an issue after re-pulling.
