### ISSUE TITLE
Truncate long integration names in the alert groups table

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2738]
### What went wrong?

**What happened**:
<img width="1238" alt="Screenshot 2023-08-03 at 12 17 09" src="https://github.com/grafana/oncall/assets/9406895/674ef7be-3c67-4d6f-8b24-adf0c4f82c36">

**What did you expect to happen**:
The integration's name should use an ellipsis (...) to truncate really long names so that it doesn't squeeze the rest of the row's contents 

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

r202-v1.3.21

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by teodosii** [comment]
Closed because it was recently fixed https://github.com/grafana/oncall/commit/f23ae999982398b26090173de83a674b6b74738f
