### ISSUE TITLE
Improve documentation - escalation policies

### ISSUE THREAD

**Issue by SpawW** [grafana/oncall#2746]
### What would you like to see!

The oncall escalation policies documetation: https://grafana.com/docs/oncall/latest/oncall-api-reference/escalation_policies/
Has this information:

Parameter | Required | Description
-- | -- | --
duration | Optional | The duration, in seconds, when type wait is chosen.

But this information is not exactly right because the unit is second, but only a subset of values is accepted, named:
60 - 1 Minute
300 - 5 Minutes
900 - 15 Minutes
1800 - 30 Minutes
3600 - 60 Minutes

I think we have a opportunity to improve documentation here, changing to:
Parameter | Required | Description
-- | -- | --
duration | Optional | The duration, in seconds, when type `wait` is chosen. The amount of seconds need to be one of: `60`, `300`, `900`, `1800`, `3600`.

### Grafana OnCall Version
1.3.22

### Product Area

Schedules, Other

**Comment by SpawW** [comment]
> The current version of Grafana OnCall, at the time this issue was opened, is v1.3.22. If your issue pertains to an older version of Grafana OnCall, please be sure to list it in the PR description. Thank you smile!

Grafana OnCall Version
1.3.22

**Comment by Ferril** [comment]
You are right, thanks for reporting this issue! We'll update our docs soon
