### ISSUE TITLE
Template not work for webhook

### ISSUE THREAD

**Issue by SpawW** [grafana/oncall#2747]
### What went wrong?

**What happened**:
- I try to make integration with external tools using Outgoing Webhooks
- 
**What did you expect to happen**:
- Send custom messages to an external webhook

### How do we reproduce it?

Integration:
`
{
    "maintenance_mode": null,
    "maintenance_started_at": null,
    "maintenance_end_at": null,
    "id": "C6QWB2MIAHTD9",
    "name": "Dummy test",
    "description_short": null,
    "team_id": null,
    "link": "http://engine:8080/integrations/v1/grafana_alerting/A45c53mxznMuBkMWmAD0s7iCv/",
    "inbound_email": null,
    "type": "grafana_alerting",
    "templates": {
        "grouping_key": "my_custom_text 1\n{# Usually title is located in payload.labels.alertname #}\n{{- payload.get(\"labels\", {}).get(\"alertname\", \"No title (check Web Title Template)\") }}\n",
        "resolve_signal": null,
        "acknowledge_signal": null,
        "source_link": null,
        "slack": {
            "title": "my_custom_text 6 {# Usually title is located in payload.labels.alertname #}\n{% set title = payload.get(\"labels\", {}).get(\"alertname\", \"No title (check Web Title Template)\") %}\n{# Combine the title from different built-in variables into slack-formatted url #}\n*<{{ grafana_oncall_link }}|#{{ grafana_oncall_incident_id }} {{ title }}>* via {{ integration_name }}\n{% if source_link %}\n (*<{{ source_link }}|source>*)\n{%- endif %}\n",
            "message": "my_custom_text 7 {{- payload.message }}\n{%- if \"status\" in payload -%}\n*Status*: {{ payload.status }}\n{% endif -%}\n*Labels:* {% for k, v in payload[\"labels\"].items() %}\n{{ k }}: {{ v }}{% endfor %}\n*Annotations:* \n{%- for k, v in payload.get(\"annotations\", {}).items() %}\n{#- render annotation as slack markdown url if it starts with http #}\n{{ k }}: {% if v.startswith(\"http\") %} <{{v}}|here> {% else %} {{v}} {% endif -%}\n{% endfor %}\n",
            "image_url": null
        },
        "web": {
            "title": "my_custom_text 2\n{# Usually title is located in payload.labels.alertname #}\n{{- payload.get(\"labels\", {}).get(\"alertname\", \"No title (check Web Title Template)\") }}\n",
            "message": "my_custom_text 3\n{{- payload.message }}\n{%- if \"status\" in payload %}\n**Status**: {{ payload.status }}\n{% endif -%}\n**Labels:** {% for k, v in payload[\"labels\"].items() %}\n*{{ k }}*: {{ v }}{% endfor %}\n**Annotations:** \n{%- for k, v in payload.get(\"annotations\", {}).items() %}\n{#- render annotation as markdown url if it starts with http #}\n*{{ k }}*: {% if v.startswith(\"http\") %} [here]({{v}}){% else %} {{v}} {% endif -%}\n{% endfor %}\n",
            "image_url": null
        },
        "sms": {
            "title": "my_custom_text 5 {{ payload.get(\"labels\", {}).get(\"alertname\", \"Title undefined\") }}"
        },
        "phone_call": {
            "title": "my_custom_text 4 {{ payload.get(\"labels\", {}).get(\"alertname\", \"Title undefined\") }}"
        },
        "telegram": {
            "title": "my_custom_text 8 {{ payload.get(\"labels\", {}).get(\"alertname\", \"Title undefined\") }}",
            "message": "my_custom_text 9\n{{- payload.messsage }}\n{%- if \"status\" in payload -%}\n<b>Status</b>: {{ payload.status }}\n{% endif -%}\n<b>Labels:</b> {% for k, v in payload[\"labels\"].items() %}\n{{ k }}: {{ v }}{% endfor %}\n<b>Annotations:</b> \n{%- for k, v in payload.get(\"annotations\", {}).items() %}\n{#- render annotation as markdown url if it starts with http #}\n{{ k }}: {{ v }}\n{% endfor %}",
            "image_url": null
        },
        "email": {
            "title": "my_custom_text 10\n{# Usually title is located in payload.labels.alertname #}\n{{- payload.get(\"labels\", {}).get(\"alertname\", \"No title (check Web Title Template)\") }}\n",
            "message": "my_custom_text 11 \n{{- payload.message }}\n{%- if \"status\" in payload %}\n**Status**: {{ payload.status }}\n{% endif -%}\n**Labels:** {% for k, v in payload[\"labels\"].items() %}\n*{{ k }}*: {{ v }}{% endfor %}\n**Annotations:** \n{%- for k, v in payload.get(\"annotations\", {}).items() %}\n{#- render annotation as markdown url if it starts with http #}\n*{{ k }}*: {% if v.startswith(\"http\") %} [here]({{v}}){% else %} {{v}} {% endif -%}\n{% endfor %}\n"
        }
    },
    "heartbeat": null,
    "default_route": {
        "id": "RWI4FSCS8F8YE",
        "escalation_chain_id": "F7WADCRGY1NRY",
        "slack": {
            "channel_id": null,
            "enabled": true
        },
        "telegram": {
            "id": null,
            "enabled": false
        },
        "mobile_app": {
            "id": null,
            "enabled": false
        },
        "mobile_app_critical": {
            "id": null,
            "enabled": false
        },
        "email": {
            "id": null,
            "enabled": false
        }
    }
}
`

Sample message generated (Like code above, I make customizations in template but are sended a standard message... without use template configuration )

`
{
  "receiver": "amixr",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "TestAlert",
        "region": "eu-1"
      },
      "annotations": {
        "description": "This alert was sent by user for demonstration purposes"
      },
      "startsAt": "2018-12-25T15:47:47.377363608Z",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "",
      "amixr_demo": true
    }
  ],
  "groupLabels": {},
  "commonLabels": {},
  "commonAnnotations": {},
  "externalURL": "http://f1d1ef51d710:9093",
  "version": "4",
  "groupKey": "{}:{}"
}
`

Value received in remote webhook
![image](https://github.com/grafana/oncall/assets/3518964/774dff09-caf4-4dcd-b527-25d1bd3dba4e)

### Grafana OnCall Version

1.3.3

### Product Area

Alert Flow & Configuration, Other

### Grafana OnCall Platform?

Docker

**Comment by Matvey-Kuk** [comment]
Hi! Are you sure you are editing the right template?

<img width="1214" alt="Screenshot 2023-08-18 at 12 38 50" src="https://github.com/grafana/oncall/assets/3284841/e0f25fd4-f8e3-417d-abae-412ce40b1341">

**Comment by SpawW** [comment]
I don't know... the web interface shows a template area... I'm using the template area... is wrong?
![image](https://github.com/grafana/oncall/assets/3518964/a1fc65dc-a04b-42cf-870b-8a3ed8aabf51)
I undestand the jinja2 templates are defined here? Is wrong ?
The "message" are created using a template... and... after that... the "data" are created and organized as required by destiny  outgoing webhook... is not this ?

> Hi! Are you sure you are editing the right template?
> 
> <img alt="Screenshot 2023-08-18 at 12 38 50" width="1214" src="https://user-images.githubusercontent.com/3284841/261567743-e0f25fd4-f8e3-417d-abae-412ce40b1341.png">

**Comment by kranthikirang** [comment]
even though we set the data (a customized data) in outgoing webhook the result shows a standard payload from the integration. Also, we can't edit the data field to check what is being received and what is being converted. I am using oncall 1.3.55 and trying to send a customized payload to MS teams. Could you please help?

<img width="754" alt="image" src="https://github.com/grafana/oncall/assets/18152400/9c804828-c7e4-4b9d-b137-b01e54bce7af">

**Comment by kranthikirang** [comment]
first field is the request data and the result contains none of that. Please advice

**Comment by mderynck** [comment]
@kranthikirang please open a separate issue if this is still a problem
