### ISSUE TITLE
Escalation Chain: Continue if not acknowledged

### ISSUE THREAD

**Issue by oliveirafilipe** [grafana/oncall#275]
Hi Folks!

My goal is to create a Escalation Chain which looks like the following:
1. Notify the On-Call user in a Schedule
2. Wait 5 minutes
3. **If alert not yet acknowledged**, notify next user in Schedule
4. Wait 5 minutes
5. **If alert not yet acknowledged**, notify Slack Group

However currently in the chain creation there is no step like "Continue if alert not yet acknowledged".

What do you think about this possibility?

> PS: Comparing to other similar incident management tools, I even believe that the escalation chain could be replaced by conditions that are independent of each other. I'll be happy to contribute more ideas and thoughts on this topic.

**Comment by mderynck** [comment]
The default behaviour of the escalation chain is to continue if not yet acknowledged.
