### ISSUE TITLE
when trying to do a helm upgrade, I get an Error message: UPGRADE FAILED [...] no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by manolooon** [grafana/oncall#2753]
### What went wrong?

**What happened**:

I have this cluster gke:

<PRE>
NAME                           STATUS   ROLES    AGE   VERSION            INTERNAL-IP   EXTERNAL-IP     OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gke-cluster-hidden-name-41e9   Ready    none   24h   v1.26.5-gke.1400   hidden-ip.74   hidden-ip.186   Container-Optimized OS from Google   5.15.107+        containerd://1.6.18
gke-cluster-hidden-name-bfl4   Ready    none   24h   v1.26.5-gke.1400   hidden-ip.75   hidden-ip.187   Container-Optimized OS from Google   5.15.107+        containerd://1.6.18
</PRE>

and this helm history:

<PRE>
REVISION	UPDATED                 	STATUS    	CHART        	APP VERSION	
6       	Fri Apr 21 01:03:20 2023	superseded	oncall-1.2.8 	v1.2.8     	
7       	Fri Apr 21 01:17:07 2023	superseded	oncall-1.2.14	v1.2.14    	
8       	Fri Apr 21 13:52:28 2023	superseded	oncall-1.2.8 	v1.2.8     	
9       	Fri May 19 15:12:49 2023	superseded	oncall-1.2.26	v1.2.26    	
10      	Thu May 25 14:38:53 2023	superseded	oncall-1.2.28	v1.2.28    	
11      	Thu May 25 14:46:24 2023	superseded	oncall-1.2.30	v1.2.30    	
12      	Mon May 29 12:03:12 2023	superseded	oncall-1.2.31	v1.2.31    	
13      	Tue May 30 19:36:12 2023	superseded	oncall-1.2.32	v1.2.32    	
14      	Tue May 30 19:43:13 2023	superseded	oncall-1.2.33	v1.2.33    	
15      	Thu Jun  1 00:25:19 2023	deployed  	oncall-1.2.34	v1.2.34    	
</PRE>

And , when  I try a helm update , from chart release 1.2.34 to chart release 1.3.21, I get thist error message:

<PRE>
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "my-release-helm-oncall" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
</PRE>

**What did you expect to happen**:

I expect an succesfully helm update to newer chart

### How do we reproduce it?

1. download to disk and uncompress the oncall chart release 1.3.21
2. do a helm update in previous helm oncall chart installation:

<PRE>
helm upgrade \
--timeout 20m \
--atomic \
--wait \
my-release-helm-oncall  \
--values ./my-release-helm-oncall.yaml \
/home_dir/oncall_chart_1.3.21_uncompress \
--description "update to chart 1.3.21"
</PRE>

the values file "./my-release-helm-oncall.yaml" contains:

<PRE>
USER-SUPPLIED VALUES:
base_url: my-hidden-fqdn
cert-manager:
  enabled: true
grafana:
  grafana.ini:
    server:
      domain: my-hidden-fqdn
    smtp:
      enabled: true
      from_address: my-hidden-mail@mail.es
      from_name: ONCALL
      host: smtp.hidden.com:587
      password: password-hidden
      skip_verify: false
      user: user-hidden
oncall:
  smtp:
    enabled: true
    fromEmail: hidden-mail
    host: smtp.hidden.com
    password: password-hidden
    port: 587
    tls: true
    username: user-hidden
</PRE>  

3. I get this error after execute helm update command:

<PRE>
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "my-release-helm-oncall" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
</PRE>

### Grafana OnCall Version

1.2.34

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

N/A

### Anything else to add?

However , if I do a new gks install ( same versions that cluster that get me oncall update errors ) , and do a helm install with the same values, no get errors , make a succesfully installation and works fine.

**Comment by joeyorlando** [comment]
this is likely related to https://github.com/grafana/oncall/issues/4499

As mentioned [here](https://github.com/grafana/oncall/tree/dev/helm/oncall#cluster-requirements) under "Cluster Requirements":

> kubernetes version 1.25+ is not supported, if cert-manager is enabled

From the values file you shared, it looks like you have `cert-manager.enabled == true`. I'll close this on favour of #4499
