### ISSUE TITLE
Archive/Delete Alert Grouos

### ISSUE THREAD

**Issue by brngates98** [grafana/oncall#2758]
### What would you like to see!

Ability to "Archive/Delete" Alert Groups.

Use Case:
During initial setup/testing we had done around 500 tests with oncall alert groups and incident resposne.

Now that we have things settled we want to clear the clutter from testing, and archive them.

Would also be useful to archive alert groups and incidents as they grow historical and out of the main view to keep things clean.

### Product Area

Alert Flow & Configuration, Other

**Comment by qmonitoring** [comment]
Hello, @brngates98! See my workaround in a discussion
https://github.com/grafana/oncall/discussions/2361#discussioncomment-6640317

**Comment by brngates98** [comment]
> Hello, @brngates98! See my workaround in a discussion [#2361 (comment)](https://github.com/grafana/oncall/discussions/2361#discussioncomment-6640317)

THATS AWESOME!!!!

You wouldnt have any ideas around how i could do a similar task in incident?

**Comment by brngates98** [comment]
did some attempts to modify the python script to work with incident but no dice
`DELETE request for element 2 failed with status code: 405
DELETE request for element 3 failed with status code: 405
DELETE request for element 4 failed with status code: 405
DELETE request for element 6 failed with status code: 405
DELETE request for element 7 failed with status code: 405
DELETE request for element 8 failed with status code: 405
DELETE request for element 9 failed with status code: 405
DELETE request for element 10 failed with status code: 405
DELETE request for element 11 failed with status code: 405
DELETE request for element 12 failed with status code: 405
DELETE request for element 13 failed with status code: 405
DELETE request for element 14 failed with status code: 405
DELETE request for element 15 failed with status code: 405
DELETE request for element 16 failed with status code: 405
DELETE request for element 18 failed with status code: 405
DELETE request for element 19 failed with status code: 405
DELETE request for element 20 failed with status code: 405
DELETE request for element 22 failed with status code: 405
DELETE request for element 24 failed with status code: 405
DELETE request for element 25 failed with status code: 405
DELETE request for element 26 failed with status code: 405
DELETE request for element 27 failed with status code: 405`

**Comment by brngates98** [comment]
`import requests
import json

url = 'https://org.grafana.net/api/plugins/grafana-incident-app/resources/api/v1/IncidentsService.QueryIncidents'
headers = {
    'Authorization': 'Bearer token',
    'Content-Type': 'application/json'
}

data = {
  "query": {
    "OrderDirection": "ASC"
  }
}

response = requests.post(url, headers=headers, data=json.dumps(data))


alert_group_status = 'resolved'  # Specify the desired value for the field

if response.status_code == 200:
    data = response.json()
    desired_elements = []
    for item in data['incidents']:
        if item.get('status') == alert_group_status:
            desired_elements.append(item['incidentID'])
    
    delete_base_url = 'https://org.grafana.net/api/plugins/grafana-incident-app/resources/api/v1/IncidentsService.QueryIncidents'
    delete_headers = {
        'Authorization': 'Bearer token',
        'Content-Type': 'application/json'
    }
    
    for element in desired_elements:
        delete_url = delete_base_url + element

        delete_payload = json.dumps({
            'mode': 'delete'
        })        
        
        delete_response = requests.delete(delete_url, headers=delete_headers, data=delete_payload)
        
        if delete_response.status_code == 204:
            print('DELETE request for element', element, 'was successful')
        else:
            print('DELETE request for element', element, 'failed with status code:', delete_response.status_code)
        # Print the HTTP request details
 #       print('HTTP Request:')
 #       print(delete_response.request.method, delete_response.request.url)
 #       print('Headers:', delete_response.request.headers)
 #       print('Body:', delete_response.request.body)            
else:
    print('GET request failed with status code:', response.status_code)`

**Comment by joeyorlando** [comment]
as mentioned this is possible via the public API ([docs](https://grafana.com/docs/oncall/latest/oncall-api-reference/alertgroups/#delete-an-alert-group)). Will go ahead and close this!
