### ISSUE TITLE
Amixr reference in Oncall

### ISSUE THREAD

**Issue by BitProcessor** [grafana/oncall#276]
The codebase seems to be needing some good old search and replace:

```
{
    "state": "alerting",
    "title": "Webhook heartbeat is missing",
    "message": "Amixr was waiting for a heartbeat from Webhook. Heartbeat is missing. That could happen because Webhook stopped or there are connectivity issues between Amixr and Webhook. Read more in Amixr docs: https://grafana.com/#/integrations/heartbeat",
    "alert_uid": "7973c835-ff3f-46e4-9444-06df127b6f8e",
    "image_url": null,
    "is_amixr_heartbeat": true,
    "link_to_upstream_details": null,
    "is_amixr_heartbeat_restored": false
}
```

**Comment by Matvey-Kuk** [comment]
Thank you for the issue!

I think it's better to leave `is_amixr_heartbeat_restored` and add `is_oncall_heartbeat_restored` for backwards compatibility.

Btw we're open for contributions ;)

**Comment by BitProcessor** [comment]
@Matvey-Kuk
The `message` part could probably easily be fixed? 
Because as a Grafana Cloud OnCall user, am I supposed to know it once upon a time was called Amixr ? ;)

**Comment by mderynck** [comment]
This has already been fixed
