### ISSUE TITLE
Editors no longer able to edit/verify their own phone number

### ISSUE THREAD

**Issue by mothershipper** [grafana/oncall#2761]
### What went wrong?

**What happened**:
Users with the editor role cannot edit their own phone numbers any longer. 

**What did you expect to happen**:
Users with editor role should be able to edit their own phone number.

### How do we reproduce it?

Should be reproducible by using an editor account and trying to verify your phone number.

### Grafana OnCall Version

1.3.22

### Product Area

Auth

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

All

### Anything else to add?

I believe it's this line: https://github.com/grafana/oncall/blame/a1a9e0c33c0c2fe5a78e68af3409dcc3ce9d5f1c/grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx#L191

Looks like OtherSettings is an admin perm?

https://github.com/grafana/oncall/blob/a1a9e0c33c0c2fe5a78e68af3409dcc3ce9d5f1c/grafana-plugin/src/utils/authorization/index.ts#L160

Also seems like this was introduced 5 days ago, so most likely a fresh issue in the plugin UI. Not sure if the API is enforcing this permission set as well though.

**Comment by nikitaspitsky** [comment]
+1, we have the same problem in Grafana Cloud

**Comment by teodosii** [comment]
This was indeed recently added to the UI because the other tabs on the user's profile also required `OtherSettingsWrite` rights (e.g. slack). My thinking was that these tabs should all behave the same in terms of permissions.

**Comment by mothershipper** [comment]
@teodosii I'm not sure if you're confirming that this is a bug or if going forward a user must be a grafana admin to set up their own phone notifications? If it is a bug, no worries, it happens :) 

If it's not a bug, I'd urge you to reconsider. There is presently no way for users to add their phone number without visiting that tab (add / edit button from the main profile page links them to that tab).

**Comment by teodosii** [comment]
@mothershipper The problem was that the tab was requiring `OtherSettingsWrite` instead of `UserSettingsWrite`. All other user's profile tabs require this, which prior to introducing this bug didn't have any permission check - that's why it was added, just that it was the wrong permission. Will add a fix soon

**Comment by teodosii** [comment]
Fixed and released

**Comment by mothershipper** [comment]
All good.

We just updated and it's working again, thanks for the fix :)
