### ISSUE TITLE
Grafana OnCall OSS docker - missing Inbound Email integration (any many others too)

### ISSUE THREAD

**Issue by tuxmartin** [grafana/oncall#2777]
### What went wrong?

**What happened**:
I tried `Grafana v10.0.3 (eb8dd72637)`, `OnCall (1.3.23, OpenSource)` using this [docker-compose file](https://github.com/grafana/oncall/blob/dev/docker-compose.yml).

My `.env` file (just for testing) contains:

```
DOMAIN=http://localhost:8080
COMPOSE_PROFILES=with_grafana  # Remove this line if you want to use existing grafana
SECRET_KEY=my_random_secret_must_be_more_than_32_characters_long

INBOUND_EMAIL_ESP=amazon_ses
INBOUND_EMAIL_DOMAIN=example.net
INBOUND_EMAIL_WEBHOOK_SECRET=123456789
```
 
[Inbound Email integration](https://grafana.com/docs/oncall/latest/integrations/inbound-email/) is missing. When I tried Grafana OnCall OSS couple of month ago, Inbound Email integration was present on the integration list.

Are all [integrations](https://grafana.com/docs/oncall/latest/integrations/) supported in Grafana OnCall OSS? Or I have to use grafana.net?

For example, [Amazon SNS](https://grafana.com/docs/oncall/latest/integrations/amazon-sns/) is not available on the integration list too.
 

**What did you expect to happen**:

Possibility to turn on [all integrations](https://grafana.com/docs/oncall/latest/integrations/) from the documentation. The most important for me is [Inbound Email integration](https://grafana.com/docs/oncall/latest/integrations/inbound-email/).

### How do we reproduce it?

1. Open Grafana OnCall and go to the http://localhost:3000/a/grafana-oncall-app/integrations?p=1
2. Now click button `New integration`

### Grafana OnCall Version

1.3.23, OpenSource

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Docker

**Comment by nonamef** [comment]
Looks like the configuration was never added for **Amazon SNS** and other integrations.
https://github.com/grafana/oncall/blob/c9cb4328e814f674b0f7b42556c14e16518c354a/engine/settings/base.py#L700
https://github.com/grafana/oncall/tree/c9cb4328e814f674b0f7b42556c14e16518c354a/engine/config_integrations

**Comment by kuzaxak** [comment]
`inbound_email` is there, so at least one of the integrations should work

**Comment by vadimkerr** [comment]
Hi @tuxmartin 👋 

I believe there's a feature flag for enabling the inbound email integration `FEATURE_INBOUND_EMAIL_ENABLED`, which is not enabled by default (and this feature flag is not documented [here](https://grafana.com/docs/oncall/latest/open-source/#inbound-email-setup) as it should be).

To get the inbound email integration working on your instance, you could add something like this to your `docker-compose.yml` file:

```yaml
FEATURE_INBOUND_EMAIL_ENABLED: "True"
INBOUND_EMAIL_ESP: "amazon_ses"
INBOUND_EMAIL_DOMAIN: "example.net"
INBOUND_EMAIL_WEBHOOK_SECRET: "123456789"
```

Opened a PR to enable the feature flag by default to make the setup process consistent with the docs: https://github.com/grafana/oncall/pull/2846.

It's expected to have some integration types missing on OSS instances, but looks like the docs on this are misleading. I propose to track the OSS vs cloud integration docs in [this issue](https://github.com/grafana/oncall/issues/2616).

**Comment by tuxmartin** [comment]
@vadimkerr thank you, it works :star_struck:  

```yaml
FEATURE_INBOUND_EMAIL_ENABLED: "True"
```

Is there a list of which integrations are only available in the commercial version (not OSS) of Grafana Oncall?

**Comment by vadimkerr** [comment]
Glad it worked! 
See [here](https://github.com/grafana/oncall/issues/2616#issuecomment-1686454196) for the list of integrations available on OSS, and [here](https://grafana.com/docs/oncall/latest/integrations/#list-of-available-integrations) for the list of integrations available in the cloud offering.
