### ISSUE TITLE
Terraform created outgoing webhook won't show in web ui

### ISSUE THREAD

**Issue by agaibura-tripleten** [grafana/oncall#2793]
### What went wrong?

**What happened**:
- I created an outgoing webhook through terraform
```
resource "grafana_oncall_outgoing_webhook" "jira_create_spi" {
  name = "jira_create_spi"
  url = "https://yourcompany.atlassian.net/rest/api/2/issue/"
  authorization_header = "Authorization: Basic ${data.vault_generic_secret.selected.data.grafana_oncall_jira_token}]"
  data = jsonencode({
    fields = {
        project = {
            key = "SPI"
        }
        summary = "[unknown] - {{ alert_payload.labels.alertname }}"
        description = "prom link: {{alert_payload.generatorUrl}}; link: {{ alert_payload.permalinks }}"
    }
  })
}
```
- i open an outgoing webhook page in web ui (OSS)

**What did you expect to happen**:
- the created webhook is shown in the web ui.

### How do we reproduce it?

1. Deploy code above
2. Open OSS web UI
3. The webhook is not shown on the page.

terraform version: 2.2.0

### Grafana OnCall Version

1.3.23

### Product Area

Terraform

### Grafana OnCall Platform?

Kubernetes

**Comment by agaibura-practicum** [comment]
I also created action_to_trigger step in an escalation chain. So i see this step as blank step in web ui.
Here is some pictures.
![image](https://github.com/grafana/oncall/assets/120477675/99d0a755-8513-4208-954d-22a8abbcb084)
![image](https://github.com/grafana/oncall/assets/120477675/c6186c96-b8e7-45b5-a88e-5c2fd7e47d6d)

**Comment by agaibura-practicum** [comment]
sample code for escalations:
```

# jira create SPI
resource "grafana_oncall_escalation" "SRE_SPI_0" {
  provider = grafana
  escalation_chain_id = grafana_oncall_escalation_chain.SRE.id
  type = "trigger_action"
  position = 0
  action_to_trigger = grafana_oncall_outgoing_webhook.jira_create_spi.id
}
```

**Comment by iskhakov** [comment]
fixed by https://github.com/grafana/oncall/pull/2790
