### ISSUE TITLE
Sort teams alphabetically in "Teams and Access Settings" page

### ISSUE THREAD

**Issue by tomwilkie** [grafana/oncall#2795]
### What would you like to see!

I'd like the teams to be sorted alphabetically in the "Teams and Access Settings" pages under OnCall > Settings, so I can find the right team in the list more quickly.

### Product Area

Auth

**Comment by Matvey-Kuk** [comment]
Also the same is with Escalation Chains page.

**Comment by joeyorlando** [comment]
closing as this has been implemented 👍
