### ISSUE TITLE
Grafana Oncall v1.3.19 version having issue with "Editor" role - not able to access alerts/configuration/home page

### ISSUE THREAD

**Issue by VenkatChowdaryK** [grafana/oncall#2796]
### What went wrong?

**What happened**:

We upgraded the version to grafana oncall to v1.3.19 and whoever having editor access they are not able to access the grafana links/schedules/alerts and getting the below error.

There is no issue with the "admin" role for the same version v1.3.19

User is missing permission(s) plugins:write, org.users:read, teams:read, apikeys:create, apikeys:delete to setup OnCall before it can be used

**What did you expect to happen**:
-
It should work as expected as per the old version.

### How do we reproduce it?

1. upgrade the version to v1.3.19
2. click on slack channel link --> it will redirect to oncall
3. giving the error mentioned.

Even if we go directly to the link home page of grafana oncall, getting the same error.

User is missing permission(s) plugins:write, org.users:read, teams:read, apikeys:create, apikeys:delete to setup OnCall before it can be used

![image](https://github.com/grafana/oncall/assets/127250005/e2eab89c-b8e8-4f83-9092-240a4e530b86)

### Grafana OnCall Version

v1.3.19

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Chrome version

**Comment by joeyorlando** [comment]
hi there @VenkatChowdaryK.

Can you try upgrading to the latest version (v1.3.24 as of this writing) and see if you are able to reproduce?

If that does not solve the issue. Can you provide the following context please:
- any relevant error logs from:
  - grafana container
  - oncall-engine and celery containers

Also, are you running w/ RBAC enabled?

**Comment by joeyorlando** [comment]
Going to close this. If you are still running into this issue, feel free to reopen @VenkatChowdaryK
