### ISSUE TITLE
Escalation option "Continue escalation if time is in range" should be shown in UTC not local

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#2817]
### What went wrong?

**What happened**:
- Link to slack https://raintank-corp.slack.com/archives/C04JCU51NF8/p1691754533392279

**What did you expect to happen**:
-

### How do we reproduce it?

1. Open Escalations screen
2. Add option to continue escalation if time
3. Input time

The inputted time you'd expect to be in UTC but it is actually converted to UTC once sent to the backend. So if you're on UTC+3 and you input 17:00 thinking it will start at 17:00 UTC it will actually be converted to 14:00 UTC.

### Grafana OnCall Version

latest

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by vadimkerr** [comment]
@teodosii this looks like a duplicate of https://github.com/grafana/oncall/issues/2781?

**Comment by teodosii** [comment]
@vadimkerr  Seems so, I didn't know there's a ticket for that already. Closing this one
