### ISSUE TITLE
Logo issue inside OnCall Insights dashboard

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#2819]
### What went wrong?

**What happened**:
- Logo location was replaced, as result we are missing the logo.

**What did you expect to happen**:
- Update logo URL inside dashboard

![image](https://github.com/grafana/oncall/assets/102970268/698fd8d2-5c0f-461f-978c-56c6ed58a1fb)

### How do we reproduce it?

1. Open Grafana OnCall Insights dashboard.

### Grafana OnCall Version

r214-v1.3.24

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by matiasb** [comment]
This has been fixed in a recent release.
