### ISSUE TITLE
Can't set up Telegram integration

### ISSUE THREAD

**Issue by Gufderald** [grafana/oncall#283]
Hi!

Faced with some difficulties while setting up Telegram integration. 

Firstly, I had set up certain Env variables (`TELEGRAM_TOKEN` and `TELEGRAM_WEBHOOK_HOST`) and restarted `engine`
Secondly, I've managed to see link to my bot on pressing `Connect Telegram Channel` button. However, after following instructions and sending verification code to the channel, nothing happens. Bot seems not to read new messages in the channel, as there is only one "viewed" icon on it (for me myself).
Third, when trying to verify user's telegram account, bot reads verification code wich was send to him, but does not responses. 

I've double checked my `WEBHOOK_HOST` is available via HTTP from outside. Am I missing something?

Thanks in advance.

**Comment by vadimkerr** [comment]
Hi @Gufderald, could you please check that the `TELEGRAM_WEBHOOK_HOST` variable you set starts with "https://"? Telegram only accepts externally available https webhook URLs, so I think this could cause the problem. Please let me know if this helps to solve the issue.

FYI: We're working on better validation for this kind of env variables in this [PR](https://github.com/grafana/oncall/pull/307).

**Comment by Tab-ops** [comment]
@Gufderald I have the same problem, did you solve it?

**Comment by Matvey-Kuk** [comment]
@Tab-ops could you please provide some details of your setup? Do you use `https://` link for telegram for TELEGRAM_WEBHOOK_HOST as @vadimkerr mentioned above?

**Comment by vadimkerr** [comment]
https://github.com/grafana/oncall/pull/307 is now merged and should allow catching erorrs related to `TELEGRAM_WEBHOOK_HOST` easier. Also after merging doc updates in https://github.com/grafana/oncall/pull/406, it should be more clear now how to set up the Telegram integration.
Updating to the newest version of OnCall should resolve the issue, so I’m closing it.
@Gufderald feel free to reopen it and provide some additional details in case this doesn’t help.
