### ISSUE TITLE
Show magical shift swaps

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#2844]
### What would you like to see!

I create shift swap for the time period when **I'm not on-call** (Thursday and Friday):
<img width="1166" alt="Screenshot 2023-08-21 at 16 16 24" src="https://github.com/grafana/oncall/assets/3284841/bc1e669a-83ce-4ff0-b1a9-6ded83045c90">

When it's created it's **invisible because there is nothing to swap**:
<img width="1162" alt="Screenshot 2023-08-21 at 16 18 09" src="https://github.com/grafana/oncall/assets/3284841/0feb5729-7d2c-4daf-9634-9f70d4ce9de9">

If I put myself on-call, shift swap request becomes visible.
<img width="1157" alt="Screenshot 2023-08-21 at 16 19 00" src="https://github.com/grafana/oncall/assets/3284841/9f85a37b-36a1-4b31-9e1d-3939f6657c60">

This behaviour is "Magical" which we would like to avoid. I propose to show shift swaps even if they don't have anything to swap.

Let's:
1) Call "overrides" panel a "Overrides and swaps"
2) Move "Create shift swap" to the "Overrides and swaps" panel.
3) Show full shift swaps at this panel.

### Product Area

Schedules

**Comment by raphael-batte** [comment]
Web/mobile UIs unified visualisation possible direction
![image](https://github.com/grafana/oncall/assets/102970268/124de463-9c6f-4129-9c95-b9887d5d6f11)
![image](https://github.com/grafana/oncall/assets/102970268/925c98d4-efa9-4538-b536-e312c981b0d4)

**Comment by raphael-batte** [comment]
****Collection from 21/08 **:**

- [ ] highlight new swap by yellow color
- [ ] disable renaming for the modal
- [ ] add swap requester name to the field in the modal
- [ ] 'Take' button is disabled for requester
- [ ] Add link button to open SSR in Slack

**- [ ] Naming**
Titles
1. Shift swap request - requested state
2. Shift swap - Accepted by user state
Users
3. Requested by
4. Swapped by
Buttons
5. Create
6. Accept
