### ISSUE TITLE
Update webhooks Terraform provider

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#2864]
### What would you like to see!

The new webhooks API adds functionality not currently available in the outgoing webhooks resource.  With the addition of #2790 webhooks created through the outgoing webhooks resource remain compatible and result in "new" webhooks objects but it would be good to have access to all the new fields and update field names to match the current API.

### Product Area

Terraform

**Comment by IdeoG** [comment]
Hi @mderynck ,
Thank you so much for your MR that fixes outgoing webhook api and that you created this merge request to make available webhooks functionality to terraform.
I see this issue without any answer for 3 weeks. Should we notify maintainers or make additional issue to grafana/grafana?

Have a nice day)

**Comment by mderynck** [comment]
@IdeoG no need for another issue, the same people that follow this repo will likely make the update to `grafana/terraform-provider-grafana` hopefully we can get to it soon.  Thanks!

**Comment by IdeoG** [comment]
Thank you!

**Comment by vadimkerr** [comment]
The new attributes for outgoing webhooks are now available in the Terraform provider [v2.6.0](https://github.com/grafana/terraform-provider-grafana/releases/tag/v2.6.0). See the [docs](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_outgoing_webhook) for more details.
