### ISSUE TITLE
[Shift Swap Request] when someone accepts my shift swap request, it would be nice to receive notifications notifying me

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2868]
### What would you like to see!

Requested by @inkel as feedback on using the feature.

**Deliverables**
When someone accepts a shift swap request:
- send a push notification to the beneficiary letting them know (if they have info notifications enabled).
- send a message in the Slack thread and tag the beneficiary letting them know

### Product Area

Schedules

**Comment by charleskorn** [comment]
As an alternative to a push notification, a response to the Slack thread created when the swap request is made, or even just an email, would also work for me
