### ISSUE TITLE
show ssr without shifts on mobile

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#2879]
Design
![Image](https://github.com/grafana/oncall/assets/20601437/bfde861c-4df6-431e-9dfc-0bf9e11e3be1)

more info [here](https://github.com/grafana/oncall/issues/2844)

**Comment by Dieterbe** [comment]
the above PR shows the new labels, but doesn't work yet for ssr's without shifts.
for those, we will need to call a new api endpoint
