### ISSUE TITLE
Update OnCall Metrics dashboard

### ISSUE THREAD

**Issue by Ferril** [grafana/oncall#2897]
### What would you like to see!

- [x] rename the dashboard to "OnCall Insights" (this name is used inside the dashboard)
- [x] fix panels location after last update
- [ ] move dashboard from "General" folder to another folder (probably create a new one)
- [x] test dashboard update on changing dashboard version

### Product Area

Other

**Comment by Ferril** [comment]
Regarding to [this thread](https://raintank-corp.slack.com/archives/C01C4K8DETW/p1693306082767529) we cannot move the dashboard to another folder using our current settings.
The option we have - import the dashboard using API instead of importing it in `plugin.json` ([example](https://github.com/grafana/synthetic-monitoring-app/blob/420e68239d2d54432d710dc73c814e3579b0f3a6/src/dashboards/loader.ts#L13))

**Comment by Matvey-Kuk** [comment]
@Ferril in this case I think we should close the issue. WDYT?

**Comment by Ferril** [comment]
@Matvey-Kuk agree, it makes sense to create a separate task for this since it's not super fast to implement and we need to discuss it first
