### ISSUE TITLE
Cleanup and refactor Slack mesages about Schedules

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#2916]
### What would you like to see!

- unify message style and time representation
- make them according to the new design.
![image](https://github.com/grafana/oncall/assets/102970268/716301d9-3319-4ca1-84cf-8acf0abfac2c)

### Product Area

Chatops

**Comment by joeyorlando** [comment]
I slightly renamed this, as shift swap requests are being updated in #2918 🙂
