### ISSUE TITLE
Pagerduty Migration failed in migrate mode

### ISSUE THREAD

**Issue by pramodh-b** [grafana/oncall#2917]
### What went wrong?

**What happened**:
- The migration is failing in migrate mode, I used the plan mode 1st and, and the output details were correct. But in migrate mode it failed and below is the error.

File "/app/migrator/oncall_api_client.py", line 46, in api_call
    raise requests.exceptions.HTTPError(
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://URL/api/v1/personal_notification_rules, response payload JSON: {'type': 'Invalid type'}

**What did you expect to happen**:
I was expecting a successful migration in migrate mode.

### How do we reproduce it?

By running Pager duty migrator in migrate mode we can reproduce this error

### Grafana OnCall Version

1.3.27

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

Are you using OSS or Grafana Cloud?
Ans: OSS
What’s the version of OnCall on your instance?
Ans: Onall plugin version: 1.3.27, Grafana version: 9.5.3
Which types of user notification rules are used on your PD instance? (e.g. email, SMS, etc.)
Ans: Email, Call, SMS, App notification

Used helm package manager to install oncall and configure.
helm install my-oncall grafana/oncall --version 1.3.27

**Comment by vadimkerr** [comment]
👋  @pramodh-b could you please try setting [`.Values.oncall.smtp.enabled`](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L201) to `true` and running the migration again and see if it helps?

**Comment by pramodh-b** [comment]
Hi @vadimkerr its still same issue.

**Comment by vadimkerr** [comment]
I'm not able to reproduce the issue when passing `--set oncall.smtp.enabled=true` to Helm. Maybe some values are not getting propagated on your deployment @pramodh-b?

**Comment by pramodh-b** [comment]
As you suggested changes SMTP values to true and provided the details. Now there is another error with migrate mode in the Migrating schedule step. below is the error.

▶ Migrating schedules...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/migrator/__main__.py", line 184, in <module>
    main()
  File "/app/migrator/__main__.py", line 157, in main
    migrate_schedule(schedule, user_id_map)
  File "/app/migrator/resources/schedules.py", line 45, in migrate_schedule
    "ical_url_primary": schedule["http_cal_url"],
                        ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'http_cal_url'

**Comment by vadimkerr** [comment]
The issue should be fixed in [this PR](https://github.com/grafana/oncall/pull/2975) by setting `oncall.smtp.enabled=true` by default.

@pramodh-b regarding the `http_cal_url`, please make sure you're using a **User Token REST API Keys** and NOT a **General Access REST API Keys** as per [the instruction](https://github.com/grafana/oncall/tree/dev/tools/pagerduty-migrator#prerequisites). If that doesn't help, feel free to open a new issue here in the GH repo.
