### ISSUE TITLE
Send alert resolved emails to all notified users

### ISSUE THREAD

**Issue by ncs29** [grafana/oncall#2926]
### What would you like to see!

Currently, it appears users are notified via email only when alerts are firing. 

It would be very useful to be able to send "Resolved" notifications to users via Email too. This resolution notification should go to all users who were notified for the firing alert.

(Apologies if this is already possible, though, from what I tried, this does not seem possible currently)

### Product Area

Alert Flow & Configuration

**Comment by roock** [comment]
Related to #3057

**Comment by Matvey-Kuk** [comment]
While this feature is not available that's somehow possible via a new advanced webhook which could be triggered by "resolved" action: https://grafana.com/docs/oncall/latest/outgoing-webhooks/

**Comment by iskhakov** [comment]
closing in favour of https://github.com/grafana/oncall/issues/3057
