### ISSUE TITLE
filter_shift_swaps does not include schedule ID unlike filter_events which does

### ISSUE THREAD

**Issue by Dieterbe** [grafana/oncall#2938]
### What would you like to see!

in internal api, if filter_shift_swaps would also include schedule ID, like filter_events, that would help us to more cleanly separate shift swap events from different schedules

### Product Area

Other

**Comment by matiasb** [comment]
To be sure, a serialized shift swap includes the schedule ID, right? e.g.

```
{
 "id":"SSRUHEPKPDJPE7M",
 "created_at":"2023-08-04T15:41:45.089627Z",
 "updated_at":"2023-08-04T15:41:45.090271Z",
 "status":"past_due",
 "schedule":"SYHY3B4M2P3YZ",
 "swap_start":"2023-08-07T12:00:00.000000Z",
 "swap_end":"2023-08-12T21:00:00.000000Z",
 "description":null,
 "beneficiary": {"display_name":"-","email":"- ","pk":"UG5LZU4AZUHU1","avatar_full":"-"},
 "benefactor":null
}
```

OTOH, you mean `filter_shift_swaps` which is available per specific schedule? ie. you have the schedule ID in the endpoint like:

`/api/internal/v1/schedules/SYHY3B4M2P3YZ/filter_shift_swaps/?date=2023-08-1&days=10`

**Comment by Dieterbe** [comment]
> you mean filter_shift_swaps which is available per specific schedule? ie. you have the schedule ID in the endpoint like:

yes. i know we technically already "know" the schedule Id because we request it, but if it's omitted from the response than it's an incomplete representation and we just have to juggle a bit on the client to re-add it.

**Comment by Matvey-Kuk** [comment]
I guess this issue is outdated.
