### ISSUE TITLE
Slack notifications when override changed but schedule was not affected

### ISSUE THREAD

**Issue by summerwollin** [grafana/oncall#294]
Context: https://raintank-corp.slack.com/archives/C0229FD3CE9/p1658852803728199

Many overrides were created within a couple minutes of each other that did not change the on-call schedule in order to preserve our rotation calendar as we are about to add another person to the rotation. This caused the on-call app to post to slack with notifications about shift changes even though who was on-call for each shift remained the same. The notifications were only for the current week's shifts so it was 4 notifications for the 4 days left in the shifts.

Possible solutions would be to  either not display a message at all if it is the same as previous or add a line indicating an override has changed but the current shifts are not affected

**Comment by matiasb** [comment]
This should have been fixed by https://github.com/grafana/oncall/pull/2080.
