### ISSUE TITLE
no "shift swap pills" shown on "my upcoming shifts" page

### ISSUE THREAD

**Issue by Dieterbe** [grafana/oncall#2940]
### What went wrong?

should this page also show the "pills"? it is more technically challenging than on the schedules page (which will show them soon)
![image](https://github.com/grafana/oncall/assets/20774/9a5d80ee-7f0b-4925-bade-386d22cb635e)

@raphael-batte 

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

latest

### Product Area

Mobile App

### Grafana OnCall Platform?

None

**Comment by imtoori** [comment]
it would be nice, but it's very hard to achieve and I don't see it as a very important thing
I suggest not to show them here
