### ISSUE TITLE
mobile: no SSR events shown for completely empty schedules

### ISSUE THREAD

**Issue by Dieterbe** [grafana/oncall#2948]
### What went wrong?

create schedule without rotations
create a shift swap request on it
mobile app shows "no events on schedule"

when we fix this, we should consider both the case of SSR's in the current 60 day window, as well as in the window before or after

### How do we reproduce it?

see above

### Grafana OnCall Version

latest

### Product Area

Mobile App

### Grafana OnCall Platform?

None

**Comment by Matvey-Kuk** [comment]
It sounds like exact same issue as #2844

**Comment by Dieterbe** [comment]
no, magic shift swaps in general work now (in open beta), at least for the normal case that a schedule has a rotation/some shifts defined (and the shifts don't need to match the SSR's).
this issue is about the specific case where a schedule has no shifts/rotations defined at all.
