### ISSUE TITLE
Not receiving notifications ahead of on-call shift

### ISSUE THREAD

**Issue by dannykopping** [grafana/oncall#2953]
### What went wrong?

**What happened**:
- I went on shift, but did not receive a push notification indicating my shift was starting soon

**What did you expect to happen**:
- I expected a push notification which I'd received when previously going on shift

### How do we reproduce it?

...

### Grafana OnCall Version

v1.3.4 - build 1118

### Product Area

Schedules

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by iskhakov** [comment]
Could you please re-open this issue if the problem persists. Also it is recommended to add notifications via slack notifications as a backup
