### ISSUE TITLE
Detail: Not Found popup message when visiting schedule detail page

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2964]
### What went wrong?

**What happened**:
When visiting a schedule detail page, this popup is shown:
<img width="1256" alt="Screenshot 2023-09-05 at 11 54 07" src="https://github.com/grafana/oncall/assets/9406895/7a921680-2edc-498c-9e9f-94448850f1b9">

**What did you expect to happen**:
We shouldn't see this popup

### How do we reproduce it?

1. Visit [schedules list page](https://ops.grafana-ops.net/a/grafana-oncall-app/schedules?p=1&team=TQBM2K8NNEMAJ)
2. Click on the "OnCall team main (8-8-8)" schedule to go to the detail page
3. Popup notification is shown

### Grafana OnCall Version

r227-v1.3.32

### Product Area

Schedules

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by maskin25** [comment]
@joeyorlando seems it is fixed already, can you confirm please?

**Comment by joeyorlando** [comment]
@maskin25 yup just checked, looks like this has been resolved 👍 I'll go ahead and close.
