### ISSUE TITLE
Oncall shows connected, but none of the pages/panels load

### ISSUE THREAD

**Issue by rfaile313** [grafana/oncall#2977]
### What went wrong?

**What happened**:
- I'm able to configure/connect OSS/external grafana to oncall and it shows connected, but none of the pages load. 

<img width="442" alt="Screenshot 2023-09-05 at 3 32 16 PM" src="https://github.com/grafana/oncall/assets/13829168/a8055901-bfae-4bfe-b77c-8b261529bb5c">
<img width="1025" alt="Screenshot 2023-09-05 at 3 32 24 PM" src="https://github.com/grafana/oncall/assets/13829168/c4033418-f33e-473d-9c0a-cc19068e9242">

In the container logs for oncall, I see 4xx responses to page navigation requests, like:

```
2023-09-05 20:32:29 source=engine:app google_trace_id=none logger=django.request Forbidden: /api/internal/v1/notification_policies/notify_by_options
2023-09-05 20:32:29 source=engine:uwsgi status=403 method=GET path=/api/internal/v1/notification_policies/notify_by_options latency=0.010127 google_trace_id=- protocol=HTTP/1.0 resp_size=249 req_body_size=0
```

**What did you expect to happen**:
- since oncall shows connected sucessfully and properly, I would expect the app pages/options to work 

### How do we reproduce it?

Connect external grafana to oncall running in a docker container elsewhere. After successfully connected, try and access the page/panels in the plugin app e.g. `<grafana_url>/a/grafana-oncall-app`

### Grafana OnCall Version

1.3.35

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Docker

### User's Browser?

Firefox 116.0.3 (64-bit)

**Comment by iskhakov** [comment]
closing in favour of https://github.com/grafana/oncall/issues/3772
