### ISSUE TITLE
Migrate @grafana/toolkit to create-plugin instead

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#2980]
### What went wrong?

We're currently using `@grafana/toolkit` but that package has been deprecated and we should aim at migrating it to `create-plugin` instead as that is the alternative grafana offers

**Comment by maskin25** [comment]
duplicate of [Migrate from grafana-toolkit to grafana plugin tools #3651](https://github.com/grafana/oncall/issues/3651), (more precisely, it’s the other way around, but it’s easier for me to close this one :)
