### ISSUE TITLE
minor UI bug: page heading partially overwritten

### ISSUE THREAD

**Issue by simonc6372** [grafana/oncall#2981]
### What went wrong?

**What happened**:
- On the settings -> about page, the page heading is overwritten by the left-arrow navigation. 
Happens in Portrait mode. In Landscap, it's fine. 

![Screenshot_20230906_090749_Grafana OnCall](https://github.com/grafana/oncall/assets/8004654/3a75d980-a6ff-4e8c-ab89-007f80fe453a)

**What did you expect to happen**:
- Title to be fully visible. 

### How do we reproduce it?

1. ensure phone is in portrait alignment. 
2. Open the android app. 
3. tap settings. 
4. tap "About Grafana OnCall

### Grafana OnCall Version

OnCall Version: 1.5.3 build 1191 - Phone : Samsung S21 (SM-G991B/DS)  - OS : Android version 13 - One UI Version: 5.1

### Product Area

Mobile App

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

n/a

### Anything else to add?

Only a minor UI bug. No impact on app usage.

**Comment by imtoori** [comment]
@simonc6372 I think this is normal, if you try to scroll more to the bottom you should see the title moving from the scrollable body to the appbar
Can you confirm this?

**Comment by simonc6372** [comment]
When scrolling down, the top of the screen shows the start of the title, but it's still not possible to see the full title. 
It's a very minor bug on this page, but if this is what the tooling produces, it may become a problem on other pages, if the title is more important. 
Also, it just makes the app look less polished.  

![image](https://github.com/grafana/oncall/assets/8004654/d304e0c1-8619-41fd-84fc-b2c63b0f50bb)

**Comment by imtoori** [comment]
@simonc6372 I suspect you are using increased font/display size, in that case this happens
I'm fixing it right now
