### ISSUE TITLE
OnCall Shift public list api's filter by schedule_id is broken

### ISSUE THREAD

**Issue by fathom-jackchen** [grafana/oncall#2988]
### What went wrong?

**What happened**:
- Ran `<API_URL>/oncall/api/v1/on_call_shifts/?schedule_id=<SCHEDULE_ID>` and got empty list
- Similar apis works though `<API_URL>/api/plugin-proxy/grafana-oncall-app/api/internal/v1/oncall_shifts/?schedule_id=<SCHEDULE_ID>`

**What did you expect to happen**:
- I expect to get same response or at least a non-empty response from the first api

### How do we reproduce it?

1. Make `<API_URL>/oncall/api/v1/on_call_shifts/?schedule_id=<SCHEDULE_ID>` call with schedule with shifts
2. Docs: https://grafana.com/docs/oncall/latest/oncall-api-reference/on_call_shifts/

### Grafana OnCall Version

Grafana Cloud

### Product Area

Schedules, Other

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

Google chrome 16.0.5845.140 (Official Build) (arm64)

### Anything else to add?

Seems like there was fix for mirrored API but not this one.

Fix: https://github.com/grafana/oncall/commit/6dc4657371a5fa6eac798406e9298d93aaf53fa4
Needs this Fix: https://github.com/grafana/oncall/blob/31759fdf8082af486f3c9dfc5d52a99718a9a0cc/engine/apps/public_api/views/on_call_shifts.py#L35

**Comment by matiasb** [comment]
Thanks! This should have been fixed in https://github.com/grafana/oncall/pull/3165.
