### ISSUE TITLE
"Add responder": DP integration by default + default E-Mail notifications

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#3021]
- [ ]  In Personal Notification settings, Email notification should be by default in both Important and Default chains.
- [ ]  When OnCall consumes new team from Grafana, OnCall should automatically create "Direct Paging" integration for this team. Including "General Team (or No Team)" 
- [ ] Should we make Team selector optional if user is selected? (Please check with @iskhakov)

**Comment by iskhakov** [comment]
IMO if user is selected for direct paging, there is no need to select a team. Either general team, or default team for this user should be used.

**Comment by iskhakov** [comment]
I think if user notification policy is set to NULL, OnCall should use the organization's default policies set up by an admin. By default it should be configured as "Notify by email"

**Comment by raphael-batte** [comment]
Probably in makes sense to change default team objects visibility settings:
Team members and admins -> All users
![image](https://github.com/grafana/oncall/assets/102970268/38a1b05a-a827-405f-9dd0-7cfd1a668cbb)

**Comment by mackgorski** [comment]
IMO every user should have a default notification chain configured with ability to change it's settings. However it should not be possible to delete it and have no notification chain at all. User should be able to delete it only when there is another notification chain defined and upon deletion user should select a new `default` chain.

Same applies for the Teams and Direct Paging. There always should be one configured with `default` role that can be edited especially around escalation policies etc. But in case when user want to delete it it should be blocked unless there is another DP integration that can serve as a `default`.
