### ISSUE TITLE
Alert group text search doesn't work in v0.0.13

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#303]
We need to add the field with the alert content to make it searchable

https://github.com/grafana/oncall/blob/dev/engine/apps/api/views/alert_group.py#L190

**Comment by Ukochka** [comment]
@iskhakov could you check if this bug about filtering by name or filtering by the content? Should it be additional work from backend?

**Comment by Matvey-Kuk** [comment]
This was done on purpose in the backend as a part of optimisation.
