### ISSUE TITLE
Remove source from alert in telegram

### ISSUE THREAD

**Issue by allanian** [grafana/oncall#3046]
### What would you like to see!

Hello, how i can exclude "source" from telegram alert, didnt find it
example of head alert message
```
Source: alertmanager - Alertmanager
http://172.21.20.7:3000/a/grafana-oncall-app/alert-groups/IE8X8FHGSWMV3
```

### Product Area

Chatops

**Comment by iskhakov** [comment]
There is no plans for core team to work on this. Please reopen the issue and submit your PR

**Comment by AmirRezaSeraji** [comment]
Hi,I have this problem too and have been trying to solve it for about 6 months. I use Grafana a lot and it is one of the favorite tools of our team. Please solve this problem if possible.

@iskhakov 

![Image](https://github.com/user-attachments/assets/41a18f44-786b-4727-af3c-cd1872a2eb8d)

**Comment by AmirRezaSeraji** [comment]
I solved this problem:

I am using containers for Grafana OnCall,
go to inside grafana oncall container ( docker exec -it your oncall containerID  bash or sh)
edit this file : vi /etc/app/apps/alerts/incident_appearance/renderers/telegram_renderer.py
comment 2 lines below:
text += f"Source: {self.alert_group.channel.short_name}\n" >>>>> #text += f"Source: {self.alert_group.channel.short_name}\n"
text += f"{self.alert_group.web_link}"  >>>>>  #text += f"{self.alert_group.web_link}"

For the changes to be permanent Please mount grafana oncall volumes to your server.

services:
  engine:
    image: grafana/oncall
    restart: always
    ports:
      - "8080:8080"
    command: sh -c "uwsgi --ini uwsgi.ini"
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
      - ./custom_renderers:/etc/app/apps/alerts/incident_appearance/renderers
------------------------------------------------------

  celery:
    image: grafana/oncall
    restart: always
    command: sh -c "./celery_with_exporter.sh"
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
      - ./custom_renderers:/etc/app/apps/alerts/incident_appearance/renderers
-----------------------------------------------------

  oncall_db_migration:
    image: grafana/oncall
    command: python manage.py migrate --noinput
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
      - ./custom_renderers:/etc/app/apps/alerts/incident_appearance/renderers
