### ISSUE TITLE
API for Alert Group resolution

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#3051]
Historically we don't allow resolving Alert Groups via API (https://grafana.com/docs/oncall/latest/oncall-api-reference/alertgroups/) because we thought it will be more correct to resolve them sending "Resolve" signal to the endpoint and leveraging "resolve" Jinja template (https://grafana.com/docs/oncall/latest/jinja2-templating/).

Since we're moving to making OnCall more integratable with 3'rd parties we've discovered that it's much more handy for those 3'rd party systems to refer to Alert Groups by ID through the REST API.

I propose to extend our REST API and add Acknowledge & Resolve API actions. Those API actions "Acknowledged by API" (or by the user the API key issued for? not sure) should also be reflected properly in the Alert Group log and all AG representations: Web, Slack, MS Teams, Telegram, Mobile. 

Since this update will touch https://grafana.com/docs/oncall/latest/oncall-api-reference/alertgroups/, kindly asking to check if parameters for deletion are mentioned in the correct way because I heard a buzz in the community that some paramethers may be missing.

**Comment by vadimkerr** [comment]
Done in https://github.com/grafana/oncall/pull/3108: https://grafana.com/docs/oncall/latest/oncall-api-reference/alertgroups/#acknowledge-an-alert-group
