### ISSUE TITLE
Newly created non-admin users cannot access OnCall

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#3061]
### What went wrong?

**What happened**:
- A newly created user cannot access OnCall when they are not an admin, they instead get the error message:
`User is missing permission(s) plugins:write, org.users:read, teams:read, apikeys:create, apikeys:delete to setup OnCall before it can be used`

**What did you expect to happen**:
- When a new user is created as long as OnCall has been initialized once by an Admin newly created users should be able to access OnCall without needing an Admin to trigger user sync with the backend.

### How do we reproduce it?

1. Open Grafana OnCall with an Admin user, OnCall should load fine
2. In Grafana settings create a new user with Editor or Viewer role
3. Log out of the Admin account without visiting OnCall
4. Log in with the newly created user and navigate to OnCall
5. User will get the error message instead of OnCall loading

### Grafana OnCall Version

v1.3.38

### Product Area

Auth

### Grafana OnCall Platform?

None

### Anything else to add?

Until this is fixed a workaround is to visit OnCall with an Admin user after a new user has been created to ensure that user is sync'd with the backend before that user tries to use OnCall.

Also if 30 minutes elapse before between editor/viewer creation and the user login the backend will use a celery task to synchronize users which would achieve the same as the Admin navigating to OnCall.

**Comment by matiasb** [comment]
This should have been fixed by the initialization rework (newly created users can now login and they are synced on-the-fly during auth if needed).
