### ISSUE TITLE
Search an alert by Title

### ISSUE THREAD

**Issue by chalut01** [grafana/oncall#3071]
### What would you like to see!

Currently, we are using  Grafana Oncall in our Production environment. we got a lot of alerts every month. So, we want to look up these alerts by their names. Like, on August 2023, we want to know how many times the alert named "Example-Alert-Title" was triggered and we want to find out all the extra info about it.

### Product Area

Other

**Comment by iskhakov** [comment]
closing in favour of https://github.com/grafana/oncall/issues/2232
