### ISSUE TITLE
Escalation chain showing twice in list after adding a team

### ISSUE THREAD

**Issue by meanmina** [grafana/oncall#3083]
### What went wrong?

**What happened**:
- After editing an existing escalation chain to add a Team, the view refreshes, now displaying the edited chain twice in the list. Upon refreshing the page, the list goes back to normal and the edited escalation chain only displays once in the list.
<img width="422" alt="Screenshot 2023-09-28 at 10 27 32" src="https://github.com/grafana/oncall/assets/11211742/aad4d169-87b7-4484-9a7f-c6f6e9ece402">

**What did you expect to happen**:
- The edited escalation chain should only show once in the list

### How do we reproduce it?

1. Open Grafana OnCall and go to Escalation chains page
2. Now click on an Escalation chain and press the gear icon on the top right corner ("Edit")
3. Ensure your chain doesn't currently have a Team assigned
4. Add a new Team to your escalation chain and press "Update Escalation Chain" (FYI shouldn't "chain" not be capitalised to be in line with navigation?)
5. Observe the Escalation chains list on the left and the chain last edited now displays twice.

### Grafana OnCall Version

r235-v1.3.40

### Product Area

Other

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by mderynck** [comment]
Seems to be fixed now
