### ISSUE TITLE
Grafana oncall UI broken

### ISSUE THREAD

**Issue by sachinmane1983** [grafana/oncall#3084]
### What went wrong?

we have setup grafana in our GKE CLuster
from Grafana UI when we click on grafana oncall it throwing me below error
An unknown error occurred when trying to install the plugin. Verify OnCall API URL, http://grafana-oncall-engine.grafana.svc.cluster.local:8080, is correct? Refresh your page and try again, or try removing your plugin configuration and reconfiguring.

### How do we reproduce it?

Install On-Call plugin
Configure plugin to use http://localhost:8080/ or http://host/ ip:8080 as the OnCall Backend URL
Click connect and wait for error message to appear.

### Grafana OnCall Version

1.3.23

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Google Chrome

**Comment by iskhakov** [comment]
this error means that grafana is not able to connect to the backend by provided url. Check networking configuration
