### ISSUE TITLE
Slack shift change notifications don't consider shift swaps

### ISSUE THREAD

**Issue by charleskorn** [grafana/oncall#3096]
### What went wrong?

**What happened**:
My regular on-call shift time based on our rotations is 13:00 - 01:00.

I'd arranged a shift swap for the last few hours of this shift, from 21:00 - 01:00.

The shift change notification in our Slack channel reported my shift as running from 13:00 - 01:00 (ie. ignored the shift swap), and reported my colleague's shift as running from 21:00 - 01:00.

<img width="537" alt="Screenshot 2023-10-02 at 9 57 34 am" src="https://github.com/grafana/oncall/assets/4017646/637a012f-ef5f-43e1-889e-f50a7e312b2e">

**What did you expect to happen**:
My shift was reported as ending at 21:00, when the swap began.

### How do we reproduce it?

1. Create a schedule and rotation
2. Add yourself to the rotation
3. Arrange a shift swap for the last portion of your regularly scheduled shift
4. Wait for the shift change notification in Slack

### Grafana OnCall Version

r236-v1.3.40

### Product Area

Chatops

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by matiasb** [comment]
This should have now been fixed with the referenced PR.
