### ISSUE TITLE
Remove hiding stars on ENV page in blank rows

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#310]
There are hidden by default row states on ENV page, but blank rows also have stars on values columns:
![image](https://user-images.githubusercontent.com/102970268/181751977-37d39705-f755-4afe-b609-11a076e2a4ce.png)

Proposal: remove stars from blank fields to make list more readable:
![image](https://user-images.githubusercontent.com/102970268/181752432-91ecaca3-dfbd-42f5-883a-a967385ce226.png)

**Comment by Matvey-Kuk** [comment]
Blank value is also a value, it's a common security pattern to hide them.
