### ISSUE TITLE
Rename user notifications titles inside profile by using more correct wording

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#3104]
### What went wrong?

**What happened**:
At the moment we have Default and Important Notifications as titles inside web UI. Probably, it would be more correct to call these objects a set of personal rules. 
![image](https://github.com/grafana/oncall/assets/102970268/0825239f-25d8-4715-a4bd-9c0ff3082e82)

It 
**What did you expect to happen**:
Suggestions:
1. 
Default notification policy
Important notification policy

2. 
Default notification rules
Important notification rules

### How do we reproduce it?

1. Open Grafana OnCall and go to user profile section

### Grafana OnCall Version

r175-v1.3.1

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by mackgorski** [comment]
These ones will be consistent with what we have in our mobile apps. 

- Default notification policy
- Important notification policy

However in generar `Rules` word is more clear and sounds better, so we could change to this in both places.

**Comment by iskhakov** [comment]
How high is the priority for that? We will also need to change the documentation
