### ISSUE TITLE
Remove feature flag for OnCall's RBAC in Grafana and enable it by default

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#3105]
OnCall's RBAC is under the feature flag in Grafana which should be manually enabled. I propose to remove this feature flag and enable it by default so:

"Who has RBAC enabled in Grafana will have OnCall RBAC as well"

Internal discussion link: https://raintank-corp.slack.com/archives/C04JCU51NF8/p1696260954781569

**Comment by joeyorlando** [comment]
This has been completed
