### ISSUE TITLE
Add the ability to submit swap requests on behalf on another user

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/oncall#3106]
### What would you like to see!

Submit a swap request on behalf of another user. It would be ok if only a manager had permission to do this, but there are occasionally times when someone forgets they're on-call and is not around to submit their own swap request. This also occured when we changed our on-call rotations recently, and someone who was already on vacation ended up being on-call, and we had no way to submit swap requests on their behalf.

### Product Area

Schedules

**Comment by iskhakov** [comment]
Closing in favour of https://github.com/grafana/oncall/issues/3132
