### ISSUE TITLE
OnCall plugin configuration page and api-key issue

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#311]
When user configures the onCall plugin on the */plugins/grafana-oncall-app page, in case of a connection error (for example host was invalid), the api-key becomes outdated, but the user does not receive this information as error message.

Proposal:
- add to error message information about key and hint what user should generate new key
- add hint to documentation

**Comment by joeyorlando** [comment]
@raphael-batte lmk if this issue is safe to close based on the recently merged PR

**Comment by joeyorlando** [comment]
Closing as this was implemented in #563
