### ISSUE TITLE
Phone call error with "we are sorry, and application error has occurred"

### ISSUE THREAD

**Issue by mingbo-turing** [grafana/oncall#312]
Got error when test alert using phone call from self-host installation.  After successfully synced with Grafana cloud, I can send alert to phone numbers. The system called and read out message correctly, but when I press "1" to ack, it says "we are sorry, and application error has occurred" then hang up.

cc: @matiasb @Matvey-Kuk

**Comment by Matvey-Kuk** [comment]
@mingbo-turing thank you for the bug report! And thanks to @matiasb for fixing it :) 

The feature of closing/acking alert groups via phone is not available for OSS-cloud connector yet. Robot won't read this text.
