### ISSUE TITLE
Connecting slack account ends with blank 401 page

### ISSUE THREAD

**Issue by matiasb** [grafana/oncall#313]
When trying to connect a user to an slack account already connected to another user in the same organization, the web flow ends with a 401 blank page, with no information or details to the user.

```
[29/Jul/2022 17:15:35] "GET /api/internal/v1/complete/slack-login/?slack_login_token=*****&code=*****&state= HTTP/1.1" 401 0
```

**Comment by DavidSpek** [comment]
@matiasb I am also seeing this when I try and connect my slack account to my user after I was the one that setup the slack installation. Meaning that the admin can't actually connect their own slack account.

**Comment by DavidSpek** [comment]
@vadimkerr This issue is also still occurring.

**Comment by vadimkerr** [comment]
@DavidSpek The user installing the Slack integration should be connected automatically, do you mean that the issue occurs if the user installing the integration disconnects their account and then tries to connect it again?

**Comment by MarcoJ-CID** [comment]
We've got the same issue. All existing connections seems still working but we can't setup slack connections for new users anymore. We did recently a big jump from 1.0.22 to 1.1.23.

**Comment by MarcoJ-CID** [comment]
We solved the issue by ourself with recreating all the secrets and readd them to the oncall configuration

**Comment by matiasb** [comment]
Referenced fix was released.
