### ISSUE TITLE
No way to disable heartbeat

### ISSUE THREAD

**Issue by ethanmdavidson** [grafana/oncall#3137]
### What went wrong?

**What happened**:

I was playing around with the OnCall integrations API using curl. When listing integrations, I accidentally clicked one of the heartbeat links that showed up. The link loaded in the browser and I got the `":)"` response. The integration whose heartbeat I triggered doesn't actually have heartbeats, so 10 minutes later an alert went out saying that this integration has stopped receiving heartbeats! I went into the web UI to disable heartbeats, but I don't see any way to do so! 

Now this integration will forever have the "broken heart" icon (![Screenshot 2023-10-09 at 17 26 58](https://github.com/grafana/oncall/assets/1311998/3f5d1a52-accc-45bd-af94-b10b06e2df27)) in the integration list. 

**What did you expect to happen**:

I would expect there to be a setting to explicitly disable heartbeats for an integration, to say "this integration doesn't expect to ever receive heartbeats". If heartbeats are disabled, it should never fire an alert for missing heartbeats, and it shouldn't display the "broken heart" icon in the integration list.

### How do we reproduce it?

1. Create a new integration, e.g. Incoming Webhook
2. Do not set up any heartbeat process for it
3. Open the heartbeat url in your browser, or hit it with curl
4. wait 10 minutes (default heartbeat timeout) and your integration will be permanently heartbroken

### Grafana OnCall Version

r241-v1.3.43

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

Google Chrome Version 117.0.5938.149 (Official Build) (arm64)

### Anything else to add?

I think I could work around this by deleting and recreating the integration, but doing that is undesirable because it's more work, and because I'll lose the existing alert history.

**Comment by iskhakov** [comment]
closing as https://github.com/grafana/oncall/issues/3956 is fixed
