### ISSUE TITLE
FEATURE_TELEGRAM_INTEGRATION_ENABLED doesn't affect telegram UI

### ISSUE THREAD

**Issue by mothershipper** [grafana/oncall#319]
We've attempted to disable the telegram integration by setting this to `False` on both the engine and celery worker deployments.  But we're still seeing the telegram verification warning in the UI for our end-users:

<img width="226" alt="Screen Shot 2022-07-29 at 1 16 57 PM" src="https://user-images.githubusercontent.com/57678801/182221474-6bec3109-393f-4ea3-aee3-d4857e6c31d7.png">

Initial thought is that perhaps Telegram should be hidden entirely in the UI if the feature flag is disabled, but even if the feature is enabled, should the plugin show a warning to end users if the admins have not configured the telegram integration?

If I find some time this weekend, I can poke around at this and see what a fix might entail.  If someone else gets to it before me, it'd be greatly appreciated :)

**Comment by Matvey-Kuk** [comment]
@mothershipper thank you for the bug report! The issue should be easy to fix, but most of core team FEs are on PTO now so feel free to hack the solution :)
