### ISSUE TITLE
Integration pagination broken

### ISSUE THREAD

**Issue by PCbIX** [grafana/oncall#3191]
### What went wrong?

**What happened**:
- If we have more than 15 integrations, ui make second page, but listing at this pages broken. Next page showing items from previous page

**What did you expect to happen**:
- Normal pagination with locked item index

### How do we reproduce it?

1. Open Grafana OnCall and add 16 or more integrations
2. Try to open next page at integrations
3. You will see items from previous not next

### Grafana OnCall Version

1.3.45

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Vivaldi \ Brave \ Chrome

**Comment by joeyorlando** [comment]
@PCbIX I believe this must've been fixed somewhere along the way. Please try upgrading to the latest version 🙂  If you're still experiencing this issue, feel free to open a new one. Thank you!
