### ISSUE TITLE
Updating OnCall plugin to 1.3.46 changes the Title format set in template

### ISSUE THREAD

**Issue by FredSiteHost** [grafana/oncall#3200]
### What went wrong?

**What happened**:
- We performed a routine update of the Grafana OnCall plugin from v1.3.44 to v1.3.46. Following the update we noticed the alert group Titles were no longer respecting the template we had set up.

**What did you expect to happen**:
- Before the update, our Titles looked something like this:

(new line)
FQDN/Server name
(new line)
Alert name and its description
other relevant information
(new line)

![multipletitleblurred](https://github.com/grafana/oncall/assets/118311103/8ba76dd0-f15f-4be1-9246-dcd69cc0adfb)

- After the update, the information was all rendered on the same line.

FQDN/Server name Alert name and its description other relevant information

![alert](https://github.com/grafana/oncall/assets/118311103/049ff531-3250-4896-9bdc-f2d036c9780d)

### How do we reproduce it?

1. From Grafana OnCall 1.3.44, create a Grafana Integration with the following Title template format: 

(new line)
instance name
(new line)
Alert name and its description

2. The new lines on that version should be present. Then update OnCall and the plugin to 1.3.46 and the new lines will no longer be rendered. 

### Grafana OnCall Version

1.3.46

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Docker

### User's Browser?

Chrome/Firefox/Brave

### Anything else to add?

We noticed this only affected the Title in the alert group. The details section looked the same as normal.

**Comment by iskhakov** [comment]
sorry for the inconvenience, it might be related to the change introduced by https://github.com/grafana/oncall/pull/2643/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR13
