### ISSUE TITLE
[Feature request] Detect it when people are on PTO and scheduled on a rotation

### ISSUE THREAD

**Issue by replay** [grafana/oncall#322]
We have experienced multiple situations where a person was scheduled on a Grafana OnCall rotation at a time when they were on PTO.

We have a PTO calendar (generated by Bamboo), it would be great if we could provide Grafana OnCall with a PTO calendar link and then OnCall could detect it if somebody is scheduled on a rotation at a time when they are expected to be on PTO. This feature doesn't need to be specific to PTO, it could also just be like a generic "unavailability calendar".

I'm not sure who the best person would be to notify about such a conflict between the unavailability calendar and the on-call schedule, probably not the affected person because they might already be unavailable, maybe each rotation could have a "manager" property to notify about such a conflict or just a Slack channel to post a message into?

**Comment by joeyorlando** [comment]
Closing this as we are actually working on this feature now 🙂 (you can take a peek over at https://github.com/grafana/oncall-private/issues/2555)
