### ISSUE TITLE
On Call schedule and Escalation policy times have gone back an hour post Daylight savings time has ended

### ISSUE THREAD

**Issue by maller5214** [grafana/oncall#3261]
### What went wrong?

DST ended in the UK last weekend on the 30th of October and the On-call schedules and escalation policies set have all gone back an hour.

Say the schedule was set to start at 8.30 every day (The setup was done during DST) and the length of the shift was 9 hours the schedule was set to run between 08.30 to 17.30 but post DST the timings have been moved back by an hour and the schedules now reflect 07:30 to 16:30. These again change back to 08:30 to 17:30 from 1st April 2024.

In addition to the schedules, we also noticed that the escalation chain policy had moved back by an hour as well. This was initially set to 08:30 to 17:30 to match our schedule which now shows 07:30 to 16:30.

In order to fix this we had to manually recreate each of our schedules.

### How do we reproduce it?

1 - Setup a schedule in UTC for say between 08:00 to 17:00
2 - Set your local times to Europe/London
3 - Move forward in the schedule to Apr 2024. This will now show the times to be 09:00 to 18:00 (Schedule would have jumped forward by an hour)

This will work in reverse if the schedule is set up during DST and we move out of it.

### Grafana OnCall Version

1.3.19

### Product Area

Schedules

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
@brojd I see they're some PRs related to this that're closed (plus it's in the Done column in the project board), can this issue be closed?
