### ISSUE TITLE
Truncate basic data list (that we need to wait before plugin being rendered)

### ISSUE THREAD

**Issue by maskin25** [grafana/oncall#3300]
Oncall plugin UI waits for a [~12](https://github.com/grafana/oncall/blob/dev/grafana-plugin/src/state/rootBaseStore/index.ts#L111) backend responses before rendering anything, so we propose to truncate this list to speed up our plugin loading. Ideally shouldn't wait for anything, but with current architecture it causes errors, so so plan is: 

- [ ] - truncate list
- [ ] - totally get rid of this approach

**Comment by joeyorlando** [comment]
@brojd it seems like this PR was mentioned in #3450 (which is closed), is it safe to close this issue?
