### ISSUE TITLE
Enable Grafana On Call Exporter/Metrics

### ISSUE THREAD

**Issue by indrahostinger** [grafana/oncall#3316]
### **What happened**:
Actually this is not a bug, I just need some information about how enable grafana on call exporter properly.
I'm currently enabling the grafana on-call metrics like:

```
  oncall:
    exporter:
      enabled: true
```

but result is seems not enabled properly:
![image](https://github.com/grafana/oncall/assets/22586668/7c6e0c9d-9367-47b1-9e39-de0a17145916)

I see `authToken` variable in: 
https://github.com/grafana/oncall/blob/456829f7681dbe763789d72c47e1aeb845f82643/helm/oncall/values.yaml#L340C9-L340C9

But I don't know how I should fill authToken variable.
So, could you guide me to enable it properly?
Thanks in advance.

---

###  **What did you expect to happen**:
My expectation is metrics able to read properly.

### How do we reproduce it?

- access <domain>/metrics/ on my grafana on call.

### Grafana OnCall Version

v1.3.23

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

**Comment by matiasb** [comment]
Hi,

The `auth_token` value is used to setup auth for the exporter metrics endpoint; so, you can set any value there, or none, but you must be sure to use the right configuration when setting up your prometheus [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) (see `authorization`).

OTOH, if you were able to get the response from the metrics endpoint, the exporter should be working; maybe there was no data yet?

**Comment by indrahostinger** [comment]
Hello @matiasb ,

Thanks for your reply, and sorry I'm late response because I'm on vacation.
Some alerts are working, just not sure why it seems doesn't run well. I will read [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) first.

**Comment by indrahostinger** [comment]
Hello @matiasb ,
issue closed. issue was related with no data on the staging side.
thanks for your support.
