### ISSUE TITLE
1 engine = 1 frontend. Need clarification.

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#334]
For now 1 engine = 1 frontend is the only one well-tested OSS setup. We need to be more explicit about it.

Idea came from: https://github.com/grafana/oncall/issues/316

**Comment by alyssawada** [comment]
Hey @Matvey-Kuk - Just saw this issue, adding it to my list to get updated.

**Comment by Matvey-Kuk** [comment]
@alyssawada thank you!

**Comment by alyssawada** [comment]
Closing this issue - merged PR370 addressed this.
