### ISSUE TITLE
Verify on user profile layout is overflowing its container

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#3340]
### What went wrong?

Verify phone number action overflows its container

![image](https://github.com/grafana/oncall/assets/40542072/0e856622-ad52-4c03-ba69-4d921b4f5a03)

### How do we reproduce it?

1. Go to User Profile
2. Input phone number

### Grafana OnCall Version

latest

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Closing as done in #3443
