### ISSUE TITLE
Verify phone number should automatically fill in the number if you opened it from the user tab

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#3341]
### What went wrong?

Right now if you had ever sent a request to validate your phone number, but you didn't complete the whole process, your phone number will show up in the User Info next to a `Verify` button action, which on click takes you to the verification screen.

The issue is that the phone number is not filled in already on that screen and you need to type it again, and it should also trigger a network request as you already pressed Verify in the previous tab.

### How do we reproduce it?

1. Go to User Info
2. Click Verify

### Grafana OnCall Version

latest

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Closing as done in #3443
