### ISSUE TITLE
The 'next' button is not tappable during mobile app setup

### ISSUE THREAD

**Issue by devinrcheevers** [grafana/oncall#3361]
### What went wrong?

**What happened**:

* Setting up iOS app for existing IRM user profile
* As part of notification policy setup the 'next' button is not tappable, even when adjusting the settings

![IMG_0904](https://github.com/grafana/oncall/assets/85312870/0a4f26da-7717-4c93-8c82-5b56e79e8060)

**What did you expect to happen**:

* The next button to be tappable 

### How do we reproduce it?

* Setting up iOS app for existing IRM user profile
* As part of notification policy setup the 'next' button is not tappable, even when adjusting the settings

### Grafana OnCall Version

iOS v1.8.1 - Build 1306

### Product Area

Mobile App

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by imtoori** [comment]
I think this is expected
The info box explicitly says you have to use "Mobile push important" for important notifications and you are using "Mobile push"
I'm gonna close it for now, please reopen it if needed
