### ISSUE TITLE
SSLCertVerificationError when sending emails after 1.3.52 upgrade (from 1.3.45)

### ISSUE THREAD

**Issue by renrutmas** [grafana/oncall#3366]
### What went wrong?

**What happened**:
Cannot send emails after upgrade due to SSLCertVerificationError

**What did you expect to happen**:
Send email as in previous version

### How do we reproduce it?

1. Upgrade to 1.3.52 from 1.3.45
2. Try and send an email from an escalation chain

> 2023-11-14 13:59:58,790 source=engine:celery worker=ForkPoolWorker-3 task_id=f0b12540-fe54-45b0-b769-d3578678d035 task_name=apps.email.tasks.notify_user_async name=celery.app.trace level=INFO Task apps.email.tasks.notify_user_async[f0b12540-fe54-45b0-b769-d3578678d035] retry: Retry in 1s: **SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')**

Probably because of this - https://medium.com/@hhuysamen/sending-emails-using-django-4-2-3e5de1ff64dc

Seems Django was updated as of 1.3.48 - https://github.com/grafana/oncall/commit/c4fb620328c9dd83646d7509de74ed72d0733dca#diff-a702a33c7a611fc83dcc7c2838f2607f00db74d8567ef55bbca2b703a7544559

### Grafana OnCall Version

v1.3.52

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

**Comment by joeyorlando** [comment]
Hi there!

Please try setting the `EMAIL_USE_TLS` engine environment variable to `False` (as stated in the Medium article you linked).

I'll go ahead and close this. If that does not work, feel free to reopen!
