### ISSUE TITLE
Cannot specify resources for celery wait-for-db container

### ISSUE THREAD

**Issue by benclauss** [grafana/oncall#339]
> In Kubernetes, [Admission Controllers](https://kubernetes.io/docs/admin/admission-controllers/) enforce semantic validation of objects during create, update, and delete operations. With OPA you can enforce custom policies on Kubernetes objects without recompiling or reconfiguring the Kubernetes API server.

https://www.openpolicyagent.org/docs/v0.12.2/kubernetes-admission-control/

When trying to deploy OnCall with a validation requirement that all containers have CPU and memory requests and limits set, my deploy fails.

```
admission webhook "validation.gatekeeper.sh" denied the request: [validate-all-controller-containers-have-requests] Controller object (Deployment) "..." container "wait-for-db" has no resource requests
```

The `wait-for-db` container has no resource requests and these values are **not** configurable via `values.yaml`.

**Comment by Matvey-Kuk** [comment]
@benjaminclauss hello, could you please provide details of your environment and other logs? Based on one log line it's almost impossible to debug.

**Comment by benjaminclauss** [comment]
> @benjaminclauss hello, could you please provide details of your environment and other logs? Based on one log line it's almost impossible to debug.

I apologize for the delay. I updated the issue description. LMK if I can provide any more information.

**Comment by joeyorlando** [comment]
Closing as this should be possible [by configuring `Values.init.resources`](https://github.com/grafana/oncall/blob/dev/helm/oncall/templates/_helpers.tpl#L101)
