### ISSUE TITLE
Outgoing webhooks: add "Alert group updated" trigger type

### ISSUE THREAD

**Issue by pbannykh** [grafana/oncall#3395]
### What would you like to see!

This event should trigger when alerts in alert group are updated.

### Product Area

Alert Flow & Configuration

**Comment by matiasb** [comment]
Hi,

FYI, there is a trigger type for each of the possible updates for an alert group (ack, resolve, unack, unresolve, silence, unsilence). I agree it would be nice to have one event "grouping" all possible events, or alternatively, allow to select multiple trigger events for one webhook (to avoid duplicating the whole config for each different trigger).

Makes sense?

**Comment by pbannykh** [comment]
Sounds good, but won't solve my problem. There is no event that can be triggered when alerts in a group change.
I also noticed that notifications in group are not updated when sent via a webhook.
https://github.com/grafana/oncall/issues/2551

**Comment by iskhakov** [comment]
closed by #3920

**Comment by zorek187** [comment]
Hey @pbannykh, seems that your initial request still isn't covered.. Dii you find a workaround how to send webhooks if content of an alert group changes?
