### ISSUE TITLE
Support an alias to alert all on-call engineers

### ISSUE THREAD

**Issue by dannykopping** [grafana/oncall#341]
At Grafana Labs, we have several teams with on-call schedules.

Occasionally, we need to make an announcement (about an incident, an impending change, etc) and alerting `@here` or `@channel` in our shared engineering channels is too noisy; we just need to alert the on-call engineers since they will likely be the first responders should anything go wrong.

We are already using (and loving) the automatic Slack alias feature; can we provide another alias which includes all engineers currently on call?

**Comment by iskhakov** [comment]
Thank you for the request
Right now we allow adding a slack group with all oncall engineers per one oncall schedule.
We'll consider adding a new slack group (e.g. @grafana-oncall-all) for all oncall engineers from every oncall schedule

**Comment by acr-varonis** [comment]
this will also be useful for issue https://github.com/grafana/oncall/issues/347 since in some cases you want to Email a whole team and not just an indevidual

**Comment by iskhakov** [comment]
the recommended way of pinging oncall engineers for a certain schedule is a slack group. Triggering notifications for every oncall engineer is not currently a priority for the team
