### ISSUE TITLE
Allow user to unlink slack account

### ISSUE THREAD

**Issue by matiasb** [grafana/oncall#342]
There is no way to change or unlink a slack account in the user's profile.

**Comment by Matvey-Kuk** [comment]
Oh wow, that's a cool catch.

**Comment by melikesozeri** [comment]
Oh really need this.

**Comment by ksa-real** [comment]
Is there an easy way to manually unlink, e.g. by manipulating the DB? I accidentally linked my Slack account to admin user instead of OAuth one.
