### ISSUE TITLE
Bump MobX version to 6.12 and simplify stores

### ISSUE THREAD

**Issue by brojd** [grafana/oncall#3453]
Currently we're using MobX v5.13.0. We should bump the version to latest stable which is 6.12.0. Thanks to it we will be able to use [makeAutoObservable](https://mobx.js.org/observable-state.html#makeautoobservable) and as a result:
1) remove a lot of decorators from the code (with `makeAutoObservable` every class method is an action by default, every setter is a computed, every other property is an observable
2) remove a lot of `this` bindings because `this` will be automatically bound to the store class
3) identify and get rid of updating `observable` without an `action`. In new version every case like that will be logged in the console so we need to fix all such places. Using actions has [benefits](https://mobx.js.org/observable-state.html#makeautoobservable) including performance so it will have a positive impact on the app itself

**Comment by joeyorlando** [comment]
closing as completed in #3561
