### ISSUE TITLE
Make integration and notifications via Email/SMTP

### ISSUE THREAD

**Issue by acr-varonis** [grafana/oncall#347]
Pretty self-explanatory.
I want the ability to configure an SMTP and notify users via Email.

Thanks.

**Comment by Matvey-Kuk** [comment]
@acr-varonis thank you for the feature request! Btw @matiasb already started working on it, feel free to try and contribute: https://github.com/grafana/oncall/pull/50

**Comment by acr-varonis** [comment]
@Matvey-Kuk Thank you for letting me know!
is the progress tracked somewhere or are you going to keep this issue for tracking?

**Comment by Matvey-Kuk** [comment]
@acr-varonis we'll keep this issue for tracking

**Comment by Matvey-Kuk** [comment]
Moved to core team's backlog.

**Comment by DavidSpek** [comment]
https://github.com/grafana/oncall/pull/670 is related. I've tested it with the changes from https://github.com/grafana/oncall/pull/621 and it works as expected.

**Comment by acr-varonis** [comment]
Looking forward to trying this in an upcoming release !

**Comment by vadimkerr** [comment]
The SMTP email backend is enabled by default and is available for use as of [v1.0.49](https://github.com/grafana/oncall/releases/tag/v1.0.49). 
Please see the docs here: https://grafana.com/docs/oncall/latest/open-source/#email-setup

**Comment by acr-varonis** [comment]
@vadimkerr  I just tried configuring SMTP in our test environment.
Our test email server is configured to allow relaying (no authentication with a username and password) from the oncall machine.

but it seems the current configuration doesnt support this kind of configuration.
We want to use the EMAIL_HOST_USER as the FROM to the email and leave the password empty.

any ideas ?

**Comment by vadimkerr** [comment]
@acr-varonis there is a similar issue on GH: https://github.com/grafana/oncall/issues/715
