### ISSUE TITLE
Teams dropdown has no options unless integration settings are visited

### ISSUE THREAD

**Issue by brojd** [grafana/oncall#3479]
### What went wrong?

**What happened**:
- Teams dropdown on Integrations page has no options after page reload

**What did you expect to happen**:
- Teams dropdown has options

### How do we reproduce it?

1. Open Grafana OnCall 
2. Go to Integrations page
3. Open Teams dropdown and notice there are no options
4. Then open any single integration settings and go back
5. Notice that there are teams present now

### Grafana OnCall Version

1.3.67

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Closing as completed in #3480
