### ISSUE TITLE
Links in OnCall plugin navigate current tab instead of opening a new one

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#351]
In the OnCall plugin throughout the interface (+configuration page) when you click on an external link it navigates to the link in the current tab instead of opening a new tab, there is no warning to the user they are about to leave Grafana.  This is annoying as usually the link is some reference material (docs) and you want it alongside the current content you are viewing.  In other plugins and Grafana itself these links open in a new tab by default.  OnCall plugin should follow this same convention.

**Comment by teodosii** [comment]
@mderynck This was merged. Can you please double check to see if there's any link left that doesn't open in a new window?
