### ISSUE TITLE
Add ability to create outgoing webhook w/ PATCH HTTP Method via the UI

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/oncall#3564]
### What would you like to see!

add the PATCH option to the list op http methods
["GET", "POST", "PUT", "DELETE", "OPTIONS"]

### Product Area

Other

**Comment by ToonTijtgat2** [comment]
Dear

Thanks for adding this feature in the code of oncall.
However after updating oncall to version 1.3.81 I tried to use the patch method.
I noticed that the code of oncall is addapted, but not the oncall grafana plugin.
Can the PATCH action please be added to the plugin?

https://github.com/grafana/oncall/blob/6c7bc4d20c8b7ecfe36e59ec7e8d1767b4575850/grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx#L108

Thanks in advance.

**Comment by ToonTijtgat2** [comment]
@joeyorlando , @ravishankar15 I'm not sure if it's possible to reopen this issue, or do I have to create a new issue? 
Thanks for checking.

**Comment by ToonTijtgat2** [comment]
FYI, if I create a new webhook with the api instead of via the grafana plugin, it already works. :) but if you check it in the plugin on grafana the value of http method is still empty.

have a good 2024

**Comment by joeyorlando** [comment]
Ahh thanks for pointing this out. I'll reopen this an add this soon 👍
