### ISSUE TITLE
service account token deleted, Plugin settings updated on every refresh

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/oncall#3566]
### What went wrong?

**What happened**:
- Every time I try to refresh the alert-groups page I receive a popup stating service account token deleted, Plugin settings updated
![Capture](https://github.com/grafana/oncall/assets/109516706/9bb06887-9832-4ff3-83ac-8563ce5b8b33)

This also happens when I sent the alert group url to someone: for example https://url/a/grafana-oncall-app/alert-groups/I1AWEDEVZHU44?perpage=25&start=1

When opening the url in the browser, you shorly see the alertgroup and then the popup appears and you are rerouted to the alert-groups page.

**What did you expect to happen**:
- I would be nice to be able to sent links from alert-groups to college's.

### How do we reproduce it?

1. Open Grafana OnCall and refresh your page.
2. copy the url of an alertgroup and open it again in a new window.

### Grafana OnCall Version

1.3.78

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

**Comment by via-justa** [comment]
I'm seeing the same thing on grafana 10.2.2 and oncall 1.3.77 (both deployment and plugin)
We also have an issue where non-admin users cannot use oncall (see screenshot) that I suspect relates to that.
@ToonTijtgat2 are you seeing the same issue with non-admin users?
![image](https://github.com/grafana/oncall/assets/25720282/99d3fd25-bfa3-4e78-a35b-2b31cb86cdc5)

**Comment by clementduveau** [comment]
Those 2 issues (#3607 and #3566) are related. Service accounts from admin users will succeed, and therefore admins are not affected by the bug.

**Comment by mderynck** [comment]
This was resolved by keeping `mirageSecretKey` constant through an external secret.
