### ISSUE TITLE
Inconsistent loading layout

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#357]
When you first open OnCall the loading screen looks different from if you access it and then navigate between other apps.
First Time Loading:
![Screenshot from 2022-08-11 13-03-59](https://user-images.githubusercontent.com/28077050/184219735-e87c7154-0684-46c2-8912-ae6575c8abe5.png)
Subsequent Loading (Tabs already present and the layout for the tabs is messy):
![Screenshot from 2022-08-11 13-05-00](https://user-images.githubusercontent.com/28077050/184219797-9f6ef750-8103-43ef-806a-648251db2081.png)

**Comment by maskin25** [comment]
I've checked, now it always look like on the first screen, @mderynck can you confirm this please?

**Comment by mderynck** [comment]
Looks good now
