### ISSUE TITLE
User Timezone Support for a Single Rotation

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#3589]
### What would you like to see!

I've been discussing with Rachel Zalkind about the possibility of having a rotation that allows people from various timezones to work only in their own timezone business hours, while still honoring the rotation.
So for example, if we only had 3 employees we wanted to include on the rotation.

## Example
User 1: Bob from California
User 2: James from the UK
User 3: Sarah from Australia

- The first week would have Bob be oncall during california business hours. (Nobody would be oncall that week except Bob during the US west coast business hours.)
- Then James would be oncall for the second week for just the US business hours. (Again, nobody else would be oncall that week except James during the UK business hours)
- The third week would have Sarah be oncall for just the Australia business hours. (Nobody else would be oncall outside of Sarah working the AUS business hours)
- Then it would repeat.

---

If this is possible or not, please let me know, I still don't think it is but could be missing something.
It seems like most cases would try to maximize coverage utilizing timezone support, however I'm trying to minimize coverage to only business hours, and only have one person oncall each week (even if it leaves really big gaps in the schedule) with the goal of the person who is oncall, covering all the alarms that have accumulated through the off hours, once their shift is started (which 
 depends on the timezone they are in.)

Thanks!
-Seth

### Product Area

Schedules

**Comment by razalkind** [comment]
#117359 internal (Grafana.com) ticket as well.

**Comment by Matvey-Kuk** [comment]
Hi! This is possible but in a bit of a hacky way. You need a dummy account (admin account in my example) and 3 rotations, one for each user:

<img width="1154" alt="Screenshot 2024-01-12 at 13 54 27" src="https://github.com/grafana/oncall/assets/3284841/26d62996-90ff-48f7-8127-4c69579ba82d">

It will put me (Matvey) on-call every 3'rd week on my working hours.

**Comment by qubitspace** [comment]
I appreciate the response.
Do I have the ability to create invisible admin accounts like that? I don't know how to do it.
I'm not sure this workaround is going to be enough for us, since it would require a seperate layer for each timezone, and we would have to sync them up anytime the rotation changed. If we can make the admin account to use, I could test it out and see how manageable it is for multiple different timezones.

**Comment by qubitspace** [comment]
@Matvey-Kuk (or whomever can help) Hello, sorry to resurrect this old ticket, I'm happy to create a new ticket or post this question somewhere else, but I would like to follow up on this workaround. I have another case where someone really wants to add these "dummy" users to pad out the schedule for some more complicated setups across different time zones.

So my question is, how can I get a dummy account to use for padding a schedule to apply this workaround?
Additionally, have there been any changes around this that would change the answer from a few moths ago?
