### ISSUE TITLE
Problem in pyroscope

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#3608]
### What went wrong?

Hi when i un-comment pyroscope-io in requirements file to install and use my build failed with this error:
ERROR: Could not build wheels for pyroscope-io, which is required to install pyproject.toml-based projects

### How do we reproduce it?

un-comment pyroscope-io

### Grafana OnCall Version

v1.3.80

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

**Comment by paneda1998** [comment]
any update?!

**Comment by pa-nguyen** [comment]
I have the same issue. 
I have Mac M2, Python 3.9. 
I have cargo installed in my venv as well.

**Comment by iskhakov** [comment]
pyroscope is not supported. This might be the good first issue to solve for the community. Please reopen this issue is you're interested
