### ISSUE TITLE
Add ability to filter mobile app "schedule" view to "just my shifts"

### ISSUE THREAD

**Issue by pr00se** [grafana/oncall#3631]
### What would you like to see!

I haven't been able to find a view within the mobile app that can quickly show me all of my upcoming shifts for a particular schedule (the "next on-call shifts" that appear when clicking my profile picture only show the next shift). 

It would be nice to be able to filter the single schedule view to only show my shifts, which would then let me scroll through the calendar and see when I'm on call in the future.

### Product Area

Mobile App

**Comment by raphael-batte** [comment]
Possible direction for schedule page in app

![Image](https://github.com/grafana/oncall/assets/102970268/8d36b7a9-efb6-4158-98bf-93048c3ef667)

**Comment by joeyorlando** [comment]
@imtoori if you need backend support here, feel free to ping me

**Comment by imtoori** [comment]
@joeyorlando I think for this we don't really need backend support, I think it should be enough to just process data on mobile, thanks though

**Comment by imtoori** [comment]
this has been implemented, you'll find it in the new release
