### ISSUE TITLE
New Grafana Users / Changes to Existing Grafana Users Not Picked Up By On Call

### ISSUE THREAD

**Issue by CloudTheWolf** [grafana/oncall#3657]
### What went wrong?

**What happened**:

When a new Grafana user is added, they do not appear in Grafana On Call until a brand new admin (Must be Grafana Admin and Org Admin) user logs in and views the On Call Users List.

Additionally, changes to a user (Eg changing a users Org Perms from Viewer to Editor) are not picked up unless the same steps are taken.

**What did you expect to happen**:
After a user is Added / Edited the changes are picked up when the user is saved.

### How do we reproduce it?

1. Open Grafana Admin and Create a new user, Make them a Grafana Admin and an Org Admin for Main Org.
2. Create a Second Grafana User with no Grafana Admin Perms 
3. On Grafana On Call go to Users
4. The new user created in Grafana will not be in the user list.
5. In a new browser Session, Login to Grafana with the Admin User from Step 1.
6. Navigate to Alerts & IRM -> OnCall -> Users
7. Both Users should now be in the list.

### Grafana OnCall Version

Grafana v10.2.3 (1e84fede54) + Grafana OnCall 1.3.83

### Product Area

Auth, Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Google Chrome 20.0.6099.200 (Official Build) (64-bit) (cohort: Stable)

**Comment by iskhakov** [comment]
do you use grafana cloud or on-prem? If on-prem, then you need to check the `grafana` celery queue
