### ISSUE TITLE
Integrate Twilio without Grafana cloud connection

### ISSUE THREAD

**Issue by donghoon-lee-mrt** [grafana/oncall#3660]
### What would you like to see!

We're using Grafana Oncall OSS, we'd like to send phone call or SMS with Twilio without Grafana cloud integration.
Also I'm wondering the reason why grafana OSS needs Grafana cloud integration for twilio setup. I think Grafana OSS could call Twilio directly with SID and Auth Token setup in Grafana OSS itself.

### Product Area

Other

### Anything else to add?

AFAIK, I understand we still need to relay phone call or SMS traffic to grafana cloud to send API call to Twilio. Below is the article I referred to.
https://grafana.com/docs/grafana-cloud/alerting-and-irm/oncall/notify/phone-calls-sms/

**Comment by donghoon-lee-mrt** [comment]
It has been resolved because I little bit misunderstood that feature, finally I can setup twilio setup without grafana cloud connection.

**Comment by douglasg14b** [comment]
@donghoon-lee-mrt How?
