### ISSUE TITLE
Docs: Refactor OnCall documentation 

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#3700]
Restructure the OnCall documentation set to align with the [Grafana documentation framework](https://grafana.com/docs/writers-toolkit/structure/). 

This issue scopes iteration 1 of 2.

### Iteration 1: Restructure existing content
 - Map existing topics to corresponding top-level TOC sections
- Update all frontmatter to reflect new alias, title, weight, etc.
- Add necessary top-level landing pages: Introduction, Set up, Configure, Manage
- Write MVP content to introduce each new section
- Update and refresh the OnCall product landing page

**Comment by alyssawada** [comment]
Additional details and context:

[Phase 1 OnCall doc structure update (Spreadsheet)](https://docs.google.com/spreadsheets/u/0/d/1zN_LRmSntAcG5Z0NwANC2aJhBgH7a48MG6kkQQnaUw4/edit)
[OnCall TOC mindmap (Miro board)](https://miro.com/app/board/uXjVN9Wzg4U=/?share_link_id=572122651801)
[Mindomo OnCall docs mindmap](https://www.mindomo.com/mindmap/oncall-toc-a83f18f69a0681449895f04c569061d2)

**Comment by alyssawada** [comment]
> The merged PR created a broken link on this page: https://grafana.com/docs/oncall/latest/integrations/inbound-email/

Hey @MoBattah! Thanks for letting us know. Unfortunately, I wasn't able to reproduce this. Do you happen to remember which doc it was linking out to?

**Comment by joeyorlando** [comment]
Closing as completed as this has been moved from "In Progress" to "Done" on the Grafana OnCall GitHub project board

**Comment by MoBattah** [comment]
@alyssawada @joeyorlando You can see the issue at https://grafana.com/docs/oncall/latest/integrations/inbound-email/  with this text "Refer to [Inbound Email Setup][] for details."

**Comment by joeyorlando** [comment]
@MoBattah thanks for the bug report! I've opened #4025 to fix this
