### ISSUE TITLE
Users with role Editor are not able to use the grafana oncall plugin

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/oncall#3719]
### What went wrong?

**What happened**:
- Users in grafana with role editor receive the following message when trying to view the alertgroups. (or anything in the oncall plugin) 
![image](https://github.com/grafana/oncall/assets/109516706/9d77ae95-8c9a-41b3-99e0-9893dcfd7e61)

Users with the admin role have no issue using the oncall plugin.

**What did you expect to happen**:
- I expect that users with role editor are able to use the oncall plugin and vieuw there alerts.

### How do we reproduce it?

1. Create or use a user in grafana with editor role permissions synced from azure ad.
2. Log on to the grafana instance with this user account and try to view alertgroups in oncall plugin.

### Grafana OnCall Version

oncall version: 1.3.89 plugin version: 1.3.89 grafana version: 10.2.3

### Product Area

Auth

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Firefow/google chrome / edge...

### Anything else to add?

I tried again with older versions of oncall plugin 1.3.87/86 but it has the same behaviour. also with grafana version 10.2.2 is the same.
Only downgrading oncall itself has not been tried out of fear that doing this would brake the setup.

**Comment by ToonTijtgat2** [comment]
strange thing is at the moment the request happens I see that the logs state the it could not find the user. but still give back the correct groups and userid and everything. but why does it get the 403 then?
![image](https://github.com/grafana/oncall/assets/109516706/7c21e38b-9b79-4238-9d17-c96fae723e76)

**Comment by ToonTijtgat2** [comment]
These lines do not happen for admin users

**Comment by ToonTijtgat2** [comment]
My new test user does not appear under the users in the oncall plugin.

**Comment by ToonTijtgat2** [comment]
Maybe the 503 status is causing problems here?
it states also that there would be an issue on certificates, but when I do a curl on the oncall pod to the same url, there is no issue.
![image](https://github.com/grafana/oncall/assets/109516706/50b615aa-f9b9-4116-b9d1-26f88d14ae70)

**Comment by Matvey-Kuk** [comment]
@ToonTijtgat2 just to verify, does the problem persist if you logout as Editor, log in as Admin, logout and log in as Editor again?

**Comment by ToonTijtgat2** [comment]
@Matvey-Kuk I just tried, and indeed the issue persist.

**Comment by ToonTijtgat2** [comment]
![image](https://github.com/grafana/oncall/assets/109516706/7abbc3ac-4d19-43d1-a924-9fa5b925d41c)
it is probably related to the token.

**Comment by ToonTijtgat2** [comment]
https://github.com/grafana/oncall/issues/3566

**Comment by mderynck** [comment]
This we resolved by keeping `mirageSecretKey` constant through an external secret.
