### ISSUE TITLE
 root-oncall_db_migration-1    install  failure

### ISSUE THREAD

**Issue by kingbug-nightraid** [grafana/oncall#3725]
### What went wrong?

grafana oncall install failure using docker-compose
no logs in  root-oncall_db_migration-1 container，Hope to find the answer here, thank you very much

### How do we reproduce it?

[root@ip-10-103-1-150 ~]# docker ps -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                     PORTS                                       NAMES
add52ff5f553   grafana/oncall           "sh -c ./celery_with…"   7 minutes ago   Up 6 minutes                                                           root-celery-1
5dac75abc654   grafana/oncall           "sh -c 'uwsgi --ini …"   7 minutes ago   Up 6 minutes               0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   root-engine-1
8110ded47caa   grafana/oncall           "python manage.py mi…"   7 minutes ago   Exited (0) 6 minutes ago                                               root-oncall_db_migration-1
2166529b353b   redis:7.0.5              "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes (healthy)     6379/tcp                                    root-redis-1
717728d7c224   grafana/grafana:latest   "/run.sh"                7 minutes ago   Up 7 minutes               0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   root-grafana-1
[root@ip-10-103-1-150 ~]# 

[root@ip-10-103-1-150 ~]# docker logs -f 8110ded47caa
Operations to perform:
  Apply all migrations: admin, alerts, auth, auth_token, base, contenttypes, email, fcm_django, heartbeat, labels, mobile_app, oss_installation, phone_notifications, schedules, sessions, slack, social_django, telegram, twilioapp, user_management, webhooks, zvonok
Running migrations:
  No migrations to apply.

### Grafana OnCall Version

latest in

### Product Area

Other

### Grafana OnCall Platform?

Docker

**Comment by kingbug-nightraid** [comment]
![Uploading 23191705979471_.pic.jpg…]()

**Comment by kingbug-nightraid** [comment]
![23191705979471_ pic](https://github.com/grafana/oncall/assets/73016667/b7a75968-e07a-43a6-8fdb-cbed754c4e03)

**Comment by matiasb** [comment]
FYI, that `root-oncall_db_migration-1` container just runs the DB migration command and exits, so it is ok that it is finished. And as you can see in the logs, there is nothing to migrate and the command ran without issues. If all the other containers are running you should be able to load grafana and use the OnCall from there.

**Comment by kingbug-nightraid** [comment]
Thank you for your reply, but when I configure the address on Grafana, the client container will report an error, and I don't 
![23271706236216_ pic](https://github.com/grafana/oncall/assets/73016667/db15c306-b101-4b17-bc0d-9143a7cd375d)
 understand why

**Comment by kingbug-nightraid** [comment]
Sorry, I made a mistake. It's ready now. Thank you
