### ISSUE TITLE
Problem with Grafana interaction when using self-signed certificates

### ISSUE THREAD

**Issue by pawellrus** [grafana/oncall#3737]
### What went wrong?

**What happened**:
I have self-signed certificates on both http endpoints: grafana and oncall
I am trying to integrate them but got SSL errors in engine and celery containers.
I tried to mount root certificates into /etc/ssl/certs folder but it didn't help
It's possible that running "update-ca-certificates" could help, but helm chart does not have options to define startup command either initContaner.

Is there any another options to make setup with self-signed certs working?

### How do we reproduce it?

Self signed certificates on grafana side and oncall side.

### Grafana OnCall Version

v1.3.90

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

**Comment by rookie-man-fack** [comment]
If you use docker-compose, delete the persistent data first, docker volume rm oncall_redis_data
docker volume rm oncall_oncall_data

Then add REQUESTS_CA_BUNDLE: "/path/xxx.crt" environment variable to docker-compose.yml x-environment 

Mount the certificate volumes path to the container
