### ISSUE TITLE
OnCall was not able to load the user

### ISSUE THREAD

**Issue by ashwaq06** [grafana/oncall#3745]
### What went wrong?

**What happened**:
- When trying to setup OnCall, It displays an error message **"OnCall was not able to load the user"**
![image](https://github.com/grafana/oncall/assets/80192952/59cac918-5d22-4fe8-b165-25688d2b7be4)
- Also We tried to insert the values of the user in the `oncall.db` in  `user_management_user` table . So that it can integrate with the user access
- It started to display a Loading screen like below and we tried if there is any restrictions of  `hidden_user` in `grafana.ini` but there aren't any restrictions

<img width="1512" alt="Screenshot 2024-01-24 at 3 53 38 PM" src="https://github.com/grafana/oncall/assets/80192952/7b698d85-7821-4079-8975-852c46696d46">
- It is working fine through the local but We have been using the grafana by hosting it on a ec2 instance and we wanted to integrate grafana-oncall to our grafana and we have followed the docker-compose setup with [Developmet](https://github.com/grafana/oncall/blob/dev/dev/README.md#running-the-project-with-docker-compose)

**What did you expect to happen**:
- I wanted to get the integration between the users of `Grafana` to `Grafana-OnCall` and work properly

### How do we reproduce it?

Follow this [[Documentation]](https://github.com/grafana/oncall/blob/dev/dev/README.md#running-the-project-with-docker-compose) 

### Grafana OnCall Version

1.3.82

### Product Area

Alert Flow & Configuration, Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Google Chrome

**Comment by iskhakov** [comment]
closing in favour of https://github.com/grafana/oncall/issues/3772
