### ISSUE TITLE
Error importing integrations using pagerduty-migrator

### ISSUE THREAD

**Issue by gilbertobr** [grafana/oncall#377]
I identified that when using pagerduty-migrator I get the following error:
TypeError: 'NoneType' object is not subscriptable

![image](https://user-images.githubusercontent.com/20375245/184963794-1a227f19-f70a-42cb-be39-f855df6a550f.png)

File:
https://github.com/grafana/oncall/blob/dev/tools/pagerduty-migrator/migrator/resources/integrations.py
Line: 17
Solution:
```
def match_integration_type(integration: dict, vendors: list[dict]) -> None:
    vendors_map = {vendor["id"]: vendor for vendor in vendors}

    if integration["type"] not in [
        "generic_events_api_inbound_integration",
        "events_api_v2_inbound_integration",
    ]:
        integration["oncall_type"] = None
        return

    if integration["vendor"] == None:
        print("WARNING:")
        print("Integration name:",integration["name"])
        print("Integration Link: ",integration["html_url"])
    else:
        vendor_id = integration["vendor"]["id"]
        vendor_name = vendors_map[vendor_id]["name"]

        integration["oncall_type"] = PAGERDUTY_TO_ONCALL_VENDOR_MAP.get(vendor_name)
```

**Comment by Matvey-Kuk** [comment]
Hi @gilbertobr thank you for the issue! @vadimkerr could you please check? Also @gilbertobr feel free to propose a PR

**Comment by Matvey-Kuk** [comment]
I found the PR, nevermind: https://github.com/grafana/oncall/pull/379

**Comment by vadimkerr** [comment]
The issue is that in some cases Pagerduty return an empty vendor for an integration - in this case we can't really do anything other than signaling that the integration cannot be created.
