### ISSUE TITLE
Chatops: Slack callback buttons in preview of alert response with 403 error.

### ISSUE THREAD

**Issue by omalko394** [grafana/oncall#3771]
### What went wrong?

**What happened**:
- Setup Slack integration according to documentation. Receiving alerts in channel but couldn't manipulate with alert via callback buttons (Acknowledge, Resolve, Silence except Unresolve). Receiving error: This app responded with status code 403.

**What did you expect to happen**:
- After pressing of callback buttons they will change the state of alert in Grafana OnCall.

### How do we reproduce it?

1. Setup ChatOps Slack integration. Send some alert that will appear in Slack.
2. Now click Acknowledge, Resolve, Silence buttons.
3. Slack will response with error: This app responded with status code 403.

### Grafana OnCall Version

Grafana OnCall: 1.3.81

### Product Area

Chatops

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

![Screenshot 2024-01-29 at 10 43 10](https://github.com/grafana/oncall/assets/95994074/0dc3ca44-43c7-43fa-89c9-2d2817be77cc)

**Comment by mderynck** [comment]
Can you include the log from your oncall engine for what you see when you press one of the buttons?  If the result is not reaching your oncall backend you'll need to double check your [slack app setup](https://grafana.com/docs/oncall/latest/set-up/open-source/#slack-setup).

**Comment by omalko394** [comment]
The problem was in WAF rules on alb, it blocked request from Slack because it's size exceed 8192 bytes.
