### ISSUE TITLE
403 Forbidden  + Slack application not connected to workspace internal Server error 500

### ISSUE THREAD

**Issue by dark-brains** [grafana/oncall#3825]
### What went wrong?

**What happened**:
- I can't use application . I tried to install latest helm chart version but using external Grafana and external MySQL. Grafana oncall app can't connect to grafana . 403 Forbiden. 

- I used elder version of each app , I don't know how but one time I can connect to oncall app. Next I tryed to connect to slack ChatOps. But Application retruned 500 Internal server error and integration don't work.
- I tried to connect my mobile application using QR code and also get error but emty. 
![Screenshot from 2024-02-02 02-45-59](https://github.com/grafana/oncall/assets/114874694/264be9c0-fc2f-48ec-8612-52727bc6d554)

![Screenshot from 2024-02-02 02-45-08](https://github.com/grafana/oncall/assets/114874694/67759974-bf23-462e-8232-04a0e5d87a7c)

Other screenshots I forgot to take.

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

helm 1.3.99

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

**Comment by dark-brains** [comment]
Please review this Issue as soon as possible .

**Comment by mderynck** [comment]
What's the URL for your Grafana instance? I see `https://grafana.darkbrains.dev` given as the OnCall backend URL on the plugin page but in the logs I see that same URL as outbound from OnCall trying to talk to Grafana API.

**Comment by dark-brains** [comment]
Yes Grafana URL is https://grafana.darkbrains.dev/grafana and OnCall URL is https://grafana.darkbrains.dev.

Some configuration perfectly working for helm version 1.3.8.

**Comment by dark-brains** [comment]
Also when using k8s internal endpoint for service engine, I'm getting other error `unable to connect to oncall engine`.

**Comment by mderynck** [comment]
What is your setting externalGrafana url? From the logs it looks like it is missing the /grafana part or the URL.
```
externalGrafana:
  # Example: https://grafana.mydomain.com
  url:
```

**Comment by dark-brains** [comment]
Sure, the external Grafana url is https://grafana.darkbrains.dev/grafana

There are no issues with version 1.3.8. Why?

**Comment by dark-brains** [comment]
Also Slack ChatOps integration is not working for  versions, latest, 1.3.100, 1.3.10, 1.3.99 etc..

https://github.com/grafana/oncall/issues/3834

It is only working normaly for version 1.3.8.

**Comment by mderynck** [comment]
In the log a request is being made to `https://grafana.darkbrains.dev/api/org` which is resulting in a 404, based on your configuration it should be making the request to `https://grafana.darkbrains.dev/grafana/api/org`

**Comment by dark-brains** [comment]
Working as expected  on the newer version.
