### ISSUE TITLE
Ability to disable "Alert Group log" on the Slack integration

### ISSUE THREAD

**Issue by RoopeHakulinen** [grafana/oncall#3849]
### What would you like to see!

I have not been able to find an option to disable the "Alert group log" on the Slack messages generated. It makes the Slack threads functionality pretty much useless by creating and updating a thread with your mention on it that also generates an undesired notification. Would it be possible to add a toggle for the Slack integration to disable the addition of the threaded message? 

Here's how 99% of my threads window looks like in Slack as is:
![image](https://github.com/grafana/oncall/assets/2197974/ff49cbf2-3114-4abd-bb4b-d6b2b529c864)

### Product Area

Alert Flow & Configuration

**Comment by ravishankar15** [comment]
@RoopeHakulinen As of now the thread message is updated which does not trigger any notification. Are you referring to having a separate message on the thread for each log ?

**Comment by salarali** [comment]
I have a similar ask. I would like to not have the Alert Group Log message at all in slack, or a configuration to disable that.

**Comment by RoopeHakulinen** [comment]
@ravishankar15 I'm not sure I understand. Every time I resolve an issue, I get a notification out of it. Here's a screenshot of my notifications now if that helps
![image](https://github.com/grafana/oncall/assets/2197974/da26a3ec-1a5e-4b9c-a1e2-d92fb1e1e165)

**Comment by salarali** [comment]
Yeah. I am talking about this alert log message, which is a separate message in the thread

![image](https://github.com/grafana/oncall/assets/1452840/ebef3045-36d3-48ed-92b7-6987d54de7fd)

I would like the ability to not send this Alert Group Log message to slack.

**Comment by RoopeHakulinen** [comment]
I see this was added for triaging last month. Thanks for that!

I just wanted to say that this is still extremely infuriating, as you get a delayed notification (it takes about 5 seconds to deliver after resolving) out of each of these alert group messages. If you go through a bunch of OnCall alerts at once, you need to wait for a bit for the notifications to stack, and then resolve those through the unresolved notifications UI of Slack, which is very slow, and you easily miss notifications for actual business.

And just for clarity, what @salarali is exactly the same issue I'm raising here.

**Comment by RoopeHakulinen** [comment]
Yeah, same problem there really. Sad to say that it is very infuriating, and pisses people off which is a shame as it is a solid product otherwise. Also, very easy to fix by allowing you to set a global configuration option to not post the extra message which doesn't anyways serve any purpose for some organizations.

**Comment by joeyorlando** [comment]
@RoopeHakulinen hang tight, we're discussing this issue internally and _hopefully_ will be working on a minor change here shortly 😄 thanks for the feedback!

**Comment by joeyorlando** [comment]
@iskhakov can this be closed since #4641 was merged?

**Comment by RoopeHakulinen** [comment]
Great news! 

If you close this issue, it would be great if you could just let us know when the part 
> After deployed we can remove it from the thread as requested in https://github.com/grafana/oncall/issues/3849
is ready as that is what I really am after with this issue :)
