### ISSUE TITLE
Mobile app "My next oncall shifts" shows only first shift per schedule, however web shows all of them

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#3859]
### What went wrong?

**What happened**:
- See title

**What did you expect to happen**:
- Show more upcoming shifts

### How do we reproduce it?

1. Open Grafana OnCall mobile app, click on your name and open My oncall shifts
2. 

### Grafana OnCall Version

Any

### Product Area

Schedules

### Grafana OnCall Platform?

None

**Comment by imtoori** [comment]
web app uses this endpoint 
api/internal/v1/schedules/current_user_events/?date=2024-02-18&days=9

I think we should just switch to using this endpoint
