### ISSUE TITLE
Schedules "Add Rotation" form doesn't fit on all screens

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#3868]
### What went wrong?

**What happened**:
- The "Add Rotation" form does not fit if the screen's vertical space is not big enough, leading to issues hiding some portion of the form content

**What did you expect to happen**:
- The form should be vertically scrollable if its content doesn't fully fit into the current window

### How do we reproduce it?

1. Open schedules
2. Open Add Rotation
3. Add masking, add a few users (on a smaller resolution screen)

### Grafana OnCall Version

all

### Product Area

Schedules

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Closing as done in #3904
