### ISSUE TITLE
Alert filtering by title not working

### ISSUE THREAD

**Issue by jakubvojacek** [grafana/oncall#388]
Hello

I am using grafana `9.1` with oncall `v1.0.22`. I tried filtering by title which should work according to https://github.com/grafana/oncall/issues/158 but I cannot get it to work.

https://user-images.githubusercontent.com/3463456/185808208-99884e02-eb44-4802-927f-1c5690d3e037.mov

Is it possible that it got broken since issue #158 was resolved? 

Thank you
Jakub

**Comment by vadimkerr** [comment]
This is indeed a bug that was introduced earlier when working on alert group API optimization. I'm currently working on returning the alert group search functionality.

**Comment by jakubvojacek** [comment]
Thanks a lot for the confirmation :+1:

**Comment by vadimkerr** [comment]
This should be fixed now as of v1.0.35, please upgrade to the latest version of Grafana OnCall and try filtering by title.
Closing the issue, @jakubvojacek thank you for raising this!
