### ISSUE TITLE
Filtering bug 

### ISSUE THREAD

**Issue by devinrcheevers** [grafana/oncall#3894]
### What went wrong?

**What happened**:
-

1. Have alerts in acknowledged state and try to filter the same in the alert group list. 
2. Clicking firing and resolved works fine. 
3. When i click acknowledged, it continues to show the previous list instead of filtering down to only the acknowledged ones. 
4. Only when i try to update the list of items shown, it'll reset the page and show the acknowledged alerts. 

Uploading bugonackfilter.mov…

**What did you expect to happen**:

Do filter to list of acknowledged alerts  
-

### How do we reproduce it?

1. Have alerts in acknowledged state and try to filter the same in the alert group list. 
2. Clicking firing and resolved works fine. 
3. When i click acknowledged, it continues to show the previous list instead of filtering down to only the acknowledged ones. 
4. Only when i try to update the list of items shown, it'll reset the page and show the acknowledged alerts. 

### Grafana OnCall Version

Cloud

### Product Area

Other

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by mackgorski** [comment]
@devinrcheevers can you upload the video. I think it did not get through.

**Comment by mackgorski** [comment]
Indeed filtering by `status` works for `firing`, `silenced`, `resolved`.
My assumption was that `acknowledged` will always show regardless of other status as those can still have `acknowledged` on record. But it is not the case as I have tested it as shown in the video. 

`acknowledged` status filtering does not work. @iskhakov I think we should prioritize this. Sending this to the dev channel for someone to check.

Video recorded on `sedemo`
https://github.com/grafana/oncall/assets/14937684/b733b2e2-5f8d-481c-9560-b5196b77f230

**Comment by brojd** [comment]
On this page frontend is doing polling calling GET `/alertgroups` every few secs. Every 2nd call lacks `status` query string. So the results on the page are jumping from filtered ones and not filtered ones depending on which response is returned later (there's a race condition because the one with `status` query string is much slower than the one without it). 

Uploading Screen Recording 2024-02-15 at 20.08.12.mov…
