### ISSUE TITLE
Oncall doesn't receive all my alerts

### ISSUE THREAD

**Issue by afreyermuth98** [grafana/oncall#3898]
### What went wrong?

**What happened**:
I have connected Grafana with Grafana OnCall with multiple alert rules, contact points, notification policy etc ...
Sometimes, an alert is fired on Grafana side, I can see that this is well sended to my contact inside my notification policy : `Delivered to <MY_CONTACT_POINT>` but then when I go in the `Alert groups` panel in the OnCall section, my alert is nowhere and therefore I'm not notified

**What did you expect to happen**:
I want that all my alert from Grafana to be well sended to Grafana OnCall
Moreover, I have no errors logs and everything "looks fine" but I just dont get all my alerts

### How do we reproduce it?

1. Creates alerts on Grafana Alerting
2. Create a Grafana OnCall integration with the type Grafana Alerting
3. Create a contact point on Grafana to this integration
4. Select this contact point in your notification policy in Grafana
5. Check your Grafana Alert Rules and your OnCall Alert groups and you'll have some dropped alert probably

### Grafana OnCall Version

1.3.102

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

**Comment by mderynck** [comment]
Have you checked that the alert is not being grouped under another open alert group?
Also check the logs for the oncall engine container to see if the request is reaching it.

**Comment by afreyermuth98** [comment]
Hey @mderynck !
I have 1 alert group per alert to be sure that this does not come from that.
Also, the logs don't call me a lot and there are no errors. On the other hand, I see the slack payload from my integration even if I don't have the firing alert inside OnCall Alert Rule and I never receive this payload on slack :/

**Comment by lucasfnds** [comment]
The same problem here, even when I click to test a notification within the contact points it sends it, it doesn't show an error, it remains as sent and it doesn't appear in OnCall's Alert Groups.

**Comment by Ennakin** [comment]
same. There is 'last delivery attempt...' in contact points section, but nothing happens in oncall alert groups. test alerts are sent successfully though.

**Comment by Ennakin** [comment]
@afreyermuth98 , did you find the culprit?
