### ISSUE TITLE
Provide access to alert group in templates

### ISSUE THREAD

**Issue by ksa-real** [grafana/oncall#390]
The ask is to allow richer notification templates similar to AlertManager. I'm particularly interested in Slack, but the ask applies everywhere. AlertManager finds common labels in the alert group and transforms the alert group into something like:
```yaml
CommonAnnotations: [...]
CommonLabels: [ ... ]
Alerts:
- Annotations:
  Labels:
- Annotations:
  Labels:
...
```
This allows nice notifications, where the common part is not repeated and full group is displayed.

Right now it looks like only one alert from the whole group is available for template rendering. If the full group is available, then taking the common part can be done by default or on demand by e.g. execution of some function:
```
{% set processedAlerts = extractCommonComponents(payload.get("alerts")) %}
{%- for k, v in processedAlerts.commonLabels.items() %}
...
{% endfor %}
{%- for k, v in processedAlerts.alerts.items() %}
...
{% endfor %}

```
Example of test Alertmanager notification. Note the combined alerts: there are two alerts with all the same components except for the `instance` label.
<img width="773" alt="Screen Shot 2022-08-22 at 03 39 16" src="https://user-images.githubusercontent.com/8188774/185903027-c35b37b8-6c7d-4c9b-bf48-75e707e23f96.png">

**Comment by Konstantinov-Innokentii** [comment]
@ksa-real we released alertmanager v2 integration, which now use whole alertmanager alertgroup. So whole group is available for rendering.
