### ISSUE TITLE
Upgrade Faro to >= v1.3.6

### ISSUE THREAD

**Issue by brojd** [grafana/oncall#3902]
### What would you like to see!

We should upgrade Grafana Faro, otherwise our instrumentation will get broken
<img width="739" alt="image" src="https://github.com/grafana/oncall/assets/12073649/a120b96a-d0ae-4bc2-b9f6-243a19735d1f">

### Product Area

Other

**Comment by cedricziel** [comment]
Little ping to ensure this has the right priority :)

**Comment by teodosii** [comment]
@cedricziel done, the change should be released with the next few days (1-2)
