### ISSUE TITLE
Helm release and  plugin out of sync

### ISSUE THREAD

**Issue by bpedersen2** [grafana/oncall#3921]
### What went wrong?

**What happened**:
- helm chart is a  1.3.105,  latest available plugin is at 1.3.102

**What did you expect to happen**:
- helm chart  and plugin versions are more or less in sync

### How do we reproduce it?

Upgrade helm chart and compare available versions for the plugin

### Grafana OnCall Version

v1.3.102 to 1.3.105

### Product Area

Helm, Other

### Grafana OnCall Platform?

None

**Comment by mderynck** [comment]
This appears to be from some connectivity issues during in the build process.  Added some logging and will continue to monitor.  Thanks for the report!
