### ISSUE TITLE
OnCall Mobile App QR Code doesn't work on OSS

### ISSUE THREAD

**Issue by elburnetto-intapp** [grafana/oncall#3935]
### What went wrong?

**What happened**:
- We have OnCall OSS installed, and setup. When we try to onboard a user onto the OnCall Mobile App via their Profile, the QR code has a malformed URL of our oncall instance:

'://oncallurl.domain.com'

When we try to scan the QR code in the Grafana OnCall mobile app, nothing happens.

**What did you expect to happen**:
- QR code to contain the correct OnCall URL, and the Mobile App to register.

### How do we reproduce it?

1. Open Grafana, navigate to users profile, click the IRM tab, then try to use the QR code
2. Download the Grafana OnCall mobile app, and try signing in using that QR code

Versions we are using are Grafana 10.3.3 and OnCall 1.3.102

### Grafana OnCall Version

1.3.102

### Product Area

Mobile App

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

1.3.102

### Anything else to add?

We configured OnCall via Helm, and have the base_url set as: 'oncallurl.domain.com' (there is no https:// prefixing, however we did try adding this, and this just seemed to make the Server URL display as ://https://oncallurl.domain.com

**Comment by vadimkerr** [comment]
👋 could you try setting helm values as follows and see if it helps:
- `base_url_protocol`: `https`
- `base_url`: `oncallurl.domain.com`

**Comment by elburnetto-intapp** [comment]
Hey @vadimkerr, thanks for that, that's fixed our issue! We must have been looking at an old/incorrect Helm chart previously and missed out the base_url_protocol. Cheers for the quick response :)

**Comment by zshakeel123** [comment]
I have put a detailed answer to the QR Code scanning problem, hope this helps,
https://stackoverflow.com/questions/77051533/grafana-oncall-mobile-app-can-t-scan-qr-code
