### ISSUE TITLE
Feature request: Automatic override requesting

### ISSUE THREAD

**Issue by mattmendick** [grafana/oncall#395]
This is definitely in the category of "nice to have for the future", but it would make lives super nice.

Sometimes folks need to schedule overrides for their shifts. You're not sure who to ask, and usually you end up sending a message to the team slack channel, but you need to stay on top of finding an override if no one responds. It would be a neat feature of Oncall if you could register an override request for a timeslot and oncall does the dirty work of pinging the channel and asking for volunteers. It could automate scheduling the override from slack, and make it way easier for people to do it. I feel that people don't schedule overrides because it's a pain to request and schedule them, when they should be passing off the pager for short spans, or when they're not feeling well, etc. This would enable more free-flowing passing of the pager and happier on-call rotations and teams.

**Comment by Matvey-Kuk** [comment]
That's a great idea!

**Comment by matiasb** [comment]
I think this is now solved with our [shift swap requests](https://grafana.com/docs/grafana-cloud/alerting-and-irm/oncall/on-call-schedules/shift-swaps/) feature. Let us know if that's not the case!
