### ISSUE TITLE
Unable to Disable Heartbeat

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#3956]
### What went wrong?

**What happened**:
After the first heartbeat request, the heartbeat feature is enabled automatically and cannot be disabled. When the heartbeat expires, the integration status turns red and can only be turned back to green by sending a new heartbeat request. There's no option to disable the heartbeat.

**What did you expect to happen**:
There should be a way to toggle the heartbeat feature on or off.

### How do we reproduce it?

1. Create an integration.
2. Set heartbeat interval to 1 minute.
3. Send a request to the heartbeat URL.
4. Wait for the interval to expire.
5. The integration turns red.
6. Attempt to disable the heartbeat fails.

### Grafana OnCall Version

drone-7380

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Closing as #3959 was merged
