### ISSUE TITLE
Route Template Returns as False When True

### ISSUE THREAD

**Issue by jpmillett** [grafana/oncall#4023]
### What went wrong?

When using 'and' in the route template it returns as false even when both statements are true. Why is this?

### How do we reproduce it?

Create a route with two statements (which are true) separated with and,
it will return as "True and True" but does not activate the route
![Screenshot 2024-03-06 at 16 21 22](https://github.com/grafana/oncall/assets/162312021/249766d1-cfca-46e3-b674-05fc95e5a221)

### Grafana OnCall Version

1.3.109

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

n/a

**Comment by mderynck** [comment]
In the displayed template `and` is literal since it is outside a `{{ }}` block
