### ISSUE TITLE
App plugin: Update to react-router v6

### ISSUE THREAD

**Issue by leventebalogh** [grafana/oncall#4031]
Starting from Grafana 10, plugins can start using the v6 of react-router. Overall, react-router v6 aims to simplify route configuration and provide a more flexible and intuitive API for developers.

### Why?
We are going to deprecate using react-router v5 in plugins from Grafana 11, and we would like to make sure our internal app plugins are using the v6 version by the time we finish migrating Grafana core itself.

### How?
We have created a migration guide for plugins (please see the links below), and also don't hesitate to reach out in `#grafana-plugins-platform` in Slack in case you have any questions.

- [How to migrate a Grafana app plugin to react-router v6](https://grafana.com/developers/plugin-tools/migration-guides/update-from-grafana-versions/migrate-10_0_x-to-10_1_x#update-to-react-router-v6)
- [Official React Router v5 to v6 migration guide](https://reactrouter.com/en/main/upgrading/v5)
- [Community topic](https://community.grafana.com/t/migrating-app-plugins-to-use-react-router-v6/115410)

**Comment by joeyorlando** [comment]
added this to "To Be Groomed" because it appears we are currently using a deprecated version of react router (Grafana 11 has been out for ~2 months as of the writing of this comment)

**Comment by teodosii** [comment]
Blocked until https://github.com/grafana/scenes/issues/608 is sorted out - Right now all other pages in OnCall work with v6, except for Insights which uses scenes

**Comment by teodosii** [comment]
Opened a PR https://github.com/grafana/oncall/pull/4703 for it - it changes OnCall so that we rely on the `react-router-compat` version but its using v6 syntax. Can't fully migrate to v6 as grafana/scenes still relies on v5 and that seems to break rendering on the Insights page
