### ISSUE TITLE
Allow shorter alert silence durations

### ISSUE THREAD

**Issue by melgl** [grafana/oncall#4063]
### What would you like to see!

As an OnCall user, the alert silence options are too long. Users have requested a duration of 15 minutes.

To confirm, this is the setting available in OnCall > Alert Group > Silence dropdown:

<img width="1061" alt="oncall_silence_fr" src="https://github.com/grafana/oncall/assets/81323402/f2b6c573-5b69-4dbc-b5ef-7617c529a3ec">

### Product Area

Alert Flow & Configuration

### Anything else to add?

This feature request was submitted for users on Grafana Cloud version 11.0.x on the steady RRC.

**Comment by teodosii** [comment]
Closing this one as now you can add your custom duration for each AG (though 15 min isn't in the list, you can just select Custom and input `15m`)

Fixed in https://github.com/grafana/oncall/commit/dfea60e7368ed46a712df7b71ea7b405009e702f
