### ISSUE TITLE
Filter Alert Groups by severity

### ISSUE THREAD

**Issue by melgl** [grafana/oncall#4071]
### What would you like to see!

As an OnCall user viewing Alert Groups, I would like the option to filter by the alert severity level. 

### Product Area

Alert Flow & Configuration

### Anything else to add?

This feature request was submitted for users on Grafana Cloud version 11.0.x on the steady RRC.

**Comment by iskhakov** [comment]
Filtering by labels is already available in OnCall

**Comment by BenjaminHodson-Pando** [comment]
> Filtering by labels is already available in OnCall

Where can we utilize this functionality? As it stands, filtering by a group or common label via the "Alert Groups" page is not immediately obvious. We have attempted to use the filter/search input and haven't had any success with filtering by a label.

Example:
All of our alerts have a group/common label "instance" that we would like to filter by.

**Comment by dmitry-tiger** [comment]
@iskhakov Is that feature only available for cloud version?

**Comment by matiasb** [comment]
The [labels](https://grafana.com/docs/oncall/latest/integrations/#labels) feature is only available for cloud at the moment.

**Comment by coutug** [comment]
Can we expect this feature to be added to the open source version?
