### ISSUE TITLE
Heartbeat Interval API

### ISSUE THREAD

**Issue by John2020-cyber** [grafana/oncall#4092]
### What would you like to see!

- Add an API to configure heartbeat intervals which enables us to set it in our automation.

### Product Area

Alert Flow & Configuration

**Comment by joeyorlando** [comment]
hi there @John2020-cyber 👋 I'm going to go ahead and close this for now as the core team doesn't have any _near term_ plans to add this ourselves. With that said, we'd certainly review a PR (and help you get it across the finish line) if you, or someone else, would be eager to put one together. You could use the ["internal" API's viewset](https://github.com/grafana/oncall/blob/dev/engine/apps/api/views/integration_heartbeat.py) as a good starting point.

Cheers!
