### ISSUE TITLE
Grafana OnCall `Publish To ChatOps` selection Not Working

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#4110]
### What went wrong?

**What happened**:
Clicking on the `Publish To ChatOps` selection for an integration route is not working. It just spins forever and never lets me enter a value for new integrations, or change the value for existing integrations.

**What did you expect to happen**:
To be able to select a slack channel.

![image](https://github.com/grafana/oncall/assets/77802/8fb53c9e-8628-4bfb-b849-56946897028d)

### How do we reproduce it?

1. Open Grafana OnCall and go to an integration.
2. Click on the Publish to ChatOps selection
3. Wait for the spinner to go away and some results to show up so i can set the channel.

### Grafana OnCall Version

grafana oncall cloud

### Product Area

Other

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

edge

### Anything else to add?

Multiple other people have reported the same issue to me.

**Comment by qubitspace** [comment]
It's a CORS error :(

Access to fetch at 'https://faro-collector-prod-us-central-0.grafana.net/collect/03a11ed03c3af04dcfc3be9755f2b053' from origin 'https://thetradedesk.grafana.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
faro-collector-prod-us-central-0.grafana.net/collect/03a11ed03c3af04dcfc3be9755f2b053:1 
        
        
        Failed to load resource: net::ERR_FAILED
instrumentation.js:23  Faro
 @grafana/faro-web-sdk:transport-fetch
 Failed sending payload to the receiver
 Objectevents: (2) [{…}, {…}]meta: {sdk: {…}, app: {…}, view: {…}, browser: {…}, page: {…}, …}[[Prototype]]: Object TypeError: Failed to fetch
    at eval (transport.js:58:28)
    at a (promiseBuffer.js:11:13)
    at eval (promiseBuffer.js:32:13)
    at new Promise (<anonymous>)
    at Object.add (promiseBuffer.js:26:16)
    at Fu.eval (transport.js:49:42)
    at Generator.next (<anonymous>)
    at eval (transport.js:7:71)
    at new Promise (<anonymous>)
    at eval (transport.js:3:12)

**Comment by qubitspace** [comment]
I tried it again and I get this error.

SlackConnector.tsx:89  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'display_name')
    at getSearchResult (SlackConnector.tsx:89:7)
    at eval (GSelect.tsx:101:28)

**Comment by qubitspace** [comment]
Please let us know what more information is needed.

**Comment by qubitspace** [comment]
Sorry. 1 more follow up.
Some search terms work, and some don't. It doesn't make sense to me.
If i search for `alert` I get a bunch of results.
![image](https://github.com/grafana/oncall/assets/77802/5d410e07-49ef-4e2c-9a5f-d510fc8af758)
However if I search for a word that was from the previous results (so i know it exists) it doesn't work.
![image](https://github.com/grafana/oncall/assets/77802/9cc114eb-e902-460e-a2db-21b88d3a8be9)

It appears like it's failing for some search terms and not others :(

**Comment by qubitspace** [comment]
Last update. I think i found the issue.

It seems like it works if the results include the default slack channel (#dev-default-gronc-alerts in our case)
Any search term that matches that will work, but any search term that doesn't match will get an error in the UI and fail to load the list of slack channels.

![image](https://github.com/grafana/oncall/assets/77802/fbced9cb-a488-4bb2-b908-b698336ddbca)

**Comment by qubitspace** [comment]
It also pushes the results below the bottom of the screen, and I can't select the bottom results. 
This wouldn't be a problem if i could just type the exact channel I want. However I have to include a keyword that matches the "default" channel or else I get that error and no results show up.

![image](https://github.com/grafana/oncall/assets/77802/1db7fa3d-1035-43b8-af8b-ce18e750f4b0)

**Comment by elburnetto-intapp** [comment]
We're also seeing this behaviour too. OnCall Plugin 1.3.113 and OnCall OSS 1.3.113.

**Comment by teodosii** [comment]
Opened PR [here](https://github.com/grafana/oncall/pull/4130) that fixes the issue

**Comment by iskhakov** [comment]
Fixed in https://github.com/grafana/oncall/pull/4130
