### ISSUE TITLE
Allow the ability to set custom values for STACK_SLUG in Self Hosted Settings

### ISSUE THREAD

**Issue by elburnetto-intapp** [grafana/oncall#4119]
### What would you like to see!

Within the Grafana OnCall Mobile App, if you create an OSS OnCall Stack and link it, you can see the Stack name of 'self_hosted_stack'. If a user had several OSS Stacks (i.e. one for Dev, one for Production), it makes it difficult to differentiate between the two.

It'd be awesome to allow for a custom variable to be set for STACK_SLUG, which is used in the OnCall Engine.

### Product Area

Mobile App, Other

**Comment by Souldiv** [comment]
Hey @joeyorlando @elburnetto-intapp after setting the ENV vars in the dockerfile it still shows up as self_hosted_stack?
