### ISSUE TITLE
URL - Potential self-reference in outgoing webhook

### ISSUE THREAD

**Issue by silabeer** [grafana/oncall#4138]
### What went wrong?

**What happened**:
When I try to send an outgoing webhook I get an error "URL - Potential self-reference"
I was try different url from webhook, same result

In logs:
2024-03-29 09:19:20,604 source=engine:celery worker=ForkPoolWorker-7 task_id=ddbe7c0f-510d-4360-9b13-d1c518e28a61 task_name=apps.webhooks.tasks.trigger_webhook.execute_webhook name=apps.alerts.models.alert_group_log_record level=DEBUG send_update_log_report_signal for alert_group 38, alert group event: Escalation failed

### How do we reproduce it?

1. Open Grafana OnCall and do Outgoring Webhook
2. Create Webhook and assign on escalation chain
3. Send test alert

### Grafana OnCall Version

v1.3.114

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
@silabeer two things:
1. what is your `BASE_URL` environment variable set to?
2. what is the FQDN of the URL you are providing to the webhook you are creating?

The error you are seeing originates [here](https://github.com/grafana/oncall/blob/a35a8949eb126cc04fa634a420918e0449093739/engine/apps/webhooks/utils.py#L41-L42) (tldr; you're not allowed to create webhooks which call back into the OnCall API)

**Comment by silabeer** [comment]
@joeyorlando  thanks for you help
            - name: BASE_URL
              value: '://'
I was try set BASE_URL to BASE_URL=http://localhost:8080
And webhook its work, thanks

**Comment by joeyorlando** [comment]
If I understand correctly, you've resolved this issue? I'll go ahead and close this issue (but feel to let me know otherwise)
