### ISSUE TITLE
Can't scroll on integration settings page

### ISSUE THREAD

**Issue by vadimkerr** [grafana/oncall#415]
When I open an integration settings page, I can't scroll down. E.g. for `Alert Templates` tab I can't scroll down to the "Save Templates" button. The same goes for the `Hearbeat` tab.
The issue occurs when I'm using Safari, but I can't reproduce it on Chrome.

<img width="998" alt="Screenshot 2022-08-25 at 15 52 16" src="https://user-images.githubusercontent.com/20116910/186698194-095008c0-e875-4430-81d2-79f13d6b766d.png">

**Comment by joeyorlando** [comment]
@maskin25  this is still reproducible on Safari. See [this](https://raintank-corp.slack.com/archives/C04JCU51NF8/p1678117654197879?thread_ts=1678108314.809149&cid=C04JCU51NF8) Slack message for more context on how I reproduced

It's blocking being able to run the e2e tests on Safari.

**Comment by deepy** [comment]
I imagine this is live on grafana.net now because I am seeing an additional scrollbar, but unfortunately it's still not possible to scroll the page
![image](https://user-images.githubusercontent.com/905507/229462529-eeaf7c8e-8b8c-4743-ad83-844d6346ebca.png)

**Comment by joeyorlando** [comment]
@deepy do you mind providing a small video reproducing what you are seeing? This fix should be live on grafana.net, I'm not able to reproduce

**Comment by deepy** [comment]
@joeyorlando the picture above is what I'm seeing, below that window is the dock from mac os, the long scrollbar to the right is the new one but it's not possible to interact with
I've tried using the scroll-wheel, clicking it, dragging it, using the keyboard to try and navigate or by trying to select text outside the window
