### ISSUE TITLE
Adding a 'wrong' phone number doesn't show any error notification

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#4158]
### What went wrong?

**What happened**:
- Try adding +PHONE_NUMBER without the prefix (so if the prefix is +4, let it only to +). Backend request will return 400 Bad Request but frontend doesn't show any warning for it, therefore this leads to some scenario where you don't understand why it's not doing anything.

**What did you expect to happen**:
- I expected to either be valid even though it lacks prefix or to at least show an error that the phone number is not in a valid state

### How do we reproduce it?

1. Go to user profile
2. Type in the + and then the phone number (or any invalid phone number would work as well)

### Grafana OnCall Version

all

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by brojd** [comment]
Seems it's been fixed by https://github.com/grafana/oncall/pull/4191/files#diff-34d4cd7d7b756371375e6a8311d56ebcdcd42071d2ea41de2e58004a849f2918R79
