### ISSUE TITLE
issue_invite_for_the_frontend subcommand not supported in engine/manager.py

### ISSUE THREAD

**Issue by SaarthakMarkandey** [grafana/oncall#4161]
### What went wrong?

I am trying to run the issue_invite_for_the_frontend subcommand inside the engine using docker-compose.
But the logs says 
```
Unknown command: 'issue_invite_for_the_frontend'
```
Is there any alternate command which has the same functionality?

### How do we reproduce it?

```
docker-compose --env-file "${SCRIPTPATH}"/.env_hobby.temp -f "${SCRIPTPATH}"/docker-compose.yml -p "${NAMESPACE}" run engine python3 manage.py issue_invite_for_the_frontend --override

### Grafana OnCall Version

v1.3.116

### Product Area

Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Chrome

### Anything else to add?

_No response_

**Comment by matiasb** [comment]
This command doesn't exist anymore and was [removed long ago](https://github.com/grafana/oncall/pull/624), where did you get a reference to it?
