### ISSUE TITLE
Plugin has not been initialized

### ISSUE THREAD

**Issue by G0nz0uk** [grafana/oncall#4166]
### What went wrong?

Attempting to install OnCall on a local version of Grafana 10.4 (not docker).  Following - https://github.com/grafana/oncall

I click this:

![image](https://github.com/grafana/oncall/assets/15994497/1153bde9-6804-4f3c-a7d6-248756a74f0b)

Then get this:

![image](https://github.com/grafana/oncall/assets/15994497/43cd6e24-3b82-4414-b450-f81a4beecc5a)

Then click open Grafana OnCall and get this:

![image](https://github.com/grafana/oncall/assets/15994497/d7edffdb-2b95-4a80-9b98-2fdc1398214b)

Got it running and looks like this:

```
  echo "DOMAIN=http://localhost:8080
  # Remove 'with_grafana' below if you want to use existing grafana
  # Add 'with_prometheus' below to optionally enable a local prometheus for oncall metrics
  # e.g. COMPOSE_PROFILES=with_grafana,with_prometheus
  COMPOSE_PROFILES=
  # to setup an auth token for prometheus exporter metrics:
  # PROMETHEUS_EXPORTER_SECRET=my_random_prometheus_secret
  # also, make sure to enable the /metrics endpoint:
  # FEATURE_PROMETHEUS_EXPORTER_ENABLED=True
  SECRET_KEY=efefefkejk2354kjeflkjelfkjef" > .env
```

docker ps

<img width="1502" alt="image" src="https://github.com/grafana/oncall/assets/15994497/fdf08247-f4d9-4b67-95b7-6edd1af4a4ae">

my docker-compose yaml, you can see I have excluded prometheus and grafana as Ialready have these runnign locally - https://pastebin.com/swBQ0SPJ

Can you see anything wrong/missing?

### How do we reproduce it?

See above

### Grafana OnCall Version

1.3.117

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by crimewaffle** [comment]
Same issue here

I got 
```
engine_1               | 2024-05-06 08:43:09 source=engine:app google_trace_id=none logger=apps.grafana_plugin.helpers.client Error connecting to api instance HTTPConnectionPool(host='grafana', port=3000): Max retries exceeded with url: /api/org (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac93549510>: Failed to establish a new connection: [Errno -3] Try again'))
```
in my logs 
(grafana is not in a container). Currently trying to fix it.

**Comment by joeyorlando** [comment]
@crimewaffle it seems like based on your latest comment that you got things working! I'll go ahead and close this out
