### ISSUE TITLE
Actions in notification bar

### ISSUE THREAD

**Issue by niasar** [grafana/oncall#4202]
### What would you like to see!

Currently the only way to Acknowledge or resolve an alert is to do it directly in the mobile app, but it would be great if there was an option to do this with notifications buttons on Android (like opsGenie). Also this will allow smart watch users to acknowledge their alerts with watches, without touching the phone.

### Product Area

Mobile App

**Comment by imtoori** [comment]
Thanks a lot for suggesting this feature! It's already in our backlog and we'll work on it in the close future

**Comment by imtoori** [comment]
The next release is gonna show "acknowledge" and "silent" actions for new alert group notifications 
Let me know what you think about it, it will be out by end of week
