### ISSUE TITLE
Shift swap request on mobile uses GMT instead of local timezone

### ISSUE THREAD

**Issue by bmalynovytch** [grafana/oncall#4256]
### What went wrong?

**What happened**:
- added a shift swap request for today from 5pm to 6pm, rendered as 3pm to 4pm (TZ Europe/Paris properly set on web and mobile)

**What did you expect to happen**:
- expected to have shift swap request for 5pm to 6pm

### How do we reproduce it?

1. Open Grafana OnCall on mobile
2. Click target schedule
3. Click the "shift swap request" button top right
4. Select date and time for start and end
5. Validate

### Grafana OnCall Version

mobile v1.16.0 - build 1549 | server v1.4.3

### Product Area

Mobile App

### Grafana OnCall Platform?

Kubernetes

**Comment by imtoori** [comment]
thanks for reporting the issue @bmalynovytch 
I'll reproduce it and fix, I'll keep you postes
