### ISSUE TITLE
Default slack /escalate commands to Important

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#4284]
### What would you like to see!

I would like to make the default importance for slack /escalate commands to Important. People aren't familiar with the difference and escalate with the default notification policy instead of with the important notification policy. For our company (the trade desk) we want to be able to set the /escalate slack slash command to default the to the important notification policy.

### Product Area

Chatops

**Comment by joeyorlando** [comment]
@matiasb I believe this is closed via https://github.com/grafana/oncall/pull/5189, right?

**Comment by qubitspace** [comment]
This seems to be resolved for us, thanks.
