### ISSUE TITLE
Clicking alert notification shows error inside mobile app if the wrong stack was selected

### ISSUE THREAD

**Issue by N3X14** [grafana/oncall#4286]
### What went wrong?

**What happened**:
- We're using multiple Grafana Stacks (on-prem, cloud)
- Example: Inside the app the Cloud stack is selected
- When we then get an alert notifications for the on-prem stack, upon tapping on it, it takes you to the app and will show an error that the alert could not have been found. 
- We then have to manually switch the stack in the settings to be able to see the alerts.

**What did you expect to happen**:
- The stack gets switched automatically depending on the origin of the alert, thus not throwing an error.

### How do we reproduce it?

1. Have at least 2 stacks in OnCall (App) [Cloud + on-prem in our case]
2. Select one of them
3. Fire an alert on the other while your screen is locked/you're outside the app
4. Tap the notification that takes you to the app
5. Error appears. 

### Grafana OnCall Version

1.4.3

### Product Area

Mobile App

### Grafana OnCall Platform?

Other

### User's Browser?

Android App version 1.16.0 (latest)

### Anything else to add?

Unfortunately I have no screenshot right now. If an alert fires, I'll make sure to take one or post the exact wording of the error message here.

We're not certain if this is also broken for iOS.

**Comment by imtoori** [comment]
I'm looking into this right now, I'll keep you posted

**Comment by imtoori** [comment]
Don't worry we managed to reproduce it and we have a fix ready.
You'll find it in the next release (1.18.1). We're gonna push it out to the beta release (here you have the links if you want to give it a try [iOS](https://testflight.apple.com/join/mGMAjYml)/[Android](https://play.google.com/apps/testing/com.grafana.oncall.prod)) today and it will be promoted to stable on Monday.
Thanks a lot for reporting the issue!

**Comment by imtoori** [comment]
hey @N3X14 
we found another bug related to having multiple stacks, the latest version should work fine, it's in review by the play store and should be out shortly
