### ISSUE TITLE
iOS app forcibly logs out user from Cloud stack if an on-prem stack is present.

### ISSUE THREAD

**Issue by N3X14** [grafana/oncall#4304]
### What went wrong?

**What happened**:
- Some of our engineers (3+) that are using iOS are frequently logged out (forcibly & at random times) from their cloud stack. 
- Their iOS app is connected to our on-prem OnCall instance as well as the Cloud instance
- The on-prem instance never gets logged out, but the cloud instance logs them out frequently at random times. Partially even during shifts.

**What did you expect to happen**:
- No random logouts

### How do we reproduce it?

1. Add an on-prem + cloud stack to your iOS Oncall app
2. Wait, because as far as we can tell, there's no pattern other than it happens only to iOS folks

### Grafana OnCall Version

1.17.2

### Product Area

Mobile App

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by imtoori** [comment]
Thanks for reporting 
I'll investigate this shortly, I'll let you know when I find the issue

**Comment by imtoori** [comment]
I think I reproduced it. I have a fix ready for this and it will be out in the next release (probably 1.19.1)
