### ISSUE TITLE
Add filters to users page

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#4353]
At the moment it's not possible to filter the list of users by specific criteria but there are some requests to have multiple options to filter users.

Suggested filters:

- Team (list)
- Notification methods (list incudes available for stack options: Slack, mobile app, phone call etc)
- Important policy: toggle y/n
- Warnings: toggle y/n

**Comment by joeyorlando** [comment]
@iskhakov I saw you have #4575 open, do you mind adding an estimate to this issue? 🙏

**Comment by iskhakov** [comment]
> @iskhakov I saw you have #4575 open, do you mind adding an estimate to this issue? 🙏

Done @joeyorlando
