### ISSUE TITLE
Use more clear naming to add difference between Notify Slack User Group and Notify whole slack channel escalation steps

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#4373]
There is a confusion around **Notify Slack User Group**  and **Notify whole slack channel**  escalation steps.  

Many people expect these to just @ people in slack not use oncall's configured personal notifications.  We should rename these to be more clear (instead of only explaining in docs) and add a step that does what they are wanting to @ a channel or group.

**Comment by iskhakov** [comment]
We need to rename "Notify whole slack channel" to "Escalate to all slack channel members (use with caution)" (or consider removing this step)
