### ISSUE TITLE
OnCall migration tool docs

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#4388]
Develop documentation for the public OnCall docs to increase visibility of the OnCall migration tool.

Resources:
https://github.com/grafana/oncall/tree/dev/tools/migrators

**Comment by joeyorlando** [comment]
I'm going to close this as completed, but feel free to re-open if that's not the case!

We do have https://grafana.com/docs/oncall/latest/set-up/migration-from-other-tools/ which gives a (very) brief overview to the migration tools available + links to the [detailed technical docs](https://github.com/grafana/oncall/tree/dev/tools/migrators). I'm not sure if it'd be worthwhile repeating information in the `README.md` in the public docs?
