### ISSUE TITLE
[DOCS] Google calendar integration doc

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#4390]
Develop documentation to support the OnCall Google calendar integration.

Resources:
Context in [Slack thread](https://raintank-corp.slack.com/archives/C03P8RYP2FP/p1711487191815229)
[Blog post](https://grafana.com/blog/2024/04/29/pto-peace-of-mind-sync-grafana-oncall-with-google-calendar-out-of-office-events/)

**Comment by joeyorlando** [comment]
I'm going to mark this as closed as we currently have docs on this (see previous comment) but feel free to re-open!
