### ISSUE TITLE
Crossplane - add missing selector and ref fields for various OnCall resources

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#4411]
### What would you like to see!

Our Crossplane provider currently doesn't allow specifying a selector for an integration's default route's escalation chain (we only provide `defaultRoute.escalationChainId`). See [our crossplane provider docs](https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.16.1/resources/oncall.grafana.crossplane.io/Integration/v1alpha1#doc:spec-initProvider-defaultRoute-escalationChainId) for more context.

See [`NotificationPolicy.contactPointRef`](https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.16.1/resources/alerting.grafana.crossplane.io/NotificationPolicy/v1alpha1#doc:spec-forProvider-contactPointRef) as an example of ideally how we should do this.

**Deliverables**
As a user of Crossplane whom is trying to code-ify my OnCall Integrations, I should be able to have my Integration's default route escalation chain reference an Escalation Chain

### Product Area

Terraform

**Comment by joeyorlando** [comment]
re-opened as we need to add selector and ref fields for a few more objects:
- [ ] `Integration` (check that there are no other related fields)
- [ ] `Schedule`
- [ ] `Route`
- [ ] `Escalation`

@MasterExecuson were they other objects you were using/came across that were missing selector/refs?

Once those changes are in, I'll go ahead and cut the v0.16.2 release over there

**Comment by MasterExecuson** [comment]
@joeyorlando , find bellow the link for the fields that are reference through ID and thus don't work great on Crossplane after this first commit.

## Escalation

[NotifyOnCallFromSchedule](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_escalation_types.go#L59)

[GroupToNotify](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_escalation_types.go#L43C2-L43C15)

[PersonsToNotifyNextEachTime](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_escalation_types.go#L73)

[PersonsToNotify](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_escalation_types.go#L68)

[NotifyToTeamMembers](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_escalation_types.go#L63)

## Escalation Chain

[TeamId](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_escalationchain_types.go#L24)

## Integration

[teamId](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_integration_types.go#L149)

##OnCallShift

[RollingUsers](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_oncallshift_types.go#L55C2-L55C14)

[teamId](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_oncallshift_types.go#L67C2-L67C8)


## Route

Done.

## Schedule

[teamId](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_schedule_types.go#L45)

[shifts](https://github.com/joeyorlando/crossplane-provider-grafana/blob/c40e756e6dcb0195ea7a06d67fe9162eda3a330e/apis/oncall/v1alpha1/zz_schedule_types.go#L37)



I know it's actually as lot of field, but without those, creating a crossplane config for on call is very hard and requires a lot of custom mapping (speaking from expirience)...
