### ISSUE TITLE
Outgoing Webhook "Forward All" field - improve UI/UX/confusion around this field wrt "Data" field

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#4412]
### What would you like to see!

When creating an advanced Outgoing Webhook the current UI around the configuration of "Forward All" and "Data" is a bit confusing (as reported by a customer):
![Screenshot 2024-05-28 at 13 37 43](https://github.com/grafana/oncall/assets/9406895/5de6c009-5b31-4314-8f3a-2bbf90a448c5)

When "Forward All" is enabled (which is the default), this essentially overrides whatever the user inputs into the "Data" field. The wording in the form aren't entirely clear that this is the case. We should either improve wording here, or as another possible solution, maybe hide "Data" if "Forward All" is enabled.

### Product Area

Other

**Comment by raphael-batte** [comment]
During the latest UI work, there was a new possible direction for the webhook drawer. We can use this specific part from it:

![Image](https://github.com/grafana/oncall/assets/102970268/2d360d68-6210-4e62-8415-4d6dd49248f7)

or update the entire drawer:

![Image](https://github.com/grafana/oncall/assets/102970268/96cefe78-ac78-40d1-a747-d2fa460ca936)


There is also an issue that is relevant to such work https://github.com/grafana/oncall/issues/3409
