### ISSUE TITLE
Readers of Notification need to be EDITOR

### ISSUE THREAD

**Issue by EvertonSA** [grafana/oncall#4430]
### What went wrong?

**What happened**:
When trying to alert users on a grafana team, because users are viewers, they do not get notified.

**What did you expect to happen**:
Viewer users be able to be notified.

### How do we reproduce it?

1. Open Grafana OnCall and create flow to an user who is viewer, not editor/admin
2. Notify
3. Notification never arrives, error message is "notification is not allowed for user"

### Grafana OnCall Version

1.5.4

### Product Area

Auth

### Grafana OnCall Platform?

Kubernetes

**Comment by joeyorlando** [comment]
hi there 👋 the (main) rationale behind this is that viewers have read only access. Should a viewer get notified about an alert group, they would not be able to react (read: edit) the alert group.

One solution here is to checkout Grafana Enterprise/Cloud where we have RBAC + RBAC for OnCall available ([Grafana docs](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/) + [OnCall docs](https://grafana.com/docs/oncall/latest/manage/user-and-team-management/))
