### ISSUE TITLE
Theme item `e.shape.radius` is not defined

### ISSUE THREAD

**Issue by hdhoang** [grafana/oncall#4437]
### What went wrong?

**What happened**:
- Open Schedules

**What did you expect to happen**:
- See schedules

### How do we reproduce it?

1. Use grafana 9.4 with oncall 1.5.4 (compatible with grafana>=9.2)
2. Open Schedules
3. Browser console show error in issue title

UI shows `Wd.faro is undefined` error (because we don't set it up), but that's separate.

### Grafana OnCall Version

1.5.4

### Product Area

Schedules

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

With grafana 9.4 themes, `shape.radius` doesn't exist.  It is available from 9.5 https://github.com/grafana/grafana/commit/1332b0d84446f50368fb3ba058891dd3e1ab8b37

Workaround: I replaced such styles in grafana's plugin storage file `plugins/grafana-oncall-app/module.js`, and can view the new Schedules update, it's good.

Usage added in #4362. Could you return to fixed value `2px`? Thanks

**Comment by teodosii** [comment]
Thanks for reporting, opened a PR for it.
