### ISSUE TITLE
Update filters UI across OnCall

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#4464]
The current version of filters used in the interface is inconsistent with other areas of Grafana and needs to be updated:
![image](https://github.com/grafana/oncall/assets/102970268/2c28ba87-6009-4f2e-9622-525c0624b270)

Expected result: unify filtering tools with Grafana.
![image](https://github.com/grafana/oncall/assets/102970268/68edb33e-3b32-41cc-bd35-ac1f8e720802)

[Figma ](https://www.figma.com/design/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=12341%3A10896&t=du3DS7RcrPdeRhJu-1)

### Product Area

Alert Flow & Configuration

**Comment by iskhakov** [comment]
Refresh button might be connected to https://github.com/grafana/oncall/issues/4454
