### ISSUE TITLE
UI bug: caret overlaps with text

### ISSUE THREAD

**Issue by jtheory** [grafana/oncall#4480]
### What went wrong?

Looks like a minor layout bug; could be browser-specific (I've only tested on Firefox).

There's a little graphic to show the row can be expanded, but it's overlapping with the "API/Terraform" text:
![image](https://github.com/grafana/oncall/assets/350728/7d701aa9-8f35-48d8-ab9d-4578e811a47c)

### How do we reproduce it?

1. Open the [OnCall schedules list in Ops](https://ops.grafana-ops.net/a/grafana-oncall-app/schedules?p=1)
2. Check the first column in the table: there's a ^ icon to show the row can expand, but it's overlapping text

I've only tested on FF/ubuntu, in case it's browser-specific.

### Grafana OnCall Version

r365-v1.6.2

### Product Area

Schedules

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0

**Comment by jtheory** [comment]
Probably unrelated (unless this is a browser-specific thing again?) but there's also text overlap in the user list, if 2 users in a row have phone numbers set
![image](https://github.com/grafana/oncall/assets/350728/db992996-98d8-4407-87f1-689df737bd34)

**Comment by teodosii** [comment]
Thanks for reporting @jtheory 
I added it to our schedules issues we found out recently after last schedule release we had. We'll look at it

**Comment by teodosii** [comment]
@jtheory does the 2nd issue with users text overlapping still reproduce to you? can't get it to show up on ops.
