### ISSUE TITLE
Helm chart - support for kubernetes > 1.25

### ISSUE THREAD

**Issue by cw-sanikachavan** [grafana/oncall#4499]
### What would you like to see!

As per the Readme.md, I can see support until 1.25, by when can we see 1.28+ support for Grafana OnCall?

### Product Area

Helm

**Comment by EvertonSA** [comment]
i'm already on 1.29 and I have oncall

**Comment by cw-sanikachavan** [comment]
@EvertonSA yes I got this working by disabling cert-manager and ingress-controller. Have you done the same?

**Comment by EvertonSA** [comment]
> @EvertonSA yes I got this working by disabling cert-manager and ingress-controller. Have you done the same?

indeed, I disable these two and also others like redis and rabbit!

**Comment by iskhakov** [comment]
[As per documentation ](https://github.com/grafana/oncall/tree/dev/helm/oncall#production-usage), we don't recommend running a default configuration that might not support recent versions of k8s. Please disable other components to use oncall in production

>Default helm chart configuration is not intended for production. The helm chart includes all the services into a single release, which is not recommended for production usage. It is recommended to run stateful services such as MySQL and RabbitMQ separately from this release or use managed PaaS solutions. It will significantly reduce the overhead of managing them. Here are the instructions on how to set up your own [ingress](https://github.com/grafana/oncall/tree/dev/helm/oncall#set-up-external-access), [MySQL](https://github.com/grafana/oncall/tree/dev/helm/oncall#connect-external-mysql), [RabbitMQ](https://github.com/grafana/oncall/tree/dev/helm/oncall#connect-external-rabbitmq), [Redis](https://github.com/grafana/oncall/tree/dev/helm/oncall#connect-external-redis)
