### ISSUE TITLE
Exotel params configuration via Helm

### ISSUE THREAD

**Issue by cw-sanikachavan** [grafana/oncall#4514]
### What would you like to see!

Add the ability to configure exotel via helm directly

### Product Area

Helm

### Anything else to add?

I am willing to create a PR for the same, if this is not already in works

**Comment by joeyorlando** [comment]
hi there 👋 

you should be able to specify [`env`](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L446) in your values file to provide the [exotel related environment variables](https://github.com/grafana/oncall/blob/dev/engine/settings/base.py#L919-L926) to configure exotel.

please let me know if this is not the case!
