### ISSUE TITLE
One-time installation key UI/UX

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#452]
Proposal:
1) Get rid of one-time installation token. Make backend to allow registering the first frontend only.
2) We still need URLS for "Frontend -> OnCall Backend" and "OnCall Backend -> Grafana. Make sure we provide proper error messages and explanation what is where.
3) Draw schematic image of network connectivity and put it right on the configuration page. To clear up what URL's do we ask for.

**Comment by raphael-batte** [comment]
One more case with same problem https://github.com/grafana/oncall/issues/468

**Comment by iskhakov** [comment]
https://github.com/grafana/oncall/issues/122

**Comment by joeyorlando** [comment]
note to self: update the frontend configuration error message to not mention the need to regenerate a new token

**Comment by joeyorlando** [comment]
Closing as this was implemented in #624
