### ISSUE TITLE
Use label for alert group in onCall on-premise

### ISSUE THREAD

**Issue by nicolas-fidel-wmx** [grafana/oncall#4545]
### What would you like to see!

I'm currently trying to use labels for group alerts, but it won't work on a Grafana on premise even with an activated license.

Is this normal?

Is it possible to have access to labels on the paid version but deployed on premise?

### Product Area

Alert Flow & Configuration

**Comment by joeyorlando** [comment]
hi there 👋 

As mentioned [in the docs](https://grafana.com/docs/oncall/latest/integrations/#labels), labels functionality is only available in Grafana Cloud:

> Note: Labels are currently available only in cloud.
