### ISSUE TITLE
ChatOps setup UI unification

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#457]
Proposal:
1. Create unified wizard-styled UI for chatops setup. Right now every chatops Ui looks different.
2. Polish sharp angles in userflows

**Comment by Matvey-Kuk** [comment]
@raphael-batte "Polish sharp angles in userflows" sounds pretty wide. Do you mind making specific proposal?

**Comment by raphael-batte** [comment]
@Matvey-Kuk still collecting details. will share update here as UI-sketches with proposals

**Comment by raphael-batte** [comment]
MS Teams setup scenarios:

**There is no bot yet**
1. the user activates it and connects the DM
2. the user activates it and connects the type-workspace

**There is a bot** and one of the users connected it, or set up a team workspace.
In this case, we show
3. simplified dialogue for team workspace
4. simplified setup for the user
