### ISSUE TITLE
Remove "v" from Grafana OnCall versions for more consistency with the rest of grafana products

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#458]
Otherwise it leads to following output
```
✔ Downloaded grafana-oncall-app vv1.0.21 zip successfully
```

**Comment by maskin25** [comment]
@iskhakov is it still reproducing?

**Comment by Matvey-Kuk** [comment]
@maskin25 I think so: https://github.com/grafana/oncall/releases/tag/v1.1.23

**Comment by kuzaxak** [comment]
double `v` doe not allow to use grafana operator, as this version wouldn't pass CRD validation. Could it be fixed?

**Comment by kuzaxak** [comment]
https://github.com/grafana/oncall/issues/1153

**Comment by kuzaxak** [comment]
https://github.com/grafana/oncall/issues/1858

**Comment by kuzaxak** [comment]
@Matvey-Kuk Could you please have a look into that issue as it was reported multiple times and create a confusion.
