### ISSUE TITLE
Terraform provider crash on resource grafana_oncall_on_call_shift when rolling_users is empty

### ISSUE THREAD

**Issue by damfle** [grafana/oncall#4603]
### What went wrong?

**What happened**:
When you use the Terraform provider resource [grafana_oncall_on_call_shift](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_on_call_shift) using `rolling_users` type with an empty `rolling_users` array. Either `[]` or `[[]]` the provider do hard crash. It is annoying as we use TeamSync and pre-configure schedules before users first connect.

**What did you expect to happen**:
Do not crash the entire provider.
Put this as a warning but not an error and do nothing.

### How do we reproduce it?

1. Create an grafana_oncall_on_call_shift with `rolling_users` type and empty `rolling_users` array
2. Run terraform apply

### Grafana OnCall Version

provider 3.1.0

### Product Area

Terraform/Crossplane

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by joeyorlando** [comment]
@matiasb can this be closed since https://github.com/grafana/terraform-provider-grafana/pull/1685 was merged?

**Comment by matiasb** [comment]
I was waiting for the release (and it seems that happened a few days ago). Closing now.
