### ISSUE TITLE
An unknown error occurred when trying to install the plugin. Verify OnCall API URL, https://grafana-backend.soulhq.ai , is correct? Refresh your page and try again, or try removing your plugin configuration and reconfiguring.

### ISSUE THREAD

**Issue by satya-soul** [grafana/oncall#4619]
### What went wrong?

**What happened**:
-I have installed Grafana Oncall Plugin.but my backend is unable to connect it is throwing me error.
An unknown error occurred when trying to install the plugin. Verify OnCall API URL, https://grafana-backend.soulhq.ai , is correct?
Refresh your page and try again, or try removing your plugin configuration and reconfiguring.

**What did you expect to happen**:
-
I expect it to connect to my backend url.which is giving an OK response

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

v1.8.0

### Product Area

API

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

I need this to be fixed immediately

**Comment by joeyorlando** [comment]
Not enough information to reproduce. Please search through existing issues for similar issues (there are a few)
