### ISSUE TITLE
Add monochrome app icon for the Android app

### ISSUE THREAD

**Issue by ThatOneCalculator** [grafana/oncall#4634]
### What would you like to see!

As of Android 13, monochrome icons can be added to apps. Having a monochrome icon for Grafana OnCall on Android would be great :)

### Product Area

Mobile App

### Anything else to add?

With the current OnCall app icon, my home screen looks like this 😅

![Screenshot_20240708-125448](https://github.com/grafana/oncall/assets/44733677/bf182850-5072-4bfa-9e2f-a439fbffa7fd)

**Comment by robert-northmind** [comment]
We added monochrome app icon support in the PR:
https://github.com/grafana/oncall-mobile-app/pull/931
We hope to have it merged and deployed within 1-2 weeks
