### ISSUE TITLE
Automatic incident normalization does not work.

### ISSUE THREAD

**Issue by gilbertobr** [grafana/oncall#471]
I have an integration with Zabbix, which notifies normally, but when zabbix sends an OK status.
Does not work.

Below is my scenario.

PAYLOAD PROBLEM:
```
{
    "alert_uid": "14816247",
    "message": "PROBLEM: Unavailable by ICMP ping'\n''\n'SEVERITY: High'\n'TIME: 23:05:56",
    "state": "alerting",
    "title": "PROBLEM: Unavailable by ICMP ping - ONCALL_GROUP: 14816247"
}
```

PAYLOAD RESOLVED:
```
{
    "alert_uid": "14816247",
    "message": "RESOLVED: Unavailable by ICMP ping'\n''\n'SEVERITY: High'\n'TIME: 23:06:56",
    "state": "ok",
    "title": "RESOLVED: Unavailable by ICMP ping - ONCALL_GROUP: 14816247"
}
```

Script:
https://grafana.com/docs/oncall/latest/integrations/available-integrations/add-zabbix/#grafana_oncallsh-script

Config Integration
![image](https://user-images.githubusercontent.com/20375245/188180973-e57ca03d-d6c2-4e58-a6f6-bcec50133528.png)
![image](https://user-images.githubusercontent.com/20375245/188181082-baa73206-e090-4a52-8af9-bac347cb7610.png)
![image](https://user-images.githubusercontent.com/20375245/188181219-32f8a22c-91be-4441-9c31-881b4808b5e4.png)
![image](https://user-images.githubusercontent.com/20375245/188182159-7d58b640-c83a-46a1-a1f5-76df050b3a41.png)

Command:
curl $url -d "${payload}" -H "Content-Type: application/json" -X POST

If you notice, you will notice that there is a reported incident "Firing" and normalization has already been reported as "Resolved"
This Firing should be grouped into a single incident.

**Comment by Matvey-Kuk** [comment]
Hey 👋 Your "Grouping ID" is "{{ Payload }}" which means that each alert with different payload will be grouped to different Alert Group. Sounds like that's exactly what happens. I suggest trying "Grouping ID" = "{{ payload.title }}"

**Comment by gilbertobr** [comment]
Thanks @Matvey-Kuk  for the guidance.
More based by title, it didn't work out very well.
But I changed it to `{{payload.alert_uid}}`,  worked.

**Comment by JohnBardoe** [comment]
I have the same problem - alerts with different states won't stack. Here are my payloads:
```
{
    "host": "static-region-id5.gdf",
    "state": "alerting",
    "title": "monit",
    "message": "No report from Monit for 164 seconds: the network, the host or Monit is down. Last report was 16 Jun 2023 11:53:31 +0300",
    "alert_uid": "1f988ccd-111c-3b29-b38f-bd126b8a53ad"
}

{
    "host": "static-region-id5.gdf",
    "state": "ok",
    "title": "monit",
    "message": "Monit status report received successfully",
    "alert_uid": "1f988ccd-111c-3b29-b38f-bd126b8a53ad"
}
```


Grouping ID:
![image](https://github.com/grafana/oncall/assets/25174105/1eceaa87-352b-4fae-80a6-386e1bcf4980)

Alerts:
![image](https://github.com/grafana/oncall/assets/25174105/08c2265b-5eeb-4c25-8bf3-6896b7184935)
![image](https://github.com/grafana/oncall/assets/25174105/84a28e40-c9cf-487b-9e85-be482a346154)
