### ISSUE TITLE
Add wrong team error for all team-specific resources

### ISSUE THREAD

**Issue by vadimkerr** [grafana/oncall#472]
Currently there's only one page ("Alert Groups") that is capable of showing a human readable error when user tries to access a resource from a different team:

<img width="482" alt="Screenshot 2022-08-04 at 16 28 23" src="https://user-images.githubusercontent.com/20116910/182886919-639e0fd7-9753-476c-bf66-1c924f159ccc.png">

There are other resources that can benefit from this as well, e.g. integrations, schedules, etc.

**Comment by Matvey-Kuk** [comment]
For example: for "escalation chain".

![Image](https://user-images.githubusercontent.com/3284841/188407134-15e961bb-3658-481c-a23c-57b604f9148f.png)

**Comment by Matvey-Kuk** [comment]
How to reproduce:
- Open any specific object (Escalation chain, Maintenance,  Schedule...)
- Copy url link in the browser
- Switch team
- Past the link to the browser
- You'll see error message

**Comment by raphael-batte** [comment]
Probably we can use here the same UI as we have at Alerts. We just need to change descriptions
