### ISSUE TITLE
Allow manually triggering a webhook

### ISSUE THREAD

**Issue by matiasb** [grafana/oncall#4748]
### What would you like to see!

It should be possible to trigger a webhook in an alert group context via a custom action button.

### Product Area

Alert Flow & Configuration

**Comment by natellium** [comment]
@matiasb @raphael-batte do we need some design work here?

**Comment by raphael-batte** [comment]
@natellium yes, definitely!

**Comment by natellium** [comment]
@matiasb @raphael-batte can you move this issue and its parent https://github.com/grafana/oncall-private/issues/2882 to In Progress if you get started? :)

**Comment by raphael-batte** [comment]
UX proposal based on WG call results.
1. We can use existing webhooks that have an Escalation step trigger as a Manual trigger, too. 
We need to rename the initial trigger type to have a broader naming to cover both cases. 
![Image](https://github.com/user-attachments/assets/e9137985-bf69-404c-8801-1a497676cac3)

2. We add a new Item to the Actions button inside the AG page.

Current view:
![Image](https://github.com/user-attachments/assets/e5570d98-6264-4705-9aad-94e35dab0bd2)

Drafted suggestion (needs better icon)


![Image](https://github.com/user-attachments/assets/3632d6be-f5bf-44b0-b10d-cdf2c7de1b2d)

3. By click we open modal and allow to select webhook from the list. The list shows only webhooks with relevant trigger type.

![Image](https://github.com/user-attachments/assets/a7ec65d3-d9a9-45ef-a04a-9c11592ad3b6)

4. The event saved in the AG timeline


Figma link to @teodosii https://www.figma.com/design/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=12672-807&t=zj6wvP7FKf7dHREZ-1

**Comment by matiasb** [comment]
This is now deployed and available in prod.
