### ISSUE TITLE
Oncall 1.91:  grafana-oncall-app can' connect to oncall

### ISSUE THREAD

**Issue by bpedersen2** [grafana/oncall#4850]
### What went wrong?

**What happened**:
- Upgraded oncall and oncall-app in an external grafana instance to v1.9.1
- The grafana app could not connect to the backend

error logs in the grafana pod:
```
2024-08-19 12:20:00.142	
logger=context userId=3 orgId=1 uname=<redacted> t=2024-08-19T10:20:00.142364973Z level=error msg="Request Completed" method=GET path=/api/plugins/grafana-oncall-app/resources/plugin/status status=500 remote_addr=10.42.0.198 time_ms=219 duration=219.648784ms size=144 referer=https://<redacted>/plugins/grafana-oncall-app handler=/api/plugins/:pluginId/resources/* status_source=downstream
2024-08-19 12:20:00.142	
logger=plugin.grafana-oncall-app t=2024-08-19T10:20:00.14224241Z level=error msg="Error validating oncall plugin settings" error="error setting up request headers: failed to parse JSON response: json: cannot unmarshal object into Go value of type []plugin.OnCallPermission "
2024-08-19 12:20:00.142	
logger=plugin.grafana-oncall-app t=2024-08-19T10:20:00.142227995Z level=error msg="Error getting user" error="failed to parse JSON response: json: cannot unmarshal object into Go value of type []plugin.OnCallPermission"
2024-08-19 12:20:00.141	
logger=context userId=11 orgId=1 uname=sa-1-autogen-1-oncall t=2024-08-19T10:20:00.141170208Z level=info msg="Request Completed" method=GET path=/api/access-control/users/3/permissions status=404 remote_addr=10.42.0.198 time_ms=17 duration=17.536455ms size=24 referer= handler=notfound status_source=server
2024-08-19 12:20:00.077	
logger=plugin.grafana-oncall-app t=2024-08-19T10:20:00.077178626Z level=info msg=GetUser user="map[Email:<redacted> Login:<redacted> Name:<redacted> Role:Admin]"
```

no error logs in oncall pods

**What did you expect to happen**:
- successful backend connection

### How do we reproduce it?

1. Upgrade oncall/ oncall app in a setup with external grafana
     - maybe relevant: feature toogle `accessControlOnCall` is set to true
3. Try to access oncall
4. See the  oncall is not configured correctly page

### Grafana OnCall Version

v1.9.1

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

**Comment by mderynck** [comment]
- Are you running Grafana Enterprise with a valid license? `accessControlOnCall` should only be used in that case
- Also `externalServiceAccounts` feature toggle should be enabled

**Comment by bpedersen2** [comment]
Yes, that was the solution. it is a oss installation. Until 1.8.13 it was running without problems with these settings. Maybe a hint in the  releasenotes would be nice.

**Comment by senpro-ingwersenk** [comment]
Ran into the same issue. Thanks for pointing out `accessControlOnCall` - that was the culprit on our end as well.

**Comment by Tchoupinax** [comment]
As precision, do **not** use `accessControlOnCall` feature flag if you are using Grafana OSS.

**Comment by bavarian-ng** [comment]
Did someone manage to disable accessControlOnCall via Environment Variable?
I tried it with GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall=false
GF_FEATURE_TOGGLES_ACCESSCONTROLONCALL=false
GF_FEATURE_TOGGLES_ACCESS_CONTROL_ON_CALL=false

but it does not seem to work .. and i can't find specifics in the docs for that

**Comment by bavarian-ng** [comment]
If someone deploys Grafana and Oncall in Kubernetes via Grafana Operator and comes here due to the issue mentioned above:

the solution on our side was also to set this option in our grafana.yaml

`apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.metadata.app_name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    dashboards: "grafana"
spec:
  [...]
  config:
    [...]
    feature_toggles:
      accessControlOnCall: "false"`

**Comment by bpedersen2** [comment]
That seems to be the correct workaround, see also #5255 and https://github.com/grafana/oncall/issues/5100
