### ISSUE TITLE
v1.8.9 cannot load on grafana 9.5

### ISSUE THREAD

**Issue by hdhoang** [grafana/oncall#4885]
### What went wrong?

**What happened**:
- All oncall pages are blank

**What did you expect to happen**:
- Plugin works

### How do we reproduce it?

1. Open Grafana OnCall v1.8.9 with grafana 9.5 (or 9.4)
   ```bash
    grafana cli plugins install grafana-oncall-app vv1.8.9
   ```
1. Restart grafana
3. All Oncall pages are blank

error console:

```text
unreachable code after return statement redux-toolkit.esm.js:321:4
unreachable code after return statement redux-toolkit.esm.js:426:4
XHRGET
https://dev-gr.example/public/react-router?_cache=1724226752251
[HTTP/1.1 404 Not Found 424ms]

[Plugins] Failed to preload plugin: plugins/grafana-oncall-app/module (version: v1.8.9) Error: Fetch error: 404 Not Found
  Instantiating https://dev-gr.example/public/react-router
  Loading https://dev-gr.example/public/plugins/grafana-oncall-app/module.js
  Loading plugins/grafana-oncall-app/module
    e system.js:4
    promise callback*$e system.js:4
    pr system.js:4
    promise callback*pr system.js:4
    Vn system.js:4
    promise callback*34105/Vn/< system.js:4
    promise callback*Vn system.js:4
    instantiatePromise system.js:4
    promise callback*L system.js:4
    A system.js:4
    promise callback*A system.js:4
    U system.js:4
    Ut system.js:4
    P system.js:4
    P system.js:4
    34105/w.prototype[d.resolveInstantiate]/< system.js:4
    promise callback*34105/w.prototype[d.resolveInstantiate] system.js:4
    import system.js:4
    promise callback*34105/d.prototype.import system.js:4
    import system.js:4
    Br plugin_loader.ts:188
    Ln pluginPreloader.ts:20
    ln pluginPreloader.ts:14
    init app.ts:190
    90295 index.ts:21
    Webpack 7
pluginPreloader.ts:24:12
    Ln pluginPreloader.ts:24
    ln pluginPreloader.ts:14
    init app.ts:190
    90295 index.ts:21
    Webpack 7
downloadable font: Glyph bbox was incorrect (glyph ids 33 55 62 81 82 83 84 87 88 89 90 112 119 120 123 139 159 162 164 166 178 184 185 217 218 272 273 274 275 279 281 284 290 291 292 309 310 319 321 323 326 329 330 331 332 333 334 339 341 347 349 351 352 353 354 357 358 361 366 367 370 371 414 431 436 444 445 458 460 464 465 483 505 508 511 514 516 517 518 520 521 538 539 546 568 574 579 580 585 586 594 596 599 602 603 616 618 622 627 629 630 633 634 638 643 645 651 654 665 675 685 686 688 691) (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1) source: https://dev-gr.example/public/fonts/fontawesome-webfont.woff2?v=4.7.0
```

### Grafana OnCall Version

v1.8.9 and later

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

We have nginx reverse proxy to provide tls and block invitation, but do not rewrite `location` otherwise.

### Anything else to add?

We can revert to 1.8.8 successfully
```[tasklist]
### Tasks
```

**Comment by ivica-prose** [comment]
Hello,

We have the same issue. I can confirm that it's happening on version 1.8.9 and later. Version 1.8.8 works well.
We're using Grafana version 9.3.

Any idea how to solve the issue, apart from upgrading Grafana?

Thank you

**Comment by mderynck** [comment]
If you are sticking with Grafana 9.5 use OnCall v1.8.8.
There were changes to the initialization process starting v1.8.9 onwards.  I recommend updating to Grafana 11 and following these instructions if possible:

Recently we made some changes to the way Grafana OnCall is initialized.  Use 1.9.22, there were quite a few changes along the way from 1.9.0-1.9.22 to get things working.
- If you are running Grafana 11 and newer you must have `externalServiceAccounts` feature toggle enabled.
This has already been enabled in the docker compose files and helm charts in the oncall repo.
- Plugin settings must be provided to the plugin using an API call if you are installing for the first time (Note: credentials and hostnames need to be adjusted for your configuration, stackId and orgId are expected to be the listed constants in a self-hosted configuration)
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/settings' -H "Content-Type: application/json" -d '{"enabled":true, "jsonData":{"stackId":5, "orgId":100, "onCallApiUrl":"http://engine:8080/", "grafanaUrl":"http://grafana:3000/"}}'
```
- Once settings are configured use this API call to install:
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/install'
```
Grafana OnCall should now be ready to use.
For additional troubleshooting see [here](https://github.com/grafana/oncall#troubleshooting)

**Comment by joeyorlando** [comment]
See See https://github.com/grafana/oncall/issues/4829#issuecomment-2334880368
