### ISSUE TITLE
v1.9.8 cannot load in Grafana 10 or 11

### ISSUE THREAD

**Issue by fhera** [grafana/oncall#4887]
### What went wrong?

**What happened**:
- After upgrade Grafana and Grafana OnCall versions We can not see anything from Grafana OnCall. If we configure from start and analize network, We can see:

![imagen](https://github.com/user-attachments/assets/734cc0e0-6eb5-4fd2-a613-36f405de476c)

We have a nginx ingress with a domain + prefix, `/grafana`, to reach Grafana. But in previous picture we can see one call to the Grafana API with domain and without prefix.

If we go to alert group view, we can see this error:

![imagen](https://github.com/user-attachments/assets/acedfcba-58a4-4268-a1bc-a1070d811209)

**What did you expect to happen**:
- Plugin works until now.

### How do we reproduce it?

1. Open Grafana OnCall plugin and configure from zero.
2. We can observe this call to the API with 404 http response.
3. We can not finish the configuration correctly,

### Grafana OnCall Version

v1.9.8

### Product Area

Alert Flow & Configuration, API, Helm/Kubernetes/Docker

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Firefox

**Comment by diogenesblip** [comment]
Same problem here

**Comment by eirisdg** [comment]
Same here, with newer version too.
If we assign to grafana a root_url ending in /grafana, the plugin seems that doesn't do the resurrection, pointing to /api, instead of /grafana/api

**Comment by eirisdg** [comment]
Solved in 1.9.13 
https://github.com/grafana/oncall/commit/5f5eefbc53543a340cfbf12902d933fae1c66c9e

**Comment by mderynck** [comment]
Recently we made some changes to the way Grafana OnCall is initialized.  Use 1.9.22, there were quite a few changes along the way from 1.9.0-1.9.22 to get things working.
- If you are running Grafana 11 and newer you must have `externalServiceAccounts` feature toggle enabled.
This has already been enabled in the docker compose files and helm charts in the oncall repo.
- Plugin settings must be provided to the plugin using an API call if you are installing for the first time (Note: credentials and hostnames need to be adjusted for your configuration, stackId and orgId are expected to be the listed constants in a self-hosted configuration)
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/settings' -H "Content-Type: application/json" -d '{"enabled":true, "jsonData":{"stackId":5, "orgId":100, "onCallApiUrl":"http://engine:8080/", "grafanaUrl":"http://grafana:3000/"}}'
```
- Once settings are configured use this API call to install:
```
`curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/install'
```
Grafana OnCall should now be ready to use.
For additional troubleshooting see [here](https://github.com/grafana/oncall#troubleshooting)

**Comment by joeyorlando** [comment]
See See https://github.com/grafana/oncall/issues/4829#issuecomment-2334880368
