### ISSUE TITLE
OnCall was not able to load the current user. Try refreshing the page, (Detail: Non-Existent or Anonymous User).

### ISSUE THREAD

**Issue by Krunal-Dharme** [grafana/oncall#4894]
### What went wrong?

**What happened**:
- I am getting message like OnCall was not able to load the current user. Try refreshing the page.
Plugin is connecting to Grafana OnCall but it is not loading and getting OnCall was not able to load the current user. Try refreshing the page.

**What did you expect to happen**:
- We should not get the message like OnCall was not able to load the current user. Try refreshing the page.

### How do we reproduce it?

1. Open Grafana OnCall by adding username and password.
2. Now click on Grafana OnCall Menu and click on OnCall.
3. Now we will get -> OnCall was not able to load the current user. Try refreshing the page.

<img width="718" alt="Anonymous User" src="https://github.com/user-attachments/assets/3f99736b-4b88-4944-8c59-e4177d450bcc">

Expected Result: We should not get message like OnCall was not able to load current user (Non-Existent or Anonymous user)

### Grafana OnCall Version

v1.3.94

### Product Area

Helm/Kubernetes/Docker

### Grafana OnCall Platform?

Docker

### User's Browser?

Chrome

### Anything else to add?

<img width="718" alt="Anonymous User" src="https://github.com/user-attachments/assets/c8e4bda6-b052-4b75-837d-3bbcac2c3fc2">

**Comment by mderynck** [comment]
Recommend updating to a newer version of Grafana OnCall, and use Grafana 11

Recently we made some changes to the way Grafana OnCall is initialized.  Use 1.9.22, there were quite a few changes along the way from 1.9.0-1.9.22 to get things working.
- If you are running Grafana 11 and newer you must have `externalServiceAccounts` feature toggle enabled.
This has already been enabled in the docker compose files and helm charts in the oncall repo.
- Plugin settings must be provided to the plugin using an API call if you are installing for the first time (Note: credentials and hostnames need to be adjusted for your configuration, stackId and orgId are expected to be the listed constants in a self-hosted configuration)
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/settings' -H "Content-Type: application/json" -d '{"enabled":true, "jsonData":{"stackId":5, "orgId":100, "onCallApiUrl":"http://engine:8080/", "grafanaUrl":"http://grafana:3000/"}}'
```
- Once settings are configured use this API call to install:
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/install'
```
Grafana OnCall should now be ready to use.
For additional troubleshooting see [here](https://github.com/grafana/oncall#troubleshooting)

**Comment by joeyorlando** [comment]
See https://github.com/grafana/oncall/issues/4829#issuecomment-2334880368
