### ISSUE TITLE
After the update, I am not able to normalize alerts

### ISSUE THREAD

**Issue by gilbertobr** [grafana/oncall#495]
After the Grafana Oncall update, I've been trying to resolve the alerts via the web.
But it returns this empty error

![image](https://user-images.githubusercontent.com/20375245/188667576-cae8843d-4398-4cd1-bb23-0b64e5883b41.png)

docker logging (oncall-engine-1)
![image](https://user-images.githubusercontent.com/20375245/188667798-e7de2d9a-3e05-42ce-85ee-960780f71df7.png)

docker logging (oncall-grafana-1)
![image](https://user-images.githubusercontent.com/20375245/188669061-0663e2ce-1c6a-49d1-a200-d3b091ffa1dd.png)

Through Slack I can normalize, quietly.

**Comment by vadimkerr** [comment]
Thank you for opening the issue! This is indeed a bug, and I managed to reproduce it when "Require resolution note when resolve incident" settting is enabled. 

<img width="1231" alt="Screenshot 2022-09-06 at 16 12 54" src="https://user-images.githubusercontent.com/20116910/188671776-16cb0bcd-22c5-4379-a845-519ceaa80be5.png">

Until it's properly fixed, as a quick solution to your problem, please try to disable this setting, or add resolution notes to your alert groups before resolving them. Hope this helps!

**Comment by gilbertobr** [comment]
@vadimkerrhelp yes,  thank you

**Comment by vadimkerr** [comment]
This should be fixed now as of v1.0.35, returning a proper error message in this cases.

<img width="605" alt="Screenshot 2022-09-07 at 10 43 31" src="https://user-images.githubusercontent.com/20116910/188868569-954e5775-c9c5-418b-bce5-09d617ccba61.png">

Closing the issue, @gilbertobr thank you for raising this!
