### ISSUE TITLE
Frontend: Code split the plugin for improved performance

### ISSUE THREAD

**Issue by jackw** [grafana/oncall#5018]
### What would you like to see!

Hello! 👋 

Whilst auditing Grafana javascript payloads we've noticed that your Grafana app plugin is not taking advantage of code splitting. This is resulting it a large amount of unused Javascript being preloaded before the Grafana application can render anything. We're aware applications grow over time and generally we're not great at keeping on top of this but we would really appreciate it if you could put some time into code splitting this app plugin to help us reduce the amount of javascript code we're loading up front.

The following are worth considering when taking on this task:

1. The module.js is the entrypoint. It's worth keeping in mind that the smaller this file is the less effect it has on the performance of Grafana as a whole during the app preload phase which is currently render blocking.
2. Rename your module.ts to module.tsx and take advantage of Suspense, lazy, and webpacks dynamic import to lazy load your apps rootPage and (if it has one) its config page too.
3. If your app contains additional routes and pages they are likely the quickest way to reduce bundle size further by lazy loading them.
4. Any component registry (i.e. an array of objects that contain components) should be considered a target for code splitting with Suspense / lazy to further reduce bundle size.
5. Any components used with the plugin ui extensions api should be considered a target for code splitting with Suspense and lazy to remove them from the bundled module.js file.

Below are two examples of Grafana plugins that have recently been code split or are in the process of being code split. The motions are generally the same for all app plugins as the module.js revolves mostly around the AppPlugin class. These should help give you a better understanding of what's involved:

- [SLO app PR](https://github.com/grafana/slo/pull/2313). This reduced the module.js from ~900kb to 12kb.
- [Collector app branch](https://github.com/grafana/grafana-collector-app/compare/main...code-split-app). This reduced the module.js from ~2.7mb to 100kb.

Further information:

- [The Survivejs book code splitting chapter](https://survivejs.com/books/webpack/building/code-splitting/)
- [Web.dev code splitting with lazy and Suspense](https://web.dev/articles/code-splitting-suspense)

### Product Area

Other

**Comment by leeoniya** [comment]
btw, this is what we're seeing when loading up an empty dashboard on an ephemeral instance, to give you an idea of potential impact on overall load times:

https://ephemeral1511182192959leeoniy.grafana-dev.net/d/cdwx3aa48mvb4d/empty?from=now-6h&to=now&timezone=browser

![Image](https://github.com/user-attachments/assets/868b1edf-28ef-4aeb-8701-c03d4997d8c9)

**Comment by teodosii** [comment]
Has been merged to IRM, will close it once it's been released

**Comment by leeoniya** [comment]
hey, @teodosii , thanks!

it's been released / deployed, and there is good improvement but we're still seeing a 1.3MB `module.tsx` bundle for `oncall-app`. it looks like there's no `Suspense` or `lazy` in [grafana-oncall-app/src/module.tsx](https://github.com/grafana/irm/blob/main/packages/%40plugins/grafana-oncall-app/src/module.tsx) ?

![Image](https://github.com/user-attachments/assets/37caeb56-1fd9-4f35-a8bf-ae59a8937687)

**Comment by teodosii** [comment]
Hey @leeoniya 

I did merge another PR regarding this
- it adds lazy loading on all the referenced components within module.tsx
- it adds additional lazy loading in other pages
- it splits the bundle into multiple smaller chunks

Not entirely familiar with how the `Coverage` tool works on a minified version, but after these changes when we build the plugin the largest file is much smaller than what he had in the past.

Network tab on oncalldev environment
![Image](https://github.com/user-attachments/assets/5d1076ce-1ee2-4d9e-a8d1-79dfd5a69fa5)

As for the coverage tab this is the result
![Image](https://github.com/user-attachments/assets/ec3747fe-7319-48b2-8243-f6d929030279)

I'm not sure how accurate is the coverage tab, as if you look closely it's saying that a huge chunk of it is taken by the library `tinycolor`, but that's not true, as if you inspect the bundle closely with tools such as bundle-analyzer, it's actually moment-timezone taking the biggest chunk (which would be the next step in reducing the bundle size by removing dep of that, as most of our date handling is in dayjs)

**Comment by teodosii** [comment]
Last  PR regarding momentjs has been merged and the overall bundle size decreased by around 700kb. Here's a screenshot of it in ops environment.

![Image](https://github.com/user-attachments/assets/4b7f4976-e37f-41a4-844d-7e9f9354d0e1)
