### ISSUE TITLE
Drop v from plugin versions to make it work with all the surrounding tooling

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/oncall#5028]
### What went wrong?

**What happened**:
- Context https://github.com/grafana/grafana/issues/92669#issuecomment-2337920610

**What did you expect to happen**:
- Drop the `v` from the future plugin versions, it is not needed and it breaks a lot of areas (gcom-api, plugins cli, etc.) that do not expect it to be there.

### How do we reproduce it?

Try installing it via plugins cli or env variables https://github.com/grafana/grafana/issues/92669#issue-2494439862

### Grafana OnCall Version

latest

### Product Area

Other

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
This has been patched in v1.9.27 (via #5051):

```bash
❯ grafana cli plugins list-versions grafana-oncall-app
1.9.27
v1.9.26
v1.9.25
v1.9.24
v1.9.23
v1.9.22
v1.9.21
v1.9.20
```
