### ISSUE TITLE
Can't connect multiple organizations to OnCall

### ISSUE THREAD

**Issue by kevingarman** [grafana/oncall#5032]
### What went wrong?

**What happened**:
--I have a grafana instance with multiple organizations configured
--I setup OnCall with one of them...this works
--I added the OnCall plugin to the next organization, but am getting...

`Plugin is not connected
jsonData.stackId is not set`

...on the OnCall plugin config page.

### How do we reproduce it?

See problem description.

### Grafana OnCall Version

v1.9.25

### Product Area

Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Chromium 128.0.6613.113 (Official Build) snap (64-bit)

**Comment by joeyorlando** [comment]
Please see https://github.com/grafana/oncall/issues/598

**Comment by kevingarman** [comment]
Ah ok, bummer.  Thanks for the answer @joeyorlando !
