### ISSUE TITLE
Update the incident label without reloading the page.

### ISSUE THREAD

**Issue by jeschkies** [grafana/oncall#504]
In order to avoid confusion it would be nice if the incident label could automatically update to `Acknowledged` or `Resolved` without reloading the incident's page. This would be similar to GitHub pull requests that change the label to `Merged`.

**Comment by Matvey-Kuk** [comment]
Related to #297

**Comment by teodosii** [comment]
Fixed by [PR 579](https://github.com/grafana/oncall/pull/579)
