### ISSUE TITLE
v1.9.30 Permission issues when using org_id!=1 in Grafana OSS

### ISSUE THREAD

**Issue by dinfdsooff** [grafana/oncall#5096]
### What went wrong?

**What happened**:
- `Plugin is not connected
Unauthorized/Forbidden while accessing OnCall engine: /api/internal/v1/plugin/v2/status, status code: 403, check token` 
![Image](https://github.com/user-attachments/assets/af1b9601-bcfe-4edd-b532-82f3577c10f1)
![Image](https://github.com/user-attachments/assets/58ba021e-12f4-4dd8-88b8-cb78638bb84b)

- We use multiple organisations in Grafana OSS, and we want to connect `org_id=2` with the engine, we managed to configure it for default `org_id=1` but if we specify other organisation it breaks with permissions issues,  the service account is created only in `org_id=1`.
- Service account id `sa-1-extsvc-grafana-oncall-app` is created only in `org_id=1` and not in the specified organization, for example `org_id=2`, so it works only for `org_id=1`
- Tried to find any documentation or info how to configure the oncall plugin to work with other organisation other than the default and did not find any information
- `grafanaToken` and `onCallApiToken` are not generated in the table `public.plugin_setting` for `org_id!=1` 

**What did you expect to happen**:
- I would expect plugin service account `sa-2-extsvc-grafana-oncall-app` to be generated for `org_id=2` and authentication to work with the engine, or at least provide a way to create that manually.
- I would expect to have Documentation:

  - a ReadMe or some info on how to setup OnCall plugin and Engine for organisation with `org_id!=1` for Grafana OSS. It would be nice to include all the relevant info regarding this topic, such as current status and feature plans, env variables to configure, manual API calls that we need to trigger, if we need multiple Engines , DB, Redis, RabbitMQ, or one, how to do separation between organization data?
  - I would expect to have also some documentation or readme to explain the authentication flow between grafana <-> plugin <-> engine, for example if we need to create grafana token manually and configure them on the engine so it can access the API, and how to specify the `org_id`

### How do we reproduce it?

1. Install Grafana Oncall Plugin
2. Enable the Grafana Plugin for both orgs
3. `curl -X POST -H "X-Grafana-Org-Id: 1" "https://grafana.xxxx.xxx/api/plugins/grafana-oncall-app/settings" \
-H "Content-Type: application/json" -H "Authorization: Basic xxxxxxxx" \
-d '{
    "enabled": true,
    "jsonData": {
        "stackId": 5,
        "orgId": 100,
        "license":"OpenSource",
        "onCallApiUrl": "http://oncall-engine:8080/",
        "grafanaUrl": "http://grafana:80/"
    }
}'`
4. `curl -X POST -H "X-Grafana-Org-Id: 2" "https://grafana.xxxx.xxx/api/plugins/grafana-oncall-app/settings" \
-H "Content-Type: application/json" -H "Authorization: Basic xxxxxxxx" \
-d '{
    "enabled": true,
    "jsonData": {
        "stackId": 5,
        "orgId": 2,
        "license":"OpenSource",
        "onCallApiUrl": "http://oncall-engine-second:8080/",
        "grafanaUrl": "http://grafana:80/"
    }
}'`
4. `curl -X POST -H "X-Grafana-Org-Id: 1" -H "Authorization: Basic xxxxxxx" 'https://grafana.xxxx.xxxx/api/plugins/grafana-oncall-app/resources/plugin/install'`
5.  `curl -X POST -H "X-Grafana-Org-Id: 2" -H "Authorization: Basic xxxxxxx" 'https://grafana.xxxx.xxxx/api/plugins/grafana-oncall-app/resources/plugin/install'`
6. Connect to the engine succesfully for `org_id=1`

### Grafana OnCall Version

v1.9.30

### Product Area

Auth, API

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

Grafana version `11.2.0`

**Comment by dinfdsooff** [comment]
Hello @joeyorlando, could you add your input on this topic with a comment it would be much appreciated! :)

**Comment by sdwerwed** [comment]
Same issue we can't make it work for other grafana organisations, we receive 403 error during setup

**Comment by joeyorlando** [comment]
oncall oss does not support multiple orgs (https://github.com/grafana/oncall/issues/598#issuecomment-1987631966; OnCall on Grafana Cloud does however 🙂)

**Comment by sdwerwed** [comment]
Hello @joeyorlando does not support even when using different engines and databases ?

**Comment by joelbarkley** [comment]
From what my company has done, we can manually create a new service account token in the right organization, and then try to connect to oncall. This has worked for us. We use the same naming scheme as the one created automatically by oncall, and just increment it each time. the service account needs admin permissions. (We also assigned each manually created service account all oncall permissions)

First org service account:
![Image](https://github.com/user-attachments/assets/6d1fde71-d95c-4dad-89f3-131b0ae7fb4e)

Second org service account:
![Image](https://github.com/user-attachments/assets/2f93f12a-e57a-46aa-861c-c9a18123d29f)

Third org service account:
![Image](https://github.com/user-attachments/assets/e333e227-095b-4fe5-9f9d-508f15cb138a)
