### ISSUE TITLE
Calendar UI: live-testing bugs 12-09-2022

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#525]
- [ ] 1. Make rotation start <-> shift start linked by default. 
- [ ] If we change rotation start date, shifts start time changes automatically. In user wants to customize shift start time, he should corrects it in this field manually.
- [ ] 2. Mark fields with errors by red color focus (with error messages)
- [ ] 3. Add days of the week to the timeline  –> Mon 12 Sep
- [ ] 4. Add warnings about gaps in finale schedule: warning overlay + instant warning label near headline (without page refreshing)
- [ ] 5. Optimize overlay block to small screens
- [ ] 6. Disable overlay hiding by click outside 
- [ ] 7. Separate date/time picker to 2 components -> date+time
- [ ] 8. Allow to edit rotations by clicking from final schedule
- [ ] 9. Visual decoration for weekends as second step

**Comment by raphael-batte** [comment]
- [ ] Wrong local time right top corner
- [ ] Lag on click existing rotation before popup appear
- [ ] Sector over users
- [ ] User tooltip should appear under avatar
- [ ] Remove back button hover circle and alight it to main vertical axe.
- [ ] Blocks color -bg-secondary, hover -overlay 
- [ ] Merge final schedule to as less rows as possible
- [ ] Export to google calendar
- [ ] Add working hours to user settings
- [ ] Mark users with broken working hours as 'outside working hours users' by linear bg without error message
- [ ] Hide unactive icons

**Comment by vadimkerr** [comment]
- [ ] Add ability to specify by_day for events of every frequency (hourly, daily, weekly, etc.)
- [ ] (Backend) Bug with 0 length shift if rotation end is set
- [ ] (Frontend) Remove ability to click “Create” if no users are added
- [ ] (Backend?/Frotntend?) Make rotation start depend on shift end (disable rotation start input by default)?
