### ISSUE TITLE
Grafana getting incident plugin settings 404

### ISSUE THREAD

**Issue by Ennakin** [grafana/oncall#5253]
### What went wrong?

**What happened**:
- Alerts aren't sent through Grafana Oncall anymore.In "Contact points' I see 'last delivery attempt... minutes ago'. I'm sure that notification policy and oncall routes are configured correctly, cause it worked. There is nothing useful in logs, but some wierd errors:
```
msg="getting incident plugin settings" error="request did not return 200: 404"  
msg="getting labels plugin settings" error="request did not return 200: 404"
```
I'm running grafana in enterprise (from v1.11.0 to main-ubuntu - we tried every version), self hosted mode. Incident or lables plugins seem to be а part of Grafana Cloud infrastucture. Something went wrong here. Can it be associated with undelivered alerts? In OnCall logs we also get 
`status=404 method=GET path=/api/internal/v1/msteams/channels`
- something from the Cloud instance mode. 
**What did you expect to happen**:
- receive alerts through grafana oncall. Or at least have relevant errors in log.

### How do we reproduce it?

1. Configure an alert rule in folder "incident". In Grafana Oncall Integration add route with 
{{ payload.commonLabels.grafana_folder == 'incident' }} and telegram channel selected. 
2. Get the alert firing. 
3. Nothing going to happend. 
"Send demo alert" is working though.

### Grafana OnCall Version

OnCall version is 1.11.0, plugin version is 1.9.26. 

### Product Area

Helm/Kubernetes/Docker

### Grafana OnCall Platform?

Docker

**Comment by dmgeurts** [comment]
@Ennakin What did you do to resolve this? I've just come across the same error message
