### ISSUE TITLE
Trigger Webhook on "Acknowledgement" And "Resolved" 

### ISSUE THREAD

**Issue by anthonypruiz** [grafana/oncall#527]
I’d like to be able to trigger a webhook when an alert is acknowledged and or when it’s resolved.

Even better as a bonus would be to have an acknowledge chain and or a resolution chain.

Ideally I’d like to have a system where all the many siloed places where we communicate issues could be updated anywhere. So If we acknowledge or resolve an issue in Slack or Telegram or Zendesk or Catalyst or Oncall directly etc… I could echo the status update on every system anywhere.

**Comment by amezioud** [comment]
We are interested too !

Duplicate issue there => https://github.com/grafana/oncall/issues/264
