### ISSUE TITLE
Oncall plugin does not work with grafana 11.3

### ISSUE THREAD

**Issue by kvaster** [grafana/oncall#5301]
### What went wrong?

Installed: grafana 11.3, grafana oncall plugin 1.13.4.

Grafana oncall plugin doesn't work with grafana >= 11.3.

I'm using victoria-metrics helm chart in kubernetes with default helm chart for grafana. Grafana helm chart version 8.5.9 uses grafana 11.3.0 and grafana helm chart 8.5.8 uses 11.2.2.

Plugin works Ok with 11.2.2 and with 11.3.0 it just can't get user permissions. Log attached.

```
logger=context userId=35 orgId=1 uname=sa-1-sa-autogen-oncall t=2024-11-26T21:58:48.609217772Z level=info msg="Request Completed" method=GET path=/api/access-control/users/2/permissions status=404 remote_addr=10.244.1.23 time_ms=4 duration=4.474313ms size=24 referer= handler=notfound status_source=server
logger=plugin.grafana-oncall-app t=2024-11-26T21:58:48.609643524Z level=error msg="Error getting user" error="failed to parse JSON response: json: cannot unmarshal object into Go value of type []plugin.OnCallPermission body={\"message\":\"Not found\"}\n"
```

### How do we reproduce it?

Install grafana 11.3.0 and oncall plugin 1.13.4 -> oncall plugin can't connect to grafana.
Install grafana 11.2.2 and oncall plugin 1.13.4 -> oncall plugin can connect to grafana.

### Grafana OnCall Version

1.13.4 and earlier

### Product Area

Helm/Kubernetes/Docker

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Chrome 113

**Comment by YgorCastor** [comment]
+1 Same issue here.

**Comment by bpedersen2** [comment]
See #5100
