### ISSUE TITLE
private  repo

### ISSUE THREAD

**Issue by mortazakiani** [grafana/oncall#5302]
### What would you like to see!

Hi can you add a filed that i can provide private repository in helm chart ?
I cannot access to internet with my cluster and i use my private repo so i need to set registry filed to my repo to download images from my repository

### Product Area

Helm/Kubernetes/Docker

**Comment by mortazakiani** [comment]
> The current version of Grafana OnCall, at the time this issue was opened, is v1.13.4. If your issue pertains to an older version of Grafana OnCall, please be sure to list it in the PR description. Thank you 😄!

I used latest vserions

**Comment by mortazakiani** [comment]
> ### What would you like to see!
> Hi can you add a filed that i can provide private repository in helm chart ?
> i cannot access to internet  with my  cluster and i  use my private repo so  i need  to  set registry filed to my repo to  download images from my repository 
> ### Product Area
> Helm/Kubernetes/Docker
> 
> ### Anything else to add?
> _No response_

**Comment by bpedersen2** [comment]
```
image:
  repository: grafana/oncall <<== change this to <private repo-url>

```

**Comment by joeyorlando** [comment]
going to close this as @bpedersen2 has kindly provided a solution, let me know if that doesn't solve your issue!
