### ISSUE TITLE
grafana oncall plugin OSS can't connect to grafana oncall engine self hosted "jsonData.stackId is not set"

### ISSUE THREAD

**Issue by aristide-moonce** [grafana/oncall#5313]
### What went wrong?

**What happened**:
- grafana oncall plugin is not able to connect to grafana oncall engine when using the docker compose file (hobby environment). We get the following error when trying to connect it : 

```
Plugin is not connected
jsonData.stackId is not set
```

See the following screenshot : 

![Image](https://github.com/user-attachments/assets/8c0b63a8-40e7-4e25-a2e0-8b8403ac22fd)

**What did you expect to happen**:
- The plugin to be able to connect to the engine.

### How do we reproduce it?

Just follow the getting started in the readme for the hobby environment : https://github.com/grafana/oncall?tab=readme-ov-file#getting-started

1. Download the docker compose file : 

```
curl -fsSL https://raw.githubusercontent.com/grafana/oncall/dev/docker-compose.yml -o docker-compose.yml
```

2. Set variables :

```
echo "DOMAIN=http://localhost:8080
# Remove 'with_grafana' below if you want to use existing grafana
# Add 'with_prometheus' below to optionally enable a local prometheus for oncall metrics
# e.g. COMPOSE_PROFILES=with_grafana,with_prometheus
COMPOSE_PROFILES=with_grafana
# to setup an auth token for prometheus exporter metrics:
# PROMETHEUS_EXPORTER_SECRET=my_random_prometheus_secret
# also, make sure to enable the /metrics endpoint:
# FEATURE_PROMETHEUS_EXPORTER_ENABLED=True
SECRET_KEY=my_random_secret_must_be_more_than_32_characters_long" > .env
```

3. Launch services:

```
docker-compose pull && docker-compose up -d
```

4. Connect to grafana : login to http://localhost:3000 with admin/admin

5. Enable the grafana oncall plugin and try to connect it to the backend at the address `http://localhost:8080`

### Grafana OnCall Version

v1.13.5

### Product Area

Helm/Kubernetes/Docker

### Grafana OnCall Platform?

Docker

**Comment by joeyorlando** [comment]
See https://github.com/grafana/oncall/issues/4829#issuecomment-2334880368
