### ISSUE TITLE
Web-based calendar polishing collection for v1

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#532]
Logical blocks:
https://github.com/grafana/oncall/issues/531

**Comment by Matvey-Kuk** [comment]
@raphael-batte 's comments from #525:

- [ ]  1. Make rotation start <-> shift start linked by default.
- [ ]  If we change rotation start date, shifts start time changes automatically. In user wants to customize shift start time, he should corrects it in this field manually.
- [ ]  2. Mark fields with errors by red color focus (with error messages)
- [ ]  3. Add days of the week to the timeline –> Mon 12 Sep
- [ ]  4. Add warnings about gaps in finale schedule: warning overlay + instant warning label near headline (without page refreshing)
- [ ]  5. Optimize overlay block to small screens
- [ ]  6. Disable overlay hiding by click outside
- [ ]  7. Separate date/time picker to 2 components -> date+time
- [ ]  8. Allow to edit rotations by clicking from final schedule
- [ ]  9. Visual decoration for weekends as second step

**Comment by raphael-batte** [comment]
- [ ] Wrong local time right top corner
- [ ] Lag on click existing rotation before popup appear
- [ ] Sector over users
- [ ] User tooltip should appear under avatar
- [ ] Remove back button hover circle and alight it to main vertical axe.
- [ ] Blocks color -bg-secondary, hover -overlay 
- [ ] Merge final schedule to as less rows as possible
- [ ] Export to google calendar
- [ ] Add working hours to user settings
- [ ] Mark users with broken working hours as 'outside working hours users' by linear bg without error message
- [ ] Hide unactive icons

**Comment by raphael-batte** [comment]
- [ ] Lock 'Save' button if user doesnt have users in schedule

**Comment by raphael-batte** [comment]
- [ ] Implement schedule additional settings to frontend
- [ ] allow scrolling when overlay is opened
- [ ] allow closing all popup-overlays by Esc key

**Comment by raphael-batte** [comment]
Schedules list:
- [ ] hide connections icon when schedule unused in escalations
- [ ] add schedule type column (web/ical/api)
- [ ] add slack channel column

**Comment by Matvey-Kuk** [comment]
Hey team, I decided to do a pretty diligent "final check". There is a chance that some of points mentioned here are not actual bugs. Please ignore them in this case:

Tested in ops.grafana.net, r36-v1.0.50, chrome:
- [ ] 0. Let's rename "Schedules α" to "Schedules NEW" because we're going to roll it to Grafana Cloud. It's not an Alpha anymore :)
- [ ] 1. User could go to "Schedules α" and try creating ICal schedule. Since we don't show Ical schedules in this page, user will see an empty list after creating one. We either should render new+old schedules on "Schedules α" page, either don't allow to create Ical schedules on the "Schedules α" page. Just disable this button.
- [ ] 2. While creating a schedule we have an option "Create schedule by API" with sub-text "Configure rotations and upload calendar by Terraform file". It's not correct, we don't allow "uploading" terraform, we allow "applying Terraform to our API". Also the link is misleading because API-based schedule could be created only using API, not through UI. I propose such a sub-text: "Use API or Terraform to manage rotations". Instead of "Create" I propose "Read more" leading to https://grafana.com/blog/2022/08/29/get-started-with-grafana-oncall-and-terraform/ in a new tab.
- [ ] 3. Bug:
         - I create rotation.
         - I delete rotation which "cuts it" (as expected)
         - I click the leftover piece of the rotation. It gives me 500.
         - I'm not able to change anything anymore.

https://user-images.githubusercontent.com/3284841/199861595-8e8cdfa7-5097-4ef3-b12e-cb8d841fc192.mov

I think it's a frontend & backend bug. Frontend shouldn't lock after 500's. Backend obviously shouldn't give us 500's :)

- [ ] 4. Override edit renders with a small excessive piece. It's probably related to the fact that I recently changed timezone from Jerusalem to New York. That's a non-blocking bug. I'm ok to roll with it being non-fixed:

https://user-images.githubusercontent.com/3284841/199862402-6afbd3df-918b-48ea-8ea0-7fe6ff0cde32.mov

- [ ] 5. Cannot delete override which is happening now:

https://user-images.githubusercontent.com/3284841/199862733-8a5cb83b-fb80-4fe5-9583-293dd9b5f8eb.mov

**Comment by Matvey-Kuk** [comment]
I didn't realize we already show all schedules in "Schedules alpha" page. So #0 and #1 are not relevant. Let's just remove old schedules page.

**Comment by mderynck** [comment]
- [ ] Exported ical link has incorrect level for override (In the UI I am overriding but in the export I have L0)
![Screenshot from 2022-11-04 10-01-50](https://user-images.githubusercontent.com/28077050/200024305-ae2eff66-15a6-493a-812d-0f9b843d47f2.png)

**Comment by vadimkerr** [comment]
> 5. Cannot delete override which is happening now:

@maskin25 I checked the backend part, the override deletion works the same as deletion of regular shifts.
When making a DELETE request, backend returns 204 and sets the `until` property to current time. This seems to be working fine for regular (non-override) shifts, so could you please check if there's some issue on the frontend part for overrides?

**Comment by matiasb** [comment]
> > 5. Cannot delete override which is happening now:
> 
> @maskin25 I checked the backend part, the override deletion works the same as deletion of regular shifts. When making a DELETE request, backend returns 204 and sets the `until` property to current time. This seems to be working fine for regular (non-override) shifts, so could you please check if there's some issue on the frontend part for overrides?

FYI, I was also checking, indeed the `until` is being set, but there is some change required in the backend to enforce the `until` in overrides shifts (no changes should be required in the frontend as far as I can tell), I have a PR in progress with the update (and some other schedule-related fixes I'm working on)

**Comment by maskin25** [comment]
> > > 5. Cannot delete override which is happening now:
> > 
> > 
> > @maskin25 I checked the backend part, the override deletion works the same as deletion of regular shifts. When making a DELETE request, backend returns 204 and sets the `until` property to current time. This seems to be working fine for regular (non-override) shifts, so could you please check if there's some issue on the frontend part for overrides?
> 
> FYI, I was also checking, indeed the `until` is being set, but there is some change required in the backend to enforce the `until` in overrides shifts (no changes should be required in the frontend as far as I can tell), I have a PR in progress with the update (and some other schedule-related fixes I'm working on)

good, let me know when you're done

**Comment by raphael-batte** [comment]
Add more clear message UI to iCalAPI calendars. 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/102970268/201296324-1ecdd798-9c5b-4e53-90f8-2750d5c0833e.png">

**Comment by raphael-batte** [comment]
- [ ] List view. If user expands row, calendar widget isn't adopted per page width (it more than 1400 px wide).
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/102970268/201300536-6a1b047c-2f50-4c10-a8c6-29b5dad76942.png">

**Comment by raphael-batte** [comment]
- [ ] Long names fix. Two proposals - clear break or gradient
<img width="628" alt="image" src="https://user-images.githubusercontent.com/102970268/201302592-e0f16f10-613a-4cd2-b076-25ff7d0b3cb4.png">

**Comment by raphael-batte** [comment]
User presentation visual issues
- [ ] shift color border should be positioned to the center or outside parent shape (now it is inside and we can see artifacts)
![image](https://user-images.githubusercontent.com/102970268/202208908-e9d7b900-ef71-4b31-87a6-19df9757a82a.png)

- [ ] users outside working hours should be disabled visually. Example - Singapore users already outside their working hours but look similar to others.
![image](https://user-images.githubusercontent.com/102970268/202209043-badd9911-3a1c-4c72-991e-e1317de4293c.png)

**Comment by Matvey-Kuk** [comment]
Closing this due to agreement not to make it a permanently open issue. @raphael-batte please file separate issues 🙏
