### ISSUE TITLE
Alertmanager integration

### ISSUE THREAD

**Issue by dyvol777** [grafana/oncall#542]
Groping and resolving issues
My version: 1.0.35 (plugin and backend)

Behavior and how to reproduce:
1. Create new alertmanager integration.
2. send `curl -XPOST http://oncall-engine:8080/integrations/v1/alertmanager/xxx/ -H "Content-Type: application/json" -d @alert.txt` (json file with 3 firing [alert.txt](https://github.com/grafana/oncall/files/9608052/alert.txt))
3. Oncall create 3 firing alert groups. Alertmanager grouping is ignoring **_Bug_**
4. Send curl again  
5. Oncall will add one new alert to each group. _It would be greate to have some deduplication possibility_
6. Change status in one alert (not group) from firing to resolved and send curl again
7. One alert in oncall will be resolved. But in [doc](https://grafana.com/docs/grafana-cloud/oncall/integrations/available-integrations/add-alertmanager/#configure-grouping-with-alertmanager-and-grafana-oncall) `Grafana OnCall marks an incident as resolved only when the amount of grouped alerts with state resolved equals the amount of alerts with state firing`. But we had 2 firing and 1 resolved alert in this group. _**Bug or misdocumantation**_

**Comment by Konstantinov-Innokentii** [comment]
Fixed with release of the alertmanager v2.
