### ISSUE TITLE
grouping of alerts fails

### ISSUE THREAD

**Issue by Raja-Kadali-FW** [grafana/oncall#560]
Hi, 
Alert grouping fails for different payloads even though grouping id is given.

the following are two paylods for my formatted webhook integration:
payload:1
{
    "state": "firing",
    "title": "Test9",
    "host": "xyz",
    "level":"webhook-success",
    "message": "webhook-success",
    "databaseid": "db-1",
    "database name": "db1",
    "database endpoint":"host1:!234",
    "Account":"fd-stg",
    "image_url": "",
    "link_to_upstream_details": ""
}

payload 2:

{
    "state": "firing",
    "title": "Test9",
    "host": "xyz",
    "level":"",
    "message": "db down",
    "databaseid": "db-1",
    "database name": "db1",
    "database endpoint":"host1:!234",
    "Account":"fd-stg",
    "image_url": "",
    "link_to_upstream_details": ""
}

grouping id in template for alert behaviour is given as, {{ payload.host }}
<img width="614" alt="image" src="https://user-images.githubusercontent.com/108932632/192216633-8fc6f5c4-634b-47cd-83a1-aac5186a58fd.png">

but both the payloads gets into different alert groups.

I've also tried with {{payload.title}}

**Comment by Matvey-Kuk** [comment]
Hi! Thank yo for the report! 
1. Do you see the result of rendering of the "Grouping ID" template at the right? Is it working as expected?
2. Grouping of "firing" alerts happening only to "open" Alert Groups. "resolve" alerts may be grouped even to "resolved" Alert Groups. Are you sure the first Alert Group still was "open" at the moment you received the second one?

**Comment by Raja-Kadali-FW** [comment]
Hi Matvey,

Yes, the result of "grouping id" is showing the host value. also, i'm sending the alerts through postman and they are still open, but not getting grouped under same alert group.

**Comment by mderynck** [comment]
I had this condition recreated but for some reason now it is working as expected.  Going to need to collect more examples. 
@Raja-Kadali-FW Does the grouping work as expected for other integrations?

**Comment by Raja-Kadali-FW** [comment]
Hi @mderynck , For some reason, grouping is working fine now. I've checked with other integrations, they are working as expected.

**Comment by mderynck** [comment]
@Raja-Kadali-FW I think I understand what happened:
If the grouping template changes it does not effect already open alert groups since the grouping id was set we don't want to re-process alerts that potentially become un-grouped. So if like me you sent an alert noticed you wanted a different grouping and then sent another it will not group with already existing groups even if logically it should.

So the behavior is intentional and we should display a message if the grouping template is changed while there are open groups.
