### ISSUE TITLE
Allow users / admins to view teams they are not members of

### ISSUE THREAD

**Issue by chrisharbro** [grafana/oncall#569]
As OnCall is currently implemented, users (including admins) can only see teams which they are a member of. In the top-right corner of the OnCall page, the "Select team" filter only allows you to view the teams you are a member or admin of, as well as the "General" option which shows everybody; there is no option for filtering by specific teams that you are not currently a member of. 

If a user / admin did not want to see certain teams, perhaps they could have some way of including/excluding certain teams from their dropdown, that way they have the option to view any team without modifying their own team membership, but they could also keep their dropdown clear of clutter.

**Comment by joeyorlando** [comment]
Closing as this should now be possible by going to the Settings page, followed by the "Teams and Access Settings" tab, then configuring to your needs:
<img width="679" alt="Screenshot 2024-03-06 at 07 24 26" src="https://github.com/grafana/oncall/assets/9406895/f6db9c34-ad02-4c9f-9df7-1c469446ecab">
