### ISSUE TITLE
Slack thread not displaying escalation plan

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#574]
While the alert group is unacknowledged and processing escalation steps the slack thread is not being updated and is displaying this:
![Screenshot from 2022-09-28 07-17-17](https://user-images.githubusercontent.com/28077050/192790344-d275eca3-d339-49b6-a971-04669dd6335d.png)

Meanwhile viewing the alert group in the web UI the following actions were taken:
![Screenshot from 2022-09-28 07-18-02](https://user-images.githubusercontent.com/28077050/192790777-8c1508a3-7689-4b9b-808d-fbd7ef2d89df.png)

After I acknowledged the alert group the alert group log rendered in slack.
Expected behavior is for the alert group log to be displayed regardless of alert group state so others viewing the thread can see what is happening.

**Comment by Matvey-Kuk** [comment]
I think there is either a stuck celery task, either a Slack API problems. Could you please try finding logs? They should be helpful
