### ISSUE TITLE
Trigger alerts ON/OFF via Email

### ISSUE THREAD

**Issue by MrBosley** [grafana/oncall#575]
Some devices we monitor don't have the ability to communicate with more modern methods.  It would be nice if OnCall could ingest email and trigger based off of that email and relay the information through an alert.

**Comment by DavidKittleSEL** [comment]
This feature is critical to many of our alerting workflows as well.

**Comment by Matvey-Kuk** [comment]
This issue moved to the core team's backlog

**Comment by Konstantinov-Innokentii** [comment]
@MrBosley, @DavidKittleSEL  We released inbound email integration both for cloud and OSS, thanks for your issue! Here is the docs https://grafana.com/docs/oncall/latest/integrations/available-integrations/configure-inbound-email/
