### ISSUE TITLE
bug: All day events show as having gaps in slack notifications

### ISSUE THREAD

**Issue by Bruno-DaSilva** [grafana/oncall#576]
# Description
Multiple all-day events in a row in the calendar are reported as having a gap in slack notifications. 

NOTE: I don't know if other parts of OnCall also have issues with all-day events. I'll leave that up to someone else to figure out. We're going to use 12:00am-12:00am events instead just in case there actually _is_ a bugged gap and people aren't going to be routed to properly.

# Steps to reproduce
1. setup a schedule connected to a google calendar. Ensure that notifications are going to a slack channel for each shift change.
2. create two all-day events, one occurring after the other -- in screenshots below I did one per week ending saturday and starting sunday.
3. Wait for the 10 min notify job to run, then observe in the slack channel it says "XXX is on call now, No one on-call next!"

## Expected result
The slack channel notification should say "XXX is on call now, YYY is on-call next."

# Versions
(Grafana Cloud)
Grafana v9.1.5-0100a6a (0100a6aa96)
OnCall r21-v1.0.37

# Screenshots
<img width="1079" alt="Screen Shot 2022-09-28 at 5 08 21 PM" src="https://user-images.githubusercontent.com/8520801/192901318-281055d6-290d-48e4-a0dc-5d4f14d8cc1b.png">
<img width="1114" alt="Screen Shot 2022-09-28 at 5 08 04 PM" src="https://user-images.githubusercontent.com/8520801/192901316-2b063ddc-94f0-4e3f-b01c-9be4033d6e8f.png">
<img width="650" alt="Screen Shot 2022-09-28 at 5 08 58 PM" src="https://user-images.githubusercontent.com/8520801/192901885-902153d5-14b7-4680-8c5d-f1895f8c7fa4.png">
<img width="792" alt="Screen Shot 2022-09-28 at 5 10 37 PM" src="https://user-images.githubusercontent.com/8520801/192901964-f9dab086-0ef8-4518-acb3-a2c40b032b20.png">

**Comment by devinrcheevers** [comment]
Thank you, looking into this!

**Comment by Bruno-DaSilva** [comment]
Hi @matiasb. I tried a few things, thinking it was caching. I tried both creating events before and after linking it to a schedule.  I get the same notification about the "No one on call next!" (like the above screenshot) whenever any update happens to the calendar, but have not yet received the separate/dedicated notification about gaps in the schedule.
