### ISSUE TITLE
query alertgroup api for alert information by alert_group_id

### ISSUE THREAD

**Issue by sdg4754** [grafana/oncall#580]
Route ID and Integration ID can be used to search/filter responses to the Get requests to the AlertGroups API; I would like to do so with the alert_group_id fed out by the Alerts API, to instantly get my alert's status programmatically.  Thank you

**Comment by Matvey-Kuk** [comment]
That's already possible, just checked with `../oncall/api/v1/alerts/?alert_group_id=IQ77F48CNJJW5`. Also mentioned in docs: https://grafana.com/docs/oncall/latest/oncall-api-reference/alerts/
