### ISSUE TITLE
Bug: List OnCall Shifts API Endpoint Returns 404

### ISSUE THREAD

**Issue by sdg4754** [grafana/oncall#581]
curl "https://oncall-prod-us-central-0.grafana.net/oncall/api/v1/users/" \
  --request GET \
  --header "Authorization: {redacted}" \
  --header "Content-Type: application/json"

...gives a 404

**Comment by matiasb** [comment]
Hi,

You mention the oncall shifts endpoint in the title but refer to the users API in the description. In any case, I was just checking both endpoints and they seem to work as expected (also, list endpoints will usually return a payload with empty results instead of a 404).
Let us know if you have any more details to understand your issue.

**Comment by sdg4754** [comment]
Hi, thank you – you can close this out.





David G. Schultz
Manager of Workplace Infrastructure
***@***.***
o+1 646-930-4754
tassat.com
CONFIDENTIALITY NOTICE
THE INFORMATION CONTAINED IN THIS COMMUNICATION IS INTENDED FOR THE NAMED RECEIVER ONLY. THE TRANSMISSION MAY CONTAIN PRIVILEGED AND CONFIDENTIAL MATERIAL. IF YOU ARE NOT THE NAMED RECIPIENT, PLEASE BE ADVISED THAT ANY USE, DISSEMINATION OR UNAUTHORIZED COPYING OF THE MATERIAL IS STRICTLY PROHIBITED. IF YOU HAVE RECEIVED THIS TRANSMISSION IN ERROR, PLEASE NOTIFY ***@***.*** AND DESTROY THE RECEIVED COPY. THANK YOU.
​
v112620
From: Matias Bordese ***@***.***>
Date: Friday, September 30, 2022 at 8:49 AM
To: grafana/oncall ***@***.***>
Cc: David G. Schultz ***@***.***>, Author ***@***.***>
Subject: Re: [grafana/oncall] Bug: List OnCall Shifts API Endpoint Returns 404 (Issue #581)
Hi, You mention the oncall shifts endpoint in the title but refer to the users API in the description. In any case, I was just checking both endpoints and they seem to work as expected (also, list endpoints will usually return a payload with
ZjQcmQRYFpfptBannerStart
This Message Is From an Untrusted Sender
You have not previously corresponded with this sender.
ZjQcmQRYFpfptBannerEnd

Hi,

You mention the oncall shifts endpoint in the title but refer to the users API in the description. In any case, I was just checking both endpoints and they seem to work as expected (also, list endpoints will usually return a payload with empty results instead of a 404).
Let us know if you have any more details to understand your issue.
