### ISSUE TITLE
OnCall installation on Bare-metal

### ISSUE THREAD

**Issue by jnunezgts** [grafana/oncall#584]
### Discussed in https://github.com/grafana/oncall/discussions/583

<div type='discussions-op-text'>

<sup>Originally posted by **jnunezgts** September 30, 2022</sup>
Hello all,

There are plans to write a guide to do a installation on bare-metal servers; Many of us already have separate instances running Redis, MySQL, RabitMQ and Grafana (loaded with plugins) and existing production for K8s is also an all-included setup.

Right now I'm checking how the full installation is done from the 'hobby' Docker compose file as it is easier to digest.

The product looks very complete feature wise, please keep the good work!
</div>

**Comment by Matvey-Kuk** [comment]
Looks like a few people are going through such a path and using docker-compose as a reference for bare metal installation. If one would like to build an instruction, I could suggest adding it as one of paragraphs to https://grafana.com/docs/grafana-cloud/oncall/open-source/

**Comment by jnunezgts** [comment]
Will work on that, seems “almost” like a 1:1 mapping. First I need to get it work on bare-metal :-D

**Comment by Matvey-Kuk** [comment]
@jnunezgts sounds great, thank you!

**Comment by salarali** [comment]
Did you make any progress towards this?
