### ISSUE TITLE
Unable to create new schedule

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#593]
![image](https://user-images.githubusercontent.com/28077050/193369985-9a9a85cb-d21e-4ceb-81e0-d0114af136ad.png)

This seems to be an issue in the plugin as switching to 1.0.37 from 1.0.38 restored the correct behavior.
Also note the issue does not occur on instances with the feature flag enabled for the new schedules.

**Comment by teodosii** [comment]
Fixed and merged to `dev`
