### ISSUE TITLE
DNS resolution for Outgoing Webhooks is inconsistent for local vs. public DNS servers

### ISSUE THREAD

**Issue by scubbo** [grafana/oncall#594]
Webhook calls fail when the webhook has a URL which uses a domain name that is resolved via either a) Kubernetes' [DNS-for-services](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/), or b) a LAN's DNS server (i.e. not a DNS server on the public internet). This is despite the fact that `wget` and `nslookup` calls from the Oncall Engine pod to both local types of DNS name (Kubernetes-defined and LAN-DNS-server defined) succeed. Resolution of a publicly-defined DNS name succeeds and the webhook payload is delivered.

Fuller write-up and replication steps [here](https://github.com/scubbo/grafana-oncall-dns-issue).

I have not tested on a non-Kubernetes Oncall instance, but would be happy to do so if you think that's a fruitful area of investigation.

**Comment by scubbo** [comment]
Wow, I'm embarrassed - Oncall has a `DANGEROUS_WEBHOOKS_ENABLED` environment variable, with description "_Enable outgoing webhooks to private networks_" (which defaults to `false`). I haven't tested yet, but depending on this definition of "private", that might very well be intentional behaviour that causes this "issue".

**Comment by scubbo** [comment]
From [here](https://github.com/grafana/oncall/blob/4412ae52d20abc35476c9ca151869d0ba105489c/engine/apps/alerts/utils.py#L47-L65) to [here](https://github.com/python/cpython/blob/d04899abb0da4cc7c0a390f5bc52d57ace8955fd/Lib/ipaddress.py#L1325-L1333) to [here](https://github.com/python/cpython/blob/d04899abb0da4cc7c0a390f5bc52d57ace8955fd/Lib/ipaddress.py#L1541-L1556), it looks pretty dang likely that that's the case. Whoops!

**Comment by scubbo** [comment]
More specifically - it doesn't actually matter whether _which_ DNS server resolves the IP address (as I originally thought), rather it just matters whether the IP address is in in a block demarcated as private.

**Comment by Matvey-Kuk** [comment]
@scubbo thank you for checking this issue anyway, happy "DANGEROUS_WEBHOOKS_ENABLED" helped :)
