### ISSUE TITLE
Customizable columns at the incidents page

### ISSUE THREAD

**Issue by tommysitehost** [grafana/oncall#597]
Hey there,

It would be good to be able to customise the incidents page so I can add/remove columns, change the color of the alert status by its severity etc so that the oncall person can easily/quickly differentiate the severity of the alerts at the first glance.

**Comment by kirpozh** [comment]
+++ I really need this thing, for example, if you integrate message from Zabbix you can display the severity level in the Alert message, but I lack the ability to parse this metric from the body of the sent mail in OnCall and display it in the appropriate color depending on the severity level.

**Comment by houstonheat** [comment]
Same as https://github.com/grafana/oncall/issues/667#issuecomment-1743882188
+1

**Comment by iskhakov** [comment]
done
