### ISSUE TITLE
Make Slack acknowledgement reminder team-specific

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#61]
Now it's slack-wide, it makes sense to make it team-specific.

<img width="1010" alt="Screenshot 2022-06-14 at 15 56 56" src="https://user-images.githubusercontent.com/3284841/173582451-2cbd0649-8e3d-451b-8b1c-b4af38047f15.png">

**Comment by Matvey-Kuk** [comment]
1

**Comment by Matvey-Kuk** [comment]
1

**Comment by iskhakov** [comment]
closing in favour of https://github.com/grafana/oncall/issues/3870
