### ISSUE TITLE
Docs file restructure 

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#612]
Restructure the OnCall doc files to align with the documentation teams information architecture best practice and the website repos publishing pipeline. This restructure will also align the OnCall docs with the Incident docs for consistency.

The new structure organizes all docs into directories. For example:
- Top-level directory --> Grafana OnCall (_index.md)
        - Parent directory --> Connect ChatOps (_index.md)
                 - Child directory --> Slack integration (index.md)

- [ ] Create a parent directory with an _index.md file for all OnCall TOC sections
- [ ] Create child directories with index.md files for each topic nested in a parent directory
- [ ] Provide new doc titles for consistency and easier scanability.

Proposed structure and titles:
![Screen Shot 2022-10-04 at 3 37 29 PM](https://user-images.githubusercontent.com/101596687/193935139-b41f7df7-21d3-448f-a261-4406d85eb78b.png)

**Comment by Matvey-Kuk** [comment]
@alyssawada this structure looks great for me, thank you for sharing! 

We rely heavily on such links within our product:
- https://grafana.com/docs/oncall/latest/open-source/
- https://grafana.com/docs/oncall/latest/open-source/#production-environment
- https://grafana.com/docs/oncall/latest/open-source/#slack-setup
- https://grafana.com/docs/oncall/latest/open-source/#telegram-setup
- https://grafana.com/docs/oncall/latest/open-source/#twilio-setup

Will those links remain the same after structure update? If no, no worries. We just need to make an update to the product's source code before we roll new links.

**Comment by alyssawada** [comment]
Thanks @Matvey-Kuk! 

The URLs will remain the same, so there should be no impact on any in-product links. I'll make a note to validate those before merging.
