### ISSUE TITLE
Move ENV variables from the tab to chat-ops tab for Telegram, Slack

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#626]
It is more user friendly, if we will have interface to fill all ENV variables at the same page where we are configuring chat ops

(We need to have backend for the part where we save environment because for now we do not have this functionality to save all parameters in the same time )

**Comment by raphael-batte** [comment]
Will be good to link relevant ENV var rows with ChatOps setup UI but centralized table for ENVs IMO should remains.

**Comment by Matvey-Kuk** [comment]
ENV variables are configured by a tech person who is performing initial setup of Chatops and other parts of OnCall. I don't think we need to "blend" ENV variables setup between different pages. Moreover I think it will reduce usability for initial configuration. We could probably link to ENV page better if you find users being stuck at this step.

**Comment by Matvey-Kuk** [comment]
I don't think we should build this, closing.
