### ISSUE TITLE
Add id parameter to url to access chat-ops directly

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#627]
We do not have the functionality to send a link to specific chat-ops, for example if we want to share the Telegram page.

The same is for USer personal settings, we need to add id to the tab in personal chat-ops

**Comment by Matvey-Kuk** [comment]
@Ukochka could you please check if it's still actual task?

**Comment by joeyorlando** [comment]
closing (issue was moved from "In Progress" to "Done" in the Grafana OnCall project board)
