### ISSUE TITLE
Resolving incidents from slack throws 404

### ISSUE THREAD

**Issue by libracoder** [grafana/oncall#631]
I have installed istio using helm and i also use istio as a service mesh

For some reason every other route goes through except the route below
https://<ONCALL_ENGINE_PUBLIC_URL>/slack/****** (which includes https://<ONCALL_ENGINE_PUBLIC_URL>/slack/interactive_api_endpoint/

It always throws 404, is there a specific configurationf for isito that i dont know about

**Comment by MaxDiOrio** [comment]
@libracoder  - did you ever figure this out?  I'm having the same thing happen on both /slack/interactive_api_endpoint/ and /slack/event_api_endpoint/

**Comment by MaxDiOrio** [comment]
Never mind - I figured it out.  The Slack integration was disabled in the helm chart, so the endpoints were never created.  Updated the helm chart and all good now.
