### ISSUE TITLE
😉 Insight: how to enable new calendar UI

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#632]
Follow this link to check the demo: https://youtu.be/o9HkQLrBbtE?t=1393

Env variable:
```
FEATURE_WEB_SCHEDULES_ENABLED=True
```

This is Alpha version of our new calendar UI. Please let us know about any bugs/problems in the GH issues!

**Comment by octoshikari** [comment]
@Matvey-Kuk Good day! For alpha version i can only create schedule managed by Grafana Oncall or i can import from existing calendar? We try import from existing but it just close form after click on save button
