### ISSUE TITLE
Better support for non-continuous shift schedules

### ISSUE THREAD

**Issue by andy-paine-numan** [grafana/oncall#633]
We have some schedules that we would only like to be Monday-Friday, 9am-5pm as they are for non-urgent issues. We assign someone to these shifts for each working day (rather than one person for the whole week) which seems impossible to represent with the current `rolling_users` shift type as a daily rotation cannot be filtered with `by_day`.

In addition to this, we get Slack notifications for shifts that are unfilled between 5pm-9am that we do not intend to fill which creates a bit of unnecessary noise.

The rolling users shifts and Slack integration work extremely well otherwise so we would love the extra flexibility for this use case

**Comment by raphael-batte** [comment]
Our upcoming calendar will have this rotation type.

**Comment by iskhakov** [comment]
closing as this is implemented
