### ISSUE TITLE
Post Json Data via webhooks

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#638]
Hello I define a webhooks for rocketchat and i want to post data to.
bet there is an extra validation in backend code that prevent me to send data
the problem is in this file:
engine/apps/api/serializers/custom_button.py
in validate_data method

this is my data that i want to send in post request:
```
{
   "receiver":"rocketchat-default",
   "status":"firing",
   "alerts":[
      {
         "status":"firing",
         "labels": {{ alert_payload.labels }},
         "annotations": {"description": "This alert was sent by user for the demonstration purposes"},
         "startsAt":"{{ alert_payload.startsAt }}",
         "endsAt":"{{ alert_payload.endsAt }}",
         "generatorURL":"{{ alert_payload.generatorURL }}"
      }
   ],
   "commonAnnotations":{
      "description":"{{ alert_payload.annotations.description }}",
      "summary":"{{ alert_group_id }}"
   },
   "externalURL":"http://vmalertmanager-darkube-alertmanager-0:9093"
}
```

I want to send a json dict for labels in alert body but i cant

```
 "labels": {{ alert_payload.labels }},

```

if i comment json.loads(data) in mentioned method the problem has been solved

**Comment by Matvey-Kuk** [comment]
@vadimkerr I see the PR is merged, smth is missing to close this issue?

**Comment by Matvey-Kuk** [comment]
@vadimkerr I think it's ok to close the issue once the PR is merged
