### ISSUE TITLE
Add "uptime" native integration templates

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#64]
Looks like nice OSS monitoring tool, do we need native support for alerts from it? 

https://github.com/fzaninotto/uptime

Btw native integrations are stored here: https://github.com/grafana/oncall/tree/dev/engine/config_integrations

**Comment by SiM22** [comment]
Instead of uptime. Maybe uptime-kuma. It is actively developed

**Comment by Matvey-Kuk** [comment]
@SiM22 noce idea!

**Comment by Matvey-Kuk** [comment]
#112
