### ISSUE TITLE
Continue escalation if < X alerts per Y minutes

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#654]
Hi.
I want to implement this step: "Continue escalation if < X alerts per Y minutes!!!"
sometimes it may i have hundreds of alerts in one minute and in that case i want to pause escalation
how i can do this?

**Comment by Matvey-Kuk** [comment]
Hi! Sounds like a good candidate for a feature request. May be implemented using "Continue escalation if > X alerts per Y minutes" as a reference.

**Comment by joeyorlando** [comment]
@paneda1998 do you have a concrete example of where this would be useful?

For example, if you set this up to "Continue escalation if < 5 alerts per 5 minutes", what would this solve? As @Matvey-Kuk mentioned, couldn't this be solved via "Continue escalation if > X alerts per Y minutes"?
