### ISSUE TITLE
Fit OnCall UI to new Grafana navigation

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#657]
- [x] Add new UI layout if Grafana instance has new nav variable. Old Grafana versions will look as is
- [x] Remove main tab section
- [ ] Remove logo and version from all the pages except */grafana-oncall-app/
- [x] Add 24 px page headline to all internal pages
- [x] Transform vertical subsection tabs inside pages (example, ChatOps) to row tab groups

**Comment by mderynck** [comment]
Adding note here to restore the Team selector drop down which disappeared with the new navigation.
