### ISSUE TITLE
Complex search by tags

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#667]
Hi i want to filter alerts based on some labels for example "severity" and ...

https://github.com/grafana/oncall/issues/667#tasklist-block-6e4e3d4e-ae49-4e3c-b459-f90d4d98293e

**Comment by Matvey-Kuk** [comment]
Hi! It's doable using search field in the Alert Group list. Search works using "title" so if you would like to search using specific field, I suggest rendering this field in the Title template in the Integration settings.

**Comment by dmitry-tiger** [comment]
>Hi! It's doable using search field in the Alert Group list. Search works using "title" so if you would like to search using specific field, I suggest rendering this field in the Title template in the Integration settings.

What about possibility to filter by two labels or nested logic, doing that requires very complex regex, also it in not guaranteed that labels will be in one order

IMHO the best approach is using nested logical constructor like
(label1 == smth AND label2 !~ .+smth|smth) OR ( label3 != smth) 
or json paths instead labels for json objects
(.payload.labels.severity == smth AND .payload.labels.status !~ .+smth|smth) OR ( .payload.annotations.runbook != smth)

**Comment by romanskugarevLMRU** [comment]
+1, cool feature for use analytics

**Comment by altokarev** [comment]
+1

Moreover, if such search inputs would be able to save as custom named presets - it would be great!

**Comment by houstonheat** [comment]
Yep, lookup by tags/payload is essential for alert management
+1

**Comment by iskhakov** [comment]
searching by labels is implemented
