### ISSUE TITLE
plugin didn't rewrite url path resources

### ISSUE THREAD

**Issue by wounkun** [grafana/oncall#672]
![image](https://user-images.githubusercontent.com/34368014/196709739-cfa72ae7-6484-4b51-a5f8-ff32a85c0fcc.png)

I got a problem on grafana that reversed by nginx which has different root url, example: %(protocol)s://%(domain)s/grafana/. Plugin page opening CSS-file with incorrect url path:

https://host/grafana/public/plugins/grafana-oncall-app/img/grafanaGlobalStyles.css

**Comment by teodosii** [comment]
Opened a PR here https://github.com/grafana/oncall/pull/1348

This will most likely fix this issue as now we will no longer import by path, instead append the whole css to the `head` element.
