### ISSUE TITLE
Docker-compose - Using rabbitmq version from 2 years ago.

### ISSUE THREAD

**Issue by acr-varonis** [grafana/oncall#695]
Hi Everyone,
This issue is both a question and a suggestion.
Looks like the example in the docker-compose file (see below) is using [rabbitmq:3.7.15-management](https://hub.docker.com/layers/library/rabbitmq/3.7.15-management/images/sha256-b00ca90bc3ae85867317ab624ee476bd5d8d2a19f9ccc414e5baf685c770120d?context=explore) which is a 3 year old version (see attached screenshot).

I was wondering if the rabbitmq version can be replaced with 3.11 and if it can be we should update the tag to [3.11-management](https://hub.docker.com/layers/library/rabbitmq/3.11-management/images/sha256-72a686d14b4869a1c02fa8675a711a99b64ae894258b0f135b2d0e5bf7972985?context=explore) which is 5 days old and will automatically update with newer 3.11.x versions.

Thank you !

https://github.com/grafana/oncall/blob/7cc01e0585d5e9dd9a4f6195212832c41d12e5e9/docker-compose.yml#L102-L104

![image](https://user-images.githubusercontent.com/40654885/197499671-ad97e703-68a0-4b06-bbac-8f58451ff89c.png)

**Comment by roock** [comment]
Also the Grafana Image uses an old outdated and beta version container image tag 😞

**Comment by PhantomPhreak** [comment]
Switched to `3.11-management` for my installations and it works fine

**Comment by Matvey-Kuk** [comment]
The team is working on updating RabbitMQ which includes a lot of testing, thank you for the request!
