### ISSUE TITLE
Introduce mypy to the codebase

### ISSUE THREAD

**Issue by vadimkerr** [grafana/oncall#700]
The repo could benefit from introducing [mypy](https://mypy.readthedocs.io/en/stable/), at least for the parts of the codebase that already have type annotations. 
This would also require adding a new CI step for mypy.

**Comment by sergeyshevch** [comment]
I also can suggest you to look on https://github.com/typeddjango/django-stubs for proper typings

**Comment by joeyorlando** [comment]
@vadimkerr great minds think a like. I added #2168 as the "master" parent issue to track all of the subtasks required to fully implement `mypy`. 

#2151 added it as a CI job and started fixing a few pre-existing errors. I'll close this issue and we can use #2168 to track this.
