### ISSUE TITLE
Investigate/fix check_escalation_finished_task

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#724]
check_escalation_finished_task is one of the reet mechanisms to check if escalations executed for all tasks properly. We noticed this thing didn't work right in one of our environments. I suggest checking the full path:
1) If it's working properly
2) If we receive alert based on it's failure.
3) Why we didn't receive alert during "#incident-2022-10-25-metamonitoring-chain-is-broken".

**Comment by Matvey-Kuk** [comment]
I propose it to be taken by @iskhakov but feel free to adjust

**Comment by Konstantinov-Innokentii** [comment]
check_escalation_finished_task  is disabled, since it produce a db query too long to execute.

**Comment by Matvey-Kuk** [comment]
Reassigning to @joeyorlando

**Comment by joeyorlando** [comment]
@Matvey-Kuk can we close this in favour of https://github.com/grafana/oncall-private/issues/1713? There's more context in that issue wrt to the latest issue.

**Comment by Matvey-Kuk** [comment]
@joeyorlando I would prefer keeping this one open since it's public.

**Comment by joeyorlando** [comment]
going to close this out in favour of https://github.com/grafana/oncall-private/issues/2028
