### ISSUE TITLE
Feature Request: Schedules Alpha - Repeat shifts every X business days

### ISSUE THREAD

**Issue by BojanOro** [grafana/oncall#733]
Hey folks, wondering if there is any appetite in being able to define on call schedules for X *business* days (in most cases, Monday - Friday, but perhaps this is a custom definition for other orgs). 

In our organization, we use an "on call" rotation as part of our business hours support team and we will only assign team members to this role for 2 days a time Monday - Friday. This gives the team a break from dealing with end user support for an entire week 😅

**Comment by Matvey-Kuk** [comment]
@BojanOro do you mean such an option? 
<img width="444" alt="Screenshot 2022-11-08 at 18 49 24" src="https://user-images.githubusercontent.com/3284841/200625925-8ef7447e-6a87-43c7-8daf-0b4bccfc6d68.png">

**Comment by BojanOro** [comment]
I don't think so @Matvey-Kuk . 

Imagine I have 3 on call engineers, and they are on call for 2 business days at a time. 

```
M | T | W | T | F
------------------
1   1   2   2   3
3   1   1   2   2
3   3   1   1   2
2   3   3   1   1
```

Is that doable in with that UI? I don't _quite_ understand the relationships between rotations, parent shifts, and groups 😅

**Comment by Matvey-Kuk** [comment]
@BojanOro I see! Pretty tricky case :) 

The closest solution which comes to my mind is to create 2-day long "parent event" and rotate every 2 days. The only problem: it will not "jump" over weekends as you expect.


<img width="439" alt="Screenshot 2022-11-09 at 14 19 42" src="https://user-images.githubusercontent.com/3284841/200829181-deb06e64-2d9e-4c30-a69d-1586fbf02fb3.png">

**Comment by matiasb** [comment]
Hey!

The PR referred above (already merged, will be deployed soon) should help with your scenario, allowing you to define exactly that:

![custom-daily](https://user-images.githubusercontent.com/260710/200835397-c70b653f-e5c6-4d6a-8679-448ceef75c04.png)


Selecting a daily shift, with custom selected days and a repeat value, you can define what you want, if I understood correctly :-)
Let us know!

**Comment by Matvey-Kuk** [comment]
@matiasb I didn't notice this trick! WOW!
