### ISSUE TITLE
docker-compose-developer-pg dockerfile fails to launch grafana service

### ISSUE THREAD

**Issue by tinvaan** [grafana/oncall#745]
Just noticed that the `docker-compose-developer-pg.yml` script fails to launch the grafana service on 0.0.0.0:3000, possible cause could be a mysql connection timeout?

```
logger=settings t=2022-11-01T09:27:13.398949132Z level=info msg="App mode production"
logger=sqlstore t=2022-11-01T09:27:13.398992299Z level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2022-11-01T09:27:23.412269887Z level=error msg="alert migration failure: could not get migration log" error="failed to check table existence: dial tcp: lookup mysql on 127.0.0.11:53: read udp 127.0.0.1:36350->127.0.0.11:53: i/o timeout"
logger=settings t=2022-11-01T09:27:24.013934471Z level=info msg="Starting Grafana" version=9.3.0-86077pre commit=61774ae7f1 branch=main compiled=2022-10-28T21:57:56Z
```
As the service isn't running, trying to dev is unable to access grafana dashboard on localhost:3000.  (ERR_EMPTY_RESPONSE)

More: https://grafana.slack.com/archives/C02LSUUSE2G/p1667108304376529

**Comment by iskhakov** [comment]
`mysql-to-create-grafana-db` and `grafana` services depend on `mysql` service, we need to change them to postgresql
