### ISSUE TITLE
Modify color pallet to use proper grafana orange color

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#768]
We should update the `--warning-text-color` (defined [here](https://github.com/grafana/oncall/blob/dev/grafana-plugin/src/style/vars.css#L29) and [here](https://github.com/grafana/oncall/blob/dev/grafana-plugin/src/style/vars.css#L57)) to use basic Grafana Orange (`rgb(255, 120, 10)`). 

See [this PR comment](https://github.com/grafana/oncall/pull/635#discussion_r1008112227) for more reference.

**Comment by felipebpl** [comment]
Hi @joeyorlando Can I be asigned to this issue?

**Comment by joeyorlando** [comment]
closing this issue as it looks like this was addressed in #790
