### ISSUE TITLE
Not enough permission to see list of users if you access the page via direct link

### ISSUE THREAD

**Issue by Ukochka** [grafana/oncall#779]
User is admin and has access to see fulll list of users at OnCall
But if user follows the link to users for example https://ops.grafana.net/a/grafana-oncall-app/?page=users the message appears: "You don't have enough permissions to view other users because you are not Admin."

If you go to another tab and come back - all users are displaying

**Comment by Matvey-Kuk** [comment]
Just faced this bug, nice catch!

**Comment by Ukochka** [comment]
It is not reproducible anymore
