### ISSUE TITLE
Add postgresql support

### ISSUE THREAD

**Issue by sergeyshevch** [grafana/oncall#80]
As Django is used in the core of oncall. It will be perfect for adding the ability to use PostgreSQL as the optional database engine. 

For example, some teams prefer PostgreSQL over MySQL or already have production-ready PostgreSQL clusters.

**Comment by Konstantinov-Innokentii** [comment]
Hey, thanks for the feedback, we are planning to extend list of supported databases and give opportunity to connect to the existing db servers.

**Comment by Matvey-Kuk** [comment]
We added this task to the core team's backlog. @matiasb and @Konstantinov-Innokentii will work on it.

**Comment by sergeyshevch** [comment]
@matiasb @Konstantinov-Innokentii Can you give us any estimates about it? This issue can prevent multiple companies from testing and adopting grafana oncall. For example, we want to try it and have grafana set up on PostgreSQL. 
But we have no MySQL databases in our company and we don't want to set up it only for oncall

**Comment by matiasb** [comment]
hey @sergeyshevch, there is a [WIP branch](https://github.com/grafana/oncall/pull/211/) where I have been doing some initial work. There are still a few decisions to be made on how we should document/how much support should be provided, but it would be great to read if you have any thoughts about that.

**Comment by sergeyshevch** [comment]
@matiasb It looks great! I also guess that we need to ensure that no MySQL or PgSQL-specific fields will be used in the code. Or they have API compatible alternatives

**Comment by DavidSpek** [comment]
I believe this issue can be closed since https://github.com/grafana/oncall/pull/660 was merged which solved the problems with using PostgreSQL. I'm using PostgreSQL in combination with the helm changes from https://github.com/grafana/oncall/pull/661 and the Zalando operator for a production setup (the built-in postgres in the chart also works).
