### ISSUE TITLE
Best practice for exporting and reimporting entities 

### ISSUE THREAD

**Issue by jascott1** [grafana/oncall#807]
After exporting entities such as escalation chains and policies, and trying to re-import, I realized that the IDs of the objects from backup are ignored and a new IDs are created on POST. It appears I will have to import and escalation chain, get its new ID and then override that on the fly when importing an escalation policy (for example). This is in contrast to Grafana API which uses UIDs to preserve identity for most items. Is there documentation for exporting / importing a working set of entities for Oncall via HTTP API?

**Comment by Matvey-Kuk** [comment]
Hi! The best practice of doing this is to keep configuration in Terraform, so dynamic ID's shouldn't be a problem: https://grafana.com/blog/2022/08/29/get-started-with-grafana-oncall-and-terraform/

**Comment by jascott1** [comment]
@Matvey-Kuk Thanks for the suggestion! We don't use Terraform but it is good to know that it is an option. I will probably just hack something for our simple needs.

**Comment by Matvey-Kuk** [comment]
@jascott1 would appreciate if you share once you have smth! Thank you!
