### ISSUE TITLE
UI speedup

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#816]
1) Measure UI performance (including requests to backend) using https://grafana.com/oss/faro/
2) Share graphs & stats with OnCall team
3) Optimize Frontend Requests
4) Optimize backend performance

**Comment by dinhdobathi1992** [comment]
hi guys, please help to check this problem soon, we are getting the problem with UI speed, it's too slow and sometime become crashed.

**Comment by Matvey-Kuk** [comment]
A lot of details about initial startup in #1024

**Comment by teodosii** [comment]
Here's a dashboard (still in progress though) on Faro visualizations - it summaries a few endpoints for now. Unfortunately more than computing `min`, `max` and `average` time for requests doesn't seem to be yet possible - if anyone has more experience querying the traces I'd appreciate any sort of help.
