### ISSUE TITLE
Schedules: create a view of my oncall shifts

### ISSUE THREAD

**Issue by colega** [grafana/oncall#829]
Hi, as an oncall engineer I need to have a response to three main questions:
- When is my next shift (and for what rotation it is?)
- What my future shift calendar looks like (I'm in the primary rotation this week, secondary next week, deployments in December, etc.)
- How the a schedule for a given rotation looks like, to know who I can ask for a trade: this is something already answered by the brand new schedule view on the web, thanks).

Currently, if I export my personal iCal, it is similar to what I'm asking for except that when I look at it:
![image](https://user-images.githubusercontent.com/1511481/201151178-23000952-92cb-46ba-9b0f-17a93a32f6a4.png)

- I am unable to say what kind of shift is that (am I secondary? primary? dev rollouts? prod rollouts?)
- I can't trust it, because it also shows the shifts which I'm already overridden for, like that Saturday (there's a second override, and I'm not oncall)

**Comment by matiasb** [comment]
Personal ical export now only includes final shifts information (so, if a shift was overriden, it won't be added to the export). There is also information about the schedule name from which a shift is coming.

There is some initial view of upcoming shifts in the mobile app, and there are plans to implement something similar for the web UI.

**Comment by colega** [comment]
Thank you for this, @matiasb
