### ISSUE TITLE
Enable New Schedule UI

### ISSUE THREAD

**Issue by dinhdobathi1992** [grafana/oncall#832]
I see we have a new schedule UI from version `1.0.52` and `1.1.0` but the `Chart.yaml` file still have `appVersion: "v1.0.51"` 
so it used the old container 6days ago. 
I tried with them but cannot see the new UI yet, do I need to do anything to enable the new UI? 
 i also  checked your docker hub and we have new image with tag `v1.1.0` 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/67835317/201280333-d4b4446f-9b5d-4140-aa60-09cd6093d656.png">

**Comment by iskhakov** [comment]
the chart is updated too, thank you for the report!
