### ISSUE TITLE
OnCall bot doesn't show warning pop-up on slash command for disconnected user in Slack

### ISSUE THREAD

**Issue by Ferril** [grafana/oncall#835]
If user with disconnected slack account tries to use `/oncall` slash command in Slack, they see error "dispatch_failed"
<img width="396" alt="Screenshot 2022-11-01 at 08 36 58" src="https://user-images.githubusercontent.com/22730923/201315862-b3d50e80-2200-4d76-b7d5-1b8951e1972f.png">

instead of OnCall warning pop-up
<img width="514" alt="Screenshot 2022-11-11 at 11 04 11" src="https://user-images.githubusercontent.com/22730923/201316919-bf5d6b76-02b8-4af1-96dc-9adca524aa72.png">

**Comment by Konstantinov-Innokentii** [comment]
Fixed
