### ISSUE TITLE
Have to re-config the plugin after redeploy by helm

### ISSUE THREAD

**Issue by dinhdobathi1992** [grafana/oncall#838]
I'm  installing on-call by helm, everything is normal after the first deploy and configure plugin. The problem is : 

When we modified the configuration of helm such as `replicas`, `resource request`, and try to redeploy by helm, it `always` required me to `reconfigure plugin`. It said: `invalid Invitation Token` and ask me to re-generate another `Invitation Token`. 

If I repeat the whole steps, it should be fine, but this maybe not an expected behavior since we already get the Invitation Token and using the same database. 
![image](https://user-images.githubusercontent.com/67835317/201343988-2c442089-1d7d-4d78-9ec8-630b88c6816a.png)

About the version: 

Oncall : `v1.1.0` 
Oncall-plugin: `1.1.0`
External DB: `postgres` instance.

**Comment by Matvey-Kuk** [comment]
@dinhdobathi1992 is the engine pod reachable from Grafana pod after you change the config?

**Comment by mderynck** [comment]
Recently we made some changes to the way Grafana OnCall is initialized.  Use 1.9.22, there were quite a few changes along the way from 1.9.0-1.9.22 to get things working.
- If you are running Grafana 11 and newer you must have `externalServiceAccounts` feature toggle enabled.
This has already been enabled in the docker compose files and helm charts in the oncall repo.
- Plugin settings must be provided to the plugin using an API call if you are installing for the first time (Note: credentials and hostnames need to be adjusted for your configuration, stackId and orgId are expected to be the listed constants in a self-hosted configuration)
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/settings' -H "Content-Type: application/json" -d '{"enabled":true, "jsonData":{"stackId":5, "orgId":100, "onCallApiUrl":"http://engine:8080/", "grafanaUrl":"http://grafana:3000/"}}'
```
- Once settings are configured use this API call to install:
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/install'
```
Grafana OnCall should now be ready to use.
For additional troubleshooting see [here](https://github.com/grafana/oncall#troubleshooting)
