### ISSUE TITLE
helm chart: make ttlSecondsAfterFinished of job-migrate configurable

### ISSUE THREAD

**Issue by kudiyarov** [grafana/oncall#841]
Setting spec.ttlSecondsAfterFinished tells built-in Job controller to delete Job resource in 20s after completion (current setting):
https://github.com/grafana/oncall/blob/41f8d4afb19ef1217663bbd94180602d9b3767eb/helm/oncall/templates/engine/job-migrate.yaml#L9

In case of using fluxcd for deploy oncall to k8s and after changing some helm values that are present in the "job-migrate" template (i.e. resources/image), fluxcd/helm-controller runs the Job and after some time I get the following error at the helm level:
`Upgrade "oncall" failed: jobs.batch "oncall-engine-migrate-2022-11-09-18-55-09" not found`

Looks like Job controller removes Job resource while fluxcd/helm-controller is expecting to see it's state.

Making ttlSecondsAfterFinished configurable allows me to disable this setting, therefore allows the helm-controller to delete the old Job resource in case of Job's parameters changes

**Comment by 3rikas** [comment]
+1 on this. I am running into the same exact problem using ArgoCD.

**Comment by kudiyarov** [comment]
done by @erikastr in https://github.com/grafana/oncall/pull/957 , thanks
