### ISSUE TITLE
[Helm] Postgres wrong key & external Postgres db description

### ISSUE THREAD

**Issue by th30nlyw4y** [grafana/oncall#845]
Hello!
Today i've figured out that `externalPostgresql` uses `.Values.externalPostgresql.db` key ([link](https://github.com/grafana/oncall/blob/41f8d4afb19ef1217663bbd94180602d9b3767eb/helm/oncall/templates/_env.tpl#L224)) instead of `.Values.externalPostgresql.db_name` ([link](https://github.com/grafana/oncall/blob/41f8d4afb19ef1217663bbd94180602d9b3767eb/helm/oncall/values.yaml#L218)), which is shown in `values.yaml`

Also i'm not sure, but it seems that [this](https://github.com/grafana/oncall/blob/41f8d4afb19ef1217663bbd94180602d9b3767eb/helm/oncall/values.yaml#L213) information is not quite accurate, since Postgresql doesn't have such charset/collate and it uses utf-8 with 1-4 bytes encoding by default (i've used `en_US.UTF-8` locale)

I'd be ready to prepare a short PR to fix this, but i'm really curious about database locale in external Postgresql

**Comment by aviau** [comment]
Thanks @th30nlyw4y <3.

**Comment by aviau** [comment]
I also had to change `passwordKey` to `postgres-password` to match the chart-created secret...
