### ISSUE TITLE
"Tiny" deployment version for those who want a small deployment footprint?

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#85]
A few HN commenters raised a topic of a large deployment footprint: https://news.ycombinator.com/item?id=31740902

We deliver OnCall with redis + rabbit + mariadb + workers + web server because we focus on reliability a lot. For some users it's not a priority. We could think about some "tiny" deployment environment based on sqlite. 

- Django UWSGI web server -> SQLite
- Celery workers -> One celery worker for all queues using Celery-SQLAlchemy -> SQLite (https://docs.celeryq.dev/en/v5.2.7/getting-started/backends-and-brokers/index.html#sqlalchemy). It's marked as not stable in docs btw. Also our celery version is 4.3.
- Redis -> We could go without cache at all or with in-memory Django engine cache. Probably impacted parts:
   - Alert Group page in web.
   - Grouping performance for heavy alert storm from Alertmanager. Typical K8S-generated alert storm.
   - Google Calendar parser relies on caching a lot.
   - Anything else?
- Rabbit -> Could be removed.
- MySQL -> Could be removed.

In total we'll need uWSGI + celery. Both could be packed in the one docker container.

Also we should make users absolutely aware of the performance/reliability limitations if they choose such a deployment.

Any thoughts?

**Comment by Konstantinov-Innokentii** [comment]
I think we can use SQLite + Redis both for caching and message broker. It will be trade-off between complexity and reliability.

**Comment by Matvey-Kuk** [comment]
@Konstantinov-Innokentii you are right. Redis is well-supported by Celery also

**Comment by iskhakov** [comment]
> Celery workers -> One celery worker for all queues using Celery-SQLAlchemy -> SQLite (https://docs.celeryq.dev/en/v5.2.7/getting-started/backends-and-brokers/index.html#sqlalchemy). It's marked as not stable in docs btw. Also our celery version is 4.3.

SQLAlchemy is backend, it wouldn't work as a Broker, unfortunately.

**Comment by Matvey-Kuk** [comment]
@iskhakov +1 for @Konstantinov-Innokentii 's idea to keep redis

**Comment by Matvey-Kuk** [comment]
We added this task to the core team's backlog. @raphael-batte and @vadimkerr  will work on it.

**Comment by kfox1111** [comment]
This is similar to the issue I raised, but slightly different. The idea being that a simple ha setup should be possible without need of an advanced orchestrator and failure modes for the system should fail in favor of too many alerts rather then failing in a way that causes alerts never to generate. alertmanager is the only tool I've seen thus far that has taken this approach to clustering and has worked out very well in practice. sqllite can't be made ha without something like a k8s pvc pushing around a mount. celery would have similar issues in that config I think.

**Comment by Matvey-Kuk** [comment]
docker-compose.yml -> docker-compose-mysql-rabbit.yml
new tiny docker-compose -> docker-compose-sqlite-redis.yml

Documentation:
- Add new paragraph "Environmental Variables" here: https://grafana.com/docs/grafana-cloud/oncall/open-source/
- We flip "Getting Started" to docker-compose-sqlite-redis.yml. 
- - Download docker-compose.yaml: -> Download docker-compose (use docker-compose-mysql-rabbit.yml for reliability or if you are missing your mysql data):
- - Set variables (check all envs):
