### ISSUE TITLE
Alert Group Doesn't show newest Alert payloads or correct Latest Alert time

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#857]
![latest](https://user-images.githubusercontent.com/77802/201995352-503ae2fc-5d98-452a-a10d-349fa5932597.png)
Example: In the above example, we have 800 alerts in the group, and the latest one was a few minutes ago, but it says it was 19 hours ago because it's only looking at the latest from the first batch of results.

In alert groups, when there are more than 100 alerts in an alert group, it shows only the first 100 payloads, and it's sorted by oldest first, so the newest alerts in the group do not shows up.
It also shows the "Latest <date>" message based on the newest alert from the first batch of 100 instead of the actual most recent alert.

**Comment by maskin25** [comment]
got it, yep it's a problem, @vadimkerr I propose to return latest alerts first, it solves the issue, now we get latest alert like:
`const latestAlert = alerts[alerts.length - 1];`

will be:
`const latestAlert = alerts[0];`
