### ISSUE TITLE
Allow users to create overrides for iCal/API schedules in UI

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#861]
UI:
![image](https://user-images.githubusercontent.com/102970268/202466417-60e5fd13-1add-4fbf-97d5-59701e1c642d.png)

**Comment by Matvey-Kuk** [comment]
I guess it's mostly a backend task.

**Comment by raphael-batte** [comment]
After thorough investigation, we have determined the following:

1. **Terraform-based Schedules**: is possible if user enables it in the schedule config.
2. **iCal-based Schedules**: implementing the same feature is not currently possible and would be complex to develop.

However, it is worth noting that shift swaps are available as UI solution for both terraform-based and iCal-based schedules. 

Given this information, we believe the issue can be closed.
