### ISSUE TITLE
problems in Continue escalation if > X alerts per Y minutes step

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#895]
hey
i have some problem in this step: Continue escalation if > X alerts per Y minutes
in escalation chain steps

its appear it's not working properly
can you please review it please?

**Comment by Konstantinov-Innokentii** [comment]
Hi, @paneda1998. Could you please give more details?

**Comment by paneda1998** [comment]
yes sure
for example i have this settings for escalation chain:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/52179148/203712166-ff9e2692-c3b1-45e8-82d8-bb2182761780.png">

and i create some demo alerts
this is the first one:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/52179148/203712896-e353d2ec-cebe-4d99-992f-2d705dc23c98.png">

second:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/52179148/203712978-46c7d972-93e0-475f-81e7-9f1db0bbfcfc.png">

third: 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/52179148/203713046-51be38a3-a384-4da5-92f7-760a4f7010c4.png">

it seems that the escalation never continued at all

**Comment by pshakhvatov** [comment]
For me it works fine if i have "Resolve incident automatically" as the next step after "Continue escalation if > X alerts per Y minutes". Alert group resolves in that case. Any another action on this position dosen't work

**Comment by Panlq** [comment]
![image](https://user-images.githubusercontent.com/33218811/221785681-46ee8491-4ec2-4699-a6d2-35cde193d743.png)
![image](https://user-images.githubusercontent.com/33218811/221785764-26d993b5-5490-499d-acb3-5130517a978c.png)
it's not working

**Comment by Schechev** [comment]
![image](https://user-images.githubusercontent.com/60988463/223402415-36e5ad22-b0cd-418e-96bf-fd8940a46fd9.png)
![image](https://user-images.githubusercontent.com/60988463/223402620-20af6bb8-09cf-4c3f-a043-6cbb34e3b3e7.png)

It's not working, the alert is immediately sent to the slack channel

**Comment by vadimkerr** [comment]
There was a bug causing this behavior, it should be fixed in [this PR](https://github.com/grafana/oncall/pull/2636) and released in [v1.3.18](https://github.com/grafana/oncall/releases/tag/v1.3.18).
