### ISSUE TITLE
Slack something went wrong when authorizing this app.

### ISSUE THREAD

**Issue by enkov** [grafana/oncall#90]
Hello!

Using docker-compose `https://raw.githubusercontent.com/grafana/oncall/dev/docker-compose.yml` I start Oncall with this command `docker-compose --env-file .env_hobby up -d` and then configure slack integration. Integration works, but when user want to connect slack account he gets this error: 

```
Something went wrong when authorizing this app.
Error details
Invalid client_id parameter
``` 

Do I need to do any additional configuration?
To get public url for slack I use  localtunnel.

**Comment by Matvey-Kuk** [comment]
@enkov could you please try setting DOMAIN in .env_hobby as your localtunnel domain? (Without "/" at the end)

**Comment by enkov** [comment]
and when I enable slack integration admin user from which I enable it automatically connects to slack and works, but only this user.

**Comment by enkov** [comment]
Here is url where grafana send me when I try to connect user
```
https://slack.com/oauth/v2/authorize?client_id=None&redirect_uri=https://DOMAIN/api/internal/v1/complete/slack-login/?slack_login_token=TOKEN&response_type=code&user_scope=channels:read,identify,chat:write,users.profile:read,users:read,users:read.email&tracked=1
```
And here is client_id None. Maybe this is a problem?

**Comment by matiasb** [comment]
Indeed, for some reason the `client_id` is missing there. I just reproduced the problem in my local dev environment, will debug and work on a fix. Thanks for raising the issue.

**Comment by DavidSpek** [comment]
@matiasb Please see https://github.com/grafana/oncall/issues/668, since there is something very strange going on with the Slack env settings being persisted somewhere.
