### ISSUE TITLE
Allow users to make shift overrides which affect schedule only on user's shift-level

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#901]
Seems like different type of schedules needs more tailored override logic. Right now we have 3 levels inside each OnCall schedule, probably will be good to allow users create overrides on each of them. 

**Possible structure:**
- main override - affects all layers inside schedule
- layer level override - affects all rotations inside layer
- shift level override - affects only selected user shifts

**Comment by raphael-batte** [comment]
UI can be like this:
![image](https://user-images.githubusercontent.com/102970268/203812032-6a701144-aaca-4660-a99c-67fec15ec803.png)

**Comment by Matvey-Kuk** [comment]
I strongly disagree we need to add any more complexity to overrides. They are supposed to be quick and easy solution to swap 1 evening. If users need to override with repeats they could use layers.

**Comment by Matvey-Kuk** [comment]
@raphael-batte could you please rename this? Would be nice to avoid general "improvements" term.

**Comment by raphael-batte** [comment]
> I strongly disagree we need to add any more complexity to overrides. They are supposed to be quick and easy solution to swap 1 evening. If users need to override with repeats they could use layers.

1. I noticed that now any override covers the entire schedule at once and it is impossible to make override a specific shift.

As an example, I took a test schedule. Lets imagine , I only need to override only part of Marc's shift who asked me to change it. But now it is impossible to replace one person - I override the entire schedule at once.

![image](https://user-images.githubusercontent.com/102970268/211276399-038de4e5-7058-4428-bdb2-5a966266e37e.png)

One of ideas in proposal was to allow users do overrides for shifts as well.


2. As second proposal I added auto length of overrides. For example, if I chooses to override specific person - by default override will be equal to his rotation shift to reduce number of clicks.

**Comment by Matvey-Kuk** [comment]
@raphael-batte I see the point that we could cover all tricky cases but wouldn't it make overrides incredible hard to use in general? Isn't our priority to keep them simple?

**Comment by Matvey-Kuk** [comment]
Also could you please rename the task so it will represent what's it about please? 🙏 Would be nice to avoid "general" tasks.

**Comment by raphael-batte** [comment]
@Matvey-Kuk I have on my mind UX-concept which wouldn't add complexity to the process. Will do prototype to test direction.

**Comment by raphael-batte** [comment]
close this as we have SSR
