### ISSUE TITLE
TopNav: Move alerts and other content into the page 

### ISSUE THREAD

**Issue by torkelo** [grafana/oncall#904]
Please try to move alert and any content into the inside of the PluginPage (nothing should be placed outside it) 

<img width="1512" alt="Screenshot 2022-11-24 at 16 20 58" src="https://user-images.githubusercontent.com/10999/203820128-9853239e-4e46-4360-99dc-6fb0bc1848d6.png">

**Comment by torkelo** [comment]
Also there is another bug, there is no page padding when using the old nav, looks like oncall is modifying the global pages styles and breaking the style system here: 

<img width="1512" alt="Screenshot 2022-11-24 at 16 28 57" src="https://user-images.githubusercontent.com/10999/203820378-a70f344b-cdaa-494b-acd5-57509f5d9d0a.png">

**Comment by teodosii** [comment]
From Raphael - https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=5310%3A109664&t=h3qXWrpGqXkNfNC9-1

**Comment by teodosii** [comment]
Also fixed #1040 not yet released
