### ISSUE TITLE
Messages on resolving alerts

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#906]
Hi
I need some messages to be sent when alerts are resolved
for example on resolving alert trigging some outgoing webhooks or sending a msg to slack or telegram or sth else.
thanks a lot

**Comment by skazochnik97** [comment]
up

**Comment by vakhariad** [comment]
+1

**Comment by Unskilled1337** [comment]
+ 1 on this

It is confusing if the alert group is auto resolved after someone has acknowledge the alert group, but before they have manually resolved it. It would be nice to have the option to send resolve notification to responders.
