### ISSUE TITLE
Alert groups list idea. Remove "resolved" alert groups and add "assigned to me" to this place

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#921]
Before
![image](https://user-images.githubusercontent.com/102970268/204806763-5786365a-40c2-4283-af99-071a39231550.png)

After
![image](https://user-images.githubusercontent.com/102970268/204806990-3648388f-3b9d-49c9-8977-70e50ac687e5.png)

**Comment by raphael-batte** [comment]
At this case we can use **Escalated to me** term

**Comment by iskhakov** [comment]
closing as we have filters
