### ISSUE TITLE
MSTeams ChatOps Integration in OSS Grafana OnCall

### ISSUE THREAD

**Issue by AzuladoToujours** [grafana/oncall#925]
Great work with this projet!

Are there any plans to add Microsoft Teams as a ChatOps Integration in the OSS Grafana On Call? Currently it is only available in the Cloud version according to the [documentation](https://grafana.com/docs/grafana-cloud/oncall/integrations/chatops-integrations/configure-teams/). 

Thanks!

**Comment by Matvey-Kuk** [comment]
Hi! No, there are no plans to open source it, sorry.

**Comment by testn** [comment]
Would you accept a PR for that?
