### ISSUE TITLE
Add hovers to calendar UI

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#929]
- rotation start
- parent shift start
- parent shift end
- delete rotation (maybe also as additional description on confirmation Popup)

**Comment by Matvey-Kuk** [comment]
@raphael-batte please be more specific, examples of texts will be helpful :)

**Comment by raphael-batte** [comment]
Added tooltips icons to latest UI update 



![Image](https://user-images.githubusercontent.com/102970268/209322854-911fb66b-7d73-4594-971d-4b945f1d6bd4.png)

**Comment by maskin25** [comment]
still don't understand you @raphael-batte :)

**Comment by raphael-batte** [comment]
We covered this by schedules v2. I think we can close the issue.
