### ISSUE TITLE
Improve slack Empty Notifications message

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#932]
Currently in slack when a user or user group is invited it displays the following if their notification preferences are empty:
![Screenshot from 2022-12-01 10-03-58](https://user-images.githubusercontent.com/28077050/205115745-df087691-f523-4e09-9b7a-2d64f070aa7b.png)

This should be improved to give a better message about which user and that they need to setup their notification preferences.

**Comment by prabhpreet332** [comment]
Hi @mderynck @Matvey-Kuk 
I would like to work on this issue. Can you please assign it to me?
Thanks

**Comment by Matvey-Kuk** [comment]
@prabhpreet332 sure, thank you for taking this one!
