### ISSUE TITLE
Streamline slack enrollment to make things easier for larger teams

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#933]
When a larger team is connecting OnCall to slack it would be nice for them to be able to setup a default policy which will connect all users to slack and for any that have empty notification policies create a default for them to be notified via slack mentions.  This would help larger teams get setup without having to make every user logon and manually setup things before they can receive a notification.

**Comment by Matvey-Kuk** [comment]
I believe such a use-case should be covered with Terraform, not a UI to keep it simple.
