### ISSUE TITLE
Terraform on-call schedules documentation

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#936]
Add documentation to support Terraform managed On-call schedules.

Initial information source: https://grafana.com/blog/2022/08/29/get-started-with-grafana-oncall-and-terraform/

**Comment by Matvey-Kuk** [comment]
We have it here: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_on_call_shift

**Comment by joeyorlando** [comment]
As mentioned, we have docs in the [Grafana terraform provider reference](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_schedule) + [the blog post](https://grafana.com/blog/2022/08/29/get-started-with-grafana-oncall-and-terraform/).

We also link to these from OnCall's public docs
https://grafana.com/docs/oncall/latest/manage/on-call-schedules/api-terraform-schedule/
