### ISSUE TITLE
Telegram: make it clear that every channel must have its own discussion group

### ISSUE THREAD

**Issue by vadimkerr** [grafana/oncall#938]
When connecting a Telegram channel on the ChatOps page, currently it's not clear that it's required to create a dedicated discussion group for every new channel, the connection popup is misleading ("find and add your group" should be changed to indicate that a new discussion group must be created):

<img width="738" alt="Screenshot 2022-12-02 at 11 28 27" src="https://user-images.githubusercontent.com/20116910/205283152-f0684dd7-5d27-4a8c-b724-38c295911e60.png">

Also, in such cases currently bot sends a Telegram message in the discussion group, which is not seen in the channel itself, but only the existing discussion group. Ideally, this message should be sent directly to the channel to make sure users don't miss it:

<img width="542" alt="Screenshot 2022-12-02 at 11 29 50" src="https://user-images.githubusercontent.com/20116910/205283311-b6526824-b480-4472-9d82-a801f46a013e.png">

This became a point of confusion for some users that prevented them from using multiple Telegram channels.

**Comment by Ukochka** [comment]
@raphael-batte any thoughts on that? 
@vadimkerr but at the 2 point we see that we should create a new discussion group?

**Comment by raphael-batte** [comment]
Suggestion for step 2
2. Create a new Discussion group. This group handles alert actions, comments and should be unique for each OnCall telegram channel.
