### ISSUE TITLE
Schedules: Permalink doesn't work with multi-teams

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#940]
How to reproduce:
1. Open specific calendar & copy direct link
2. Open new tab, go to OnCall, switch team
3. Open previously opened link in this new tab
4. You'll see empty schedule:

<img width="1439" alt="Screenshot 2022-12-02 at 16 51 35" src="https://user-images.githubusercontent.com/3284841/205307992-c005edbd-2dc7-428e-92cb-a1e30ddc29b9.png">

**Comment by maskin25** [comment]
@Matvey-Kuk ideally we should make team as a part of url and automatically switch to proper team (like it was in amixr), quick solution is to display 404 instead of blank schedule

**Comment by Matvey-Kuk** [comment]
@maskin25 I vote for proper solution, it's a frequent use-case

**Comment by joeyorlando** [comment]
closing as completed in #1356
