### ISSUE TITLE
OnCall Schedule Filters Ignored

### ISSUE THREAD

**Issue by joe-stelmach** [grafana/oncall#941]
Visiting the `Schedules` page, if filters are selected before the initial load of schedule is completed, the filters will be ignored. As an example:

* Click on Schedules
* Immediately select filters (Ex: `Unused` & `Web`)
* Expected Result: Only unused web schedules will show in th e list
* Actual Result: All schedules are listed

**Comment by Matvey-Kuk** [comment]
Good catch, thank you!
