### ISSUE TITLE
[Calendar Schedule] Relabel/Rename Layers

### ISSUE THREAD

**Issue by joe-stelmach** [grafana/oncall#943]
When creating several layers, it would be useful to relabel them so that their existence is clear to other users. 

Additionally, and this is minor, but as you create layers, their number increments `Layer 1` `Layer 2` etc. If you have delete a layer that is in the middle, the next layer does not fill the cap, the number continues to increment, so a user could end up with the following layers `Layer 1, Layer 2, Layer 4, Layer 5`

**Comment by joeyorlando** [comment]
this should be possible by clicking on a shift within the rotation layer, which will open this modal:
![Screenshot 2024-06-14 at 14 55 08](https://github.com/grafana/oncall/assets/9406895/b7ce00a3-fa30-4a65-b5ad-0cf728e44517)

from there, if you hover over the rotation layer's name you'll see the pencil icon. Clicking that will open another modal where you can edit the rotation layer's name:
![Screenshot 2024-06-14 at 14 55 02](https://github.com/grafana/oncall/assets/9406895/a433185b-4a2c-4bb8-8aba-3e4580e375e0)
