### ISSUE TITLE
Helm: existingSecret support for redis and mysql

### ISSUE THREAD

**Issue by timchenko-a** [grafana/oncall#955]
Right now both external [MySQL](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L222-L227) and external [Redis](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L278-L280) support only explicit password setup, while some services, e.g. [RabbitMQ](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L267) and [PostgreSQL](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L246) already support using existing secret.
Main request of this issue is to add existingSecret support to Redis and MySQL. Otherwise this causes security issues when managing Helm charts in a declarative way, e.g. with helm controller.
I can work on this, unless somebody else has already started.

**Comment by Matvey-Kuk** [comment]
@timchenko-a I'm not aware of anybody working on this feature, would be happy to see your contribution!

**Comment by timchenko-a** [comment]
@Matvey-Kuk there is a PR resolving this issue (https://github.com/grafana/oncall/pull/1016). Would you be so kind as to help with getting some review there?
