### ISSUE TITLE
Mount CA certificate inside the pod.

### ISSUE THREAD

**Issue by neverlless** [grafana/oncall#964]
Hi, I'm running into a problem when using my self signed certificates.
In this case, it becomes necessary to mount my CA certificate inside the pod.

As I see from the charts and my attempts to use volumeMounts, it is not provided.
How can I mount my CA certificate inside the engine and celery pods in this case?

**Comment by ak0nst** [comment]
Just note: after adding certificate no need to update pod system certificate authority. Just pass env to container:
`  name: REQUESTS_CA_BUNDLE
    value: /path/to/your-cert.pem`

**Comment by joeyorlando** [comment]
Hi there 👋 this _should_ be possible by setting [`engine.extraVolumeMounts`/`engine.extraVolumes`](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L84-L91) and [`celery.extraVolumeMounts`/`celery.extraVolumes`](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L237-L244) in your Helm chart's values.

Going to close this, but feel free to re-open if you're still running into this issue after trying the above.
