### ISSUE TITLE
[Question] Installer for windows

### ISSUE THREAD

**Issue by henjoe** [grafana/oncall#97]
Hi, just wanna ask if there is an installer for Grafana OnCall for windows like in .exe?
Like in grafana, we can download the .exe and just one click install to our OS. 

Thank you.

Regards,
Henjoe

**Comment by D4g4n9** [comment]
**hahhha_**

**Comment by henjoe** [comment]
Lol. OnCall is an App plugin 🤣 
Never knew this before.

Regards,
Henjoe
