### ISSUE TITLE
When logged in as a viewer, the users page shows "Loading" indefinitely

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#971]
Steps to reproduce:
- log in as a viewer
- go to the User's page
- "Loading" message is shown indefinitely

<img width="1389" alt="Screenshot 2022-12-09 at 11 53 56" src="https://user-images.githubusercontent.com/9406895/206686725-1f86a633-6868-4ef9-af1c-7943885779da.png">

**Comment by raphael-batte** [comment]
We can hide the list without info or provide information that the current user role doesn't give permission to view users list.
