### ISSUE TITLE
Issue when trying to install with helm

### ISSUE THREAD

**Issue by PatMis81** [grafana/oncall#98]
Hi, 
I have encountered an issue when trying to install the helm chart on my local kubernetes. I get the following message:

`Error: INSTALLATION FAILED: template: oncall/templates/engine/job-migrate.yaml:48:14: executing "oncall/templates/engine/job-migrate.yaml" at <include "snippet.redis.env" .>: error calling include: templa
te: oncall/templates/_env.tpl:157:12: executing "snippet.redis.env" at <include "snippet.redis.host" .>: error calling include: template: oncall/templates/_env.tpl:140:46: executing "snippet.redis.host" a
t <.Values.externalRedis.host>: nil pointer evaluating interface {}.host`

Regards,
Patrick

**Comment by andy812** [comment]
Solution: change `external_redis` to `externalRedis` in values.yaml

**Comment by PatMis81** [comment]
Thank you Andy! This worked!

**Comment by andy812** [comment]
Be careful, there's a lot of errors: `nginx-ingress` instead of `ingress-nginx`, cert issuer issue, etc.
Please, don't close this bug until it will be fixed by Grafana team.

**Comment by PatMis81** [comment]
Reopen for several bugs to be fixed by Grafana.

**Comment by idv-Evgenii** [comment]
Hi, this error appears at startup and at the same time it starts everything except oncall celery and oncall engine, it initializes under oncall, but does not start

Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install oncall/templates/cert-issuer.yaml failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://******.svc:443/mutate?timeout=30s": service "test-cert-manager-webhook" not found

but nevertheless it starts grafana, but without oncall

**Comment by idv-Evgenii** [comment]
Hi, this error appears at startup and at the same time it starts everything except oncall celery and oncall engine, it initializes under oncall, but does not start

Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install oncall/templates/cert-issuer.yaml failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://******.svc:443/mutate?timeout=30s": service "test-cert-manager-webhook" not found

but nevertheless it starts grafana, but without oncall

**Comment by francis-cassbana** [comment]
Hi , I have disabled ingress false, eventhough its trying to install ingress in default namespace ,
i have ingress running in default namespace and trying to install oncall in monitoring namespace and disabled ingress getging below error
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "oncall": current value is "ingress"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "monitoring": current value is "default"

**Comment by idv-Evgenii** [comment]
@francis-cassbana 
Hello, try changing the name from nginx-ingress to ingress-nginx in values.yaml (that is, the name of the archive that is in the chart folder)

**Comment by francis-cassbana** [comment]
Hi @idv-Evgenii  i changed to ingress-nginx still same error !! i  have ingress controller and cert manager already installed in the cluster so i disabled  it to false eventhough its trying to install it
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "oncall": current value is "ingress"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "monitoring": current value is "default"

**Comment by billmetangmo** [comment]
The issue seems to be related to the version of k8s installed by default right now by minkube which is v1.25+ . I installed v1.21.4  instead `minikube start --kubernetes-version=v1.21.14` and it's working.

**Comment by Matvey-Kuk** [comment]
We added this task to the core team's backlog.

**Comment by iskhakov** [comment]
* Redis issue is fixed and merged
* Nginx issue is fixed and merged
* If cert-manager is enabled, Kubernetes version 1.25+ is not supported, added the note into helm chart README.md requirements section https://github.com/grafana/oncall/commit/e7b89575f848841bc739940d4846f6107c8c0ea6
