### ISSUE TITLE
Document manual alert group configuration

### ISSUE THREAD

**Issue by alyssawada** [grafana/oncall#993]
**Context**
It's unclear what happens when a manual alert group is created and how to configure manually created alert groups. an option for configuring the 'manual incidents integration' unless you've actually created one. 

From the Integrations tab in Grafana OnCall, there's no option to configure manual alert groups or add a new integration for manual alert groups until you've already created one. 

Once you've created a manual alert group, a new integration called 'manual incidents integration' populates in your list of integrations and you can configure escalation from there. 

For further context refer to:
- [Grafana OnCall Internal FAQ](https://docs.google.com/document/d/1--BR30obI16RipwNoO4dVO5NhkwQCRkYVZTeosFlj0A/edit?usp=sharing)
- [12/11 JustEats Slack thread](https://raintank-corp.slack.com/archives/CRUKW54N5/p1670775877416619) 

**What needs to be done**
- [ ] Document how to 'discover' configuring what happens when an alert group is created manually in Grafana OnCall
- [ ] Add docs to help users configure the 'manual incidents integration'

**Comment by joeyorlando** [comment]
going to close this out as we now have documentation on [Paging people manually](https://grafana.com/docs/oncall/latest/integrations/manual/) (ie. direct paging; I'm assuming this is what you mean by manual alert group configuration?)
